DROP SYNONYM CSMRT_OWNER.PS_D_ACAD_CAR_TEST
/

--
-- PS_D_ACAD_CAR_TEST  (Synonym) 
--
CREATE SYNONYM CSMRT_OWNER.PS_D_ACAD_CAR_TEST FOR CSMRT_OWNER.PS_D_ACAD_CAR_TEST@"OBDEV00_CSMRT_BOS.UMASSDB.NET"
/
