ALTER TABLE CSSTG_OWNER.PS_SAA_ADB_COURSES
  DROP CONSTRAINT PK_PS_SAA_ADB_COURSES
/

ALTER TABLE CSSTG_OWNER.PS_SAA_ADB_COURSES ADD (
  CONSTRAINT PK_PS_SAA_ADB_COURSES
  PRIMARY KEY
  (EMPLID, ANALYSIS_DB_SEQ, SAA_CAREER_RPT, CRSE_TAG, SRC_SYS_ID)
  RELY
  ENABLE VALIDATE)
/
