DROP FUNCTION CSMRT_OWNER.GET_CURRENT_TERM
/

--
-- GET_CURRENT_TERM  (Function) 
--
CREATE OR REPLACE FUNCTION CSMRT_OWNER.GET_CURRENT_TERM
(
IN_CAREER_CD IN VARCHAR2,
IN_INSTITUTION_CD IN VARCHAR2 ) 
RETURN VARCHAR2 IS CURRENT_TERM VARCHAR2(4);
BEGIN


SELECT 
  MIN(TERM_CD) 
INTO CURRENT_TERM   
FROM PS_D_TERM
WHERE TERM_END_DT > SYSDATE
  AND IN_CAREER_CD = ACAD_CAR_CD
  AND IN_INSTITUTION_CD = INSTITUTION_CD;
 

  


  RETURN CURRENT_TERM;
        
END GET_CURRENT_TERM;
/
