DROP TABLE CSSTG_OWNER.PS_STDNT_AWRD_ACTV CASCADE CONSTRAINTS
/

--
-- PS_STDNT_AWRD_ACTV  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_STDNT_AWRD_ACTV
(
  EMPLID             VARCHAR2(11 BYTE)          NOT NULL,
  INSTITUTION        VARCHAR2(5 BYTE)           NOT NULL,
  AID_YEAR           VARCHAR2(4 BYTE)           NOT NULL,
  ITEM_TYPE          VARCHAR2(12 BYTE)          NOT NULL,
  ACAD_CAREER        VARCHAR2(4 BYTE)           NOT NULL,
  ACTION_DTTM        TIMESTAMP(6)               NOT NULL,
  SRC_SYS_ID         VARCHAR2(5 BYTE)           NOT NULL,
  DISBURSEMENT_PLAN  VARCHAR2(2 BYTE)           NOT NULL,
  SPLIT_CODE         VARCHAR2(2 BYTE)           NOT NULL,
  DISBURSEMENT_ID    VARCHAR2(2 BYTE)           NOT NULL,
  OPRID              VARCHAR2(30 BYTE)          NOT NULL,
  AWARD_DISB_ACTION  VARCHAR2(1 BYTE)           NOT NULL,
  OFFER_AMOUNT       NUMBER(11,2)               NOT NULL,
  ACCEPT_AMOUNT      NUMBER(11,2)               NOT NULL,
  AUTHORIZED_AMOUNT  NUMBER(11,2)               NOT NULL,
  DISB_AMOUNT        NUMBER(11,2)               NOT NULL,
  CURRENCY_CD        VARCHAR2(3 BYTE)           NOT NULL,
  BUSINESS_UNIT      VARCHAR2(5 BYTE)           NOT NULL,
  ADJUST_REASON_CD   VARCHAR2(3 BYTE)           NOT NULL,
  ADJUST_AMOUNT      NUMBER(11,2)               NOT NULL,
  LOAN_ADJUST_CD     VARCHAR2(1 BYTE)           NOT NULL,
  DISB_TO_DATE       NUMBER(11,2)               NOT NULL,
  AUTH_TO_DATE       NUMBER(11,2)               NOT NULL,
  PKG_APP_DATA_USED  VARCHAR2(1 BYTE)           NOT NULL,
  LOAD_ERROR         VARCHAR2(1 BYTE)           NOT NULL,
  DATA_ORIGIN        VARCHAR2(1 BYTE)           NOT NULL,
  CREATED_EW_DTTM    DATE,
  LASTUPD_EW_DTTM    DATE,
  BATCH_SID          NUMBER(10)                 NOT NULL
)
COMPRESS BASIC
/
