DROP TABLE CSSTG_OWNER.PS_X_ADM_APP_PROG2_OLD CASCADE CONSTRAINTS
/

--
-- PS_X_ADM_APP_PROG2_OLD  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_X_ADM_APP_PROG2_OLD
(
  EMPLID           VARCHAR2(11 BYTE)            NOT NULL,
  ACAD_CAREER      VARCHAR2(4 BYTE)             NOT NULL,
  STDNT_CAR_NBR    INTEGER                      NOT NULL,
  ADM_APPL_NBR     VARCHAR2(8 BYTE)             NOT NULL,
  APPL_PROG_NBR    INTEGER                      NOT NULL,
  EFFDT            DATE                         NOT NULL,
  EFFSEQ           INTEGER                      NOT NULL,
  SRC_SYS_ID       VARCHAR2(5 BYTE)             NOT NULL,
  INSTITUTION      VARCHAR2(5 BYTE)             NOT NULL,
  ACAD_PROG        VARCHAR2(5 BYTE)             NOT NULL,
  PROG_STATUS      VARCHAR2(4 BYTE)             NOT NULL,
  PROG_ACTION      VARCHAR2(4 BYTE)             NOT NULL,
  ACTION_DT        DATE,
  PROG_REASON      VARCHAR2(4 BYTE)             NOT NULL,
  ADMIT_TERM       VARCHAR2(4 BYTE)             NOT NULL,
  EXP_GRAD_TERM    VARCHAR2(4 BYTE)             NOT NULL,
  REQ_TERM         VARCHAR2(4 BYTE)             NOT NULL,
  ACAD_LOAD_APPR   VARCHAR2(1 BYTE)             NOT NULL,
  CAMPUS           VARCHAR2(5 BYTE)             NOT NULL,
  ACAD_PROG_DUAL   VARCHAR2(5 BYTE)             NOT NULL,
  JOINT_PROG_APPR  VARCHAR2(1 BYTE)             NOT NULL,
  LOAD_ERROR       VARCHAR2(1 BYTE)             NOT NULL,
  DATA_ORIGIN      VARCHAR2(1 BYTE)             NOT NULL,
  CREATED_EW_DTTM  DATE,
  LASTUPD_EW_DTTM  DATE,
  BATCH_SID        NUMBER(10)                   NOT NULL
)
COMPRESS BASIC
/
