DROP TABLE CSSTG_OWNER.PS_ETHNIC_GRP_TBL CASCADE CONSTRAINTS
/

--
-- PS_ETHNIC_GRP_TBL  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_ETHNIC_GRP_TBL
(
  SETID            VARCHAR2(5 BYTE)             NOT NULL,
  ETHNIC_GRP_CD    VARCHAR2(8 BYTE)             NOT NULL,
  EFFDT            DATE                         NOT NULL,
  SRC_SYS_ID       VARCHAR2(5 BYTE)             NOT NULL,
  EFF_STATUS       VARCHAR2(1 BYTE)             NOT NULL,
  DESCR50          VARCHAR2(50 BYTE)            NOT NULL,
  DESCRSHORT       VARCHAR2(10 BYTE)            NOT NULL,
  ETHNIC_CATEGORY  VARCHAR2(1 BYTE)             NOT NULL,
  ETHNIC_GROUP     VARCHAR2(1 BYTE)             NOT NULL,
  LOAD_ERROR       VARCHAR2(1 BYTE)             NOT NULL,
  DATA_ORIGIN      VARCHAR2(1 BYTE)             NOT NULL,
  CREATED_EW_DTTM  DATE,
  LASTUPD_EW_DTTM  DATE,
  BATCH_SID        NUMBER(10)                   NOT NULL
)
COMPRESS BASIC
/
