DROP TABLE CSSTG_OWNER.PS_ETHNICITY_DTL CASCADE CONSTRAINTS
/

--
-- PS_ETHNICITY_DTL  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_ETHNICITY_DTL
(
  EMPLID              VARCHAR2(11 BYTE)         NOT NULL,
  REG_REGION          VARCHAR2(5 BYTE)          NOT NULL,
  ETHNIC_GRP_CD       VARCHAR2(8 BYTE)          NOT NULL,
  SRC_SYS_ID          VARCHAR2(5 BYTE)          NOT NULL,
  ETHNIC_PCT_NUMRATR  INTEGER                   NOT NULL,
  ETHNIC_PCT_DENMRTR  INTEGER                   NOT NULL,
  ETH_VALIDATED       VARCHAR2(1 BYTE)          NOT NULL,
  HISP_LATINO         VARCHAR2(1 BYTE)          NOT NULL,
  LASTUPDDTTM         DATE,
  LASTUPDOPRID        VARCHAR2(30 BYTE)         NOT NULL,
  LOAD_ERROR          VARCHAR2(1 BYTE)          NOT NULL,
  DATA_ORIGIN         VARCHAR2(1 BYTE)          NOT NULL,
  CREATED_EW_DTTM     DATE,
  LASTUPD_EW_DTTM     DATE,
  BATCH_SID           NUMBER(10)                NOT NULL
)
COMPRESS BASIC
/
