DROP TABLE CSSTG_OWNER.PS_SUBJECT_TBL CASCADE CONSTRAINTS
/

--
-- PS_SUBJECT_TBL  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_SUBJECT_TBL
(
  INSTITUTION        VARCHAR2(5 BYTE)           NOT NULL,
  SUBJECT            VARCHAR2(25 BYTE)          NOT NULL,
  EFFDT              DATE                       NOT NULL,
  SRC_SYS_ID         VARCHAR2(5 BYTE)           NOT NULL,
  EFF_STATUS         VARCHAR2(1 BYTE)           NOT NULL,
  DESCR              VARCHAR2(30 BYTE)          NOT NULL,
  DESCRSHORT         VARCHAR2(10 BYTE)          NOT NULL,
  ACAD_ORG           VARCHAR2(10 BYTE)          NOT NULL,
  SPLIT_OWNER        VARCHAR2(1 BYTE)           NOT NULL,
  EXT_SUBJECT_AREA   VARCHAR2(4 BYTE)           NOT NULL,
  CIP_CODE           VARCHAR2(13 BYTE)          NOT NULL,
  HEGIS_CODE         VARCHAR2(8 BYTE)           NOT NULL,
  DESCRFORMAL        VARCHAR2(50 BYTE)          NOT NULL,
  USE_BLIND_GRADING  VARCHAR2(1 BYTE)           NOT NULL,
  STUDY_FIELD        VARCHAR2(10 BYTE)          NOT NULL,
  LOAD_ERROR         VARCHAR2(1 BYTE)           NOT NULL,
  DATA_ORIGIN        VARCHAR2(1 BYTE)           NOT NULL,
  CREATED_EW_DTTM    DATE,
  LASTUPD_EW_DTTM    DATE,
  BATCH_SID          NUMBER(10)                 NOT NULL
)
COMPRESS BASIC
/
