DROP TABLE CSSTG_OWNER.PS_STDNT_ADVR_HIST CASCADE CONSTRAINTS
/

--
-- PS_STDNT_ADVR_HIST  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_STDNT_ADVR_HIST
(
  EMPLID             VARCHAR2(11 BYTE)          NOT NULL,
  INSTITUTION        VARCHAR2(5 BYTE)           NOT NULL,
  EFFDT              DATE                       NOT NULL,
  ADVISOR_ROLE       VARCHAR2(4 BYTE)           NOT NULL,
  STDNT_ADVISOR_NBR  INTEGER                    NOT NULL,
  SRC_SYS_ID         VARCHAR2(5 BYTE)           NOT NULL,
  ACAD_PROG          VARCHAR2(5 BYTE)           NOT NULL,
  ADVISOR_ID         VARCHAR2(11 BYTE)          NOT NULL,
  ACAD_CAREER        VARCHAR2(4 BYTE)           NOT NULL,
  ACAD_PLAN          VARCHAR2(10 BYTE)          NOT NULL,
  APPROVE_ENRLMT     VARCHAR2(1 BYTE)           NOT NULL,
  APPROVE_GRAD       VARCHAR2(1 BYTE)           NOT NULL,
  GRAD_APPROVED      VARCHAR2(1 BYTE)           NOT NULL,
  COMMITTEE_ID       VARCHAR2(6 BYTE)           NOT NULL,
  COMM_PERS_CD       VARCHAR2(1 BYTE)           NOT NULL,
  LOAD_ERROR         VARCHAR2(1 BYTE)           NOT NULL,
  DATA_ORIGIN        VARCHAR2(1 BYTE)           NOT NULL,
  CREATED_EW_DTTM    DATE,
  LASTUPD_EW_DTTM    DATE,
  BATCH_SID          NUMBER(10)                 NOT NULL
)
COMPRESS BASIC
/
