DROP TABLE CSSTG_OWNER.PS_IMMUN_CRITERIA CASCADE CONSTRAINTS
/

--
-- PS_IMMUN_CRITERIA  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_IMMUN_CRITERIA
(
  EMPLID           VARCHAR2(11 BYTE)            NOT NULL,
  IMMUNIZATION     VARCHAR2(5 BYTE)             NOT NULL,
  IMMUN_SEQ        INTEGER                      NOT NULL,
  CRITERIA_SEQ     INTEGER                      NOT NULL,
  SRC_SYS_ID       VARCHAR2(5 BYTE)             NOT NULL,
  DATE_TAKEN       DATE,
  EXPIRATION_DT    DATE,
  DESCR            VARCHAR2(30 BYTE)            NOT NULL,
  TEST_STATUS      VARCHAR2(1 BYTE)             NOT NULL,
  STATUS_IMMUN     VARCHAR2(1 BYTE)             NOT NULL,
  DATE_RECEIVED    DATE,
  LOAD_ERROR       VARCHAR2(1 BYTE)             NOT NULL,
  DATA_ORIGIN      VARCHAR2(1 BYTE)             NOT NULL,
  CREATED_EW_DTTM  DATE,
  LASTUPD_EW_DTTM  DATE,
  BATCH_SID        NUMBER(10)                   NOT NULL
)
COMPRESS BASIC
/
