DROP TABLE CSSTG_OWNER.PS_T_SCC_CKLSITM_TBL CASCADE CONSTRAINTS
/

--
-- PS_T_SCC_CKLSITM_TBL  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_T_SCC_CKLSITM_TBL
(
  CHKLST_ITEM_CD    VARCHAR2(6 BYTE)            NOT NULL,
  EFFDT             DATE                        NOT NULL,
  EFF_STATUS        VARCHAR2(1 BYTE),
  ITEM_ASSOCIATION  VARCHAR2(1 BYTE),
  DESCR             VARCHAR2(30 BYTE),
  DESCRSHORT        VARCHAR2(10 BYTE),
  DESCRLONG         VARCHAR2(4000 BYTE),
  SRC_SCN           NUMBER
)
NOCOMPRESS
/
