DROP TABLE CSSTG_OWNER.UM_AF_AMH_STUDENT_ADM_S2 CASCADE CONSTRAINTS
/

--
-- UM_AF_AMH_STUDENT_ADM_S2  (Table) 
--
CREATE TABLE CSSTG_OWNER.UM_AF_AMH_STUDENT_ADM_S2
(
  INSTITUTION_CD     VARCHAR2(5 BYTE)           NOT NULL,
  INSTITUTION_LD     VARCHAR2(50 BYTE),
  ADMIT_TERM_CD      VARCHAR2(4 BYTE)           NOT NULL,
  ADMIT_TERM_LD      VARCHAR2(50 BYTE),
  REPORTING_TERM_CD  VARCHAR2(4 BYTE)           NOT NULL,
  REPORTING_TERM_LD  VARCHAR2(50 BYTE),
  ACAD_YR            VARCHAR2(4 BYTE),
  FISCAL_YR          VARCHAR2(4 BYTE),
  PERSON_ID          VARCHAR2(11 BYTE)          NOT NULL,
  ADM_APPL_NBR       VARCHAR2(8 BYTE)           NOT NULL,
  SLATE_ID           VARCHAR2(100 BYTE)         NOT NULL,
  EXT_ADM_APPL_NBR   VARCHAR2(30 BYTE)          NOT NULL,
  APPL_CNTR_ID       VARCHAR2(8 BYTE),
  ACAD_CAR_CD        VARCHAR2(5 BYTE)           NOT NULL,
  ACAD_CAR_LD        VARCHAR2(50 BYTE),
  CE_APPL_FLG        VARCHAR2(1 BYTE),
  ADMIT_TYPE_ID      VARCHAR2(5 BYTE),
  ADMIT_TYPE_LD      VARCHAR2(50 BYTE),
  ADMIT_TYPE_GRP     VARCHAR2(50 BYTE),
  ACAD_PROG_CD       VARCHAR2(8 BYTE)           NOT NULL,
  ACAD_PROG_LD       VARCHAR2(50 BYTE),
  ACAD_PLAN_CD       VARCHAR2(10 BYTE)          NOT NULL,
  ACAD_PLAN_LD       VARCHAR2(50 BYTE),
  PLAN_CIP_CD        VARCHAR2(13 BYTE),
  PLAN_CIP_LD        VARCHAR2(50 BYTE),
  EDU_LVL_CD         VARCHAR2(10 BYTE),
  EDU_LVL_LD         VARCHAR2(50 BYTE),
  RSDNCY_ID          VARCHAR2(5 BYTE),
  RSDNCY_LD          VARCHAR2(50 BYTE),
  IS_RSDNCY_FLG      VARCHAR2(1 BYTE),
  APPL_CNT           NUMBER,
  ADMIT_CNT          NUMBER,
  DENY_CNT           NUMBER,
  DEPOSIT_CNT        NUMBER,
  ENROLL_CNT         NUMBER,
  ENROLL_SUBSEQ_CNT  NUMBER,
  CREATED_EW_DTTM    DATE                       DEFAULT SYSDATE
)
COMPRESS BASIC
/


ALTER TABLE CSSTG_OWNER.UM_AF_AMH_STUDENT_ADM_S2 ADD (
  CONSTRAINT PK_UM_AF_AMH_STUDENT_ADM_S2
  PRIMARY KEY
  (INSTITUTION_CD, ADMIT_TERM_CD, PERSON_ID, ADM_APPL_NBR, SLATE_ID, EXT_ADM_APPL_NBR, ACAD_CAR_CD, ACAD_PROG_CD, ACAD_PLAN_CD)
  RELY
  ENABLE VALIDATE)
/
