DROP TABLE CSSTG_OWNER.PS_ACAD_DEGR CASCADE CONSTRAINTS
/

--
-- PS_ACAD_DEGR  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_ACAD_DEGR
(
  EMPLID            VARCHAR2(11 BYTE)           NOT NULL,
  STDNT_DEGR        VARCHAR2(2 BYTE)            NOT NULL,
  SRC_SYS_ID        VARCHAR2(5 BYTE)            NOT NULL,
  DEGREE            VARCHAR2(8 BYTE)            NOT NULL,
  INSTITUTION       VARCHAR2(5 BYTE)            NOT NULL,
  ACAD_CAREER       VARCHAR2(4 BYTE)            NOT NULL,
  COMPLETION_TERM   VARCHAR2(4 BYTE)            NOT NULL,
  DEGR_CONFER_DT    DATE                        NOT NULL,
  HONORS_PREFIX     VARCHAR2(3 BYTE)            NOT NULL,
  HONORS_SUFFIX     VARCHAR2(3 BYTE)            NOT NULL,
  GPA_DEGREE        NUMBER(9,3)                 NOT NULL,
  CLASS_RANK_NBR    INTEGER                     NOT NULL,
  CLASS_RANK_TOT    INTEGER                     NOT NULL,
  ACAD_DEGR_STATUS  VARCHAR2(1 BYTE)            NOT NULL,
  DEGR_STATUS_DATE  DATE,
  OPRID             VARCHAR2(30 BYTE)           NOT NULL,
  LOAD_ERROR        VARCHAR2(1 BYTE)            NOT NULL,
  DATA_ORIGIN       VARCHAR2(1 BYTE)            NOT NULL,
  CREATED_EW_DTTM   DATE,
  LASTUPD_EW_DTTM   DATE,
  BATCH_SID         NUMBER(10)                  NOT NULL
)
COMPRESS BASIC
/
