DROP TABLE CSSTG_OWNER.PS_T_PRSPCT_RCR_CAT CASCADE CONSTRAINTS
/

--
-- PS_T_PRSPCT_RCR_CAT  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_T_PRSPCT_RCR_CAT
(
  EMPLID            VARCHAR2(11 BYTE)           NOT NULL,
  ACAD_CAREER       VARCHAR2(4 BYTE)            NOT NULL,
  INSTITUTION       VARCHAR2(5 BYTE)            NOT NULL,
  RECRUITMENT_CAT   VARCHAR2(4 BYTE)            NOT NULL,
  RECRUIT_SUB_CAT   VARCHAR2(4 BYTE)            NOT NULL,
  MOVE_TO_APPL      VARCHAR2(1 BYTE)            NOT NULL,
  PROMPT_RECRUITER  VARCHAR2(1 BYTE)            NOT NULL,
  DESCRLONG         VARCHAR2(4000 BYTE),
  SRC_SCN           NUMBER
)
NOCOMPRESS
/
