DROP TABLE CSSTG_OWNER.PS_EXT_ORG_TBL CASCADE CONSTRAINTS
/

--
-- PS_EXT_ORG_TBL  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_EXT_ORG_TBL
(
  EXT_ORG_ID          VARCHAR2(11 BYTE)         NOT NULL,
  EFFDT               DATE                      NOT NULL,
  SRC_SYS_ID          VARCHAR2(5 BYTE)          NOT NULL,
  EFF_STATUS          VARCHAR2(1 BYTE)          NOT NULL,
  OTH_NAME_SORT_SRCH  VARCHAR2(50 BYTE)         NOT NULL,
  EXT_ORG_TYPE        VARCHAR2(4 BYTE)          NOT NULL,
  DESCR               VARCHAR2(30 BYTE)         NOT NULL,
  DESCR50             VARCHAR2(50 BYTE)         NOT NULL,
  DESCRSHORT          VARCHAR2(10 BYTE)         NOT NULL,
  ORG_CONTACT         INTEGER                   NOT NULL,
  ORG_LOCATION        INTEGER                   NOT NULL,
  ORG_DEPARTMENT      INTEGER                   NOT NULL,
  PROPRIETORSHIP      VARCHAR2(4 BYTE)          NOT NULL,
  SETID               VARCHAR2(5 BYTE)          NOT NULL,
  VENDOR_ID           VARCHAR2(10 BYTE)         NOT NULL,
  TAXPAYER_ID_NO      VARCHAR2(9 BYTE)          NOT NULL,
  LASTUPDDTTM         DATE,
  LASTUPDOPRID        VARCHAR2(30 BYTE)         NOT NULL,
  LOAD_ERROR          VARCHAR2(1 BYTE)          NOT NULL,
  DATA_ORIGIN         VARCHAR2(1 BYTE)          NOT NULL,
  CREATED_EW_DTTM     DATE,
  LASTUPD_EW_DTTM     DATE,
  BATCH_SID           NUMBER(10)                NOT NULL
)
COMPRESS BASIC
/
