DROP TABLE CSSTG_OWNER.PS_SCC_STN_LTR_TBL CASCADE CONSTRAINTS
/

--
-- PS_SCC_STN_LTR_TBL  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_SCC_STN_LTR_TBL
(
  SCC_LETTER_CD       VARCHAR2(3 BYTE)          NOT NULL,
  SRC_SYS_ID          VARCHAR2(5 BYTE)          NOT NULL,
  SCC_SET_LETTER_CD   VARCHAR2(4 BYTE)          NOT NULL,
  DESCR               VARCHAR2(30 BYTE)         NOT NULL,
  DESCRSHORT          VARCHAR2(10 BYTE)         NOT NULL,
  ADMIN_FUNCTION      VARCHAR2(4 BYTE)          NOT NULL,
  SQC_NAME            VARCHAR2(8 BYTE)          NOT NULL,
  ENCL_TYPE           VARCHAR2(1 BYTE)          NOT NULL,
  LTR_PRINT_DATA_OPT  VARCHAR2(4 BYTE)          NOT NULL,
  ALLOW_JOINT         VARCHAR2(1 BYTE)          NOT NULL,
  INCLUDE_ENCL        VARCHAR2(1 BYTE)          NOT NULL,
  LOAD_ERROR          VARCHAR2(1 BYTE)          NOT NULL,
  DATA_ORIGIN         VARCHAR2(1 BYTE)          NOT NULL,
  CREATED_EW_DTTM     DATE,
  LASTUPD_EW_DTTM     DATE,
  BATCH_SID           NUMBER(10)                NOT NULL
)
COMPRESS BASIC
/
