DROP TABLE CSSTG_OWNER.PS_CLASS_CHRSTC CASCADE CONSTRAINTS
/

--
-- PS_CLASS_CHRSTC  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_CLASS_CHRSTC
(
  CRSE_ID             VARCHAR2(6 BYTE)          NOT NULL,
  CRSE_OFFER_NBR      INTEGER                   NOT NULL,
  STRM                VARCHAR2(4 BYTE)          NOT NULL,
  SESSION_CODE        VARCHAR2(3 BYTE)          NOT NULL,
  CLASS_SECTION       VARCHAR2(4 BYTE)          NOT NULL,
  ROOM_CHRSTC         VARCHAR2(2 BYTE)          NOT NULL,
  SRC_SYS_ID          VARCHAR2(5 BYTE)          NOT NULL,
  ROOM_CHRSTC_QUANTI  INTEGER                   NOT NULL,
  LOAD_ERROR          VARCHAR2(1 BYTE)          NOT NULL,
  DATA_ORIGIN         VARCHAR2(1 BYTE)          NOT NULL,
  CREATED_EW_DTTM     DATE,
  LASTUPD_EW_DTTM     DATE,
  BATCH_SID           NUMBER(10)                NOT NULL
)
COMPRESS BASIC
/
