DROP TABLE CSSTG_OWNER.PS_INSTRUCT_MODE CASCADE CONSTRAINTS
/

--
-- PS_INSTRUCT_MODE  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_INSTRUCT_MODE
(
  INSTITUTION       VARCHAR2(5 BYTE)            NOT NULL,
  INSTRUCTION_MODE  VARCHAR2(2 BYTE)            NOT NULL,
  EFFDT             DATE,
  SRC_SYS_ID        VARCHAR2(5 BYTE)            NOT NULL,
  EFF_STATUS        VARCHAR2(1 BYTE)            NOT NULL,
  DESCR             VARCHAR2(30 BYTE)           NOT NULL,
  DESCRSHORT        VARCHAR2(10 BYTE)           NOT NULL,
  PRINT_ON_CATLG    VARCHAR2(1 BYTE)            NOT NULL,
  PRINT_ON_SCHED    VARCHAR2(1 BYTE)            NOT NULL,
  PRINT_ON_XCRIPT   VARCHAR2(1 BYTE)            NOT NULL,
  LOAD_ERROR        VARCHAR2(1 BYTE)            NOT NULL,
  DATA_ORIGIN       VARCHAR2(1 BYTE)            NOT NULL,
  CREATED_EW_DTTM   DATE,
  LASTUPD_EW_DTTM   DATE,
  BATCH_SID         NUMBER(10)                  NOT NULL
)
COMPRESS BASIC
/
