DROP TABLE CSSTG_OWNER.PS_UM_DEGR_LIM_TBL CASCADE CONSTRAINTS
/

--
-- PS_UM_DEGR_LIM_TBL  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_UM_DEGR_LIM_TBL
(
  INSTITUTION      VARCHAR2(5 BYTE)             NOT NULL,
  ACAD_CAREER      VARCHAR2(4 BYTE)             NOT NULL,
  ACAD_PROG        VARCHAR2(5 BYTE)             NOT NULL,
  ACAD_PLAN        VARCHAR2(10 BYTE)            NOT NULL,
  ACAD_SUB_PLAN    VARCHAR2(10 BYTE)            NOT NULL,
  EFFDT            DATE                         NOT NULL,
  SRC_SYS_ID       VARCHAR2(5 BYTE)             NOT NULL,
  YEARS            INTEGER,
  LOAD_ERROR       VARCHAR2(1 BYTE)             NOT NULL,
  DATA_ORIGIN      VARCHAR2(1 BYTE)             NOT NULL,
  CREATED_EW_DTTM  DATE,
  LASTUPD_EW_DTTM  DATE,
  BATCH_SID        NUMBER(10)                   NOT NULL
)
COMPRESS BASIC
/
