DROP TABLE CSSTG_OWNER.PS_ACCT_TYP_TBL_SF CASCADE CONSTRAINTS
/

--
-- PS_ACCT_TYP_TBL_SF  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_ACCT_TYP_TBL_SF
(
  SETID               VARCHAR2(5 BYTE)          NOT NULL,
  ACCOUNT_TYPE_SF     VARCHAR2(3 BYTE)          NOT NULL,
  SRC_SYS_ID          VARCHAR2(5 BYTE)          NOT NULL,
  DESCR               VARCHAR2(30 BYTE)         NOT NULL,
  DESCRSHORT          VARCHAR2(10 BYTE)         NOT NULL,
  BALANCE_FWD_SW      VARCHAR2(1 BYTE)          NOT NULL,
  ACCT_NUM_PREFIX     VARCHAR2(7 BYTE)          NOT NULL,
  ACCT_PER_TERM       VARCHAR2(1 BYTE)          NOT NULL,
  PRIMARY_ACCOUNT     VARCHAR2(1 BYTE)          NOT NULL,
  CANCEL_CLASS        VARCHAR2(1 BYTE)          NOT NULL,
  EXCLUDE_AGE_FLG     VARCHAR2(1 BYTE)          NOT NULL,
  PMT_PLAN_ACCT_FLG   VARCHAR2(1 BYTE)          NOT NULL,
  LATE_FEE_ACCT_IND   VARCHAR2(1 BYTE)          NOT NULL,
  LATE_FEE_CODE       VARCHAR2(6 BYTE)          NOT NULL,
  LATE_FEE_ACCT_ORG   VARCHAR2(1 BYTE)          NOT NULL,
  LATE_FEE_CODE_ORG   VARCHAR2(6 BYTE)          NOT NULL,
  INCLUDE_IN_BALANCE  VARCHAR2(1 BYTE)          NOT NULL,
  INCLUDE_BILLING     VARCHAR2(1 BYTE)          NOT NULL,
  INCLUDE_TRANSFER    VARCHAR2(1 BYTE)          NOT NULL,
  INCLUDE_PREPAY      VARCHAR2(1 BYTE)          NOT NULL,
  MOVE_EXCESS_FA      VARCHAR2(1 BYTE)          NOT NULL,
  MOVE_EXCESS_PMT     VARCHAR2(1 BYTE)          NOT NULL,
  MOVE_EXCESS_WAIVER  VARCHAR2(1 BYTE)          NOT NULL,
  UNAPP_PMT_CREDHIST  VARCHAR2(1 BYTE)          NOT NULL,
  SF_ACCOUNT_CLASS    VARCHAR2(10 BYTE)         NOT NULL,
  LOAD_ERROR          VARCHAR2(1 BYTE)          NOT NULL,
  DATA_ORIGIN         VARCHAR2(1 BYTE)          NOT NULL,
  CREATED_EW_DTTM     DATE,
  LASTUPD_EW_DTTM     DATE,
  BATCH_SID           NUMBER(10)                NOT NULL
)
COMPRESS BASIC
/
