DROP TABLE CSSTG_OWNER.PS_MLSTN_LVL_TBL_OLD CASCADE CONSTRAINTS
/

--
-- PS_MLSTN_LVL_TBL_OLD  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_MLSTN_LVL_TBL_OLD
(
  INSTITUTION      VARCHAR2(5 BYTE)             NOT NULL,
  MILESTONE        VARCHAR2(10 BYTE)            NOT NULL,
  EFFDT            DATE                         NOT NULL,
  MILESTONE_LEVEL  VARCHAR2(15 BYTE)            NOT NULL,
  SRC_SYS_ID       VARCHAR2(5 BYTE)             NOT NULL,
  DESCR            VARCHAR2(30 BYTE)            NOT NULL,
  DESCRFORMAL      VARCHAR2(50 BYTE)            NOT NULL,
  LOAD_ERROR       VARCHAR2(1 BYTE)             NOT NULL,
  DATA_ORIGIN      VARCHAR2(1 BYTE)             NOT NULL,
  CREATED_EW_DTTM  DATE,
  LASTUPD_EW_DTTM  DATE,
  BATCH_SID        NUMBER(10)                   NOT NULL
)
COMPRESS BASIC
/
