DROP TABLE CSSTG_OWNER.PS_CRSE_FEE_TBL CASCADE CONSTRAINTS
/

--
-- PS_CRSE_FEE_TBL  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_CRSE_FEE_TBL
(
  SETID            VARCHAR2(5 BYTE)             NOT NULL,
  CRSE_ID          VARCHAR2(6 BYTE)             NOT NULL,
  SSR_COMPONENT    VARCHAR2(3 BYTE)             NOT NULL,
  INSTITUTION      VARCHAR2(5 BYTE)             NOT NULL,
  CAMPUS           VARCHAR2(5 BYTE)             NOT NULL,
  LOCATION         VARCHAR2(10 BYTE)            NOT NULL,
  STRM             VARCHAR2(4 BYTE)             NOT NULL,
  SESSION_CODE     VARCHAR2(3 BYTE)             NOT NULL,
  SRC_SYS_ID       VARCHAR2(5 BYTE)             NOT NULL,
  CHARGE_METHOD    VARCHAR2(1 BYTE)             NOT NULL,
  CALC_PRO_RATA    VARCHAR2(1 BYTE)             NOT NULL,
  CALC_OTHER_WDRW  VARCHAR2(1 BYTE)             NOT NULL,
  AUDIT_RT_FLAG    VARCHAR2(1 BYTE)             NOT NULL,
  LOAD_ERROR       VARCHAR2(1 BYTE)             NOT NULL,
  DATA_ORIGIN      VARCHAR2(1 BYTE)             NOT NULL,
  CREATED_EW_DTTM  DATE,
  LASTUPD_EW_DTTM  DATE,
  BATCH_SID        NUMBER(10)                   NOT NULL
)
COMPRESS BASIC
/
