DROP TABLE CSSTG_OWNER.PS_UM_CUMGPA CASCADE CONSTRAINTS
/

--
-- PS_UM_CUMGPA  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_UM_CUMGPA
(
  EMPLID           VARCHAR2(11 BYTE)            NOT NULL,
  INSTITUTION      VARCHAR2(5 BYTE)             NOT NULL,
  EXT_SUMM_TYPE    VARCHAR2(4 BYTE)             NOT NULL,
  SRC_SYS_ID       VARCHAR2(5 BYTE)             NOT NULL,
  UM_CUM_CREDIT    NUMBER                       NOT NULL,
  UM_CUM_GPA       NUMBER                       NOT NULL,
  UM_CUM_QP        NUMBER                       NOT NULL,
  LOAD_ERROR       VARCHAR2(1 BYTE)             NOT NULL,
  DATA_ORIGIN      VARCHAR2(1 BYTE)             NOT NULL,
  CREATED_EW_DTTM  DATE,
  LASTUPD_EW_DTTM  DATE,
  BATCH_SID        NUMBER(10)                   NOT NULL
)
COMPRESS BASIC
/
