DROP TABLE CSSTG_OWNER.PS_SAA_ADB_COURSES CASCADE CONSTRAINTS
/

--
-- PS_SAA_ADB_COURSES  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_SAA_ADB_COURSES
(
  EMPLID              VARCHAR2(11 BYTE)         NOT NULL,
  ANALYSIS_DB_SEQ     INTEGER                   NOT NULL,
  SAA_CAREER_RPT      VARCHAR2(4 BYTE)          NOT NULL,
  CRSE_TAG            VARCHAR2(4 BYTE)          NOT NULL,
  SRC_SYS_ID          VARCHAR2(4 BYTE)          NOT NULL,
  RPT_DATE            DATE,
  INSTITUTION         VARCHAR2(5 BYTE)          NOT NULL,
  ACAD_CAREER         VARCHAR2(4 BYTE),
  CRSE_CAREER         VARCHAR2(4 BYTE),
  STRM                VARCHAR2(4 BYTE),
  CLASS_NBR           INTEGER,
  STDNT_ENRL_STATUS   VARCHAR2(2 BYTE),
  UNT_TAKEN           NUMBER(5,2),
  UNT_EARNED          NUMBER(5,2),
  UNT_PRGRSS          NUMBER(5,2),
  GRADING_BASIS_ENRL  VARCHAR2(3 BYTE),
  CRSE_GRADE_OFF      VARCHAR2(3 BYTE),
  REPEAT_CODE         VARCHAR2(4 BYTE),
  ASSOCIATED_CLASS    INTEGER,
  AUDIT_GRADE_BASIS   VARCHAR2(1 BYTE),
  EARN_CREDIT         VARCHAR2(1 BYTE),
  INCLUDE_IN_GPA      VARCHAR2(1 BYTE),
  UNITS_ATTEMPTED     VARCHAR2(1 BYTE),
  GRADE_POINTS        NUMBER(9,3),
  CRSE_ID             VARCHAR2(6 BYTE),
  CRSE_OFFER_NBR      INTEGER,
  SESSION_CODE        VARCHAR2(3 BYTE),
  CLASS_SECTION       VARCHAR2(4 BYTE),
  ACAD_GROUP          VARCHAR2(5 BYTE),
  SUBJECT             VARCHAR2(8 BYTE),
  CATALOG_NBR         VARCHAR2(10 BYTE),
  DESCR               VARCHAR2(30 BYTE),
  SSR_COMPONENT       VARCHAR2(3 BYTE),
  CRS_TOPIC_ID        INTEGER,
  SAA_DISPLAY_TOPIC   VARCHAR2(1 BYTE),
  EQUIV_CRSE_ID       VARCHAR2(5 BYTE),
  OVRD_CRSE_EQUIV_ID  VARCHAR2(1 BYTE),
  START_DT            DATE,
  END_DT              DATE,
  CRSE_COUNT          NUMBER(4,2),
  CLASS_ENRL_TYPE     VARCHAR2(1 BYTE),
  SAA_CRSE_TYPE       VARCHAR2(1 BYTE),
  RQ_SCHOOL_TYPE      VARCHAR2(4 BYTE),
  GRADE_CATEGORY      VARCHAR2(4 BYTE),
  VALID_ATTEMPT       VARCHAR2(1 BYTE),
  GRD_PTS_PER_UNIT    NUMBER(9,3),
  RQMNT_DESIGNTN      VARCHAR2(4 BYTE),
  EVALUATION_DT       DATE,
  TEST_DT             DATE,
  GRADING_SCHEME      VARCHAR2(3 BYTE),
  SUB_ACAD_GROUP      VARCHAR2(5 BYTE),
  SUB_CRSE_ID         VARCHAR2(6 BYTE),
  SUB_SUBJECT         VARCHAR2(8 BYTE),
  SUB_CATLG_NBR       VARCHAR2(10 BYTE),
  SAA_SUB_DESCR       VARCHAR2(30 BYTE),
  OPRID               VARCHAR2(30 BYTE),
  SAA_DISPLAY_OPTION  VARCHAR2(1 BYTE),
  STDNT_SUB_NBR       VARCHAR2(4 BYTE),
  DESCR254A           VARCHAR2(254 BYTE),
  CREATED_EW_DTTM     DATE
)
COMPRESS BASIC
/


ALTER TABLE CSSTG_OWNER.PS_SAA_ADB_COURSES ADD (
  CONSTRAINT PK_PS_SAA_ADB_COURSES
  PRIMARY KEY
  (EMPLID, ANALYSIS_DB_SEQ, SAA_CAREER_RPT, CRSE_TAG, SRC_SYS_ID)
  RELY
  ENABLE VALIDATE)
/
