DROP TABLE CSSTG_OWNER.PS_K_PERSON_COMMENT CASCADE CONSTRAINTS
/

--
-- PS_K_PERSON_COMMENT  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_K_PERSON_COMMENT
(
  COMMON_ID   VARCHAR2(11 BYTE)                 NOT NULL,
  SEQ_3C      INTEGER                           NOT NULL,
  SRC_SYS_ID  VARCHAR2(5 BYTE)                  NOT NULL
)
COMPRESS BASIC
/
