DROP TABLE CSSTG_OWNER.PS_RATING_CMP_TBL_OLD CASCADE CONSTRAINTS
/

--
-- PS_RATING_CMP_TBL_OLD  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_RATING_CMP_TBL_OLD
(
  INSTITUTION         VARCHAR2(5 BYTE)          NOT NULL,
  RATING_SCHEME       VARCHAR2(10 BYTE)         NOT NULL,
  EFFDT               DATE                      NOT NULL,
  RATING_CMP          VARCHAR2(5 BYTE)          NOT NULL,
  SRC_SYS_ID          VARCHAR2(5 BYTE)          NOT NULL,
  RATING_CMP_TYPE     VARCHAR2(4 BYTE)          NOT NULL,
  DESCR               VARCHAR2(30 BYTE)         NOT NULL,
  DESCRSHORT          VARCHAR2(10 BYTE)         NOT NULL,
  DETERM_METHOD       VARCHAR2(3 BYTE)          NOT NULL,
  FORMULA_ID          VARCHAR2(18 BYTE)         NOT NULL,
  FINAL_CMP_VALUE     VARCHAR2(1 BYTE)          NOT NULL,
  RTNG_CMP_PROC_ORDR  INTEGER                   NOT NULL,
  REQUIRED            VARCHAR2(8 BYTE)          NOT NULL,
  LOAD_ERROR          VARCHAR2(1 BYTE)          NOT NULL,
  DATA_ORIGIN         VARCHAR2(1 BYTE)          NOT NULL,
  CREATED_EW_DTTM     DATE,
  LASTUPD_EW_DTTM     DATE,
  BATCH_SID           NUMBER(10)                NOT NULL
)
COMPRESS BASIC
/
