DROP TABLE CSSTG_OWNER.PS_T_STDNT_BUDGET_IT CASCADE CONSTRAINTS
/

--
-- PS_T_STDNT_BUDGET_IT  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_T_STDNT_BUDGET_IT
(
  EMPLID              VARCHAR2(11 BYTE)         NOT NULL,
  INSTITUTION         VARCHAR2(5 BYTE)          NOT NULL,
  AID_YEAR            VARCHAR2(4 BYTE)          NOT NULL,
  ACAD_CAREER         VARCHAR2(4 BYTE)          NOT NULL,
  STRM                VARCHAR2(4 BYTE)          NOT NULL,
  EFFDT               DATE                      NOT NULL,
  EFFSEQ              INTEGER                   NOT NULL,
  BGT_ITEM_CATEGORY   VARCHAR2(4 BYTE)          NOT NULL,
  SRC_SYS_ID          VARCHAR2(5 BYTE)          NOT NULL,
  BUDGET_ITEM_CD      VARCHAR2(6 BYTE)          NOT NULL,
  BUDGET_ITEM_AMOUNT  NUMBER(7,2)               NOT NULL,
  OPRID               VARCHAR2(30 BYTE)         NOT NULL,
  PELL_ITEM_AMOUNT    NUMBER(7,2)               NOT NULL,
  SFA_PELITMAMT_LHT   NUMBER(7,2)               NOT NULL,
  BATCH_SID           NUMBER(10)                NOT NULL
)
NOCOMPRESS
/
