DROP TABLE CSSTG_OWNER.PS_CLASS_ASSOC CASCADE CONSTRAINTS
/

--
-- PS_CLASS_ASSOC  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_CLASS_ASSOC
(
  CRSE_ID             VARCHAR2(6 BYTE)          NOT NULL,
  CRSE_OFFER_NBR      INTEGER                   NOT NULL,
  STRM                VARCHAR2(4 BYTE)          NOT NULL,
  SESSION_CODE        VARCHAR2(3 BYTE)          NOT NULL,
  ASSOCIATED_CLASS    INTEGER                   NOT NULL,
  SRC_SYS_ID          VARCHAR2(5 BYTE)          NOT NULL,
  UNITS_MINIMUM       NUMBER(5,2)               NOT NULL,
  UNITS_MAXIMUM       NUMBER(5,2)               NOT NULL,
  UNITS_ACAD_PROG     NUMBER(5,2)               NOT NULL,
  UNITS_FINAID_PROG   NUMBER(5,2)               NOT NULL,
  GRADING_BASIS       VARCHAR2(3 BYTE)          NOT NULL,
  GRADE_ROSTER_PRINT  VARCHAR2(1 BYTE)          NOT NULL,
  SSR_COMPONENT       VARCHAR2(3 BYTE)          NOT NULL,
  BILLING_FACTOR      NUMBER(5,3)               NOT NULL,
  CRSE_CONTACT_HRS    NUMBER(5,2)               NOT NULL,
  RQRMNT_GROUP        VARCHAR2(6 BYTE)          NOT NULL,
  USE_CATLG_RQS       VARCHAR2(1 BYTE)          NOT NULL,
  RQMNT_DESIGNTN      VARCHAR2(4 BYTE)          NOT NULL,
  CRSE_COUNT          NUMBER(4,2)               NOT NULL,
  INSTRUCTOR_EDIT     VARCHAR2(2 BYTE)          NOT NULL,
  USE_BLIND_GRADING   VARCHAR2(1 BYTE)          NOT NULL,
  SEL_GROUP           VARCHAR2(10 BYTE)         NOT NULL,
  COMPONENT_PRIMARY   VARCHAR2(3 BYTE)          NOT NULL,
  UPDATE_STDNT_ENRL   VARCHAR2(1 BYTE)          NOT NULL,
  LOAD_ERROR          VARCHAR2(1 BYTE)          NOT NULL,
  DATA_ORIGIN         VARCHAR2(1 BYTE)          NOT NULL,
  CREATED_EW_DTTM     DATE,
  LASTUPD_EW_DTTM     DATE,
  BATCH_SID           NUMBER(10)                NOT NULL
)
COMPRESS BASIC
/
