DROP TABLE CSSTG_OWNER.PS_T_RESIDENCY_APEAL CASCADE CONSTRAINTS
/

--
-- PS_T_RESIDENCY_APEAL  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_T_RESIDENCY_APEAL
(
  EMPLID          VARCHAR2(11 BYTE)             NOT NULL,
  ACAD_CAREER     VARCHAR2(4 BYTE)              NOT NULL,
  INSTITUTION     VARCHAR2(5 BYTE)              NOT NULL,
  EFFECTIVE_TERM  VARCHAR2(4 BYTE)              NOT NULL,
  EFFDT           DATE                          NOT NULL,
  APPEAL_STATUS   VARCHAR2(1 BYTE)              NOT NULL,
  COMMENTS        VARCHAR2(4000 BYTE),
  SRC_SCN         NUMBER
)
NOCOMPRESS
/
