DROP TABLE CSSTG_OWNER.PS_S_SET_CNTRL_GRP_OLD CASCADE CONSTRAINTS
/

--
-- PS_S_SET_CNTRL_GRP_OLD  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_S_SET_CNTRL_GRP_OLD
(
  SETCNTRLVALUE    VARCHAR2(20 BYTE)            NOT NULL,
  REC_GROUP_ID     VARCHAR2(10 BYTE)            NOT NULL,
  SRC_SYS_ID       VARCHAR2(5 BYTE)             NOT NULL,
  SETID            VARCHAR2(5 BYTE)             NOT NULL,
  LOAD_ERROR       VARCHAR2(1 BYTE)             NOT NULL,
  DATA_ORIGIN      VARCHAR2(1 BYTE)             NOT NULL,
  CREATED_EW_DTTM  DATE,
  LASTUPD_EW_DTTM  DATE,
  BATCH_SID        NUMBER(10)                   NOT NULL
)
COMPRESS BASIC
/
