DROP TABLE CSSTG_OWNER.PS_RQMNT_DESIG_TBL CASCADE CONSTRAINTS
/

--
-- PS_RQMNT_DESIG_TBL  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_RQMNT_DESIG_TBL
(
  RQMNT_DESIGNTN      VARCHAR2(4 BYTE)          NOT NULL,
  EFFDT               DATE                      NOT NULL,
  SRC_SYS_ID          VARCHAR2(5 BYTE)          NOT NULL,
  EFF_STATUS          VARCHAR2(1 BYTE)          NOT NULL,
  DESCR               VARCHAR2(30 BYTE)         NOT NULL,
  DESCRSHORT          VARCHAR2(10 BYTE)         NOT NULL,
  DESCRFORMAL         VARCHAR2(50 BYTE)         NOT NULL,
  CATALOG_PRINT       VARCHAR2(1 BYTE)          NOT NULL,
  SCHEDULE_PRINT      VARCHAR2(1 BYTE)          NOT NULL,
  TSCRPT_PRINT        VARCHAR2(1 BYTE)          NOT NULL,
  AT_STDNT_OPTION     VARCHAR2(1 BYTE)          NOT NULL,
  ACAD_PLAN           VARCHAR2(10 BYTE)         NOT NULL,
  SEPARATE_CRSE_GRD   VARCHAR2(1 BYTE)          NOT NULL,
  INSTITUTION         VARCHAR2(5 BYTE)          NOT NULL,
  SAA_DISPLAY_OPTION  VARCHAR2(1 BYTE)          NOT NULL,
  LOAD_ERROR          VARCHAR2(1 BYTE)          NOT NULL,
  DATA_ORIGIN         VARCHAR2(1 BYTE)          NOT NULL,
  CREATED_EW_DTTM     DATE,
  LASTUPD_EW_DTTM     DATE,
  BATCH_SID           NUMBER(10)                NOT NULL
)
COMPRESS BASIC
/
