DROP TABLE CSSTG_OWNER.UM_JOB_STATS CASCADE CONSTRAINTS
/

--
-- UM_JOB_STATS  (Table) 
--
CREATE TABLE CSSTG_OWNER.UM_JOB_STATS
(
  PROJECT       VARCHAR2(50 BYTE)               NOT NULL,
  JOB_NBR       VARCHAR2(20 BYTE)               NOT NULL,
  JOB_NAME      VARCHAR2(150 BYTE)              NOT NULL,
  JOB_STATUS    VARCHAR2(25 BYTE)               NOT NULL,
  START_TIME    VARCHAR2(250 BYTE)              NOT NULL,
  END_TIME      VARCHAR2(250 BYTE),
  ELAPSED_TIME  VARCHAR2(250 BYTE),
  CATEGORY      VARCHAR2(250 BYTE),
  JOB_LOG       VARCHAR2(4000 BYTE)
)
COMPRESS BASIC
/
