DROP TABLE CSSTG_OWNER.PS_SSS_CRSE_PLNR CASCADE CONSTRAINTS
/

--
-- PS_SSS_CRSE_PLNR  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_SSS_CRSE_PLNR
(
  EMPLID             VARCHAR2(11 BYTE)          NOT NULL,
  ACAD_CAREER        VARCHAR2(4 BYTE)           NOT NULL,
  INSTITUTION        VARCHAR2(5 BYTE)           NOT NULL,
  SAA_PLNR_SEQ       INTEGER                    NOT NULL,
  SAA_PLNR_CRSE_SEQ  INTEGER                    NOT NULL,
  SRC_SYS_ID         VARCHAR2(5 BYTE)           NOT NULL,
  CRSE_ID            VARCHAR2(6 BYTE)           NOT NULL,
  CRSE_OFFER_NBR     INTEGER                    NOT NULL,
  CRS_TOPIC_ID       INTEGER                    NOT NULL,
  SUBJECT            VARCHAR2(8 BYTE)           NOT NULL,
  CATALOG_NBR        VARCHAR2(10 BYTE)          NOT NULL,
  UNT_TAKEN          NUMBER(5,2)                NOT NULL,
  STRM               VARCHAR2(4 BYTE)           NOT NULL,
  SAA_ADD_RG         VARCHAR2(6 BYTE),
  SAA_ADD_RQ         VARCHAR2(9 BYTE),
  SAA_ADD_RQL        VARCHAR2(4 BYTE),
  SAA_USED_RG        VARCHAR2(6 BYTE),
  SAA_USED_RQ        VARCHAR2(9 BYTE),
  SAA_USED_RQL       VARCHAR2(4 BYTE),
  LASTUPDOPRID       VARCHAR2(30 BYTE),
  LASTUPDDTTM        DATE,
  LOAD_ERROR         VARCHAR2(1 BYTE)           NOT NULL,
  DATA_ORIGIN        VARCHAR2(1 BYTE)           NOT NULL,
  CREATED_EW_DTTM    DATE,
  LASTUPD_EW_DTTM    DATE,
  BATCH_SID          NUMBER(10)                 NOT NULL
)
COMPRESS BASIC
/
