DROP TABLE CSSTG_OWNER.PS_PMT_CHRG_TBL CASCADE CONSTRAINTS
/

--
-- PS_PMT_CHRG_TBL  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_PMT_CHRG_TBL
(
  SETID             VARCHAR2(5 BYTE)            NOT NULL,
  CHARGE_PRIORITY   VARCHAR2(8 BYTE)            NOT NULL,
  EFFDT             DATE                        NOT NULL,
  SRC_SYS_ID        VARCHAR2(5 BYTE)            NOT NULL,
  EFF_STATUS        VARCHAR2(1 BYTE)            NOT NULL,
  DESCR             VARCHAR2(30 BYTE)           NOT NULL,
  DESCRSHORT        VARCHAR2(10 BYTE)           NOT NULL,
  TREE_NAME         VARCHAR2(18 BYTE)           NOT NULL,
  DESCR254A         VARCHAR2(254 BYTE)          NOT NULL,
  WAIVER_FORM       VARCHAR2(10 BYTE)           NOT NULL,
  SSF_USE_AID_YEAR  VARCHAR2(1 BYTE)            NOT NULL,
  LOAD_ERROR        VARCHAR2(1 BYTE)            NOT NULL,
  DATA_ORIGIN       VARCHAR2(1 BYTE)            NOT NULL,
  CREATED_EW_DTTM   DATE,
  LASTUPD_EW_DTTM   DATE,
  BATCH_SID         NUMBER(10)                  NOT NULL
)
COMPRESS BASIC
/
