DROP TABLE CSSTG_OWNER.PS_PERS_APPL_INFO_OLD CASCADE CONSTRAINTS
/

--
-- PS_PERS_APPL_INFO_OLD  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_PERS_APPL_INFO_OLD
(
  EMPLID           VARCHAR2(11 BYTE)            NOT NULL,
  EFFDT            DATE                         NOT NULL,
  SRC_SYS_ID       VARCHAR2(5 BYTE)             NOT NULL,
  HRS_PERSON_ID    NUMBER(15)                   NOT NULL,
  HRS_PROFILE_SEQ  INTEGER                      NOT NULL,
  LOAD_ERROR       VARCHAR2(1 BYTE)             NOT NULL,
  DATA_ORIGIN      VARCHAR2(1 BYTE)             NOT NULL,
  CREATED_EW_DTTM  DATE,
  LASTUPD_EW_DTTM  DATE,
  BATCH_SID        NUMBER(10)                   NOT NULL
)
COMPRESS BASIC
/
