DROP TABLE CSSTG_OWNER.PS_ACAD_HISTORY CASCADE CONSTRAINTS
/

--
-- PS_ACAD_HISTORY  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_ACAD_HISTORY
(
  EMPLID           VARCHAR2(11 BYTE)            NOT NULL,
  EXT_ORG_ID       VARCHAR2(11 BYTE)            NOT NULL,
  SRC_SYS_ID       VARCHAR2(5 BYTE)             NOT NULL,
  CHKLST_ITM_UPDT  VARCHAR2(1 BYTE)             NOT NULL,
  LOAD_ERROR       VARCHAR2(1 BYTE)             NOT NULL,
  DATA_ORIGIN      VARCHAR2(1 BYTE)             NOT NULL,
  CREATED_EW_DTTM  DATE,
  LASTUPD_EW_DTTM  DATE,
  BATCH_SID        NUMBER(10)                   NOT NULL
)
COMPRESS BASIC
/
