DROP TABLE CSSTG_OWNER.PS_T_STDNT_GRPS_HIST CASCADE CONSTRAINTS
/

--
-- PS_T_STDNT_GRPS_HIST  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_T_STDNT_GRPS_HIST
(
  EMPLID       VARCHAR2(11 BYTE)                NOT NULL,
  INSTITUTION  VARCHAR2(5 BYTE)                 NOT NULL,
  STDNT_GROUP  VARCHAR2(4 BYTE)                 NOT NULL,
  EFFDT        DATE                             NOT NULL,
  SRC_SYS_ID   VARCHAR2(5 BYTE)                 NOT NULL,
  EFF_STATUS   VARCHAR2(1 BYTE)                 NOT NULL,
  COMMENTS     VARCHAR2(4000 BYTE),
  SRC_SCN      NUMBER
)
COMPRESS BASIC
/
