DROP TABLE CSSTG_OWNER.PS_K_STDNT_FA_TERM CASCADE CONSTRAINTS
/

--
-- PS_K_STDNT_FA_TERM  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_K_STDNT_FA_TERM
(
  EMPLID       VARCHAR2(11 BYTE)                NOT NULL,
  INSTITUTION  VARCHAR2(5 BYTE)                 NOT NULL,
  STRM         VARCHAR2(4 BYTE)                 NOT NULL,
  EFFDT        DATE                             NOT NULL,
  EFFSEQ       INTEGER                          NOT NULL,
  SRC_SYS_ID   VARCHAR2(5 BYTE)                 NOT NULL
)
NOCOMPRESS
/
