DROP TABLE CSSTG_OWNER.PS_K_ITEM_SF CASCADE CONSTRAINTS
/

--
-- PS_K_ITEM_SF  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_K_ITEM_SF
(
  BUSINESS_UNIT  VARCHAR2(5 BYTE)               NOT NULL,
  COMMON_ID      VARCHAR2(11 BYTE)              NOT NULL,
  SA_ID_TYPE     VARCHAR2(1 BYTE)               NOT NULL,
  ITEM_NBR       VARCHAR2(15 BYTE)              NOT NULL,
  SRC_SYS_ID     VARCHAR2(5 BYTE)               NOT NULL
)
NOCOMPRESS
/
