DROP TABLE CSSTG_OWNER.PS_T_PERSON_CHECKLST CASCADE CONSTRAINTS
/

--
-- PS_T_PERSON_CHECKLST  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_T_PERSON_CHECKLST
(
  COMMON_ID         VARCHAR2(11 BYTE)           NOT NULL,
  SEQ_3C            INTEGER                     NOT NULL,
  SRC_SYS_ID        VARCHAR2(5 BYTE)            NOT NULL,
  SA_ID_TYPE        VARCHAR2(1 BYTE)            NOT NULL,
  CHECKLIST_DTTM    DATE                        NOT NULL,
  ADMIN_FUNCTION    VARCHAR2(4 BYTE)            NOT NULL,
  CHECKLIST_CD      VARCHAR2(6 BYTE)            NOT NULL,
  CHECKLIST_STATUS  VARCHAR2(1 BYTE)            NOT NULL,
  STATUS_DT         DATE,
  STATUS_CHANGE_ID  VARCHAR2(11 BYTE)           NOT NULL,
  DUE_DT            DATE,
  CURRENCY_CD       VARCHAR2(3 BYTE)            NOT NULL,
  DUE_AMT           NUMBER(16,2)                NOT NULL,
  DEPTID            VARCHAR2(10 BYTE)           NOT NULL,
  RESPONSIBLE_ID    VARCHAR2(11 BYTE)           NOT NULL,
  INSTITUTION       VARCHAR2(5 BYTE)            NOT NULL,
  TRACKING_SEQ      INTEGER                     NOT NULL,
  ORG_CONTACT       INTEGER                     NOT NULL,
  CONTACT_NAME      VARCHAR2(50 BYTE)           NOT NULL,
  VAR_DATA_SEQ      INTEGER                     NOT NULL,
  COMM_COMMENTS     VARCHAR2(4000 BYTE),
  SRC_SCN           NUMBER
)
COMPRESS BASIC
/
