DROP TABLE CSSTG_OWNER.PS_SCTN_CMBND_TBL CASCADE CONSTRAINTS
/

--
-- PS_SCTN_CMBND_TBL  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_SCTN_CMBND_TBL
(
  INSTITUTION       VARCHAR2(5 BYTE)            NOT NULL,
  STRM              VARCHAR2(4 BYTE)            NOT NULL,
  SESSION_CODE      VARCHAR2(3 BYTE)            NOT NULL,
  SCTN_COMBINED_ID  VARCHAR2(4 BYTE)            NOT NULL,
  SRC_SYS_ID        VARCHAR2(5 BYTE)            NOT NULL,
  DESCR             VARCHAR2(30 BYTE)           NOT NULL,
  DESCRSHORT        VARCHAR2(10 BYTE)           NOT NULL,
  ENRL_CAP          INTEGER                     NOT NULL,
  ENRL_TOT          INTEGER                     NOT NULL,
  WAIT_CAP          INTEGER                     NOT NULL,
  WAIT_TOT          INTEGER                     NOT NULL,
  ROOM_CAP_REQUEST  INTEGER                     NOT NULL,
  PERM_COMBINATION  VARCHAR2(1 BYTE)            NOT NULL,
  COMBINATION_TYPE  VARCHAR2(2 BYTE)            NOT NULL,
  SKIP_MTGPAT_EDIT  VARCHAR2(1 BYTE)            NOT NULL,
  LOAD_ERROR        VARCHAR2(1 BYTE)            NOT NULL,
  DATA_ORIGIN       VARCHAR2(1 BYTE)            NOT NULL,
  CREATED_EW_DTTM   DATE,
  LASTUPD_EW_DTTM   DATE,
  BATCH_SID         NUMBER(10)                  NOT NULL
)
COMPRESS BASIC
/
