DROP TABLE CSSTG_OWNER.PS_SFA_ASG_CIP_CD CASCADE CONSTRAINTS
/

--
-- PS_SFA_ASG_CIP_CD  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_SFA_ASG_CIP_CD
(
  AID_YEAR            VARCHAR2(4 BYTE)          NOT NULL,
  SFA_COD_PROGCIP_CD  VARCHAR2(7 BYTE)          NOT NULL,
  SRC_SYS_ID          VARCHAR2(5 BYTE)          NOT NULL,
  EFF_STATUS          VARCHAR2(1 BYTE)          NOT NULL,
  DESCR254            VARCHAR2(254 BYTE)        NOT NULL,
  LOAD_ERROR          VARCHAR2(1 BYTE)          NOT NULL,
  DATA_ORIGIN         VARCHAR2(1 BYTE)          NOT NULL,
  CREATED_EW_DTTM     DATE,
  LASTUPD_EW_DTTM     DATE,
  BATCH_SID           NUMBER(10)                NOT NULL
)
COMPRESS BASIC
/
