DROP TABLE CSSTG_OWNER.PS_EXT_COURSE CASCADE CONSTRAINTS
/

--
-- PS_EXT_COURSE  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_EXT_COURSE
(
  EMPLID             VARCHAR2(11 BYTE)          NOT NULL,
  EXT_ORG_ID         VARCHAR2(11 BYTE)          NOT NULL,
  EXT_COURSE_NBR     INTEGER                    NOT NULL,
  SRC_SYS_ID         VARCHAR2(5 BYTE)           NOT NULL,
  EXT_CRSE_TYPE      VARCHAR2(3 BYTE)           NOT NULL,
  LS_DATA_SOURCE     VARCHAR2(3 BYTE)           NOT NULL,
  EXT_DATA_NBR       INTEGER                    NOT NULL,
  BEGIN_DT           DATE,
  END_DT             DATE,
  EXT_TERM_TYPE      VARCHAR2(4 BYTE)           NOT NULL,
  UNT_TAKEN          NUMBER(5,2)                NOT NULL,
  GRADING_SCHEME     VARCHAR2(3 BYTE)           NOT NULL,
  GRADING_BASIS      VARCHAR2(3 BYTE)           NOT NULL,
  COURSE_LEVEL       VARCHAR2(2 BYTE)           NOT NULL,
  CRSE_GRADE_INPUT   VARCHAR2(3 BYTE)           NOT NULL,
  CRSE_GRADE_OFF     VARCHAR2(3 BYTE)           NOT NULL,
  SCHOOL_SUBJECT     VARCHAR2(8 BYTE)           NOT NULL,
  SCHOOL_CRSE_NBR    VARCHAR2(10 BYTE)          NOT NULL,
  EXT_SUBJECT_AREA   VARCHAR2(4 BYTE)           NOT NULL,
  EXT_CAREER         VARCHAR2(4 BYTE)           NOT NULL,
  EXT_TERM           VARCHAR2(4 BYTE)           NOT NULL,
  TERM_YEAR          INTEGER                    NOT NULL,
  DESCR              VARCHAR2(30 BYTE)          NOT NULL,
  UNT_TYPE           VARCHAR2(3 BYTE)           NOT NULL,
  INSTITUTION        VARCHAR2(5 BYTE)           NOT NULL,
  EXT_ACAD_LEVEL     VARCHAR2(4 BYTE)           NOT NULL,
  TRANS_CREDIT_FLAG  VARCHAR2(1 BYTE)           NOT NULL,
  CAN_TRNS_TYPE      VARCHAR2(2 BYTE)           NOT NULL,
  LASTUPDDTTM        DATE,
  LASTUPDOPRID       VARCHAR2(30 BYTE)          NOT NULL,
  LOAD_ERROR         VARCHAR2(1 BYTE)           NOT NULL,
  DATA_ORIGIN        VARCHAR2(1 BYTE)           NOT NULL,
  CREATED_EW_DTTM    DATE,
  LASTUPD_EW_DTTM    DATE,
  BATCH_SID          NUMBER(10)                 NOT NULL
)
COMPRESS BASIC
/
