DROP TABLE CSSTG_OWNER.PS_ACAD_SUBPLN_TBL CASCADE CONSTRAINTS
/

--
-- PS_ACAD_SUBPLN_TBL  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_ACAD_SUBPLN_TBL
(
  INSTITUTION         VARCHAR2(5 BYTE)          NOT NULL,
  ACAD_PLAN           VARCHAR2(10 BYTE)         NOT NULL,
  ACAD_SUB_PLAN       VARCHAR2(10 BYTE)         NOT NULL,
  EFFDT               DATE                      NOT NULL,
  SRC_SYS_ID          VARCHAR2(5 BYTE)          NOT NULL,
  EFF_STATUS          VARCHAR2(1 BYTE)          NOT NULL,
  ACAD_SUBPLAN_TYPE   VARCHAR2(3 BYTE)          NOT NULL,
  DESCR               VARCHAR2(30 BYTE)         NOT NULL,
  DESCRSHORT          VARCHAR2(10 BYTE)         NOT NULL,
  SUBPLN_REQTRM_DFLT  VARCHAR2(1 BYTE)          NOT NULL,
  DIPLOMA_DESCR       VARCHAR2(100 BYTE)        NOT NULL,
  DIPLOMA_PRINT_FL    VARCHAR2(1 BYTE)          NOT NULL,
  DIPLOMA_INDENT      INTEGER                   NOT NULL,
  TRNSCR_DESCR        VARCHAR2(100 BYTE)        NOT NULL,
  TRNSCR_PRINT_FL     VARCHAR2(1 BYTE)          NOT NULL,
  TRNSCR_INDENT       INTEGER                   NOT NULL,
  FIRST_TERM_VALID    VARCHAR2(4 BYTE)          NOT NULL,
  CIP_CODE            VARCHAR2(13 BYTE)         NOT NULL,
  HEGIS_CODE          VARCHAR2(8 BYTE)          NOT NULL,
  TRANSCRIPT_LEVEL    VARCHAR2(2 BYTE)          NOT NULL,
  EVALUATE_SUBPLAN    VARCHAR2(1 BYTE)          NOT NULL,
  SSR_LAST_PRS_DT     DATE,
  SSR_LAST_ADM_TERM   VARCHAR2(4 BYTE)          NOT NULL,
  LOAD_ERROR          VARCHAR2(1 BYTE)          NOT NULL,
  DATA_ORIGIN         VARCHAR2(1 BYTE)          NOT NULL,
  CREATED_EW_DTTM     DATE,
  LASTUPD_EW_DTTM     DATE,
  BATCH_SID           NUMBER(10)                NOT NULL
)
COMPRESS BASIC
/
