DROP TABLE CSSTG_OWNER.PS_EXT_DEGREE CASCADE CONSTRAINTS
/

--
-- PS_EXT_DEGREE  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_EXT_DEGREE
(
  EMPLID            VARCHAR2(11 BYTE)           NOT NULL,
  EXT_ORG_ID        VARCHAR2(11 BYTE)           NOT NULL,
  EXT_DEGREE_NBR    INTEGER                     NOT NULL,
  SRC_SYS_ID        VARCHAR2(5 BYTE)            NOT NULL,
  DEGREE            VARCHAR2(8 BYTE)            NOT NULL,
  DESCR             VARCHAR2(30 BYTE)           NOT NULL,
  DEGREE_DT         DATE                        NOT NULL,
  DEGREE_STATUS     VARCHAR2(1 BYTE)            NOT NULL,
  HONORS_CATEGORY   VARCHAR2(4 BYTE)            NOT NULL,
  EXT_SUBJ_AREA_1   VARCHAR2(4 BYTE)            NOT NULL,
  EXT_SUBJ_AREA_2   VARCHAR2(4 BYTE)            NOT NULL,
  FIELD_OF_STUDY_1  VARCHAR2(30 BYTE)           NOT NULL,
  FIELD_OF_STUDY_2  VARCHAR2(30 BYTE)           NOT NULL,
  EXT_CAREER        VARCHAR2(4 BYTE)            NOT NULL,
  EXT_DATA_NBR      INTEGER                     NOT NULL,
  LS_DATA_SOURCE    VARCHAR2(3 BYTE)            NOT NULL,
  LOAD_ERROR        VARCHAR2(1 BYTE)            NOT NULL,
  DATA_ORIGIN       VARCHAR2(1 BYTE)            NOT NULL,
  CREATED_EW_DTTM   DATE,
  LASTUPD_EW_DTTM   DATE,
  BATCH_SID         NUMBER(10)                  NOT NULL
)
COMPRESS BASIC
/
