DROP TABLE CSSTG_OWNER.PS_PERS_DATA_USF_OLD CASCADE CONSTRAINTS
/

--
-- PS_PERS_DATA_USF_OLD  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_PERS_DATA_USF_OLD
(
  EMPLID              VARCHAR2(11 BYTE)         NOT NULL,
  EFFDT               DATE                      NOT NULL,
  SRC_SYS_ID          VARCHAR2(5 BYTE)          NOT NULL,
  GVT_CRED_MIL_SVCE   VARCHAR2(4 BYTE)          NOT NULL,
  GVT_MILITARY_COMP   VARCHAR2(1 BYTE)          NOT NULL,
  GVT_MIL_GRADE       VARCHAR2(3 BYTE)          NOT NULL,
  GVT_MIL_RESRVE_CAT  VARCHAR2(1 BYTE)          NOT NULL,
  GVT_MIL_SEP_RET     VARCHAR2(1 BYTE)          NOT NULL,
  GVT_MIL_SVCE_END    DATE,
  GVT_MIL_SVCE_START  DATE,
  GVT_MIL_VERIFY      VARCHAR2(1 BYTE)          NOT NULL,
  GVT_PAR_NBR_LAST    INTEGER                   NOT NULL,
  GVT_UNIF_SVC_CTR    VARCHAR2(1 BYTE)          NOT NULL,
  GVT_VET_PREF_APPT   VARCHAR2(1 BYTE)          NOT NULL,
  GVT_VET_PREF_RIF    VARCHAR2(1 BYTE)          NOT NULL,
  GVT_CHANGE_FLAG     VARCHAR2(1 BYTE)          NOT NULL,
  GVT_DRAFT_STATUS    VARCHAR2(1 BYTE)          NOT NULL,
  GVT_YR_ATTAINED     DATE,
  DISABLED_VET        VARCHAR2(1 BYTE)          NOT NULL,
  DISABLED            VARCHAR2(1 BYTE)          NOT NULL,
  GVT_DISABILITY_CD   VARCHAR2(2 BYTE)          NOT NULL,
  GRADE               VARCHAR2(3 BYTE)          NOT NULL,
  SAL_ADMIN_PLAN      VARCHAR2(4 BYTE)          NOT NULL,
  GVT_CURR_AGCY_EMPL  VARCHAR2(1 BYTE)          NOT NULL,
  GVT_CURR_FED_EMPL   VARCHAR2(1 BYTE)          NOT NULL,
  GVT_HIGH_PAY_PLAN   VARCHAR2(3 BYTE)          NOT NULL,
  GVT_HIGH_GRADE      VARCHAR2(3 BYTE)          NOT NULL,
  GVT_PREV_AGCY_EMPL  VARCHAR2(1 BYTE)          NOT NULL,
  GVT_PREV_FED_EMPL   VARCHAR2(1 BYTE)          NOT NULL,
  GVT_SEP_INCENTIVE   VARCHAR2(1 BYTE)          NOT NULL,
  GVT_SEP_INCENT_DT   DATE,
  GVT_TENURE          VARCHAR2(1 BYTE)          NOT NULL,
  GVT_PAY_PLAN        VARCHAR2(2 BYTE)          NOT NULL,
  BARG_UNIT           VARCHAR2(4 BYTE)          NOT NULL,
  LOAD_ERROR          VARCHAR2(1 BYTE)          NOT NULL,
  DATA_ORIGIN         VARCHAR2(1 BYTE)          NOT NULL,
  CREATED_EW_DTTM     DATE,
  LASTUPD_EW_DTTM     DATE,
  BATCH_SID           NUMBER(10)                NOT NULL
)
COMPRESS BASIC
/
