DROP TABLE CSSTG_OWNER.PS_S_CURR_CD_TBL_OLD CASCADE CONSTRAINTS
/

--
-- PS_S_CURR_CD_TBL_OLD  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_S_CURR_CD_TBL_OLD
(
  CURRENCY_CD        VARCHAR2(3 BYTE)           NOT NULL,
  EFFDT              DATE                       NOT NULL,
  SRC_SYS_ID         VARCHAR2(5 BYTE)           NOT NULL,
  EFF_STATUS         VARCHAR2(1 BYTE)           NOT NULL,
  DESCR              VARCHAR2(30 BYTE)          NOT NULL,
  DESCRSHORT         VARCHAR2(10 BYTE)          NOT NULL,
  COUNTRY            VARCHAR2(3 BYTE)           NOT NULL,
  CUR_SYMBOL         VARCHAR2(4 BYTE)           NOT NULL,
  DECIMAL_POSITIONS  INTEGER                    NOT NULL,
  SCALE_POSITIONS    INTEGER                    NOT NULL,
  SYNCID             INTEGER                    NOT NULL,
  LASTUPDDTTM        DATE,
  TIMEZONE           VARCHAR2(9 BYTE)           NOT NULL,
  LOAD_ERROR         VARCHAR2(1 BYTE)           NOT NULL,
  DATA_ORIGIN        VARCHAR2(1 BYTE)           NOT NULL,
  CREATED_EW_DTTM    DATE,
  LASTUPD_EW_DTTM    DATE,
  BATCH_SID          NUMBER(10)                 NOT NULL
)
NOCOMPRESS
/
