DROP TABLE CSSTG_OWNER.PS_T_ACAD_PLAN_TBL CASCADE CONSTRAINTS
/

--
-- PS_T_ACAD_PLAN_TBL  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_T_ACAD_PLAN_TBL
(
  INSTITUTION         VARCHAR2(5 BYTE)          NOT NULL,
  ACAD_PLAN           VARCHAR2(10 BYTE)         NOT NULL,
  EFFDT               DATE                      NOT NULL,
  SRC_SYS_ID          VARCHAR2(5 BYTE)          NOT NULL,
  EFF_STATUS          VARCHAR2(1 BYTE)          NOT NULL,
  DESCR               VARCHAR2(30 BYTE)         NOT NULL,
  DESCRSHORT          VARCHAR2(10 BYTE)         NOT NULL,
  ACAD_PLAN_TYPE      VARCHAR2(3 BYTE)          NOT NULL,
  ACAD_PROG           VARCHAR2(5 BYTE)          NOT NULL,
  PLN_REQTRM_DFLT     VARCHAR2(1 BYTE)          NOT NULL,
  DEGREE              VARCHAR2(8 BYTE)          NOT NULL,
  DIPLOMA_DESCR       VARCHAR2(100 BYTE)        NOT NULL,
  DIPLOMA_PRINT_FL    VARCHAR2(1 BYTE)          NOT NULL,
  DIPLOMA_INDENT      INTEGER                   NOT NULL,
  TRNSCR_DESCR        VARCHAR2(100 BYTE)        NOT NULL,
  TRNSCR_PRINT_FL     VARCHAR2(1 BYTE)          NOT NULL,
  TRNSCR_INDENT       INTEGER                   NOT NULL,
  FIRST_TERM_VALID    VARCHAR2(4 BYTE)          NOT NULL,
  CIP_CODE            VARCHAR2(13 BYTE)         NOT NULL,
  HEGIS_CODE          VARCHAR2(8 BYTE)          NOT NULL,
  ACAD_CAREER         VARCHAR2(4 BYTE)          NOT NULL,
  TRANSCRIPT_LEVEL    VARCHAR2(2 BYTE)          NOT NULL,
  STUDY_FIELD         VARCHAR2(10 BYTE)         NOT NULL,
  EVALUATE_PLAN       VARCHAR2(1 BYTE)          NOT NULL,
  SSR_LAST_PRS_DT     DATE,
  SSR_LAST_ADM_TERM   VARCHAR2(4 BYTE),
  SAA_WHIF_DISP_ADVR  VARCHAR2(1 BYTE),
  SAA_WHIF_DISP_PREM  VARCHAR2(1 BYTE),
  SAA_WHIF_DISP_STD   VARCHAR2(1 BYTE),
  SSR_NSC_CRD_LVL     VARCHAR2(1 BYTE),
  SSR_PROG_LEN_TYPE   VARCHAR2(1 BYTE),
  SSR_PROG_LENGTH     NUMBER(6,3),
  SFA_SPEC_PROG_FLG   VARCHAR2(1 BYTE),
  SSR_NSC_INCL_PLAN   VARCHAR2(1 BYTE),
  DESCRLONG           VARCHAR2(4000 BYTE),
  SRC_SCN             NUMBER
)
COMPRESS BASIC
/
