DROP TABLE CSSTG_OWNER.UM_SF_AMH_TUITION_WVR_STG CASCADE CONSTRAINTS
/

--
-- UM_SF_AMH_TUITION_WVR_STG  (Table) 
--
CREATE TABLE CSSTG_OWNER.UM_SF_AMH_TUITION_WVR_STG
(
  INSTITUTION_CD            VARCHAR2(5 BYTE)    NOT NULL,
  ITEM_TERM                 VARCHAR2(4 BYTE)    NOT NULL,
  ITEM_TERM_LD              VARCHAR2(30 BYTE)   NOT NULL,
  PERSON_ID                 VARCHAR2(11 BYTE)   NOT NULL,
  FIRST_NAME                VARCHAR2(30 BYTE),
  LAST_NAME                 VARCHAR2(30 BYTE),
  ITEM_TYPE                 VARCHAR2(12 BYTE)   NOT NULL,
  ITEM_TYPE_LD              VARCHAR2(30 BYTE),
  ACAD_CAREER               VARCHAR2(4 BYTE)    NOT NULL,
  ACAD_YEAR                 VARCHAR2(4 BYTE),
  SPONSOR_ID                VARCHAR2(20 BYTE),
  EMPLOYEE_TYPE             VARCHAR2(30 BYTE),
  ITEM_AMT                  NUMBER(16,2),
  AMOUNT_TYPE               VARCHAR2(30 BYTE),
  DAY_CE_FLAG               VARCHAR2(30 BYTE),
  TAXABLE_FLAG              VARCHAR2(30 BYTE),
  STUDENT_IS_EMPLOYEE_FLAG  VARCHAR2(30 BYTE),
  PARTITION_KEY             VARCHAR2(10 BYTE),
  CREATED_EW_DTTM           DATE
)
NOCOMPRESS 
PARTITION BY LIST (PARTITION_KEY)
(  
  PARTITION UMAFAL2016 VALUES ('UMAFAL2016')
    NOCOMPRESS ,  
  PARTITION UMASPR2017 VALUES ('UMASPR2017')
    NOCOMPRESS ,  
  PARTITION UMAFAL2017 VALUES ('UMAFAL2017')
    NOCOMPRESS ,  
  PARTITION UMASPR2018 VALUES ('UMASPR2018')
    NOCOMPRESS ,  
  PARTITION UMAFAL2018 VALUES ('UMAFAL2018')
    NOCOMPRESS ,  
  PARTITION UMASPR2019 VALUES ('UMASPR2019')
    NOCOMPRESS ,  
  PARTITION UMAFAL2019 VALUES ('UMAFAL2019')
    NOCOMPRESS ,  
  PARTITION UMASPR2020 VALUES ('UMASPR2020')
    NOCOMPRESS ,  
  PARTITION UMAFAL2020 VALUES ('UMAFAL2020')
    NOCOMPRESS ,  
  PARTITION UMASPR2021 VALUES ('UMASPR2021')
    NOCOMPRESS ,  
  PARTITION UMAFAL2021 VALUES ('UMAFAL2021')
    NOCOMPRESS ,  
  PARTITION UMASPR2022 VALUES ('UMASPR2022')
    NOCOMPRESS ,  
  PARTITION UMAFAL2022 VALUES ('UMAFAL2022')
    NOCOMPRESS
)
/


ALTER TABLE CSSTG_OWNER.UM_SF_AMH_TUITION_WVR_STG ADD (
  CONSTRAINT PK_UM_SF_AMH_TUITION_WVR_STG
  PRIMARY KEY
  (INSTITUTION_CD, PERSON_ID, ITEM_TERM_LD, ITEM_TYPE, ACAD_CAREER)
  RELY
  ENABLE VALIDATE)
/
