DROP TABLE CSSTG_OWNER.PS_SAA_ADB_CRSEUSE CASCADE CONSTRAINTS
/

--
-- PS_SAA_ADB_CRSEUSE  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_SAA_ADB_CRSEUSE
(
  EMPLID              VARCHAR2(11 BYTE)         NOT NULL,
  ANALYSIS_DB_SEQ     INTEGER                   NOT NULL,
  SAA_CAREER_RPT      VARCHAR2(4 BYTE)          NOT NULL,
  SAA_ENTRY_SEQ       INTEGER                   NOT NULL,
  SAA_COURSE_SEQ      INTEGER                   NOT NULL,
  CRSE_TAG            VARCHAR2(4 BYTE)          NOT NULL,
  SRC_SYS_ID          VARCHAR2(4 BYTE)          NOT NULL,
  RPT_DATE            DATE,
  SEL_PROCESS_TYPE    VARCHAR2(3 BYTE),
  SEL_MODE            VARCHAR2(1 BYTE),
  IN_PROGRESS_GRD     VARCHAR2(1 BYTE),
  UNT_TAKEN           NUMBER(5,2),
  UNT_EARNED          NUMBER(5,2),
  CRSE_COUNT          NUMBER(4,2),
  RQ_AA_OVERRIDE      VARCHAR2(9 BYTE),
  ASOF_DATE           DATE,
  DIRCT_TYPE          VARCHAR2(1 BYTE),
  SAA_DISPLAY_OPTION  VARCHAR2(1 BYTE),
  OPRID               VARCHAR2(30 BYTE),
  DESCR254A           VARCHAR2(254 BYTE),
  CREATED_EW_DTTM     DATE
)
COMPRESS BASIC
/


ALTER TABLE CSSTG_OWNER.PS_SAA_ADB_CRSEUSE ADD (
  CONSTRAINT PK_PS_SAA_ADB_CRSEUSE
  PRIMARY KEY
  (EMPLID, ANALYSIS_DB_SEQ, SAA_CAREER_RPT, SAA_ENTRY_SEQ, SAA_COURSE_SEQ, CRSE_TAG, SRC_SYS_ID)
  RELY
  ENABLE VALIDATE)
/
