DROP TABLE CSSTG_OWNER.PS_PERS_DATA_USA CASCADE CONSTRAINTS
/

--
-- PS_PERS_DATA_USA  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_PERS_DATA_USA
(
  EMPLID              VARCHAR2(11 BYTE)         NOT NULL,
  EFFDT               DATE,
  SRC_SYS_ID          VARCHAR2(5 BYTE)          NOT NULL,
  US_WORK_ELIGIBILTY  VARCHAR2(1 BYTE)          NOT NULL,
  MILITARY_STATUS     VARCHAR2(1 BYTE)          NOT NULL,
  CITIZEN_PROOF1      VARCHAR2(10 BYTE)         NOT NULL,
  CITIZEN_PROOF2      VARCHAR2(10 BYTE)         NOT NULL,
  MEDICARE_ENTLD_DT   DATE,
  LOAD_ERROR          VARCHAR2(1 BYTE)          NOT NULL,
  DATA_ORIGIN         VARCHAR2(1 BYTE)          NOT NULL,
  CREATED_EW_DTTM     DATE,
  LASTUPD_EW_DTTM     DATE,
  BATCH_SID           NUMBER(10)                NOT NULL
)
COMPRESS BASIC
/
