DROP TABLE CSSTG_OWNER.PS_CLST_MAIN_TBL CASCADE CONSTRAINTS
/

--
-- PS_CLST_MAIN_TBL  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_CLST_MAIN_TBL
(
  COURSE_LIST      VARCHAR2(9 BYTE)             NOT NULL,
  EFFDT            DATE                         NOT NULL,
  SRC_SYS_ID       VARCHAR2(5 BYTE)             NOT NULL,
  EFF_STATUS       VARCHAR2(1 BYTE)             NOT NULL,
  DESCR            VARCHAR2(30 BYTE),
  DESCRSHORT       VARCHAR2(10 BYTE),
  RQRMNT_USEAGE    VARCHAR2(4 BYTE),
  INSTITUTION      VARCHAR2(5 BYTE),
  ACAD_CAREER      VARCHAR2(4 BYTE),
  ACAD_GROUP       VARCHAR2(5 BYTE),
  ACAD_PROG        VARCHAR2(5 BYTE),
  ACAD_PLAN        VARCHAR2(10 BYTE),
  ACAD_SUB_PLAN    VARCHAR2(10 BYTE),
  SUBJECT          VARCHAR2(8 BYTE),
  CATALOG_NBR      VARCHAR2(10 BYTE),
  DESCR254A        VARCHAR2(254 BYTE),
  LOAD_ERROR       VARCHAR2(1 BYTE)             NOT NULL,
  DATA_ORIGIN      VARCHAR2(1 BYTE)             NOT NULL,
  CREATED_EW_DTTM  DATE,
  LASTUPD_EW_DTTM  DATE,
  BATCH_SID        NUMBER(10)                   NOT NULL
)
COMPRESS BASIC
/
