DROP TABLE CSSTG_OWNER.PS_TRNSFR_SUBJ CASCADE CONSTRAINTS
/

--
-- PS_TRNSFR_SUBJ  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_TRNSFR_SUBJ
(
  INSTITUTION        VARCHAR2(5 BYTE)           NOT NULL,
  TRNSFR_SRC_ID      VARCHAR2(11 BYTE)          NOT NULL,
  COMP_SUBJECT_AREA  VARCHAR2(16 BYTE)          NOT NULL,
  EFFDT              DATE                       NOT NULL,
  SRC_SYS_ID         VARCHAR2(5 BYTE)           NOT NULL,
  EFF_STATUS         VARCHAR2(1 BYTE)           NOT NULL,
  DESCR              VARCHAR2(30 BYTE)          NOT NULL,
  TC_CATLG_ORG_TYPE  VARCHAR2(1 BYTE)           NOT NULL,
  CATALOG_ORG        VARCHAR2(11 BYTE)          NOT NULL,
  TRNSFR_GRADE_FL    VARCHAR2(1 BYTE)           NOT NULL,
  EXT_TERM_TYPE      VARCHAR2(4 BYTE)           NOT NULL,
  GRADE_PTS_MIN      NUMBER(9,3)                NOT NULL,
  GRADE_PTS_MAX      NUMBER(9,3)                NOT NULL,
  UNITS_MINIMUM      NUMBER(5,2)                NOT NULL,
  UNITS_MAXIMUM      NUMBER(5,2)                NOT NULL,
  UNT_TRNSFR_SRC     VARCHAR2(1 BYTE)           NOT NULL,
  CRSE_ID            VARCHAR2(6 BYTE)           NOT NULL,
  RQMNT_DESIGNTN     VARCHAR2(4 BYTE)           NOT NULL,
  LOAD_ERROR         VARCHAR2(1 BYTE)           NOT NULL,
  DATA_ORIGIN        VARCHAR2(1 BYTE)           NOT NULL,
  CREATED_EW_DTTM    DATE,
  LASTUPD_EW_DTTM    DATE,
  BATCH_SID          NUMBER(10)                 NOT NULL
)
COMPRESS BASIC
/
