DROP TABLE CSSTG_OWNER.PS_PERS_DATA_EFFDT CASCADE CONSTRAINTS
/

--
-- PS_PERS_DATA_EFFDT  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_PERS_DATA_EFFDT
(
  EMPLID            VARCHAR2(11 BYTE)           NOT NULL,
  EFFDT             DATE                        NOT NULL,
  SRC_SYS_ID        VARCHAR2(5 BYTE)            NOT NULL,
  MAR_STATUS        VARCHAR2(1 BYTE)            NOT NULL,
  MAR_STATUS_DT     DATE,
  SEX               VARCHAR2(1 BYTE)            NOT NULL,
  HIGHEST_EDUC_LVL  VARCHAR2(2 BYTE)            NOT NULL,
  FT_STUDENT        VARCHAR2(1 BYTE)            NOT NULL,
  LANG_CD           VARCHAR2(3 BYTE)            NOT NULL,
  ALTER_EMPLID      VARCHAR2(11 BYTE)           NOT NULL,
  LASTUPDDTTM       DATE,
  LASTUPDOPRID      VARCHAR2(30 BYTE)           NOT NULL,
  LOAD_ERROR        VARCHAR2(1 BYTE)            NOT NULL,
  DATA_ORIGIN       VARCHAR2(1 BYTE)            NOT NULL,
  CREATED_EW_DTTM   DATE,
  LASTUPD_EW_DTTM   DATE,
  BATCH_SID         NUMBER(10)                  NOT NULL
)
COMPRESS BASIC
/
