DROP TABLE CSSTG_OWNER.PS_CAMPUS_MTG_SEL CASCADE CONSTRAINTS
/

--
-- PS_CAMPUS_MTG_SEL  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_CAMPUS_MTG_SEL
(
  CAMPUS_EVENT_NBR   VARCHAR2(9 BYTE)           NOT NULL,
  CAMPUS_EVENT_ATND  VARCHAR2(5 BYTE)           NOT NULL,
  EVENT_MTG_NBR      INTEGER                    NOT NULL,
  SRC_SYS_ID         VARCHAR2(5 BYTE)           NOT NULL,
  EVNT_ATND_STAT     VARCHAR2(1 BYTE)           NOT NULL,
  EMPLID             VARCHAR2(11 BYTE)          NOT NULL,
  LOAD_ERROR         VARCHAR2(1 BYTE)           NOT NULL,
  DATA_ORIGIN        VARCHAR2(1 BYTE)           NOT NULL,
  CREATED_EW_DTTM    DATE,
  LASTUPD_EW_DTTM    DATE,
  BATCH_SID          NUMBER(10)                 NOT NULL
)
COMPRESS BASIC
/
