DROP TABLE CSSTG_OWNER.PS_STDNT_AWD_PER CASCADE CONSTRAINTS
/

--
-- PS_STDNT_AWD_PER  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_STDNT_AWD_PER
(
  EMPLID              VARCHAR2(11 BYTE)         NOT NULL,
  INSTITUTION         VARCHAR2(5 BYTE)          NOT NULL,
  AID_YEAR            VARCHAR2(4 BYTE)          NOT NULL,
  AWARD_PERIOD        VARCHAR2(1 BYTE)          NOT NULL,
  SRC_SYS_ID          VARCHAR2(5 BYTE)          NOT NULL,
  FED_EFC             INTEGER                   NOT NULL,
  EFC_STATUS          VARCHAR2(1 BYTE)          NOT NULL,
  INST_EFC            INTEGER                   NOT NULL,
  FED_NEED_BASE_AID   NUMBER(8,2)               NOT NULL,
  INST_NEED_BASE_AID  NUMBER(8,2)               NOT NULL,
  FED_YEAR_COA        NUMBER(8,2)               NOT NULL,
  INST_YEAR_COA       NUMBER(8,2)               NOT NULL,
  PELL_YEAR_COA       NUMBER(8,2)               NOT NULL,
  FED_NEED            NUMBER(8,2)               NOT NULL,
  INST_NEED           NUMBER(8,2)               NOT NULL,
  FED_UNMET_NEED      NUMBER(8,2)               NOT NULL,
  FED_OVRAWD_AMT      NUMBER(8,2)               NOT NULL,
  INST_UNMET_NEED     NUMBER(8,2)               NOT NULL,
  INST_OVRAWD_AMT     NUMBER(8,2)               NOT NULL,
  FED_PARENT_CONTRB   INTEGER                   NOT NULL,
  INST_PARENT_CONTRB  INTEGER                   NOT NULL,
  FED_STDNT_CONTRB    INTEGER                   NOT NULL,
  INST_STDNT_CONTRB   INTEGER                   NOT NULL,
  INST_EFC_OVERIDE    VARCHAR2(1 BYTE)          NOT NULL,
  BASE_WEEKS          NUMBER(3,1)               NOT NULL,
  WEEKS_ENROLLED      NUMBER(3,1)               NOT NULL,
  WEEKLY_PC           INTEGER                   NOT NULL,
  WEEKLY_SC           INTEGER                   NOT NULL,
  PRORATED_EFC        INTEGER                   NOT NULL,
  FED_SPECIAL_AID     NUMBER(8,2)               NOT NULL,
  INST_SPECIAL_AID    NUMBER(8,2)               NOT NULL,
  FED_TOTAL_AID       NUMBER(8,2)               NOT NULL,
  INST_TOTAL_AID      NUMBER(8,2)               NOT NULL,
  FED_UNMET_COA       NUMBER(8,2)               NOT NULL,
  INST_UNMET_COA      NUMBER(8,2)               NOT NULL,
  FED_OVRAWD_COA      NUMBER(8,2)               NOT NULL,
  INST_OVRAWD_COA     NUMBER(8,2)               NOT NULL,
  VET_ED_BENEFIT      INTEGER                   NOT NULL,
  VET_ED_FAN_PRINT    VARCHAR2(1 BYTE)          NOT NULL,
  PRORATED_PAR_CNTRB  INTEGER                   NOT NULL,
  PRORATED_STU_CNTRB  INTEGER                   NOT NULL,
  BDGT_DURATION_FED   INTEGER                   NOT NULL,
  BDGT_DURATION_INST  NUMBER(3,1)               NOT NULL,
  FANLTR_STATUS       VARCHAR2(4 BYTE)          NOT NULL,
  FANLTR_STATUS_PREH  VARCHAR2(4 BYTE)          NOT NULL,
  INST_CALC_SC        INTEGER                   NOT NULL,
  INST_CALC_PC        INTEGER                   NOT NULL,
  INST_CALC_EFC       INTEGER                   NOT NULL,
  ISIR_CALC_SC        INTEGER                   NOT NULL,
  ISIR_CALC_PC        INTEGER                   NOT NULL,
  ISIR_CALC_EFC       INTEGER                   NOT NULL,
  SFA_PELLYR_COA_LHT  NUMBER(8,2)               NOT NULL,
  LOAD_ERROR          VARCHAR2(1 BYTE)          NOT NULL,
  DATA_ORIGIN         VARCHAR2(1 BYTE)          NOT NULL,
  CREATED_EW_DTTM     DATE,
  LASTUPD_EW_DTTM     DATE,
  BATCH_SID           NUMBER(10)                NOT NULL,
  COMMENTS            VARCHAR2(4000 BYTE)
)
NOCOMPRESS
/
