DROP TABLE CSSTG_OWNER.PS_T_TRNS_TEST_DTL CASCADE CONSTRAINTS
/

--
-- PS_T_TRNS_TEST_DTL  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_T_TRNS_TEST_DTL
(
  EMPLID              VARCHAR2(11 BYTE)         NOT NULL,
  ACAD_CAREER         VARCHAR2(4 BYTE)          NOT NULL,
  INSTITUTION         VARCHAR2(5 BYTE)          NOT NULL,
  MODEL_NBR           INTEGER                   NOT NULL,
  ARTICULATION_TERM   VARCHAR2(4 BYTE)          NOT NULL,
  TRNSFR_EQVLNCY_GRP  INTEGER                   NOT NULL,
  TRNSFR_EQVLNCY_SEQ  INTEGER                   NOT NULL,
  TRNSFR_STAT         VARCHAR2(1 BYTE)          NOT NULL,
  TST_EQVLNCY         VARCHAR2(6 BYTE)          NOT NULL,
  TRNSFR_EQVLNCY_CMP  VARCHAR2(4 BYTE)          NOT NULL,
  TEST_ID             VARCHAR2(11 BYTE)         NOT NULL,
  TEST_COMPONENT      VARCHAR2(5 BYTE)          NOT NULL,
  DESCR               VARCHAR2(30 BYTE)         NOT NULL,
  TEST_DT             DATE,
  LS_DATA_SOURCE      VARCHAR2(3 BYTE)          NOT NULL,
  SCORE               NUMBER(6,2)               NOT NULL,
  PERCENTILE          INTEGER                   NOT NULL,
  CRSE_ID             VARCHAR2(6 BYTE)          NOT NULL,
  CRSE_OFFER_NBR      INTEGER                   NOT NULL,
  UNT_TRNSFR          NUMBER(8,3)               NOT NULL,
  GRADING_SCHEME      VARCHAR2(3 BYTE)          NOT NULL,
  GRADING_BASIS       VARCHAR2(3 BYTE)          NOT NULL,
  CRSE_GRADE_OFF      VARCHAR2(3 BYTE)          NOT NULL,
  GRD_PTS_PER_UNIT    NUMBER(9,3)               NOT NULL,
  EARN_CREDIT         VARCHAR2(1 BYTE)          NOT NULL,
  INCLUDE_IN_GPA      VARCHAR2(1 BYTE)          NOT NULL,
  UNITS_ATTEMPTED     VARCHAR2(1 BYTE)          NOT NULL,
  REPEAT_CODE         VARCHAR2(4 BYTE)          NOT NULL,
  RQMNT_DESIGNTN      VARCHAR2(4 BYTE)          NOT NULL,
  FREEZE_REC_FL       VARCHAR2(1 BYTE)          NOT NULL,
  INPUT_CHG_FL        VARCHAR2(1 BYTE)          NOT NULL,
  REJECT_REASON       VARCHAR2(2 BYTE)          NOT NULL,
  OVRD_TRCR_FL        VARCHAR2(1 BYTE)          NOT NULL,
  OVRD_RSN            VARCHAR2(50 BYTE)         NOT NULL,
  VALID_ATTEMPT       VARCHAR2(1 BYTE)          NOT NULL,
  GRADE_CATEGORY      VARCHAR2(4 BYTE)          NOT NULL,
  SSR_FAWI_INCL       VARCHAR2(1 BYTE)          NOT NULL,
  COMMENTS            VARCHAR2(4000 BYTE),
  SRC_SCN             NUMBER
)
NOCOMPRESS
/
