DROP TABLE CSSTG_OWNER.PS_T_CLASS_NOTES_TBL CASCADE CONSTRAINTS
/

--
-- PS_T_CLASS_NOTES_TBL  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_T_CLASS_NOTES_TBL
(
  INSTITUTION     VARCHAR2(5 BYTE)              NOT NULL,
  CLASS_NOTE_NBR  VARCHAR2(4 BYTE)              NOT NULL,
  EFFDT           DATE                          NOT NULL,
  SRC_SYS_ID      VARCHAR2(5 BYTE)              NOT NULL,
  EFF_STATUS      VARCHAR2(1 BYTE)              NOT NULL,
  DESCR           VARCHAR2(30 BYTE)             NOT NULL,
  BATCH_SID       NUMBER(10)                    NOT NULL,
  DESCRLONG       VARCHAR2(4000 BYTE),
  SRC_SCN         NUMBER
)
COMPRESS BASIC
/
