DROP TABLE CSSTG_OWNER.PS_CLASS_COMPONENT CASCADE CONSTRAINTS
/

--
-- PS_CLASS_COMPONENT  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_CLASS_COMPONENT
(
  CRSE_ID            VARCHAR2(6 BYTE)           NOT NULL,
  CRSE_OFFER_NBR     INTEGER                    NOT NULL,
  STRM               VARCHAR2(4 BYTE)           NOT NULL,
  SESSION_CODE       VARCHAR2(3 BYTE)           NOT NULL,
  ASSOCIATED_CLASS   INTEGER                    NOT NULL,
  SSR_COMPONENT      VARCHAR2(3 BYTE)           NOT NULL,
  SRC_SYS_ID         VARCHAR2(5 BYTE)           NOT NULL,
  OPTIONAL_SECTION   VARCHAR2(1 BYTE)           NOT NULL,
  CONTACT_HOURS      NUMBER(7,3)                NOT NULL,
  FINAL_EXAM         VARCHAR2(2 BYTE)           NOT NULL,
  AUTO_CREATE_CMPNT  VARCHAR2(1 BYTE)           NOT NULL,
  WEEK_WORKLOAD_HRS  NUMBER(5,2)                NOT NULL,
  LOAD_ERROR         VARCHAR2(1 BYTE)           NOT NULL,
  DATA_ORIGIN        VARCHAR2(1 BYTE)           NOT NULL,
  CREATED_EW_DTTM    DATE,
  LASTUPD_EW_DTTM    DATE,
  BATCH_SID          NUMBER(10)                 NOT NULL
)
COMPRESS BASIC
/
