DROP TABLE CSSTG_OWNER.PS_T_ISIR_COMMT_TBL CASCADE CONSTRAINTS
/

--
-- PS_T_ISIR_COMMT_TBL  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_T_ISIR_COMMT_TBL
(
  AID_YEAR          VARCHAR2(4 BYTE)            NOT NULL,
  COMMENT_CODE      VARCHAR2(3 BYTE)            NOT NULL,
  SFA_DB_MATCH_USE  VARCHAR2(2 BYTE),
  SEVERITY_LVL      VARCHAR2(1 BYTE),
  DESCRLONG         VARCHAR2(4000 BYTE),
  SRC_SCN           NUMBER
)
NOCOMPRESS
/
