DROP TABLE CSSTG_OWNER.PS_TRNSFR_TO CASCADE CONSTRAINTS
/

--
-- PS_TRNSFR_TO  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_TRNSFR_TO
(
  INSTITUTION         VARCHAR2(5 BYTE)          NOT NULL,
  TRNSFR_SRC_ID       VARCHAR2(11 BYTE)         NOT NULL,
  COMP_SUBJECT_AREA   VARCHAR2(16 BYTE)         NOT NULL,
  EFFDT               DATE                      NOT NULL,
  TRNSFR_EQVLNCY_CMP  VARCHAR2(4 BYTE)          NOT NULL,
  CRSE_ID             VARCHAR2(6 BYTE)          NOT NULL,
  SRC_SYS_ID          VARCHAR2(5 BYTE)          NOT NULL,
  CRSE_OFFER_NBR      INTEGER                   NOT NULL,
  UNT_TAKEN           NUMBER(5,2)               NOT NULL,
  SSR_TR_DEF_GRD_TYP  VARCHAR2(1 BYTE)          NOT NULL,
  SSR_TR_DEF_GRD_SEQ  VARCHAR2(4 BYTE)          NOT NULL,
  LOAD_ERROR          VARCHAR2(1 BYTE)          NOT NULL,
  DATA_ORIGIN         VARCHAR2(1 BYTE)          NOT NULL,
  CREATED_EW_DTTM     DATE,
  LASTUPD_EW_DTTM     DATE,
  BATCH_SID           NUMBER(10)                NOT NULL
)
COMPRESS BASIC
/
