DROP TABLE CSSTG_OWNER.PS_ADDR_ORDER_TBL CASCADE CONSTRAINTS
/

--
-- PS_ADDR_ORDER_TBL  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_ADDR_ORDER_TBL
(
  ADDR_USAGE        VARCHAR2(10 BYTE)           NOT NULL,
  ADDR_USAGE_ORDER  INTEGER                     NOT NULL,
  SRC_SYS_ID        VARCHAR2(5 BYTE)            NOT NULL,
  ADDR_USAGE_TYPE   VARCHAR2(2 BYTE)            NOT NULL,
  ADDRESS_TYPE      VARCHAR2(4 BYTE)            NOT NULL,
  E_ADDR_TYPE       VARCHAR2(4 BYTE)            NOT NULL,
  LOAD_ERROR        VARCHAR2(1 BYTE)            NOT NULL,
  DATA_ORIGIN       VARCHAR2(1 BYTE)            NOT NULL,
  CREATED_EW_DTTM   DATE,
  LASTUPD_EW_DTTM   DATE,
  BATCH_SID         NUMBER(10)                  NOT NULL
)
COMPRESS BASIC
/
