DROP TABLE CSSTG_OWNER.PS_CLASS_SBFEE_TBL CASCADE CONSTRAINTS
/

--
-- PS_CLASS_SBFEE_TBL  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_CLASS_SBFEE_TBL
(
  SETID               VARCHAR2(5 BYTE)          NOT NULL,
  CRSE_ID             VARCHAR2(6 BYTE)          NOT NULL,
  CRSE_OFFER_NBR      INTEGER                   NOT NULL,
  STRM                VARCHAR2(4 BYTE)          NOT NULL,
  SESSION_CODE        VARCHAR2(3 BYTE)          NOT NULL,
  CLASS_SECTION       VARCHAR2(4 BYTE)          NOT NULL,
  SSR_COMPONENT       VARCHAR2(3 BYTE)          NOT NULL,
  ACCOUNT_TYPE_SF     VARCHAR2(3 BYTE)          NOT NULL,
  ITEM_TYPE           VARCHAR2(12 BYTE)         NOT NULL,
  SRC_SYS_ID          VARCHAR2(5 BYTE)          NOT NULL,
  SSF_CRITR_EQUTN_SW  VARCHAR2(1 BYTE),
  FEE_TRIGGER         VARCHAR2(12 BYTE),
  EQUATION_NAME       VARCHAR2(12 BYTE),
  CRSE_RATE_ID        VARCHAR2(6 BYTE),
  AMT_PER_UNIT        NUMBER(16,2),
  FLAT_AMT            NUMBER(16,2),
  AMT_PER_UNIT_AUDIT  NUMBER(16,2),
  FLAT_AMT_AUDIT      NUMBER(16,2),
  MIN_AMOUNT          NUMBER(16,2),
  MAX_AMOUNT          NUMBER(16,2),
  CURRENCY_CD         VARCHAR2(3 BYTE),
  ADJ_TERM_CD         VARCHAR2(8 BYTE),
  DUE_DATE_CODE       VARCHAR2(8 BYTE),
  WAIVER_GROUP        VARCHAR2(10 BYTE),
  DYNAMIC_ORG         VARCHAR2(1 BYTE),
  SSF_EXCLUDE_HECS    VARCHAR2(1 BYTE),
  LOAD_ERROR          VARCHAR2(1 BYTE)          NOT NULL,
  DATA_ORIGIN         VARCHAR2(1 BYTE)          NOT NULL,
  CREATED_EW_DTTM     DATE,
  LASTUPD_EW_DTTM     DATE,
  BATCH_SID           NUMBER(10)                NOT NULL
)
COMPRESS BASIC
/
