DROP TABLE CSSTG_OWNER.PS_ORG_CONTACT CASCADE CONSTRAINTS
/

--
-- PS_ORG_CONTACT  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_ORG_CONTACT
(
  EXT_ORG_ID          VARCHAR2(11 BYTE)         NOT NULL,
  ORG_CONTACT         INTEGER                   NOT NULL,
  EFFDT               DATE,
  SRC_SYS_ID          VARCHAR2(5 BYTE)          NOT NULL,
  EFF_STATUS          VARCHAR2(1 BYTE)          NOT NULL,
  EMPLID              VARCHAR2(11 BYTE)         NOT NULL,
  CONTACT_NAME        VARCHAR2(50 BYTE)         NOT NULL,
  JOBTITLE            VARCHAR2(30 BYTE)         NOT NULL,
  ORG_LOCATION        INTEGER                   NOT NULL,
  ORG_DEPARTMENT      INTEGER                   NOT NULL,
  EMAILID             VARCHAR2(70 BYTE)         NOT NULL,
  ORG_CONTACT_TYPE    VARCHAR2(3 BYTE)          NOT NULL,
  URL_ADDRESS         VARCHAR2(254 BYTE)        NOT NULL,
  SCC_CNTC_ADDR_TYPE  VARCHAR2(4 BYTE)          NOT NULL,
  ADDRESS_TYPE        VARCHAR2(4 BYTE)          NOT NULL,
  LASTUPDDTTM         DATE,
  LASTUPDOPRID        VARCHAR2(30 BYTE)         NOT NULL,
  LOAD_ERROR          VARCHAR2(1 BYTE)          NOT NULL,
  DATA_ORIGIN         VARCHAR2(1 BYTE)          NOT NULL,
  CREATED_EW_DTTM     DATE,
  LASTUPD_EW_DTTM     DATE,
  BATCH_SID           NUMBER(10)                NOT NULL
)
COMPRESS BASIC
/
