DROP TABLE CSSTG_OWNER.PS_LOAN_ORIG_DTL CASCADE CONSTRAINTS
/

--
-- PS_LOAN_ORIG_DTL  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_LOAN_ORIG_DTL
(
  EMPLID              VARCHAR2(11 BYTE)         NOT NULL,
  INSTITUTION         VARCHAR2(5 BYTE)          NOT NULL,
  AID_YEAR            VARCHAR2(4 BYTE)          NOT NULL,
  ACAD_CAREER         VARCHAR2(4 BYTE)          NOT NULL,
  LOAN_TYPE           VARCHAR2(4 BYTE)          NOT NULL,
  LN_APPL_SEQ         INTEGER                   NOT NULL,
  ITEM_TYPE           VARCHAR2(12 BYTE)         NOT NULL,
  SRC_SYS_ID          VARCHAR2(5 BYTE)          NOT NULL,
  LN_APPL_ID          VARCHAR2(21 BYTE)         NOT NULL,
  DISBURSEMENT_PLAN   VARCHAR2(2 BYTE)          NOT NULL,
  SPLIT_CODE          VARCHAR2(2 BYTE)          NOT NULL,
  LOAN_INTEREST_ATTR  VARCHAR2(1 BYTE)          NOT NULL,
  LN_BORRQSTD_DTL     NUMBER(11,2)              NOT NULL,
  LN_AMT_CERTIFIED    NUMBER(11,2)              NOT NULL,
  LN_ANTIC_FEE_TOT    NUMBER(11,2)              NOT NULL,
  LN_ANTIC_REBATE     NUMBER(6,2)               NOT NULL,
  LN_ANTIC_NET_TOT    NUMBER(11,2)              NOT NULL,
  LN_REMAIN_ELGBLTY   INTEGER                   NOT NULL,
  LN_AMT_APPROVED     NUMBER(11,2)              NOT NULL,
  ACCEPT_AMOUNT       NUMBER(11,2)              NOT NULL,
  OFFER_AMOUNT        NUMBER(11,2)              NOT NULL,
  LN_FEE_AMT          NUMBER(6,2)               NOT NULL,
  LN_REBATE_AMT       NUMBER(6,2)               NOT NULL,
  CL_TYPE_CODE        VARCHAR2(2 BYTE)          NOT NULL,
  CL_SEQ_NUM          VARCHAR2(2 BYTE)          NOT NULL,
  CURRENCY_CD         VARCHAR2(3 BYTE)          NOT NULL,
  LN_TRNS_OFFER_AMT   NUMBER(11,2)              NOT NULL,
  LN_TRNS_ACCEPT_AMT  NUMBER(11,2)              NOT NULL,
  LN_TRNS_CERT_AMT    NUMBER(11,2)              NOT NULL,
  LN_TRNS_BQSTD_DTL   NUMBER(11,2)              NOT NULL,
  LOAN_PROC_STAT      VARCHAR2(1 BYTE)          NOT NULL,
  LN_ORIG_TRANS       VARCHAR2(1 BYTE)          NOT NULL,
  LN_GUAR_DT          DATE,
  CL_SERV_TYPE_CD     VARCHAR2(2 BYTE)          NOT NULL,
  CL_REV_NOG_CD       VARCHAR2(1 BYTE)          NOT NULL,
  CL_GUAR_AMT_RED_CD  VARCHAR2(2 BYTE)          NOT NULL,
  LN_FORCE_CHG_SW     VARCHAR2(1 BYTE)          NOT NULL,
  SFA_CL_ESIGN_TYPE   VARCHAR2(9 BYTE)          NOT NULL,
  LOAD_ERROR          VARCHAR2(1 BYTE)          NOT NULL,
  DATA_ORIGIN         VARCHAR2(1 BYTE)          NOT NULL,
  CREATED_EW_DTTM     DATE,
  LASTUPD_EW_DTTM     DATE,
  BATCH_SID           NUMBER(10)                NOT NULL
)
COMPRESS BASIC
/
