DROP TABLE CSSTG_OWNER.PS_T_STDNT_RTN_TIV CASCADE CONSTRAINTS
/

--
-- PS_T_STDNT_RTN_TIV  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_T_STDNT_RTN_TIV
(
  INSTITUTION         VARCHAR2(5 BYTE)          NOT NULL,
  AID_YEAR            VARCHAR2(4 BYTE)          NOT NULL,
  EMPLID              VARCHAR2(11 BYTE)         NOT NULL,
  STRM                VARCHAR2(4 BYTE)          NOT NULL,
  RTRN_TIV_PGM_TYPE   VARCHAR2(1 BYTE)          NOT NULL,
  SRC_SYS_ID          VARCHAR2(5 BYTE)          NOT NULL,
  RTRN_TIV_STATUS     VARCHAR2(1 BYTE)          NOT NULL,
  RTRN_TIV_WSTAT_DT   DATE                      NOT NULL,
  RTRN_TIV_PERIOD_TP  VARCHAR2(1 BYTE)          NOT NULL,
  RTRN_TIV_FORM_DT    DATE,
  SESSION_CODE        VARCHAR2(3 BYTE)          NOT NULL,
  STU_TOT_WK_1        NUMBER(8,2)               NOT NULL,
  STU_TOT_WK_2        NUMBER(8,2)               NOT NULL,
  STU_TOT_WK_3        NUMBER(8,2)               NOT NULL,
  STU_TOT_WK_4        NUMBER(8,2)               NOT NULL,
  STU_TOT_WK_5        NUMBER(8,2)               NOT NULL,
  STU_TOT_WK_6        NUMBER(8,2)               NOT NULL,
  STU_TOT_WK_7        NUMBER(8,2)               NOT NULL,
  STU_TOT_WK_8        NUMBER(8,2)               NOT NULL,
  STU_TOT_WK_9        NUMBER(8,2)               NOT NULL,
  STU_TOT_WK_10       NUMBER(8,2)               NOT NULL,
  STU_TOT_WK_7_GRANT  NUMBER(8,2)               NOT NULL,
  TOTAL_TIV_DISB      NUMBER(8,2)               NOT NULL,
  TOTAL_TIV_DISB_ALL  NUMBER(8,2)               NOT NULL,
  WITHDRAW_DATE       DATE,
  PERIOD_START_DT     DATE                      NOT NULL,
  PERIOD_END_DT       DATE                      NOT NULL,
  RTRN_TIV_COMP_DAYS  INTEGER                   NOT NULL,
  RTRN_TIV_TOT_DAYS   INTEGER                   NOT NULL,
  RTRN_TIV_HDAY_ADJ   INTEGER                   NOT NULL,
  RTRN_TIV_HDAY_ADJ2  INTEGER                   NOT NULL,
  RTRN_TIV_COMP_HRS   INTEGER                   NOT NULL,
  RTRN_TIV_TOT_HRS    INTEGER                   NOT NULL,
  RTRN_TIV_SCHD_HRS   INTEGER                   NOT NULL,
  RTRN_TIV_CAL_PCT1   NUMBER(5,2)               NOT NULL,
  RTRN_TIV_CAL_PCT2   NUMBER(5,2)               NOT NULL,
  RTRN_TIV_CAL_PCT3   NUMBER(5,2)               NOT NULL,
  RTRN_TIV_CAL_PCT    NUMBER(5,2)               NOT NULL,
  RTRN_TIV_AID_EARN   NUMBER(8,2)               NOT NULL,
  TOT_AMT_DISB_RTN    NUMBER(8,2)               NOT NULL,
  TOT_TIV_AID_RTRN    NUMBER(8,2)               NOT NULL,
  INST_CHRG_BOARD     NUMBER(8,2)               NOT NULL,
  INST_CHRG_OTHER     NUMBER(8,2)               NOT NULL,
  INST_CHRG_TUIT_FEE  NUMBER(8,2)               NOT NULL,
  TOT_INST_CHARGES    NUMBER(8,2)               NOT NULL,
  TIV_AID_UNEARN_PCT  NUMBER(5,2)               NOT NULL,
  TOT_INST_UNEARN     NUMBER(8,2)               NOT NULL,
  TOT_AMT_SCHL_OWE    NUMBER(8,2)               NOT NULL,
  SCHL_RTN_WK_1       NUMBER(8,2)               NOT NULL,
  SCHL_RTN_WK_2       NUMBER(8,2)               NOT NULL,
  SCHL_RTN_WK_3       NUMBER(8,2)               NOT NULL,
  SCHL_RTN_WK_4       NUMBER(8,2)               NOT NULL,
  SCHL_RTN_WK_5       NUMBER(8,2)               NOT NULL,
  SCHL_RTN_WK_6       NUMBER(8,2)               NOT NULL,
  SCHL_RTN_WK_7       NUMBER(8,2)               NOT NULL,
  SCHL_RTN_WK_8       NUMBER(8,2)               NOT NULL,
  SCHL_RTN_WK_9       NUMBER(8,2)               NOT NULL,
  SCHL_RTN_WK_10      NUMBER(8,2)               NOT NULL,
  STU_NO_RTN_GRANT    NUMBER(8,2)               NOT NULL,
  TOT_AMT_STU_OWE     NUMBER(8,2)               NOT NULL,
  STU_RTN_WK_1        NUMBER(8,2)               NOT NULL,
  STU_RTN_WK_2        NUMBER(8,2)               NOT NULL,
  STU_RTN_WK_3        NUMBER(8,2)               NOT NULL,
  STU_RTN_WK_4        NUMBER(8,2)               NOT NULL,
  STU_RTN_WK_5        NUMBER(8,2)               NOT NULL,
  STU_RTN_WK_6        NUMBER(8,2)               NOT NULL,
  STU_RTN_WK_7        NUMBER(8,2)               NOT NULL,
  STU_RTN_WK_8        NUMBER(8,2)               NOT NULL,
  STU_RTN_WK_9        NUMBER(8,2)               NOT NULL,
  STU_RTN_WK_10       NUMBER(8,2)               NOT NULL,
  STU_RTN_WK_5_PRO    NUMBER(8,2)               NOT NULL,
  STU_RTN_WK_6_PRO    NUMBER(8,2)               NOT NULL,
  STU_RTN_WK_7_PRO    NUMBER(8,2)               NOT NULL,
  RTRN_TIV_DAYS_PAST  INTEGER                   NOT NULL,
  RTRN_TIV_UNOFFW     VARCHAR2(1 BYTE)          NOT NULL,
  PROCESS_INSTANCE    NUMBER(10)                NOT NULL,
  RTRN_TIV_PROC_DTTM  DATE,
  LAST_UPDATE_DTTM    DATE,
  OPRID               VARCHAR2(30 BYTE)         NOT NULL,
  SFA_DSB_TOT_WK1     NUMBER(8,2)               NOT NULL,
  SFA_DSB_TOT_WK2     NUMBER(8,2)               NOT NULL,
  SFA_DSB_TOT_WK3     NUMBER(8,2)               NOT NULL,
  SFA_DSB_TOT_WK4     NUMBER(8,2)               NOT NULL,
  SFA_DSB_TOT_WK5     NUMBER(8,2)               NOT NULL,
  SFA_DSB_TOT_WK6     NUMBER(8,2)               NOT NULL,
  SFA_DSB_TOT_WK7     NUMBER(8,2)               NOT NULL,
  SFA_DSB_TOT_WK8     NUMBER(8,2)               NOT NULL,
  SFA_DSB_TOT_WK9     NUMBER(8,2)               NOT NULL,
  SFA_DSB_TOT_WK10    NUMBER(8,2)               NOT NULL,
  SFA_SUB_TOT_A       NUMBER(8,2)               NOT NULL,
  SFA_SUB_TOT_B       NUMBER(8,2)               NOT NULL,
  SFA_SUB_TOT_C       NUMBER(8,2)               NOT NULL,
  SFA_SUB_TOT_D       NUMBER(8,2)               NOT NULL,
  SFA_SUB_TOT_F       NUMBER(8,2)               NOT NULL,
  SFA_SUB_TOT_P       NUMBER(8,2)               NOT NULL,
  SFA_SUB_TOT_R       NUMBER(8,2)               NOT NULL,
  SFA_SUB_TOT_S       NUMBER(8,2)               NOT NULL,
  SFA_SUB_TOT_T       NUMBER(8,2)               NOT NULL,
  SFA_SUB_TOT_U       NUMBER(8,2)               NOT NULL,
  SFA_HERA_FLG        VARCHAR2(1 BYTE)          NOT NULL,
  SFA_RTIV_CHD_OVRDE  VARCHAR2(1 BYTE)          NOT NULL,
  SFA_RTIV_TDH_OVRD   VARCHAR2(1 BYTE)          NOT NULL,
  SFA_RTIV_PADJ_OVRD  VARCHAR2(1 BYTE)          NOT NULL,
  SFA_RTIV_DAY_OVRDE  VARCHAR2(1 BYTE)          NOT NULL,
  BATCH_SID           NUMBER(10)                NOT NULL
)
NOCOMPRESS
/
