DROP TABLE CSSTG_OWNER.PS_REG_REGION_TBL CASCADE CONSTRAINTS
/

--
-- PS_REG_REGION_TBL  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_REG_REGION_TBL
(
  REG_REGION       VARCHAR2(5 BYTE)             NOT NULL,
  SRC_SYS_ID       VARCHAR2(5 BYTE)             NOT NULL,
  DESCR50          VARCHAR2(50 BYTE)            NOT NULL,
  COUNTRY          VARCHAR2(3 BYTE)             NOT NULL,
  REG_AVAIL        VARCHAR2(3 BYTE)             NOT NULL,
  DEFAULT_SETID    VARCHAR2(5 BYTE)             NOT NULL,
  REG_REGION_DUP   VARCHAR2(5 BYTE)             NOT NULL,
  LOAD_ERROR       VARCHAR2(1 BYTE)             NOT NULL,
  DATA_ORIGIN      VARCHAR2(1 BYTE)             NOT NULL,
  CREATED_EW_DTTM  DATE,
  LASTUPD_EW_DTTM  DATE,
  BATCH_SID        NUMBER(10)                   NOT NULL
)
COMPRESS BASIC
/
