DROP TABLE CSSTG_OWNER.PS_DISB_ID_SPLIT CASCADE CONSTRAINTS
/

--
-- PS_DISB_ID_SPLIT  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_DISB_ID_SPLIT
(
  INSTITUTION        VARCHAR2(5 BYTE)           NOT NULL,
  AID_YEAR           VARCHAR2(4 BYTE)           NOT NULL,
  ACAD_CAREER        VARCHAR2(4 BYTE)           NOT NULL,
  DISBURSEMENT_PLAN  VARCHAR2(2 BYTE)           NOT NULL,
  SPLIT_CODE         VARCHAR2(2 BYTE)           NOT NULL,
  DISBURSEMENT_ID    VARCHAR2(2 BYTE)           NOT NULL,
  SRC_SYS_ID         VARCHAR2(5 BYTE)           NOT NULL,
  PERCENT_OF_AWARD   NUMBER(5,2)                NOT NULL,
  SFA_MIDTERM_DISB   VARCHAR2(1 BYTE)           NOT NULL,
  LOAD_ERROR         VARCHAR2(1 BYTE)           NOT NULL,
  DATA_ORIGIN        VARCHAR2(1 BYTE)           NOT NULL,
  CREATED_EW_DTTM    DATE,
  LASTUPD_EW_DTTM    DATE,
  BATCH_SID          NUMBER(10)                 NOT NULL
)
COMPRESS BASIC
/
