DROP TABLE CSSTG_OWNER.PS_PERS_NID CASCADE CONSTRAINTS
/

--
-- PS_PERS_NID  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_PERS_NID
(
  EMPLID            VARCHAR2(11 BYTE)           NOT NULL,
  COUNTRY           VARCHAR2(3 BYTE)            NOT NULL,
  NATIONAL_ID_TYPE  VARCHAR2(6 BYTE)            NOT NULL,
  SRC_SYS_ID        VARCHAR2(5 BYTE)            NOT NULL,
  NATIONAL_ID       VARCHAR2(20 BYTE)           NOT NULL,
  SSN_KEY_FRA       VARCHAR2(2 BYTE)            NOT NULL,
  PRIMARY_NID       VARCHAR2(1 BYTE)            NOT NULL,
  TAX_REF_ID_SGP    VARCHAR2(1 BYTE)            NOT NULL,
  LASTUPDDTTM       DATE                        NOT NULL,
  LASTUPDOPRID      VARCHAR2(30 BYTE)           NOT NULL,
  LOAD_ERROR        VARCHAR2(1 BYTE)            NOT NULL,
  DATA_ORIGIN       VARCHAR2(1 BYTE)            NOT NULL,
  CREATED_EW_DTTM   DATE,
  LASTUPD_EW_DTTM   DATE,
  BATCH_SID         NUMBER(10)                  NOT NULL
)
NOCOMPRESS
/
