DROP TABLE CSSTG_OWNER.PS_HONOR_AWARD_CS CASCADE CONSTRAINTS
/

--
-- PS_HONOR_AWARD_CS  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_HONOR_AWARD_CS
(
  EMPLID              VARCHAR2(11 BYTE)         NOT NULL,
  SRC_SYS_ID          VARCHAR2(5 BYTE)          NOT NULL,
  DT_RECVD            DATE                      NOT NULL,
  INTERNAL_EXTERNAL   VARCHAR2(1 BYTE)          NOT NULL,
  INSTITUTION         VARCHAR2(5 BYTE)          NOT NULL,
  ACAD_CAREER         VARCHAR2(4 BYTE)          NOT NULL,
  STRM                VARCHAR2(4 BYTE)          NOT NULL,
  AWARD_CODE          VARCHAR2(6 BYTE)          NOT NULL,
  DESCRFORMAL         VARCHAR2(50 BYTE)         NOT NULL,
  GRANTOR             VARCHAR2(20 BYTE)         NOT NULL,
  ACAD_PROG           VARCHAR2(5 BYTE)          NOT NULL,
  ACAD_PLAN           VARCHAR2(10 BYTE)         NOT NULL,
  TRANSCRIPT_LEVEL    VARCHAR2(2 BYTE)          NOT NULL,
  AWRD_SYS_GENERATED  VARCHAR2(1 BYTE)          NOT NULL,
  LOAD_ERROR          VARCHAR2(1 BYTE)          NOT NULL,
  DATA_ORIGIN         VARCHAR2(1 BYTE)          NOT NULL,
  CREATED_EW_DTTM     DATE,
  LASTUPD_EW_DTTM     DATE,
  BATCH_SID           NUMBER(10)                NOT NULL,
  COMMENTS            VARCHAR2(4000 BYTE)
)
COMPRESS BASIC
/
