DROP TABLE CSSTG_OWNER.PS_STDNT_ENRL_NOTE CASCADE CONSTRAINTS
/

--
-- PS_STDNT_ENRL_NOTE  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_STDNT_ENRL_NOTE
(
  EMPLID              VARCHAR2(11 BYTE)         NOT NULL,
  ACAD_CAREER         VARCHAR2(4 BYTE)          NOT NULL,
  INSTITUTION         VARCHAR2(5 BYTE)          NOT NULL,
  STRM                VARCHAR2(4 BYTE)          NOT NULL,
  CLASS_NBR           INTEGER                   NOT NULL,
  TSCRPT_NOTE_SEQ     INTEGER                   NOT NULL,
  SRC_SYS_ID          VARCHAR2(5 BYTE)          NOT NULL,
  TSCRPT_NOTE254      VARCHAR2(254 BYTE),
  TSCRPT_NOTE_FR_INC  VARCHAR2(1 BYTE),
  LOAD_ERROR          VARCHAR2(1 BYTE),
  DATA_ORIGIN         VARCHAR2(1 BYTE),
  CREATED_EW_DTTM     DATE,
  LASTUPD_EW_DTTM     DATE,
  BATCH_SID           NUMBER(10)                NOT NULL
)
COMPRESS BASIC
/
