DROP TABLE CSSTG_OWNER.PS_T_CAMPUS_EVENT CASCADE CONSTRAINTS
/

--
-- PS_T_CAMPUS_EVENT  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_T_CAMPUS_EVENT
(
  CAMPUS_EVENT_NBR   VARCHAR2(9 BYTE)           NOT NULL,
  INSTITUTION        VARCHAR2(5 BYTE)           NOT NULL,
  DESCR              VARCHAR2(30 BYTE),
  DESCRSHORT         VARCHAR2(10 BYTE),
  CAMPUS_EVENT_TYPE  VARCHAR2(4 BYTE),
  EVENT_MANAGER      VARCHAR2(11 BYTE),
  PRIMARY_MEETING    INTEGER,
  ATTENDEE_NBR_LST   INTEGER,
  COMMENTS           VARCHAR2(4000 BYTE),
  SRC_SCN            NUMBER
)
NOCOMPRESS
/
