DROP TABLE CSSTG_OWNER.PS_K_STDNT_AGGR_LIFE CASCADE CONSTRAINTS
/

--
-- PS_K_STDNT_AGGR_LIFE  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_K_STDNT_AGGR_LIFE
(
  EMPLID          VARCHAR2(11 BYTE)             NOT NULL,
  AGGREGATE_AREA  VARCHAR2(10 BYTE)             NOT NULL,
  AID_YEAR        VARCHAR2(4 BYTE)              NOT NULL,
  SRC_SYS_ID      VARCHAR2(5 BYTE)              NOT NULL
)
COMPRESS BASIC
/
