DROP TABLE CSSTG_OWNER.PS_K_UM_ADM_APP_TMP CASCADE CONSTRAINTS
/

--
-- PS_K_UM_ADM_APP_TMP  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_K_UM_ADM_APP_TMP
(
  UM_ADM_USERID   VARCHAR2(15 BYTE)             NOT NULL,
  UM_ADM_APP_SEQ  VARCHAR2(10 BYTE)             NOT NULL,
  UM_ADM_REC_NBR  VARCHAR2(15 BYTE)             NOT NULL,
  INSTITUTION     VARCHAR2(5 BYTE)              NOT NULL,
  SRC_SYS_ID      VARCHAR2(5 BYTE)              NOT NULL
)
COMPRESS BASIC
/
