DROP TABLE CSSTG_OWNER.TEMP_EMPLID_ISSUE_TABLE CASCADE CONSTRAINTS
/

--
-- TEMP_EMPLID_ISSUE_TABLE  (Table) 
--
CREATE TABLE CSSTG_OWNER.TEMP_EMPLID_ISSUE_TABLE
(
  OWNER        VARCHAR2(100 BYTE),
  TABLE_NAME   VARCHAR2(100 BYTE),
  COLUMN_NAME  VARCHAR2(100 BYTE)
)
NOCOMPRESS
/
