DROP TABLE CSSTG_OWNER.PS_SCHOOL_CRSE_TBL CASCADE CONSTRAINTS
/

--
-- PS_SCHOOL_CRSE_TBL  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_SCHOOL_CRSE_TBL
(
  EXT_ORG_ID        VARCHAR2(11 BYTE)           NOT NULL,
  SCHOOL_SUBJECT    VARCHAR2(8 BYTE)            NOT NULL,
  SCHOOL_CRSE_NBR   VARCHAR2(10 BYTE)           NOT NULL,
  EFFDT             DATE                        NOT NULL,
  SRC_SYS_ID        VARCHAR2(5 BYTE)            NOT NULL,
  EFF_STATUS        VARCHAR2(1 BYTE)            NOT NULL,
  EXT_SUBJECT_AREA  VARCHAR2(4 BYTE)            NOT NULL,
  EXT_CAREER        VARCHAR2(4 BYTE)            NOT NULL,
  EXT_CRSE_TYPE     VARCHAR2(3 BYTE)            NOT NULL,
  COURSE_LEVEL      VARCHAR2(2 BYTE)            NOT NULL,
  DESCR             VARCHAR2(30 BYTE)           NOT NULL,
  DESCRSHORT        VARCHAR2(10 BYTE)           NOT NULL,
  EXT_UNITS         NUMBER(5,2)                 NOT NULL,
  LOAD_ERROR        VARCHAR2(1 BYTE)            NOT NULL,
  DATA_ORIGIN       VARCHAR2(1 BYTE)            NOT NULL,
  CREATED_EW_DTTM   DATE,
  LASTUPD_EW_DTTM   DATE,
  BATCH_SID         NUMBER(10)                  NOT NULL
)
COMPRESS BASIC
/
