DROP TABLE CSSTG_OWNER.PS_STUDENT_AID CASCADE CONSTRAINTS
/

--
-- PS_STUDENT_AID  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_STUDENT_AID
(
  EMPLID              VARCHAR2(11 BYTE)         NOT NULL,
  INSTITUTION         VARCHAR2(5 BYTE)          NOT NULL,
  AID_YEAR            VARCHAR2(4 BYTE)          NOT NULL,
  SRC_SYS_ID          VARCHAR2(5 BYTE)          NOT NULL,
  INST_DEPEND_STAT    VARCHAR2(1 BYTE)          NOT NULL,
  FED_DEPEND_STAT     VARCHAR2(1 BYTE)          NOT NULL,
  INAS_RULE_SET_INST  VARCHAR2(4 BYTE)          NOT NULL,
  INAS_RULE_SET_FED   VARCHAR2(4 BYTE)          NOT NULL,
  EFC_USE_IM          VARCHAR2(1 BYTE)          NOT NULL,
  LOAD_ERROR          VARCHAR2(1 BYTE)          NOT NULL,
  DATA_ORIGIN         VARCHAR2(1 BYTE)          NOT NULL,
  CREATED_EW_DTTM     DATE,
  LASTUPD_EW_DTTM     DATE,
  BATCH_SID           NUMBER(10)                NOT NULL
)
COMPRESS BASIC
/
