DROP TABLE CSSTG_OWNER.PS_HRS_APP_PROFILE_OLD CASCADE CONSTRAINTS
/

--
-- PS_HRS_APP_PROFILE_OLD  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_HRS_APP_PROFILE_OLD
(
  HRS_PERSON_ID       NUMBER(15)                NOT NULL,
  HRS_PROFILE_SEQ     INTEGER                   NOT NULL,
  SRC_SYS_ID          VARCHAR2(5 BYTE)          NOT NULL,
  HRS_SUBMITTED_BY    VARCHAR2(15 BYTE)         NOT NULL,
  HRS_SUBMITTED_DTTM  DATE,
  HRS_RESUME_ID       NUMBER(15)                NOT NULL,
  HRS_AL_LOG_ID       NUMBER(15)                NOT NULL,
  HRS_PAGE_LAYOUT_ID  NUMBER(15)                NOT NULL,
  APPLIC_PURGE_DT     DATE,
  HIGHEST_EDUC_LVL    VARCHAR2(2 BYTE)          NOT NULL,
  GVT_CRED_MIL_SVCE   VARCHAR2(4 BYTE)          NOT NULL,
  GVT_MILITARY_COMP   VARCHAR2(1 BYTE)          NOT NULL,
  GVT_MIL_GRADE       VARCHAR2(3 BYTE)          NOT NULL,
  GVT_MIL_RESRVE_CAT  VARCHAR2(1 BYTE)          NOT NULL,
  GVT_MIL_SEP_RET     VARCHAR2(1 BYTE)          NOT NULL,
  GVT_MIL_SVCE_END    DATE,
  GVT_MIL_SVCE_START  DATE,
  GVT_MIL_VERIFY      VARCHAR2(1 BYTE)          NOT NULL,
  GVT_PAR_NBR_LAST    INTEGER                   NOT NULL,
  GVT_UNIF_SVC_CTR    VARCHAR2(1 BYTE)          NOT NULL,
  GVT_VET_PREF_APPT   VARCHAR2(1 BYTE)          NOT NULL,
  GVT_VET_PREF_RIF    VARCHAR2(1 BYTE)          NOT NULL,
  GVT_CHANGE_FLAG     VARCHAR2(1 BYTE)          NOT NULL,
  GVT_DRAFT_STATUS    VARCHAR2(1 BYTE)          NOT NULL,
  GVT_YR_ATTAINED     DATE,
  DISABLED_VET        VARCHAR2(1 BYTE)          NOT NULL,
  DISABLED            VARCHAR2(1 BYTE)          NOT NULL,
  ETHNIC_GROUP        VARCHAR2(1 BYTE)          NOT NULL,
  GVT_DISABILITY_CD   VARCHAR2(2 BYTE)          NOT NULL,
  GRADE               VARCHAR2(3 BYTE)          NOT NULL,
  SAL_ADMIN_PLAN      VARCHAR2(4 BYTE)          NOT NULL,
  GVT_CURR_AGCY_EMPL  VARCHAR2(1 BYTE)          NOT NULL,
  GVT_CURR_FED_EMPL   VARCHAR2(1 BYTE)          NOT NULL,
  GVT_HIGH_PAY_PLAN   VARCHAR2(3 BYTE)          NOT NULL,
  GVT_HIGH_GRADE      VARCHAR2(3 BYTE)          NOT NULL,
  GVT_PREV_AGCY_EMPL  VARCHAR2(1 BYTE)          NOT NULL,
  GVT_PREV_FED_EMPL   VARCHAR2(1 BYTE)          NOT NULL,
  GVT_SEP_INCENTIVE   VARCHAR2(1 BYTE)          NOT NULL,
  GVT_SEP_INCENT_DT   DATE,
  GVT_TENURE          VARCHAR2(1 BYTE)          NOT NULL,
  GVT_PAY_PLAN        VARCHAR2(2 BYTE)          NOT NULL,
  BARG_UNIT           VARCHAR2(4 BYTE)          NOT NULL,
  LANG_CD             VARCHAR2(3 BYTE)          NOT NULL,
  YEARS_OF_EXP        NUMBER(4,1)               NOT NULL,
  LETTER_CD           VARCHAR2(3 BYTE)          NOT NULL,
  LETTER_PRINTED_DT   DATE,
  TRAVELLING          VARCHAR2(1 BYTE)          NOT NULL,
  RELOCATE            VARCHAR2(1 BYTE)          NOT NULL,
  UNION_CD            VARCHAR2(3 BYTE)          NOT NULL,
  DESIRED_HOURS       NUMBER(3,1)               NOT NULL,
  MIN_RATE            NUMBER(18,6)              NOT NULL,
  CURRENCY_CD         VARCHAR2(3 BYTE)          NOT NULL,
  PAY_FREQ_ABBRV      VARCHAR2(1 BYTE)          NOT NULL,
  DESIRED_START_DT    DATE,
  DESIRED_FULL_PART   VARCHAR2(1 BYTE)          NOT NULL,
  DESIRED_REG_TEMP    VARCHAR2(1 BYTE)          NOT NULL,
  DESIRED_SHIFT       VARCHAR2(1 BYTE)          NOT NULL,
  MON                 VARCHAR2(1 BYTE)          NOT NULL,
  TUES                VARCHAR2(1 BYTE)          NOT NULL,
  WED                 VARCHAR2(1 BYTE)          NOT NULL,
  THURS               VARCHAR2(1 BYTE)          NOT NULL,
  FRI                 VARCHAR2(1 BYTE)          NOT NULL,
  SAT                 VARCHAR2(1 BYTE)          NOT NULL,
  SUN                 VARCHAR2(1 BYTE)          NOT NULL,
  BUSINESS_UNIT       VARCHAR2(5 BYTE)          NOT NULL,
  DESIRED_LOCATN1     VARCHAR2(10 BYTE)         NOT NULL,
  DESIRED_LOCATN2     VARCHAR2(10 BYTE)         NOT NULL,
  TRAVEL_PERCENT      INTEGER                   NOT NULL,
  HRS_TRAVEL_PERCENT  VARCHAR2(1 BYTE)          NOT NULL,
  PREV_EMPL_BY_COMPY  VARCHAR2(1 BYTE)          NOT NULL,
  PREV_TERM_DT        DATE,
  HRS_ROW_ADD_DTTM    DATE,
  HRS_ROW_ADD_OPRID   VARCHAR2(30 BYTE)         NOT NULL,
  HRS_ROW_UPD_DTTM    DATE,
  HRS_ROW_UPD_OPRID   VARCHAR2(30 BYTE)         NOT NULL,
  HRS_DES_LOC1        NUMBER(15)                NOT NULL,
  HRS_DES_LOC2        NUMBER(15)                NOT NULL,
  LOAD_ERROR          VARCHAR2(1 BYTE)          NOT NULL,
  DATA_ORIGIN         VARCHAR2(1 BYTE)          NOT NULL,
  CREATED_EW_DTTM     DATE,
  LASTUPD_EW_DTTM     DATE,
  BATCH_SID           NUMBER(10)                NOT NULL,
  GEOG_PREFER         CLOB
)
LOB (GEOG_PREFER) STORE AS BASICFILE (
  TABLESPACE  CSSTG_DATA1
  ENABLE      STORAGE IN ROW
  CHUNK       16384
  RETENTION
  STORAGE    (
              INITIAL          1M
              NEXT             1M
              MINEXTENTS       1
              MAXEXTENTS       UNLIMITED
              PCTINCREASE      0
              BUFFER_POOL      DEFAULT
             ))
COMPRESS BASIC
/
