DROP TABLE CSSTG_OWNER.PS_AGING_CAT_SF_OLD CASCADE CONSTRAINTS
/

--
-- PS_AGING_CAT_SF_OLD  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_AGING_CAT_SF_OLD
(
  SETID             VARCHAR2(5 BYTE)            NOT NULL,
  AGING_SET         VARCHAR2(5 BYTE)            NOT NULL,
  EFFDT             DATE,
  AGE_CATEGORY      VARCHAR2(2 BYTE)            NOT NULL,
  SRC_SYS_ID        VARCHAR2(5 BYTE)            NOT NULL,
  STARTD            INTEGER                     NOT NULL,
  ENDD              INTEGER                     NOT NULL,
  DESCR             VARCHAR2(30 BYTE)           NOT NULL,
  DESCRSHORT        VARCHAR2(10 BYTE)           NOT NULL,
  SUMMARY_CATEGORY  VARCHAR2(1 BYTE)            NOT NULL,
  CREDIT_CHECK      VARCHAR2(1 BYTE)            NOT NULL,
  LOAD_ERROR        VARCHAR2(1 BYTE)            NOT NULL,
  DATA_ORIGIN       VARCHAR2(1 BYTE)            NOT NULL,
  CREATED_EW_DTTM   DATE,
  LASTUPD_EW_DTTM   DATE,
  BATCH_SID         NUMBER(10)                  NOT NULL
)
COMPRESS BASIC
/
