DROP TABLE CSSTG_OWNER.PS_TRNS_CRSE_DTL CASCADE CONSTRAINTS
/

--
-- PS_TRNS_CRSE_DTL  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_TRNS_CRSE_DTL
(
  EMPLID              VARCHAR2(11 BYTE)         NOT NULL,
  ACAD_CAREER         VARCHAR2(4 BYTE)          NOT NULL,
  INSTITUTION         VARCHAR2(5 BYTE)          NOT NULL,
  MODEL_NBR           INTEGER                   NOT NULL,
  ARTICULATION_TERM   VARCHAR2(4 BYTE)          NOT NULL,
  TRNSFR_EQVLNCY_GRP  INTEGER                   NOT NULL,
  TRNSFR_EQVLNCY_SEQ  INTEGER                   NOT NULL,
  SRC_SYS_ID          VARCHAR2(5 BYTE)          NOT NULL,
  TRNSFR_STAT         VARCHAR2(1 BYTE)          NOT NULL,
  TRNSFR_SRC_ID       VARCHAR2(11 BYTE)         NOT NULL,
  TRNSFR_EQVLNCY      VARCHAR2(6 BYTE)          NOT NULL,
  TRNSFR_EQVLNCY_CMP  VARCHAR2(4 BYTE)          NOT NULL,
  EXT_COURSE_NBR      INTEGER                   NOT NULL,
  SRC_TERM            VARCHAR2(4 BYTE)          NOT NULL,
  SRC_CLASS_NBR       INTEGER                   NOT NULL,
  TERM_YEAR           INTEGER                   NOT NULL,
  EXT_TERM            VARCHAR2(4 BYTE)          NOT NULL,
  SCHOOL_SUBJECT      VARCHAR2(8 BYTE)          NOT NULL,
  SCHOOL_CRSE_NBR     VARCHAR2(10 BYTE)         NOT NULL,
  DESCR               VARCHAR2(30 BYTE)         NOT NULL,
  SSR_UNT_TAKEN_EXT   NUMBER(5,2)               NOT NULL,
  UNT_TAKEN           NUMBER(5,2)               NOT NULL,
  CRSE_GRADE_INPUT    VARCHAR2(3 BYTE)          NOT NULL,
  CRSE_ID             VARCHAR2(6 BYTE)          NOT NULL,
  CRSE_OFFER_NBR      INTEGER                   NOT NULL,
  GRADING_SCHEME      VARCHAR2(3 BYTE)          NOT NULL,
  GRADING_BASIS       VARCHAR2(3 BYTE)          NOT NULL,
  UNT_TRNSFR          NUMBER(8,3)               NOT NULL,
  CRSE_GRADE_OFF      VARCHAR2(3 BYTE)          NOT NULL,
  GRD_PTS_PER_UNIT    NUMBER(9,3)               NOT NULL,
  EARN_CREDIT         VARCHAR2(1 BYTE)          NOT NULL,
  INCLUDE_IN_GPA      VARCHAR2(1 BYTE)          NOT NULL,
  UNITS_ATTEMPTED     VARCHAR2(1 BYTE)          NOT NULL,
  REPEAT_CODE         VARCHAR2(4 BYTE)          NOT NULL,
  RQMNT_DESIGNTN      VARCHAR2(4 BYTE)          NOT NULL,
  FREEZE_REC_FL       VARCHAR2(1 BYTE)          NOT NULL,
  INPUT_CHG_FL        VARCHAR2(1 BYTE)          NOT NULL,
  REJECT_REASON       VARCHAR2(2 BYTE)          NOT NULL,
  OVRD_TRCR_FL        VARCHAR2(1 BYTE)          NOT NULL,
  OVRD_RSN            VARCHAR2(50 BYTE)         NOT NULL,
  COURSE_LEVEL        VARCHAR2(2 BYTE)          NOT NULL,
  VALID_ATTEMPT       VARCHAR2(1 BYTE)          NOT NULL,
  GRADE_CATEGORY      VARCHAR2(4 BYTE)          NOT NULL,
  COMP_SUBJECT_AREA   VARCHAR2(16 BYTE)         NOT NULL,
  SSR_FAWI_INCL       VARCHAR2(1 BYTE)          NOT NULL,
  LOAD_ERROR          VARCHAR2(1 BYTE)          NOT NULL,
  DATA_ORIGIN         VARCHAR2(1 BYTE)          NOT NULL,
  CREATED_EW_DTTM     DATE,
  LASTUPD_EW_DTTM     DATE,
  BATCH_SID           NUMBER(10)                NOT NULL,
  COMMENTS            VARCHAR2(4000 BYTE)
)
COMPRESS BASIC
/
