DROP TABLE CSSTG_OWNER.PS_HONOR_AWARD_TBL CASCADE CONSTRAINTS
/

--
-- PS_HONOR_AWARD_TBL  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_HONOR_AWARD_TBL
(
  INSTITUTION        VARCHAR2(5 BYTE)           NOT NULL,
  AWARD_CODE         VARCHAR2(6 BYTE)           NOT NULL,
  EFFDT              DATE                       NOT NULL,
  SRC_SYS_ID         VARCHAR2(5 BYTE)           NOT NULL,
  EFF_STATUS         VARCHAR2(1 BYTE)           NOT NULL,
  DESCR              VARCHAR2(30 BYTE)          NOT NULL,
  DESCRSHORT         VARCHAR2(10 BYTE)          NOT NULL,
  INTERNAL_EXTERNAL  VARCHAR2(1 BYTE)           NOT NULL,
  GRANTOR            VARCHAR2(20 BYTE)          NOT NULL,
  TRANSCRIPT_LEVEL   VARCHAR2(2 BYTE)           NOT NULL,
  DESCRFORMAL        VARCHAR2(50 BYTE)          NOT NULL,
  LOAD_ERROR         VARCHAR2(1 BYTE)           NOT NULL,
  DATA_ORIGIN        VARCHAR2(1 BYTE)           NOT NULL,
  CREATED_EW_DTTM    DATE,
  LASTUPD_EW_DTTM    DATE,
  BATCH_SID          NUMBER(10)                 NOT NULL
)
COMPRESS BASIC
/
