DROP TABLE CSSTG_OWNER.PS_SRVC_IMPACT_TBL CASCADE CONSTRAINTS
/

--
-- PS_SRVC_IMPACT_TBL  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_SRVC_IMPACT_TBL
(
  INSTITUTION      VARCHAR2(5 BYTE)             NOT NULL,
  SERVICE_IMPACT   VARCHAR2(5 BYTE)             NOT NULL,
  EFFDT            DATE                         NOT NULL,
  SRC_SYS_ID       VARCHAR2(5 BYTE)             NOT NULL,
  EFF_STATUS       VARCHAR2(1 BYTE)             NOT NULL,
  SCC_IMPACT_TERM  VARCHAR2(1 BYTE)             NOT NULL,
  SCC_IMPACT_DATE  VARCHAR2(1 BYTE)             NOT NULL,
  POS_SRVC_IMPACT  VARCHAR2(1 BYTE)             NOT NULL,
  SYSTEM_FUNCTION  VARCHAR2(1 BYTE)             NOT NULL,
  DESCR            VARCHAR2(30 BYTE)            NOT NULL,
  DESCRSHORT       VARCHAR2(10 BYTE)            NOT NULL,
  LOAD_ERROR       VARCHAR2(1 BYTE)             NOT NULL,
  DATA_ORIGIN      VARCHAR2(1 BYTE)             NOT NULL,
  CREATED_EW_DTTM  DATE,
  LASTUPD_EW_DTTM  DATE,
  BATCH_SID        NUMBER(10)                   NOT NULL
)
COMPRESS BASIC
/
