DROP TABLE CSSTG_OWNER.PS_STDNT_RESPONSE_OLD CASCADE CONSTRAINTS
/

--
-- PS_STDNT_RESPONSE_OLD  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_STDNT_RESPONSE_OLD
(
  EMPLID           VARCHAR2(11 BYTE)            NOT NULL,
  ACAD_CAREER      VARCHAR2(4 BYTE)             NOT NULL,
  STDNT_CAR_NBR    INTEGER                      NOT NULL,
  ADM_APPL_NBR     VARCHAR2(8 BYTE)             NOT NULL,
  SEQNUM           INTEGER                      NOT NULL,
  SRC_SYS_ID       VARCHAR2(5 BYTE)             NOT NULL,
  RESPONSE_REASON  VARCHAR2(4 BYTE)             NOT NULL,
  RESPONSE_DT      DATE                         NOT NULL,
  EXT_ORG_ID       VARCHAR2(11 BYTE)            NOT NULL,
  DESCR            VARCHAR2(30 BYTE)            NOT NULL,
  LOAD_ERROR       VARCHAR2(1 BYTE)             NOT NULL,
  DATA_ORIGIN      VARCHAR2(1 BYTE)             NOT NULL,
  CREATED_EW_DTTM  DATE,
  LASTUPD_EW_DTTM  DATE,
  BATCH_SID        NUMBER(10)                   NOT NULL
)
COMPRESS BASIC
/
