DROP TABLE CSSTG_OWNER.PS_SESSION_TBL CASCADE CONSTRAINTS
/

--
-- PS_SESSION_TBL  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_SESSION_TBL
(
  INSTITUTION         VARCHAR2(5 BYTE)          NOT NULL,
  ACAD_CAREER         VARCHAR2(4 BYTE)          NOT NULL,
  STRM                VARCHAR2(4 BYTE)          NOT NULL,
  SESSION_CODE        VARCHAR2(3 BYTE)          NOT NULL,
  SRC_SYS_ID          VARCHAR2(5 BYTE)          NOT NULL,
  SESS_BEGIN_DT       DATE,
  SESS_END_DT         DATE,
  ENROLL_OPEN_DT      DATE,
  SESSN_ENRL_CNTL     VARCHAR2(3 BYTE)          NOT NULL,
  SESSN_APPT_CNTL     VARCHAR2(3 BYTE)          NOT NULL,
  FIRST_ENRL_DT       DATE,
  LAST_ENRL_DT        DATE,
  LAST_WAIT_DT        DATE,
  HOLIDAY_SCHEDULE    VARCHAR2(6 BYTE)          NOT NULL,
  WEEKS_OF_INSTRUCT   INTEGER                   NOT NULL,
  CENSUS_DT           DATE,
  USE_DYN_CLASS_DATE  VARCHAR2(1 BYTE)          NOT NULL,
  SIXTY_PCT_DT        DATE,
  FACILITY_ASSIGNMNT  DATE,
  SSR_ENR_APT_APPROV  VARCHAR2(1 BYTE)          NOT NULL,
  SSR_VAL_APT_APPROV  VARCHAR2(1 BYTE)          NOT NULL,
  LOAD_ERROR          VARCHAR2(1 BYTE)          NOT NULL,
  DATA_ORIGIN         VARCHAR2(1 BYTE)          NOT NULL,
  CREATED_EW_DTTM     DATE,
  LASTUPD_EW_DTTM     DATE,
  BATCH_SID           NUMBER(10)                NOT NULL
)
COMPRESS BASIC
/
