DROP TABLE CSSTG_OWNER.PS_ACAD_ORG_TBL CASCADE CONSTRAINTS
/

--
-- PS_ACAD_ORG_TBL  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_ACAD_ORG_TBL
(
  ACAD_ORG         VARCHAR2(10 BYTE)            NOT NULL,
  EFFDT            DATE                         NOT NULL,
  SRC_SYS_ID       VARCHAR2(5 BYTE)             NOT NULL,
  EFF_STATUS       VARCHAR2(1 BYTE)             NOT NULL,
  DESCR            VARCHAR2(30 BYTE)            NOT NULL,
  DESCRSHORT       VARCHAR2(10 BYTE)            NOT NULL,
  DESCRFORMAL      VARCHAR2(50 BYTE)            NOT NULL,
  INSTITUTION      VARCHAR2(5 BYTE)             NOT NULL,
  CAMPUS           VARCHAR2(5 BYTE)             NOT NULL,
  MANAGER_ID       VARCHAR2(11 BYTE)            NOT NULL,
  INSTR_EDIT       VARCHAR2(1 BYTE)             NOT NULL,
  CAMPUS_EDIT      VARCHAR2(1 BYTE)             NOT NULL,
  SUBJECT_EDIT     VARCHAR2(1 BYTE)             NOT NULL,
  COURSE_EDIT      VARCHAR2(1 BYTE)             NOT NULL,
  LOAD_ERROR       VARCHAR2(1 BYTE)             NOT NULL,
  DATA_ORIGIN      VARCHAR2(1 BYTE)             NOT NULL,
  CREATED_EW_DTTM  DATE,
  LASTUPD_EW_DTTM  DATE,
  BATCH_SID        NUMBER(10)                   NOT NULL
)
COMPRESS BASIC
/
