DROP TABLE CSSTG_OWNER.PS_TERM_SUBFEE_TBL CASCADE CONSTRAINTS
/

--
-- PS_TERM_SUBFEE_TBL  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_TERM_SUBFEE_TBL
(
  SETID             VARCHAR2(5 BYTE)            NOT NULL,
  FEE_CODE          VARCHAR2(6 BYTE)            NOT NULL,
  STRM              VARCHAR2(4 BYTE)            NOT NULL,
  SESSION_CODE      VARCHAR2(3 BYTE)            NOT NULL,
  SUB_FEE_CODE      VARCHAR2(6 BYTE)            NOT NULL,
  INSTITUTION       VARCHAR2(5 BYTE)            NOT NULL,
  ACAD_CAREER       VARCHAR2(4 BYTE)            NOT NULL,
  ACAD_GROUP        VARCHAR2(5 BYTE)            NOT NULL,
  SUBJECT           VARCHAR2(8 BYTE)            NOT NULL,
  CAMPUS            VARCHAR2(5 BYTE)            NOT NULL,
  LOCATION          VARCHAR2(10 BYTE)           NOT NULL,
  INSTRUCTION_MODE  VARCHAR2(2 BYTE)            NOT NULL,
  ACAD_PROG         VARCHAR2(5 BYTE)            NOT NULL,
  SSR_COHORT_YR     VARCHAR2(4 BYTE)            NOT NULL,
  UNIT_FROM         NUMBER(5,2)                 NOT NULL,
  UNIT_TO           NUMBER(5,2)                 NOT NULL,
  SRC_SYS_ID        VARCHAR2(5 BYTE)            NOT NULL,
  EQUATION_NAME     VARCHAR2(12 BYTE)           NOT NULL,
  AMT_PER_UNIT      NUMBER(16,2)                NOT NULL,
  FLAT_AMT          NUMBER(16,2)                NOT NULL,
  LOAD_ERROR        VARCHAR2(1 BYTE)            NOT NULL,
  DATA_ORIGIN       VARCHAR2(1 BYTE)            NOT NULL,
  CREATED_EW_DTTM   DATE,
  LASTUPD_EW_DTTM   DATE,
  BATCH_SID         NUMBER(10)                  NOT NULL
)
COMPRESS BASIC
/
