DROP TABLE CSSTG_OWNER.PS_ISIR_COMPUTED CASCADE CONSTRAINTS
/

--
-- PS_ISIR_COMPUTED  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_ISIR_COMPUTED
(
  EMPLID              VARCHAR2(11 BYTE)         NOT NULL,
  INSTITUTION         VARCHAR2(5 BYTE)          NOT NULL,
  AID_YEAR            VARCHAR2(4 BYTE)          NOT NULL,
  EFFDT               DATE                      NOT NULL,
  EFFSEQ              INTEGER                   NOT NULL,
  TABLE_ID            VARCHAR2(1 BYTE)          NOT NULL,
  SRC_SYS_ID          VARCHAR2(5 BYTE)          NOT NULL,
  PRIMARY_EFC         INTEGER                   NOT NULL,
  SECONDARY_EFC       INTEGER                   NOT NULL,
  PELL_SPCL_PRM_EFC   INTEGER                   NOT NULL,
  PELL_SPCL_SEC_EFC   INTEGER                   NOT NULL,
  PELL_PAID_EFC_TYPE  VARCHAR2(1 BYTE)          NOT NULL,
  VALID_EFC_CALC      VARCHAR2(1 BYTE)          NOT NULL,
  AUTO_ZERO_EFC       VARCHAR2(1 BYTE)          NOT NULL,
  FORMULA_TYPE        VARCHAR2(1 BYTE)          NOT NULL,
  PRM_ALT_MONTH_1     VARCHAR2(6 BYTE)          NOT NULL,
  PRM_ALT_MONTH_2     VARCHAR2(6 BYTE)          NOT NULL,
  PRM_ALT_MONTH_3     VARCHAR2(6 BYTE)          NOT NULL,
  PRM_ALT_MONTH_4     VARCHAR2(6 BYTE)          NOT NULL,
  PRM_ALT_MONTH_5     VARCHAR2(6 BYTE)          NOT NULL,
  PRM_ALT_MONTH_6     VARCHAR2(6 BYTE)          NOT NULL,
  PRM_ALT_MONTH_7     VARCHAR2(6 BYTE)          NOT NULL,
  PRM_ALT_MONTH_8     VARCHAR2(6 BYTE)          NOT NULL,
  PRM_ALT_MONTH_10    VARCHAR2(6 BYTE)          NOT NULL,
  PRM_ALT_MONTH_11    VARCHAR2(6 BYTE)          NOT NULL,
  PRM_ALT_MONTH_12    VARCHAR2(6 BYTE)          NOT NULL,
  SEC_ALT_MONTH_1     VARCHAR2(6 BYTE)          NOT NULL,
  SEC_ALT_MONTH_2     VARCHAR2(6 BYTE)          NOT NULL,
  SEC_ALT_MONTH_3     VARCHAR2(6 BYTE)          NOT NULL,
  SEC_ALT_MONTH_4     VARCHAR2(6 BYTE)          NOT NULL,
  SEC_ALT_MONTH_5     VARCHAR2(6 BYTE)          NOT NULL,
  SEC_ALT_MONTH_6     VARCHAR2(6 BYTE)          NOT NULL,
  SEC_ALT_MONTH_7     VARCHAR2(6 BYTE)          NOT NULL,
  SEC_ALT_MONTH_8     VARCHAR2(6 BYTE)          NOT NULL,
  SEC_ALT_MONTH_10    VARCHAR2(6 BYTE)          NOT NULL,
  SEC_ALT_MONTH_11    VARCHAR2(6 BYTE)          NOT NULL,
  SEC_ALT_MONTH_12    VARCHAR2(6 BYTE)          NOT NULL,
  TOTAL_INCOME        NUMBER(11)                NOT NULL,
  ALWNC_AGAINST_TI    INTEGER                   NOT NULL,
  STATE_TAX_ALWNC     INTEGER                   NOT NULL,
  EMPLOYMENT_ALWNC    INTEGER                   NOT NULL,
  INC_PROTECTN_ALWNC  INTEGER                   NOT NULL,
  AVAILABLE_INCOME    INTEGER                   NOT NULL,
  DESCRTN_NET_WORTH   INTEGER                   NOT NULL,
  AST_PROTECTN_ALWNC  INTEGER                   NOT NULL,
  CONTRIB_FROM_ASSET  INTEGER                   NOT NULL,
  ADJ_AVAILABLE_INC   INTEGER                   NOT NULL,
  TOTAL_PAR_CONTRIB   INTEGER                   NOT NULL,
  TOTAL_STU_CONTRIB   INTEGER                   NOT NULL,
  ADJ_PAR_CONTRIB     INTEGER                   NOT NULL,
  DEP_STU_I_CONTRIB   INTEGER                   NOT NULL,
  DEP_STU_A_CONTRIB   INTEGER                   NOT NULL,
  STU_TOTAL_INC       INTEGER                   NOT NULL,
  CONTRIB_AVAIL_INC   INTEGER                   NOT NULL,
  FICA_TAX_PD         NUMBER(11)                NOT NULL,
  CURRENCY_CD         VARCHAR2(3 BYTE)          NOT NULL,
  EFC_CALC_DT         DATE,
  BUDGET_DURATION     INTEGER                   NOT NULL,
  ADJ_EFC_AMT         INTEGER                   NOT NULL,
  WEEKLY_PC           INTEGER                   NOT NULL,
  WEEKLY_SC           INTEGER                   NOT NULL,
  PRORATED_EFC        INTEGER                   NOT NULL,
  SECONDARY_EFC_TP    VARCHAR2(1 BYTE)          NOT NULL,
  EFC_NET_WORTH       INTEGER                   NOT NULL,
  STU_ALLOW_VS_TI     INTEGER                   NOT NULL,
  STU_DISC_NET_WORTH  INTEGER                   NOT NULL,
  SEC_NET_WORTH       INTEGER                   NOT NULL,
  SEC_ALLOW_VS_TI     INTEGER                   NOT NULL,
  SEC_SDNW            INTEGER                   NOT NULL,
  PAID_EFC            INTEGER                   NOT NULL,
  ISIR_CALC_SC        INTEGER                   NOT NULL,
  ISIR_CALC_PC        INTEGER                   NOT NULL,
  ISIR_CALC_EFC       INTEGER                   NOT NULL,
  SFA_SIG_REJ_EFC     INTEGER                   NOT NULL,
  SFA_PRIMARY_PC      NUMBER(11)                NOT NULL,
  SFA_PRIMARY_SCA     NUMBER(11)                NOT NULL,
  SFA_PRIMARY_SIC     NUMBER(11)                NOT NULL,
  LOAD_ERROR          VARCHAR2(1 BYTE)          NOT NULL,
  DATA_ORIGIN         VARCHAR2(1 BYTE)          NOT NULL,
  CREATED_EW_DTTM     DATE,
  LASTUPD_EW_DTTM     DATE,
  BATCH_SID           NUMBER(10)                NOT NULL
)
COMPRESS BASIC
/
