DROP TABLE CSSTG_OWNER.PS_STDNT_ATTR_DTL CASCADE CONSTRAINTS
/

--
-- PS_STDNT_ATTR_DTL  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_STDNT_ATTR_DTL
(
  EMPLID              VARCHAR2(11 BYTE)         NOT NULL,
  ACAD_CAREER         VARCHAR2(4 BYTE)          NOT NULL,
  STDNT_CAR_NBR       INTEGER                   NOT NULL,
  EFFDT               DATE                      NOT NULL,
  EFFSEQ              INTEGER                   NOT NULL,
  STDNT_ATTR          VARCHAR2(4 BYTE)          NOT NULL,
  STDNT_ATTR_VALUE    VARCHAR2(10 BYTE)         NOT NULL,
  SRC_SYS_ID          VARCHAR2(5 BYTE)          NOT NULL,
  STDNT_ATTR_VAL_PRM  INTEGER                   NOT NULL,
  INSTITUTION         VARCHAR2(5 BYTE)          NOT NULL,
  LOAD_ERROR          VARCHAR2(1 BYTE)          NOT NULL,
  DATA_ORIGIN         VARCHAR2(1 BYTE)          NOT NULL,
  CREATED_EW_DTTM     DATE,
  LASTUPD_EW_DTTM     DATE,
  BATCH_SID           NUMBER(10)                NOT NULL
)
COMPRESS BASIC
/
