DROP TABLE CSSTG_OWNER.PS_T_HEALTH_TEST CASCADE CONSTRAINTS
/

--
-- PS_T_HEALTH_TEST  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_T_HEALTH_TEST
(
  EMPLID         VARCHAR2(11 BYTE)              NOT NULL,
  HEALTH_TEST    VARCHAR2(5 BYTE)               NOT NULL,
  HEALTH_SEQ     INTEGER                        NOT NULL,
  DATE_TAKEN     DATE,
  DATE_RECEIVED  DATE,
  TEST_VALUE     NUMBER(7,3)                    NOT NULL,
  TEST_RESULT    VARCHAR2(3 BYTE)               NOT NULL,
  COMMENTS       VARCHAR2(4000 BYTE),
  SRC_SCN        NUMBER
)
NOCOMPRESS
/
