DROP TABLE CSSTG_OWNER.PS_K_ETHNICITY_DTL CASCADE CONSTRAINTS
/

--
-- PS_K_ETHNICITY_DTL  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_K_ETHNICITY_DTL
(
  EMPLID         VARCHAR2(11 BYTE)              NOT NULL,
  REG_REGION     VARCHAR2(5 BYTE)               NOT NULL,
  ETHNIC_GRP_CD  VARCHAR2(8 BYTE)               NOT NULL,
  SRC_SYS_ID     VARCHAR2(5 BYTE)               NOT NULL
)
COMPRESS BASIC
/
