DROP TABLE CSSTG_OWNER.PS_E_CAMPUS_TBL CASCADE CONSTRAINTS
/

--
-- PS_E_CAMPUS_TBL  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_E_CAMPUS_TBL
(
  ERROR_SID           INTEGER                   NOT NULL,
  INSTITUTION         VARCHAR2(5 BYTE)          NOT NULL,
  CAMPUS              VARCHAR2(5 BYTE)          NOT NULL,
  EFFDT               DATE,
  SRC_SYS_ID          VARCHAR2(5 BYTE)          NOT NULL,
  TARGET_TABLE_NAME   VARCHAR2(15 BYTE)         NOT NULL,
  TARGET_TABLE_TYPE   VARCHAR2(3 BYTE)          NOT NULL,
  SOURCE_COLUMN_LIST  VARCHAR2(254 BYTE)        NOT NULL,
  LOOKUP_TABLE        VARCHAR2(15 BYTE)         NOT NULL,
  LOOKUP_COL_LIST     VARCHAR2(254 BYTE)        NOT NULL,
  ERR_DATA_VAL_LIST   VARCHAR2(1000 BYTE),
  LOAD_ERROR          VARCHAR2(1 BYTE)          NOT NULL,
  DATA_ORIGIN         VARCHAR2(1 BYTE)          NOT NULL,
  CREATED_EW_DTTM     DATE,
  LASTUPD_EW_DTTM     DATE,
  BATCH_SID           NUMBER(10)                NOT NULL
)
COMPRESS BASIC
/
