DROP TABLE CSSTG_OWNER.PS_T_IMMUNIZATIONS CASCADE CONSTRAINTS
/

--
-- PS_T_IMMUNIZATIONS  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_T_IMMUNIZATIONS
(
  EMPLID         VARCHAR2(11 BYTE)              NOT NULL,
  IMMUNIZATION   VARCHAR2(5 BYTE)               NOT NULL,
  IMMUN_SEQ      INTEGER                        NOT NULL,
  DATE_TAKEN     DATE,
  EXPIRATION_DT  DATE,
  DATE_RECEIVED  DATE,
  STATUS_IMMUN   VARCHAR2(1 BYTE)               NOT NULL,
  COMMENTS       VARCHAR2(4000 BYTE),
  SRC_SCN        NUMBER
)
COMPRESS BASIC
/
