DROP TABLE CSSTG_OWNER.PS_DISB_ID_TBL CASCADE CONSTRAINTS
/

--
-- PS_DISB_ID_TBL  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_DISB_ID_TBL
(
  INSTITUTION        VARCHAR2(5 BYTE)           NOT NULL,
  AID_YEAR           VARCHAR2(4 BYTE)           NOT NULL,
  ACAD_CAREER        VARCHAR2(4 BYTE)           NOT NULL,
  DISBURSEMENT_PLAN  VARCHAR2(2 BYTE)           NOT NULL,
  DISBURSEMENT_ID    VARCHAR2(2 BYTE)           NOT NULL,
  SRC_SYS_ID         VARCHAR2(5 BYTE)           NOT NULL,
  DESCR              VARCHAR2(30 BYTE)          NOT NULL,
  DESCRSHORT         VARCHAR2(10 BYTE)          NOT NULL,
  DISBURSEMENT_DATE  DATE                       NOT NULL,
  LOAN_DISB_DATE     DATE,
  STRM               VARCHAR2(4 BYTE)           NOT NULL,
  FISCAL_YEAR        INTEGER                    NOT NULL,
  LOAD_ERROR         VARCHAR2(1 BYTE)           NOT NULL,
  DATA_ORIGIN        VARCHAR2(1 BYTE)           NOT NULL,
  CREATED_EW_DTTM    DATE,
  LASTUPD_EW_DTTM    DATE,
  BATCH_SID          NUMBER(10)                 NOT NULL
)
COMPRESS BASIC
/
