DROP TABLE CSSTG_OWNER.PS_ADM_BASIS_ADMIT_OLD CASCADE CONSTRAINTS
/

--
-- PS_ADM_BASIS_ADMIT_OLD  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_ADM_BASIS_ADMIT_OLD
(
  EMPLID             VARCHAR2(11 BYTE)          NOT NULL,
  INSTITUTION        VARCHAR2(5 BYTE)           NOT NULL,
  ACAD_CAREER        VARCHAR2(4 BYTE)           NOT NULL,
  STDNT_CAR_NBR      INTEGER                    NOT NULL,
  BASIS_ADMIT_CODE   VARCHAR2(5 BYTE)           NOT NULL,
  ADMIT_TERM         VARCHAR2(4 BYTE)           NOT NULL,
  ACAD_PROG          VARCHAR2(5 BYTE)           NOT NULL,
  ADM_APPL_NBR       VARCHAR2(8 BYTE)           NOT NULL,
  APPL_PROG_NBR_AF   VARCHAR2(1 BYTE)           NOT NULL,
  SRC_SYS_ID         VARCHAR2(5 BYTE)           NOT NULL,
  BEGIN_DT           DATE,
  END_DT             DATE,
  INCLUDE_OFFER      VARCHAR2(1 BYTE)           NOT NULL,
  INCLUDE_IN_TSCRPT  VARCHAR2(1 BYTE)           NOT NULL,
  DESCR254           VARCHAR2(254 BYTE)         NOT NULL,
  LOAD_ERROR         VARCHAR2(1 BYTE)           NOT NULL,
  DATA_ORIGIN        VARCHAR2(1 BYTE)           NOT NULL,
  CREATED_EW_DTTM    DATE,
  LASTUPD_EW_DTTM    DATE,
  BATCH_SID          NUMBER(10)                 NOT NULL
)
COMPRESS BASIC
/
