DROP TABLE CSSTG_OWNER.PS_EXT_ACAD_DATA CASCADE CONSTRAINTS
/

--
-- PS_EXT_ACAD_DATA  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_EXT_ACAD_DATA
(
  EMPLID           VARCHAR2(11 BYTE)            NOT NULL,
  EXT_ORG_ID       VARCHAR2(11 BYTE)            NOT NULL,
  EXT_CAREER       VARCHAR2(4 BYTE)             NOT NULL,
  EXT_DATA_NBR     INTEGER                      NOT NULL,
  SRC_SYS_ID       VARCHAR2(5 BYTE)             NOT NULL,
  LS_DATA_SOURCE   VARCHAR2(3 BYTE)             NOT NULL,
  TRANSCRIPT_FLAG  VARCHAR2(1 BYTE)             NOT NULL,
  TRANSCRIPT_TYPE  VARCHAR2(3 BYTE)             NOT NULL,
  TRNSCRPT_STATUS  VARCHAR2(1 BYTE)             NOT NULL,
  EXT_ACAD_LEVEL   VARCHAR2(4 BYTE)             NOT NULL,
  TRANSCRIPT_DT    DATE,
  EXT_TERM_TYPE    VARCHAR2(4 BYTE)             NOT NULL,
  EXT_TERM         VARCHAR2(4 BYTE)             NOT NULL,
  TERM_YEAR        INTEGER                      NOT NULL,
  RECEIVED_FLAG    VARCHAR2(1 BYTE)             NOT NULL,
  RECEIVED_DT      DATE,
  DATA_MEDIUM      VARCHAR2(1 BYTE)             NOT NULL,
  FROM_DT          DATE,
  TO_DT            DATE,
  LOAD_ERROR       VARCHAR2(1 BYTE)             NOT NULL,
  DATA_ORIGIN      VARCHAR2(1 BYTE)             NOT NULL,
  CREATED_EW_DTTM  DATE,
  LASTUPD_EW_DTTM  DATE,
  BATCH_SID        NUMBER(10)                   NOT NULL
)
COMPRESS BASIC
/
