DROP TABLE CSSTG_OWNER.PS_BUDGET_ITEM CASCADE CONSTRAINTS
/

--
-- PS_BUDGET_ITEM  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_BUDGET_ITEM
(
  INSTITUTION         VARCHAR2(5 BYTE)          NOT NULL,
  BUDGET_GROUP_CODE   VARCHAR2(6 BYTE)          NOT NULL,
  AID_YEAR            VARCHAR2(4 BYTE)          NOT NULL,
  ACAD_CAREER         VARCHAR2(4 BYTE)          NOT NULL,
  STRM                VARCHAR2(4 BYTE)          NOT NULL,
  BGT_ITEM_CATEGORY   VARCHAR2(4 BYTE)          NOT NULL,
  SRC_SYS_ID          VARCHAR2(5 BYTE)          NOT NULL,
  BUDGET_ITEM_CD      VARCHAR2(6 BYTE)          NOT NULL,
  BUDGET_ITEM_AMOUNT  NUMBER(7,2)               NOT NULL,
  PELL_ITEM_AMOUNT    NUMBER(7,2)               NOT NULL,
  SFA_PELITMAMT_LHT   NUMBER(7,2)               NOT NULL,
  CURRENCY_CD         VARCHAR2(3 BYTE)          NOT NULL,
  LOAD_ERROR          VARCHAR2(1 BYTE)          NOT NULL,
  DATA_ORIGIN         VARCHAR2(1 BYTE)          NOT NULL,
  CREATED_EW_DTTM     DATE,
  LASTUPD_EW_DTTM     DATE,
  BATCH_SID           NUMBER(10)                NOT NULL
)
COMPRESS BASIC
/
