DROP TABLE CSSTG_OWNER.PS_ADM_APPLCTR_TBL CASCADE CONSTRAINTS
/

--
-- PS_ADM_APPLCTR_TBL  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_ADM_APPLCTR_TBL
(
  INSTITUTION         VARCHAR2(5 BYTE)          NOT NULL,
  ADM_APPL_CTR        VARCHAR2(4 BYTE)          NOT NULL,
  EFFDT               DATE                      NOT NULL,
  SRC_SYS_ID          VARCHAR2(5 BYTE)          NOT NULL,
  EFF_STATUS          VARCHAR2(1 BYTE)          NOT NULL,
  DESCR               VARCHAR2(30 BYTE)         NOT NULL,
  DESCRSHORT          VARCHAR2(10 BYTE)         NOT NULL,
  FEE_CODE            VARCHAR2(6 BYTE)          NOT NULL,
  ACAD_CAREER         VARCHAR2(4 BYTE)          NOT NULL,
  DEPOSIT_FEE_CD      VARCHAR2(6 BYTE)          NOT NULL,
  SF_MERCHANT_ID      VARCHAR2(12 BYTE)         NOT NULL,
  BATCH_APP_FEE_FLG   VARCHAR2(1 BYTE)          NOT NULL,
  BATCH_DEP_FEE_FLG   VARCHAR2(1 BYTE)          NOT NULL,
  SAD_CRM_SA_URL_ID   VARCHAR2(30 BYTE)         NOT NULL,
  SAD_CRM_CRM_URL_ID  VARCHAR2(30 BYTE)         NOT NULL,
  LOAD_ERROR          VARCHAR2(1 BYTE)          NOT NULL,
  DATA_ORIGIN         VARCHAR2(1 BYTE)          NOT NULL,
  CREATED_EW_DTTM     DATE,
  LASTUPD_EW_DTTM     DATE,
  BATCH_SID           NUMBER(10)                NOT NULL
)
COMPRESS BASIC
/
