DROP TABLE CSSTG_OWNER.PS_UM_TCA_REVIEW CASCADE CONSTRAINTS
/

--
-- PS_UM_TCA_REVIEW  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_UM_TCA_REVIEW
(
  EMPLID           VARCHAR2(11 BYTE)            NOT NULL,
  ACAD_CAREER      VARCHAR2(4 BYTE)             NOT NULL,
  STDNT_CAR_NBR    INTEGER                      NOT NULL,
  ADM_APPL_NBR     VARCHAR2(8 BYTE)             NOT NULL,
  APPL_PROG_NBR    INTEGER                      NOT NULL,
  SRC_SYS_ID       VARCHAR2(5 BYTE)             NOT NULL,
  UM_TCA_CREDITS   NUMBER(5,2)                  NOT NULL,
  UM_TCA_COMPLETE  VARCHAR2(1 BYTE)             NOT NULL,
  LOAD_ERROR       VARCHAR2(1 BYTE)             NOT NULL,
  DATA_ORIGIN      VARCHAR2(1 BYTE)             NOT NULL,
  CREATED_EW_DTTM  DATE,
  LASTUPD_EW_DTTM  DATE,
  BATCH_SID        NUMBER(10)                   NOT NULL
)
COMPRESS BASIC
/
