DROP TABLE CSSTG_OWNER.PS_T_ADM_APPL_RCR_CA CASCADE CONSTRAINTS
/

--
-- PS_T_ADM_APPL_RCR_CA  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_T_ADM_APPL_RCR_CA
(
  EMPLID           VARCHAR2(11 BYTE)            NOT NULL,
  ACAD_CAREER      VARCHAR2(4 BYTE)             NOT NULL,
  STDNT_CAR_NBR    INTEGER                      NOT NULL,
  ADM_APPL_NBR     VARCHAR2(8 BYTE)             NOT NULL,
  INSTITUTION      VARCHAR2(5 BYTE)             NOT NULL,
  RECRUITMENT_CAT  VARCHAR2(4 BYTE)             NOT NULL,
  RECRUIT_SUB_CAT  VARCHAR2(4 BYTE)             NOT NULL,
  DESCRLONG        VARCHAR2(4000 BYTE),
  SRC_SCN          NUMBER
)
NOCOMPRESS
/
