DROP TABLE CSSTG_OWNER.PS_STDNT_AWRD_DISB CASCADE CONSTRAINTS
/

--
-- PS_STDNT_AWRD_DISB  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_STDNT_AWRD_DISB
(
  EMPLID              VARCHAR2(11 BYTE)         NOT NULL,
  INSTITUTION         VARCHAR2(5 BYTE)          NOT NULL,
  AID_YEAR            VARCHAR2(4 BYTE)          NOT NULL,
  ITEM_TYPE           VARCHAR2(12 BYTE)         NOT NULL,
  ACAD_CAREER         VARCHAR2(4 BYTE)          NOT NULL,
  DISBURSEMENT_ID     VARCHAR2(2 BYTE)          NOT NULL,
  SRC_SYS_ID          VARCHAR2(5 BYTE)          NOT NULL,
  OFFER_BALANCE       NUMBER(11,2)              NOT NULL,
  ACCEPT_BALANCE      NUMBER(11,2)              NOT NULL,
  AUTHORIZED_BALANCE  NUMBER(11,2)              NOT NULL,
  DISBURSED_BALANCE   NUMBER(11,2)              NOT NULL,
  NET_DISB_BALANCE    NUMBER(11,2)              NOT NULL,
  CURRENCY_CD         VARCHAR2(3 BYTE)          NOT NULL,
  BUSINESS_UNIT       VARCHAR2(5 BYTE)          NOT NULL,
  AGGREGATE_AREA      VARCHAR2(10 BYTE)         NOT NULL,
  AGGREGATE_LEVEL     VARCHAR2(2 BYTE)          NOT NULL,
  CPS_SCHOOL_CODE     VARCHAR2(6 BYTE)          NOT NULL,
  OFFER_BAL_LN_FEE    NUMBER(6,2)               NOT NULL,
  ACCEPT_BAL_LN_FEE   NUMBER(6,2)               NOT NULL,
  OFFER_BAL_REBATE    NUMBER(6,2)               NOT NULL,
  ACCEPT_BAL_REBATE   NUMBER(6,2)               NOT NULL,
  SFA_AGGR_BALANCE    NUMBER(11,2)              NOT NULL,
  STRM                VARCHAR2(4 BYTE)          NOT NULL,
  LOAD_ERROR          VARCHAR2(1 BYTE)          NOT NULL,
  DATA_ORIGIN         VARCHAR2(1 BYTE)          NOT NULL,
  CREATED_EW_DTTM     DATE,
  LASTUPD_EW_DTTM     DATE,
  BATCH_SID           NUMBER(10)                NOT NULL
)
COMPRESS BASIC
/
