DROP TABLE CSSTG_OWNER.PS_APPOINTMENT_TBL CASCADE CONSTRAINTS
/

--
-- PS_APPOINTMENT_TBL  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_APPOINTMENT_TBL
(
  INSTITUTION         VARCHAR2(5 BYTE)          NOT NULL,
  ACAD_CAREER         VARCHAR2(4 BYTE)          NOT NULL,
  STRM                VARCHAR2(4 BYTE)          NOT NULL,
  SESSION_CODE        VARCHAR2(3 BYTE)          NOT NULL,
  SSR_APPT_BLOCK      VARCHAR2(6 BYTE)          NOT NULL,
  APPOINTMENT_NBR     VARCHAR2(4 BYTE)          NOT NULL,
  SRC_SYS_ID          VARCHAR2(5 BYTE)          NOT NULL,
  APPT_START_DATE     DATE                      NOT NULL,
  APPT_START_TIME     DATE                      NOT NULL,
  APPT_END_DATE       DATE                      NOT NULL,
  APPT_END_TIME       DATE                      NOT NULL,
  SSR_APPT_NBR_STDNT  INTEGER                   NOT NULL,
  SSR_APPT_STD_ASGN   INTEGER                   NOT NULL,
  LOAD_ERROR          VARCHAR2(1 BYTE)          NOT NULL,
  DATA_ORIGIN         VARCHAR2(1 BYTE)          NOT NULL,
  CREATED_EW_DTTM     DATE,
  LASTUPD_EW_DTTM     DATE,
  BATCH_SID           NUMBER(10)                NOT NULL
)
COMPRESS BASIC
/
