DROP TABLE CSSTG_OWNER.PS_LN_TYPE_TBL CASCADE CONSTRAINTS
/

--
-- PS_LN_TYPE_TBL  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_LN_TYPE_TBL
(
  INSTITUTION         VARCHAR2(5 BYTE)          NOT NULL,
  AID_YEAR            VARCHAR2(4 BYTE)          NOT NULL,
  LOAN_TYPE           VARCHAR2(4 BYTE)          NOT NULL,
  SRC_SYS_ID          VARCHAR2(5 BYTE)          NOT NULL,
  DESCR               VARCHAR2(30 BYTE)         NOT NULL,
  DESCRSHORT          VARCHAR2(10 BYTE)         NOT NULL,
  LOAN_PROGRAM        VARCHAR2(1 BYTE)          NOT NULL,
  LOAN_CATEGORY       VARCHAR2(1 BYTE)          NOT NULL,
  LOAN_FEE_RT         NUMBER(5,3)               NOT NULL,
  LOAN_INS_RT         NUMBER(4,2)               NOT NULL,
  LOAN_REF_RQRD       VARCHAR2(1 BYTE)          NOT NULL,
  LOAN_NBR_REF_RQRD   INTEGER                   NOT NULL,
  LOAN_COSIGN_RQRD    VARCHAR2(1 BYTE)          NOT NULL,
  LOAN_AMT_COSIGN     INTEGER                   NOT NULL,
  LOAN_NBR_CSGN_RQRD  INTEGER                   NOT NULL,
  LOAN_CREDIT_RQRD    VARCHAR2(1 BYTE)          NOT NULL,
  LOAN_PCKG_ORDR      VARCHAR2(1 BYTE)          NOT NULL,
  FED_OR_INST_COST    VARCHAR2(1 BYTE)          NOT NULL,
  SVCR_PRINT_PNOTE    VARCHAR2(1 BYTE)          NOT NULL,
  LN_REFUND_INDC      VARCHAR2(1 BYTE)          NOT NULL,
  CL_TYPE_CODE        VARCHAR2(2 BYTE)          NOT NULL,
  CL_ALT_LN_TYPE_CD   VARCHAR2(3 BYTE)          NOT NULL,
  LN_RPT_PKG_ID       VARCHAR2(10 BYTE)         NOT NULL,
  CHECKLIST_CD        VARCHAR2(6 BYTE)          NOT NULL,
  CURRENCY_CD         VARCHAR2(3 BYTE)          NOT NULL,
  LN_DL_DISB_SW       VARCHAR2(1 BYTE)          NOT NULL,
  LN_DL_TRNS_DISB_SW  VARCHAR2(1 BYTE)          NOT NULL,
  DL_VER_TYPE_USE     VARCHAR2(1 BYTE)          NOT NULL,
  LN_MAX_NBR_DISBS    INTEGER                   NOT NULL,
  LN_MIN_LOAN_AMT     INTEGER                   NOT NULL,
  LN_DL_ADD_DAYS      INTEGER                   NOT NULL,
  SFA_LN_GRAD_PLUS    VARCHAR2(1 BYTE)          NOT NULL,
  SFA_ADDL_USUB_IND   VARCHAR2(1 BYTE)          NOT NULL,
  LOAD_ERROR          VARCHAR2(1 BYTE)          NOT NULL,
  DATA_ORIGIN         VARCHAR2(1 BYTE)          NOT NULL,
  CREATED_EW_DTTM     DATE,
  LASTUPD_EW_DTTM     DATE,
  BATCH_SID           NUMBER(10)                NOT NULL
)
COMPRESS BASIC
/
