DROP TABLE CSSTG_OWNER.PS_STDNT_AGGR_SCHL CASCADE CONSTRAINTS
/

--
-- PS_STDNT_AGGR_SCHL  (Table) 
--
CREATE TABLE CSSTG_OWNER.PS_STDNT_AGGR_SCHL
(
  EMPLID            VARCHAR2(11 BYTE)           NOT NULL,
  AGGREGATE_AREA    VARCHAR2(10 BYTE)           NOT NULL,
  AID_YEAR          VARCHAR2(4 BYTE)            NOT NULL,
  AGGREGATE_LEVEL   VARCHAR2(2 BYTE)            NOT NULL,
  CPS_SCHOOL_CODE   VARCHAR2(6 BYTE)            NOT NULL,
  AGGREGATE_STATUS  VARCHAR2(1 BYTE)            NOT NULL,
  SRC_SYS_ID        VARCHAR2(5 BYTE)            NOT NULL,
  EXPECTED_AWARD    NUMBER(11,2)                NOT NULL,
  ACTUAL_AWARD      NUMBER(11,2)                NOT NULL,
  SCHEDULED_AWARD   NUMBER(11,2)                NOT NULL,
  TERM_COUNT        INTEGER                     NOT NULL,
  ACAD_YEAR         VARCHAR2(4 BYTE)            NOT NULL,
  CURRENCY_CD       VARCHAR2(3 BYTE)            NOT NULL,
  LOAD_ERROR        VARCHAR2(1 BYTE)            NOT NULL,
  DATA_ORIGIN       VARCHAR2(1 BYTE)            NOT NULL,
  CREATED_EW_DTTM   DATE,
  LASTUPD_EW_DTTM   DATE,
  BATCH_SID         NUMBER(10)                  NOT NULL
)
COMPRESS BASIC
/
