DROP VIEW CSSTG_OWNER.BB_COURSE_TERM_S2_VW
/

--
-- BB_COURSE_TERM_S2_VW  (View) 
--
CREATE OR REPLACE VIEW CSSTG_OWNER.BB_COURSE_TERM_S2_VW
BEQUEATH DEFINER
AS 
select BB_SOURCE,PK1,TERM_PK1,CRSMAIN_PK1,DELETE_FLAG,INSERT_TIME,UPDATE_TIME from CSSTG_OWNER.BB_COURSE_TERM_S2@SMTPROD
/
