DROP VIEW CSSTG_OWNER.PS_PRSPCT_RCR_CAT_VW
/

--
-- PS_PRSPCT_RCR_CAT_VW  (View) 
--
CREATE OR REPLACE VIEW CSSTG_OWNER.PS_PRSPCT_RCR_CAT_VW
BEQUEATH DEFINER
AS 
SELECT 
EMPLID, 
ACAD_CAREER, 
INSTITUTION, 
RECRUITMENT_CAT, 
SRC_SYS_ID, 
RECRUIT_SUB_CAT, 
MOVE_TO_APPL, 
PROMPT_RECRUITER, 
LOAD_ERROR, 
DATA_ORIGIN, 
CREATED_EW_DTTM, 
LASTUPD_EW_DTTM, 
BATCH_SID, 
CAST (TRIM (SUBSTR (DESCRLONG, 1, 2000)) AS VARCHAR2 (2000)) DESCRLONG
FROM PS_PRSPCT_RCR_CAT
/
