DROP VIEW CSSTG_OWNER.PS_STDNT_GRPS_HIST_VW
/

--
-- PS_STDNT_GRPS_HIST_VW  (View) 
--
CREATE OR REPLACE VIEW CSSTG_OWNER.PS_STDNT_GRPS_HIST_VW
BEQUEATH DEFINER
AS 
SELECT 
EMPLID, 
INSTITUTION, 
STDNT_GROUP, 
EFFDT, 
SRC_SYS_ID, 
EFF_STATUS, 
LOAD_ERROR, 
DATA_ORIGIN, 
CREATED_EW_DTTM, 
LASTUPD_EW_DTTM, 
BATCH_SID, 
CAST (TRIM (SUBSTR (COMMENTS, 1, 2000)) AS VARCHAR2 (2000)) COMMENTS
FROM PS_STDNT_GRPS_HIST
/
