DROP VIEW CSSTG_OWNER.UMOL_ACTIVITY_ACCUMULATOR_UMLOW_VW
/

--
-- UMOL_ACTIVITY_ACCUMULATOR_UMLOW_VW  (View) 
--
CREATE OR REPLACE VIEW CSSTG_OWNER.UMOL_ACTIVITY_ACCUMULATOR_UMLOW_VW
BEQUEATH DEFINER
AS 
select PK1,EVENT_TYPE,USER_PK1,COURSE_PK1,GROUP_PK1,FORUM_PK1,INTERNAL_HANDLE,CONTENT_PK1,DATA,TIMESTAMP,STATUS,SESSION_ID,DELETE_FLAG,INSERT_TIME,UPDATE_TIME from CSSTG_OWNER.UMOL_ACTIVITY_ACCUMULATOR_UMLOW@SMTPROD
/
