DROP VIEW CSSTG_OWNER.PS_E_ADM_APPL_STAT
/

--
-- PS_E_ADM_APPL_STAT  (View) 
--
CREATE OR REPLACE VIEW CSSTG_OWNER.PS_E_ADM_APPL_STAT
BEQUEATH DEFINER
AS 
select 
TARGET_TABLE, TARGET_COLUMN, TARGET_COL_LIST, TARGET_VAL_LIST, 
substr(TARGET_VAL_LIST,1,8) EMPLID,
SOURCE_TABLE, SOURCE_COL_LIST, 
LOOKUP_TABLE, LOOKUP_COL_LIST, LOOKUP_VAL_LIST, 
LOAD_ERROR, DATA_ORIGIN, CREATED_EW_DTTM, LASTUPD_EW_DTTM, BATCH_SID
from CSSTG_OWNER.UM_E_LOOKUP
where TARGET_TABLE = 'PS_F_ADM_APPL_STAT'
/
