DROP VIEW CSSTG_OWNER.BB_CLASSIFICATIONS_S2_VW
/

--
-- BB_CLASSIFICATIONS_S2_VW  (View) 
--
CREATE OR REPLACE VIEW CSSTG_OWNER.BB_CLASSIFICATIONS_S2_VW
BEQUEATH DEFINER
AS 
select BB_SOURCE,PK1,TITLE,BATCH_UID,ROW_STATUS,DATA_SRC_PK1,PARENT_PK1,DELETE_FLAG,INSERT_TIME,UPDATE_TIME from CSSTG_OWNER.BB_CLASSIFICATIONS_S2@SMTPROD
/
