DROP VIEW CSSTG_OWNER.BB_CONFERENCE_MAIN_S2_VW
/

--
-- BB_CONFERENCE_MAIN_S2_VW  (View) 
--
CREATE OR REPLACE VIEW CSSTG_OWNER.BB_CONFERENCE_MAIN_S2_VW
BEQUEATH DEFINER
AS 
select BB_SOURCE,PK1,DTCREATED,DTMODIFIED,CRSMAIN_PK1,GROUPS_PK1,AVAILABLE_IND,TEXT_FORMAT_TYPE,ORDER_NUM,NAME,ICON,DELETE_FLAG,INSERT_TIME,UPDATE_TIME from CSSTG_OWNER.BB_CONFERENCE_MAIN_S2@SMTPROD
/
