DROP VIEW CSSTG_OWNER.PS_CAMPUS_EVENT_VW
/

--
-- PS_CAMPUS_EVENT_VW  (View) 
--
CREATE OR REPLACE VIEW CSSTG_OWNER.PS_CAMPUS_EVENT_VW
BEQUEATH DEFINER
AS 
SELECT 
CAMPUS_EVENT_NBR, 
SRC_SYS_ID, 
INSTITUTION, 
DESCR, 
DESCRSHORT, 
CAMPUS_EVENT_TYPE, 
EVENT_MANAGER, 
PRIMARY_MEETING, 
ATTENDEE_NBR_LST, 
LOAD_ERROR, 
DATA_ORIGIN, 
CREATED_EW_DTTM, 
LASTUPD_EW_DTTM, 
BATCH_SID, 
CAST (TRIM (SUBSTR (COMMENTS, 1, 2000)) AS VARCHAR2 (2000)) COMMENTS
FROM PS_CAMPUS_EVENT
/
