DROP MATERIALIZED VIEW CSMRT_OWNER.UM_F_SAA_RES_CRSEAVL_MV
/

--
-- UM_F_SAA_RES_CRSEAVL_MV  (Materialized View) 
--
CREATE MATERIALIZED VIEW CSMRT_OWNER.UM_F_SAA_RES_CRSEAVL_MV 
    (R_EMPLID,R_ANALYSIS_DB_SEQ,R_SAA_CAREER_RPT,R_SAA_ENTRY_SEQ,R_SRC_SYS_ID,
     R_INSTITUTION_CD,R_INSTITUTION_SID,R_ACAD_CAR_SID,R_TERM_SID,R_PERSON_SID,
     R_RQRMNT_GROUP_SID,R_REQUIREMENT_SID,R_RQRMNT_LINE_SID,R_ACAD_PROG_SID,R_ACAD_PLAN_SID,
     R_ACAD_SPLAN_SID,R_RPT_DATE,R_RPT_TYPE,R_RPT_TYPE_SD,R_RPT_TYPE_LD,
     R_SAA_RPT_IDENTIFIER,R_TSCRPT_TYPE,R_SAA_RPT_DTTM_STAMP,R_ENTRY_R_TYPE,R_ITEM_R_STATUS,
     R_ITEM_R_STATUS_SD,R_ITEM_R_STATUS_LD,R_RQ_DATE,R_RQRMNT_LIST_SEQ,R_REQ_LINE_TYPE,
     R_REQ_LINE_TYPE_SD,R_REQ_LINE_TYPE_LD,R_UNITS_REQUIRED,R_SAA_UNITS_USED,R_UNITS_NEEDED,
     R_CRSES_REQUIRED,R_SAA_CRSES_USED,R_CRSES_NEEDED,R_SAA_CRSE_COUNT,R_GPA_REQUIRED,
     R_GPA_ACTUAL,R_CREATED_EW_DTTM,A_EMPLID,A_ANALYSIS_DB_SEQ,A_SAA_CAREER_RPT,
     A_SAA_ENTRY_SEQ,A_SAA_COURSE_SEQ,A_SRC_SYS_ID,A_INSTITUTION_CD,A_CRSE_SID,
     A_PLAN_TERM_SID,A_COURSE_LIST,A_R_COURSE_SEQUENCE,A_SUBJECT,A_CATALOG_NBR,
     A_CRSE_ID,A_CRSE_OFFER_NUM,A_CRS_TOPIC_ID,A_EARN_CREDIT,A_PRE_REQ_MET_FLG,
     A_ENROLL_FLG,A_DEMAND_COUNT,A_PLAN_COUNT,A_CREATED_EW_DTTM)
COMPRESS BASIC
BUILD DEFERRED
USING NO INDEX
REFRESH COMPLETE ON DEMAND
WITH PRIMARY KEY
ENABLE QUERY REWRITE
AS 
/* Formatted on 11/22/2022 4:04:33 PM (QP5 v5.381) */
SELECT /*+ parallel(8) */
       UM_F_SAA_ADB_RESULTS.EMPLID                 R_EMPLID,
       UM_F_SAA_ADB_RESULTS.ANALYSIS_DB_SEQ        R_ANALYSIS_DB_SEQ,
       UM_F_SAA_ADB_RESULTS.SAA_CAREER_RPT         R_SAA_CAREER_RPT,
       UM_F_SAA_ADB_RESULTS.SAA_ENTRY_SEQ          R_SAA_ENTRY_SEQ,
       UM_F_SAA_ADB_RESULTS.SRC_SYS_ID             R_SRC_SYS_ID,
       UM_F_SAA_ADB_RESULTS.INSTITUTION_CD         R_INSTITUTION_CD,
       UM_F_SAA_ADB_RESULTS.INSTITUTION_SID        R_INSTITUTION_SID,
       UM_F_SAA_ADB_RESULTS.ACAD_CAR_SID           R_ACAD_CAR_SID,
       UM_F_SAA_ADB_RESULTS.TERM_SID               R_TERM_SID,
       UM_F_SAA_ADB_RESULTS.PERSON_SID             R_PERSON_SID,
       UM_F_SAA_ADB_RESULTS.RQRMNT_GROUP_SID       R_RQRMNT_GROUP_SID,
       UM_F_SAA_ADB_RESULTS.REQUIREMENT_SID        R_REQUIREMENT_SID,
       UM_F_SAA_ADB_RESULTS.RQRMNT_LINE_SID        R_RQRMNT_LINE_SID,
       UM_F_SAA_ADB_RESULTS.ACAD_PROG_SID          R_ACAD_PROG_SID,
       UM_F_SAA_ADB_RESULTS.ACAD_PLAN_SID          R_ACAD_PLAN_SID,
       UM_F_SAA_ADB_RESULTS.ACAD_SPLAN_SID         R_ACAD_SPLAN_SID,
       UM_F_SAA_ADB_RESULTS.RPT_DATE               R_RPT_DATE,
       UM_F_SAA_ADB_RESULTS.RPT_TYPE               R_RPT_TYPE,
       UM_F_SAA_ADB_RESULTS.RPT_TYPE_SD            R_RPT_TYPE_SD,
       UM_F_SAA_ADB_RESULTS.RPT_TYPE_LD            R_RPT_TYPE_LD,
       UM_F_SAA_ADB_RESULTS.SAA_RPT_IDENTIFIER     R_SAA_RPT_IDENTIFIER,
       UM_F_SAA_ADB_RESULTS.TSCRPT_TYPE            R_TSCRPT_TYPE,
       UM_F_SAA_ADB_RESULTS.SAA_RPT_DTTM_STAMP     R_SAA_RPT_DTTM_STAMP,
       UM_F_SAA_ADB_RESULTS.ENTRY_R_TYPE           R_ENTRY_R_TYPE,
       UM_F_SAA_ADB_RESULTS.ITEM_R_STATUS          R_ITEM_R_STATUS,
       UM_F_SAA_ADB_RESULTS.ITEM_R_STATUS_SD       R_ITEM_R_STATUS_SD,
       UM_F_SAA_ADB_RESULTS.ITEM_R_STATUS_LD       R_ITEM_R_STATUS_LD,
       UM_F_SAA_ADB_RESULTS.RQ_DATE                R_RQ_DATE,
       UM_F_SAA_ADB_RESULTS.RQRMNT_LIST_SEQ        R_RQRMNT_LIST_SEQ,
       UM_F_SAA_ADB_RESULTS.REQ_LINE_TYPE          R_REQ_LINE_TYPE,
       UM_F_SAA_ADB_RESULTS.REQ_LINE_TYPE_SD       R_REQ_LINE_TYPE_SD,
       UM_F_SAA_ADB_RESULTS.REQ_LINE_TYPE_LD       R_REQ_LINE_TYPE_LD,
       UM_F_SAA_ADB_RESULTS.UNITS_REQUIRED         R_UNITS_REQUIRED,
       UM_F_SAA_ADB_RESULTS.SAA_UNITS_USED         R_SAA_UNITS_USED,
       UM_F_SAA_ADB_RESULTS.UNITS_NEEDED           R_UNITS_NEEDED,
       UM_F_SAA_ADB_RESULTS.CRSES_REQUIRED         R_CRSES_REQUIRED,
       UM_F_SAA_ADB_RESULTS.SAA_CRSES_USED         R_SAA_CRSES_USED,
       UM_F_SAA_ADB_RESULTS.CRSES_NEEDED           R_CRSES_NEEDED,
       UM_F_SAA_ADB_RESULTS.SAA_CRSE_COUNT         R_SAA_CRSE_COUNT,
       UM_F_SAA_ADB_RESULTS.GPA_REQUIRED           R_GPA_REQUIRED,
       UM_F_SAA_ADB_RESULTS.GPA_ACTUAL             R_GPA_ACTUAL,
       UM_F_SAA_ADB_RESULTS.CREATED_EW_DTTM        R_CREATED_EW_DTTM,
       UM_F_SAA_ADB_CRSEAVL.EMPLID                 A_EMPLID,
       UM_F_SAA_ADB_CRSEAVL.ANALYSIS_DB_SEQ        A_ANALYSIS_DB_SEQ,
       UM_F_SAA_ADB_CRSEAVL.SAA_CAREER_RPT         A_SAA_CAREER_RPT,
       UM_F_SAA_ADB_CRSEAVL.SAA_ENTRY_SEQ          A_SAA_ENTRY_SEQ,
       UM_F_SAA_ADB_CRSEAVL.SAA_COURSE_SEQ         A_SAA_COURSE_SEQ,
       UM_F_SAA_ADB_CRSEAVL.SRC_SYS_ID             A_SRC_SYS_ID,
       UM_F_SAA_ADB_CRSEAVL.INSTITUTION_CD         A_INSTITUTION_CD,
       UM_F_SAA_ADB_CRSEAVL.CRSE_SID               A_CRSE_SID,
       UM_F_SAA_ADB_CRSEAVL.PLAN_TERM_SID          A_PLAN_TERM_SID,
       UM_F_SAA_ADB_CRSEAVL.COURSE_LIST            A_COURSE_LIST,
       UM_F_SAA_ADB_CRSEAVL.R_COURSE_SEQUENCE      A_R_COURSE_SEQUENCE, -- Remove???
       UM_F_SAA_ADB_CRSEAVL.SUBJECT                A_SUBJECT,     -- Remove???
       UM_F_SAA_ADB_CRSEAVL.CATALOG_NBR            A_CATALOG_NBR, -- Remove???
       UM_F_SAA_ADB_CRSEAVL.CRSE_ID                A_CRSE_ID,     -- Remove???
       UM_F_SAA_ADB_CRSEAVL.CRSE_OFFER_NUM         A_CRSE_OFFER_NUM, -- Remove???
       UM_F_SAA_ADB_CRSEAVL.CRS_TOPIC_ID           A_CRS_TOPIC_ID,
       UM_F_SAA_ADB_CRSEAVL.EARN_CREDIT            A_EARN_CREDIT,
       UM_F_SAA_ADB_CRSEAVL.PRE_REQ_MET_FLG        A_PRE_REQ_MET_FLG,
       UM_F_SAA_ADB_CRSEAVL.ENROLL_FLG             A_ENROLL_FLG, -- Added Mar 2017
       UM_F_SAA_ADB_CRSEAVL.DEMAND_COUNT           A_DEMAND_COUNT,
       UM_F_SAA_ADB_CRSEAVL.PLAN_COUNT             A_PLAN_COUNT,
       UM_F_SAA_ADB_CRSEAVL.CREATED_EW_DTTM        A_CREATED_EW_DTTM
  FROM UM_F_SAA_ADB_RESULTS, UM_F_SAA_ADB_CRSEAVL
 WHERE     UM_F_SAA_ADB_RESULTS.EMPLID = UM_F_SAA_ADB_CRSEAVL.EMPLID
       AND UM_F_SAA_ADB_RESULTS.ANALYSIS_DB_SEQ =
           UM_F_SAA_ADB_CRSEAVL.ANALYSIS_DB_SEQ
       AND UM_F_SAA_ADB_RESULTS.SAA_CAREER_RPT =
           UM_F_SAA_ADB_CRSEAVL.SAA_CAREER_RPT
       AND UM_F_SAA_ADB_RESULTS.SAA_ENTRY_SEQ =
           UM_F_SAA_ADB_CRSEAVL.SAA_ENTRY_SEQ
       AND UM_F_SAA_ADB_RESULTS.SRC_SYS_ID = UM_F_SAA_ADB_CRSEAVL.SRC_SYS_ID
/


COMMENT ON MATERIALIZED VIEW CSMRT_OWNER.UM_F_SAA_RES_CRSEAVL_MV IS 'snapshot table for snapshot CSMRT_OWNER.UM_F_SAA_RES_CRSEAVL_MV'
/

--
-- FK_UM_F_SAA_RES_CRSEAVL_MV9  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_SAA_RES_CRSEAVL_MV9 ON CSMRT_OWNER.UM_F_SAA_RES_CRSEAVL_MV
(R_TERM_SID)
/

--
-- UM_F_SAA_RES_CRSEAVL_MV10  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.UM_F_SAA_RES_CRSEAVL_MV10 ON CSMRT_OWNER.UM_F_SAA_RES_CRSEAVL_MV
(R_PERSON_SID)
/

--
-- UM_F_SAA_RES_CRSEAVL_MV50  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.UM_F_SAA_RES_CRSEAVL_MV50 ON CSMRT_OWNER.UM_F_SAA_RES_CRSEAVL_MV
(A_CRSE_SID)
/

--
-- UM_F_SAA_RES_CRSEAVL_MV51  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.UM_F_SAA_RES_CRSEAVL_MV51 ON CSMRT_OWNER.UM_F_SAA_RES_CRSEAVL_MV
(A_PLAN_TERM_SID)
/

--
-- UM_F_SAA_RES_CRSEAVL_MV54  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.UM_F_SAA_RES_CRSEAVL_MV54 ON CSMRT_OWNER.UM_F_SAA_RES_CRSEAVL_MV
(A_SUBJECT)
/

--
-- UM_F_SAA_RES_CRSEAVL_MV7  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.UM_F_SAA_RES_CRSEAVL_MV7 ON CSMRT_OWNER.UM_F_SAA_RES_CRSEAVL_MV
(R_INSTITUTION_SID)
/

--
-- UM_F_SAA_RES_CRSEAVL_MV8  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.UM_F_SAA_RES_CRSEAVL_MV8 ON CSMRT_OWNER.UM_F_SAA_RES_CRSEAVL_MV
(R_ACAD_CAR_SID)
/
