ALTER TABLE CSMRT_OWNER.UM_D_PERSON_CITIZEN
  DROP CONSTRAINT PK_UM_D_PERSON_CITIZEN
/

ALTER TABLE CSMRT_OWNER.UM_D_PERSON_CITIZEN ADD (
  CONSTRAINT PK_UM_D_PERSON_CITIZEN
  PRIMARY KEY
  (PERSON_ID, DEPENDENT_ID, COUNTRY, SRC_SYS_ID)
  RELY
  ENABLE VALIDATE)
/
