ALTER TABLE CSMRT_OWNER.PS_D_EXT_ACAD_LVL
  DROP CONSTRAINT PK_PS_D_EXT_ACAD_LVL
/

ALTER TABLE CSMRT_OWNER.PS_D_EXT_ACAD_LVL ADD (
  CONSTRAINT PK_PS_D_EXT_ACAD_LVL
  PRIMARY KEY
  (EXT_ACAD_LVL_SID)
  RELY
  DISABLE NOVALIDATE)
/
