ALTER TABLE CSMRT_OWNER.PS_D_CHKLST_CD
  DROP CONSTRAINT PK_PS_D_CHKLST_CD
/

ALTER TABLE CSMRT_OWNER.PS_D_CHKLST_CD ADD (
  CONSTRAINT PK_PS_D_CHKLST_CD
  PRIMARY KEY
  (CHKLIST_CD_SID)
  RELY
  DISABLE NOVALIDATE)
/
