ALTER TABLE CSMRT_OWNER.PS_D_EXT_ORG
  DROP CONSTRAINT PK_PS_D_EXT_ORG
/

ALTER TABLE CSMRT_OWNER.PS_D_EXT_ORG ADD (
  CONSTRAINT PK_PS_D_EXT_ORG
  PRIMARY KEY
  (EXT_ORG_SID)
  RELY
  DISABLE NOVALIDATE)
/
