ALTER TABLE CSMRT_OWNER.UM_F_STDNT_TERM_STRUCT_ADVR_MV MODIFY 
  A_ADVISOR_ROLE_LD NULL
/

ALTER TABLE CSMRT_OWNER.UM_F_STDNT_TERM_STRUCT_ADVR_MV MODIFY 
  A_ADVISOR_ROLE_LD NOT NULL
  ENABLE VALIDATE
/
