ALTER TABLE CSMRT_OWNER.UM_F_ADM_APPL_PRSPCT_CPPS
  DROP CONSTRAINT PK_UM_F_ADM_APPL_PRSPCT_CPPS
/

ALTER TABLE CSMRT_OWNER.UM_F_ADM_APPL_PRSPCT_CPPS ADD (
  CONSTRAINT PK_UM_F_ADM_APPL_PRSPCT_CPPS
  PRIMARY KEY
  (ADM_APPL_SID, PRSPCT_CAR_SID, ACAD_PROG_SID, ACAD_PLAN_SID, ACAD_SPLAN_SID, SRC_SYS_ID)
  RELY
  ENABLE VALIDATE)
/
