ALTER TABLE CSMRT_OWNER.UM_F_ADM_APPL_ACAD_STRUCT
  DROP CONSTRAINT PK_UM_F_ADM_APPL_ACAD_STRUCT
/

ALTER TABLE CSMRT_OWNER.UM_F_ADM_APPL_ACAD_STRUCT ADD (
  CONSTRAINT PK_UM_F_ADM_APPL_ACAD_STRUCT
  PRIMARY KEY
  (ADM_APPL_SID, TERM_SID, PERSON_SID, STDNT_CAR_NUM, ACAD_PLAN_SID, ACAD_SPLAN_SID, SRC_SYS_ID)
  RELY
  ENABLE VALIDATE)
/
