ALTER TABLE CSMRT_OWNER.PS_D_RSDNCY
  DROP CONSTRAINT PK_PS_D_RSDNCY
/

ALTER TABLE CSMRT_OWNER.PS_D_RSDNCY ADD (
  CONSTRAINT PK_PS_D_RSDNCY
  PRIMARY KEY
  (RSDNCY_SID)
  RELY
  DISABLE NOVALIDATE)
/
