ALTER TABLE CSMRT_OWNER.UM_F_STDNT_TERM_STRUCT_ENRL_MV MODIFY 
  S_STACK_LAST_UPD_TERM_SID NULL
/

ALTER TABLE CSMRT_OWNER.UM_F_STDNT_TERM_STRUCT_ENRL_MV MODIFY 
  S_STACK_LAST_UPD_TERM_SID NOT NULL
  ENABLE VALIDATE
/
