ALTER TABLE CSMRT_OWNER.PS_D_LOCATION
  DROP CONSTRAINT PK_PS_D_LOCATION
/

ALTER TABLE CSMRT_OWNER.PS_D_LOCATION ADD (
  CONSTRAINT PK_PS_D_LOCATION
  PRIMARY KEY
  (LOC_SID)
  RELY
  DISABLE NOVALIDATE)
/
