ALTER TABLE CSMRT_OWNER.UM_D_EXT_CRSE
  DROP CONSTRAINT PK_UM_D_EXT_CRSE
/

ALTER TABLE CSMRT_OWNER.UM_D_EXT_CRSE ADD (
  CONSTRAINT PK_UM_D_EXT_CRSE
  PRIMARY KEY
  (EXT_CRSE_SID)
  RELY
  DISABLE NOVALIDATE)
/
