ALTER TABLE CSMRT_OWNER.UM_F_STDNT_TERM_STRUCT_MV MODIFY 
  S_CALC_TERM_LIMIT_SID NULL
/

ALTER TABLE CSMRT_OWNER.UM_F_STDNT_TERM_STRUCT_MV MODIFY 
  S_CALC_TERM_LIMIT_SID NOT NULL
  ENABLE VALIDATE
/
