ALTER TABLE CSMRT_OWNER.UM_S_AF_STDNT_ENRL_BDL
  DROP CONSTRAINT PK_UM_S_AF_STDNT_ENRL_BDL
/

ALTER TABLE CSMRT_OWNER.UM_S_AF_STDNT_ENRL_BDL ADD (
  CONSTRAINT PK_UM_S_AF_STDNT_ENRL_BDL
  PRIMARY KEY
  (INSTITUTION_CD, ACAD_CAR_CD, TERM_CD, PERSON_ID, SRC_SYS_ID, EFFDT_START)
  RELY
  ENABLE VALIDATE)
/
