ALTER TABLE CSMRT_OWNER.PS_F_ADM_APPL_STAT
  DROP CONSTRAINT PK_PS_F_ADM_APPL_STAT
/

ALTER TABLE CSMRT_OWNER.PS_F_ADM_APPL_STAT ADD (
  CONSTRAINT PK_PS_F_ADM_APPL_STAT
  PRIMARY KEY
  (ACAD_CAR_CD, STU_CAR_NBR, PERSON_ID, ADM_APPL_NBR, APPL_PROG_NBR, ACAD_PLAN_CD, ACAD_SPLAN_CD, EFFDT, EFFSEQ, SRC_SYS_ID)
  RELY
  ENABLE VALIDATE)
/
