ALTER TABLE CSMRT_OWNER.UM_D_PERSON_EMAIL
  DROP CONSTRAINT PK_UM_D_PERSON_EMAIL
/

ALTER TABLE CSMRT_OWNER.UM_D_PERSON_EMAIL ADD (
  CONSTRAINT PK_UM_D_PERSON_EMAIL
  PRIMARY KEY
  (INSTITUTION_CD, PERSON_ID, E_ADDR_TYPE, SRC_SYS_ID)
  RELY
  DISABLE NOVALIDATE)
/
