ALTER TABLE CSMRT_OWNER.UM_F_STDNT_GRAD_TRACK
  DROP CONSTRAINT PK_UM_F_STDNT_GRAD_TRACK
/

ALTER TABLE CSMRT_OWNER.UM_F_STDNT_GRAD_TRACK ADD (
  CONSTRAINT PK_UM_F_STDNT_GRAD_TRACK
  PRIMARY KEY
  (PERSON_ID, INSTITUTION_CD, ACAD_CAR_CD, STDNT_CAR_NUM, ACAD_PROG_CD, EXP_GRAD_TERM, DEG_CD, SSR_GRAD_REV_DTTM, SRC_SYS_ID)
  RELY
  ENABLE VALIDATE)
/
