ALTER TABLE CSMRT_OWNER.UM_F_FA_AWARD_DISB
  DROP CONSTRAINT PK_UM_F_FA_AWARD_DISB
/

ALTER TABLE CSMRT_OWNER.UM_F_FA_AWARD_DISB ADD (
  CONSTRAINT PK_UM_F_FA_AWARD_DISB
  PRIMARY KEY
  (INSTITUTION_CD, ACAD_CAR_CD, AID_YEAR, TERM_CD, PERSON_ID, ITEM_TYPE, SRC_SYS_ID)
  RELY
  ENABLE VALIDATE)
/
