ALTER TABLE CSMRT_OWNER.UM_F_STDNT_TERM_STRUCT_ADVR_MV MODIFY 
  A_ACAD_SPLAN_SID NULL
/

ALTER TABLE CSMRT_OWNER.UM_F_STDNT_TERM_STRUCT_ADVR_MV MODIFY 
  A_ACAD_SPLAN_SID NOT NULL
  ENABLE VALIDATE
/
