ALTER TABLE CSMRT_OWNER.PS_D_EXT_SUMM_TYP
  DROP CONSTRAINT PK_PS_D_EXT_SUMM_TYP
/

ALTER TABLE CSMRT_OWNER.PS_D_EXT_SUMM_TYP ADD (
  CONSTRAINT PK_PS_D_EXT_SUMM_TYP
  PRIMARY KEY
  (EXT_SUMM_TYPE_SID)
  RELY
  DISABLE NOVALIDATE)
/
