ALTER TABLE CSMRT_OWNER.PS_D_ACAD_UNIT_TYP
  DROP CONSTRAINT PK_PS_D_ACAD_UNIT_TYP
/

ALTER TABLE CSMRT_OWNER.PS_D_ACAD_UNIT_TYP ADD (
  CONSTRAINT PK_PS_D_ACAD_UNIT_TYP
  PRIMARY KEY
  (ACAD_UNIT_TYPE_SID)
  RELY
  DISABLE NOVALIDATE)
/
