ALTER TABLE CSMRT_OWNER.UM_D_PERSON_SRVC_IND
  DROP CONSTRAINT PK_UM_D_PERSON_SRVC_IND
/

ALTER TABLE CSMRT_OWNER.UM_D_PERSON_SRVC_IND ADD (
  CONSTRAINT PK_UM_D_PERSON_SRVC_IND
  PRIMARY KEY
  (INSTITUTION_CD, PERSON_ID, SRVC_IND_DTTM, SRC_SYS_ID, SERVICE_IMPACT)
  RELY
  ENABLE VALIDATE)
/
