ALTER TABLE CSMRT_OWNER.UM_F_FA_STDNT_LOAN_ORIG
  DROP CONSTRAINT PK_UM_F_FA_STDNT_LOAN_ORIG
/

ALTER TABLE CSMRT_OWNER.UM_F_FA_STDNT_LOAN_ORIG ADD (
  CONSTRAINT PK_UM_F_FA_STDNT_LOAN_ORIG
  PRIMARY KEY
  (INSTITUTION_CD, ACAD_CAR_CD, AID_YEAR, PERSON_ID, LOAN_TYPE, LN_APPL_SEQ, ITEM_TYPE, SRC_SYS_ID)
  RELY
  ENABLE VALIDATE)
/
