ALTER TABLE CSMRT_OWNER.PS_R_PERSON_RSDNCY
  DROP CONSTRAINT PK_PS_R_PERSON_RSDNCY
/

ALTER TABLE CSMRT_OWNER.PS_R_PERSON_RSDNCY ADD (
  CONSTRAINT PK_PS_R_PERSON_RSDNCY
  PRIMARY KEY
  (INSTITUTION_CD, ACAD_CAR_CD, EFF_TERM_CD, PERSON_ID, SRC_SYS_ID)
  RELY
  ENABLE VALIDATE)
/
