ALTER TABLE CSMRT_OWNER.UM_D_ACAD_PROG
  DROP CONSTRAINT PK_UM_D_ACAD_PROG
/

ALTER TABLE CSMRT_OWNER.UM_D_ACAD_PROG ADD (
  CONSTRAINT PK_UM_D_ACAD_PROG
  PRIMARY KEY
  (ACAD_PROG_SID)
  RELY
  DISABLE NOVALIDATE)
/
