ALTER TABLE CSMRT_OWNER.UM_D_ENRL_MSG
  DROP CONSTRAINT PK_UM_D_ENRL_MSG
/

ALTER TABLE CSMRT_OWNER.UM_D_ENRL_MSG ADD (
  CONSTRAINT PK_UM_D_ENRL_MSG
  PRIMARY KEY
  (MESSAGE_SET_NBR, MESSAGE_NBR, SRC_SYS_ID)
  RELY
  DISABLE NOVALIDATE)
/
