ALTER TABLE CSMRT_OWNER.UM_D_XLATITEM
  DROP CONSTRAINT PK_UM_D_XLATITEM
/

ALTER TABLE CSMRT_OWNER.UM_D_XLATITEM ADD (
  CONSTRAINT PK_UM_D_XLATITEM
  PRIMARY KEY
  (FIELDNAME, FIELDVALUE, SRC_SYS_ID)
  RELY
  DISABLE NOVALIDATE)
/
