ALTER TABLE CSMRT_OWNER.PS_D_APPL_MTHD
  DROP CONSTRAINT PK_PS_D_APPL_MTHD
/

ALTER TABLE CSMRT_OWNER.PS_D_APPL_MTHD ADD (
  CONSTRAINT PK_PS_D_APPL_MTHD
  PRIMARY KEY
  (APPL_MTHD_SID)
  RELY
  DISABLE NOVALIDATE)
/
