ALTER TABLE CSMRT_OWNER.UM_D_PRSPCT_CAR
  DROP CONSTRAINT PK_UM_D_PRSPCT_CAR
/

ALTER TABLE CSMRT_OWNER.UM_D_PRSPCT_CAR ADD (
  CONSTRAINT PK_UM_D_PRSPCT_CAR
  PRIMARY KEY
  (PRSPCT_CAR_SID)
  RELY
  DISABLE NOVALIDATE)
/
