ALTER TABLE CSMRT_OWNER.PS_D_APPL_CNTR
  DROP CONSTRAINT PK_PS_D_APPL_CNTR
/

ALTER TABLE CSMRT_OWNER.PS_D_APPL_CNTR ADD (
  CONSTRAINT PK_PS_D_APPL_CNTR
  PRIMARY KEY
  (APPL_CNTR_SID)
  RELY
  DISABLE NOVALIDATE)
/
