ALTER TABLE CSMRT_OWNER.UM_F_STDNT_TERM_STRUCT_ADVR_MV MODIFY 
  S_UNDUP_STDNT_CNT NULL
/

ALTER TABLE CSMRT_OWNER.UM_F_STDNT_TERM_STRUCT_ADVR_MV MODIFY 
  S_UNDUP_STDNT_CNT NOT NULL
  ENABLE VALIDATE
/
