ALTER TABLE CSMRT_OWNER.UM_D_EVENT_MTG
  DROP CONSTRAINT PK_UM_D_EVENT_MTG
/

ALTER TABLE CSMRT_OWNER.UM_D_EVENT_MTG ADD (
  CONSTRAINT PK_UM_D_EVENT_MTG
  PRIMARY KEY
  (EVENT_MTG_SID)
  RELY
  DISABLE NOVALIDATE)
/
