ALTER TABLE CSMRT_OWNER.UM_D_ITEM_LINE
  DROP CONSTRAINT PK_UM_D_ITEM_LINE
/

ALTER TABLE CSMRT_OWNER.UM_D_ITEM_LINE ADD (
  CONSTRAINT PK_UM_D_ITEM_LINE
  PRIMARY KEY
  (ITEM_LINE)
  RELY
  DISABLE NOVALIDATE)
/
