ALTER TABLE CSMRT_OWNER.UM_D_RQ_LINE
  DROP CONSTRAINT PK_UM_D_RQ_LINE
/

ALTER TABLE CSMRT_OWNER.UM_D_RQ_LINE ADD (
  CONSTRAINT PK_UM_D_RQ_LINE
  PRIMARY KEY
  (RQRMNT_LINE_SID)
  RELY
  DISABLE NOVALIDATE)
/
