ALTER TABLE CSMRT_OWNER.PS_D_DEG_HONORS
  DROP CONSTRAINT PK_PS_D_DEG_HONORS
/

ALTER TABLE CSMRT_OWNER.PS_D_DEG_HONORS ADD (
  CONSTRAINT PK_PS_D_DEG_HONORS
  PRIMARY KEY
  (DEG_HONORS_SID)
  RELY
  DISABLE NOVALIDATE)
/
