ALTER TABLE CSMRT_OWNER.UM_F_STDNT_TERM_STRUCT_ENRL_MV MODIFY 
  T_INSTITUTION_SID NULL
/

ALTER TABLE CSMRT_OWNER.UM_F_STDNT_TERM_STRUCT_ENRL_MV MODIFY 
  T_INSTITUTION_SID NOT NULL
  ENABLE VALIDATE
/
