ALTER TABLE CSMRT_OWNER.PS_R_ADM_RECRTR
  DROP CONSTRAINT PK_PS_R_ADM_RECRTR
/

ALTER TABLE CSMRT_OWNER.PS_R_ADM_RECRTR ADD (
  CONSTRAINT PK_PS_R_ADM_RECRTR
  PRIMARY KEY
  (INSTITUTION_CD, ACAD_CAR_CD, PERSON_ID, STDNT_CAR_NUM, ADM_APPL_NBR, RECRT_CTGRY_ID, RECRTR_ID, SRC_SYS_ID)
  RELY
  ENABLE VALIDATE)
/
