ALTER TABLE CSMRT_OWNER.UM_F_STDNT_TERM_TRANSFER_MV MODIFY 
  TRF_INSTITUTION_SID NULL
/

ALTER TABLE CSMRT_OWNER.UM_F_STDNT_TERM_TRANSFER_MV MODIFY 
  TRF_INSTITUTION_SID NOT NULL
  ENABLE VALIDATE
/
