ALTER TABLE CSMRT_OWNER.UM_F_FA_STDNT_BDGT_ITEM
  DROP CONSTRAINT PK_UM_F_FA_STDNT_BDGT_ITEM
/

ALTER TABLE CSMRT_OWNER.UM_F_FA_STDNT_BDGT_ITEM ADD (
  CONSTRAINT PK_UM_F_FA_STDNT_BDGT_ITEM
  PRIMARY KEY
  (INSTITUTION_CD, ACAD_CAR_CD, AID_YEAR, TERM_CD, PERSON_ID, BGT_ITEM_CATEGORY, SRC_SYS_ID)
  RELY
  ENABLE VALIDATE)
/
