ALTER TABLE CSMRT_OWNER.PS_D_RSDNCY_EXCPT
  DROP CONSTRAINT PK_PS_D_RSDNCY_EXCPT
/

ALTER TABLE CSMRT_OWNER.PS_D_RSDNCY_EXCPT ADD (
  CONSTRAINT PK_PS_D_RSDNCY_EXCPT
  PRIMARY KEY
  (RSDNCY_EXCPT_SID)
  RELY
  DISABLE NOVALIDATE)
/
