ALTER TABLE CSMRT_OWNER.PS_D_INSTRCTR_LOAD
  DROP CONSTRAINT PK_PS_D_INSTRCTR_LOAD
/

ALTER TABLE CSMRT_OWNER.PS_D_INSTRCTR_LOAD ADD (
  CONSTRAINT PK_PS_D_INSTRCTR_LOAD
  PRIMARY KEY
  (INSTRCTR_LOAD_SID)
  RELY
  DISABLE NOVALIDATE)
/
