ALTER TABLE CSMRT_OWNER.PS_D_ITEM_TYPE
  DROP CONSTRAINT PK_PS_D_ITEM_TYPE
/

ALTER TABLE CSMRT_OWNER.PS_D_ITEM_TYPE ADD (
  CONSTRAINT PK_PS_D_ITEM_TYPE
  PRIMARY KEY
  (ITEM_TYPE_SID)
  RELY
  DISABLE NOVALIDATE)
/
