ALTER TABLE CSMRT_OWNER.PS_D_INSTITUTION
  DROP CONSTRAINT PK_PS_D_INSTITUTION
/

ALTER TABLE CSMRT_OWNER.PS_D_INSTITUTION ADD (
  CONSTRAINT PK_PS_D_INSTITUTION
  PRIMARY KEY
  (INSTITUTION_SID)
  RELY
  DISABLE NOVALIDATE)
/
