ALTER TABLE CSMRT_OWNER.UM_F_EXT_DEG
  DROP CONSTRAINT PK_UM_F_EXT_DEG
/

ALTER TABLE CSMRT_OWNER.UM_F_EXT_DEG ADD (
  CONSTRAINT PK_UM_F_EXT_DEG
  PRIMARY KEY
  (PERSON_ID, EXT_ORG_ID, EXT_DEG_NBR, SRC_SYS_ID)
  RELY
  ENABLE VALIDATE)
/
