ALTER TABLE CSMRT_OWNER.UM_F_STDNT_ENRL_REQ
  DROP CONSTRAINT PK_UM_F_STDNT_ENRL_REQ
/

ALTER TABLE CSMRT_OWNER.UM_F_STDNT_ENRL_REQ ADD (
  CONSTRAINT PK_UM_F_STDNT_ENRL_REQ
  PRIMARY KEY
  (ENRL_REQUEST_ID, ENRL_REQ_DETL_SEQ, SRC_SYS_ID)
  RELY
  ENABLE VALIDATE)
/
