ALTER TABLE CSMRT_OWNER.PS_D_REPEAT
  DROP CONSTRAINT PK_PS_D_REPEAT
/

ALTER TABLE CSMRT_OWNER.PS_D_REPEAT ADD (
  CONSTRAINT PK_PS_D_REPEAT
  PRIMARY KEY
  (REPEAT_SID)
  RELY
  DISABLE NOVALIDATE)
/
