ALTER TABLE CSMRT_OWNER.UM_F_STDNT_TERM_STRUCT_MV MODIFY 
  S_PRIM_PROG_MAJOR1_ORDER NULL
/

ALTER TABLE CSMRT_OWNER.UM_F_STDNT_TERM_STRUCT_MV MODIFY 
  S_PRIM_PROG_MAJOR1_ORDER NOT NULL
  ENABLE VALIDATE
/
