ALTER TABLE CSMRT_OWNER.UM_F_STDNT_TERM_STRUCT_ENRL_MV MODIFY 
  E_INSTITUTION_CD NULL
/

ALTER TABLE CSMRT_OWNER.UM_F_STDNT_TERM_STRUCT_ENRL_MV MODIFY 
  E_INSTITUTION_CD NOT NULL
  ENABLE VALIDATE
/
