ALTER TABLE CSMRT_OWNER.PS_D_ENRL_ACTION
  DROP CONSTRAINT PK_PS_D_ENRL_ACTION
/

ALTER TABLE CSMRT_OWNER.PS_D_ENRL_ACTION ADD (
  CONSTRAINT PK_PS_D_ENRL_ACTION
  PRIMARY KEY
  (ENRL_REQ_ACTN_SID)
  RELY
  DISABLE NOVALIDATE)
/
