ALTER TABLE CSMRT_OWNER.UM_D_VISA_PERMIT
  DROP CONSTRAINT PK_UM_D_VISA_PERMIT
/

ALTER TABLE CSMRT_OWNER.UM_D_VISA_PERMIT ADD (
  CONSTRAINT PK_UM_D_VISA_PERMIT
  PRIMARY KEY
  (VISA_PERMIT_SID)
  RELY
  DISABLE NOVALIDATE)
/
