ALTER TABLE CSMRT_OWNER.UM_D_PRSPCT_PLAN
  DROP CONSTRAINT PK_UM_D_PRSPCT_PLAN
/

ALTER TABLE CSMRT_OWNER.UM_D_PRSPCT_PLAN ADD (
  CONSTRAINT PK_UM_D_PRSPCT_PLAN
  PRIMARY KEY
  (PRSPCT_PLAN_SID)
  RELY
  DISABLE NOVALIDATE)
/
