ALTER TABLE CSMRT_OWNER.UM_R_ENRL_MSG_LOG
  DROP CONSTRAINT PK_PK_UM_R_ENRL_MSG_LOG
/

ALTER TABLE CSMRT_OWNER.UM_R_ENRL_MSG_LOG ADD (
  CONSTRAINT PK_PK_UM_R_ENRL_MSG_LOG
  PRIMARY KEY
  (ENRL_REQUEST_ID, ENRL_REQ_DETL_SEQ, MESSAGE_SEQ, SRC_SYS_ID)
  RELY
  ENABLE VALIDATE)
/
