ALTER TABLE CSMRT_OWNER.UM_F_STDNT_TERM
  DROP CONSTRAINT PK_UM_F_STDNT_TERM
/

ALTER TABLE CSMRT_OWNER.UM_F_STDNT_TERM ADD (
  CONSTRAINT PK_UM_F_STDNT_TERM
  PRIMARY KEY
  (TERM_SID, PERSON_SID, SRC_SYS_ID)
  RELY
  ENABLE VALIDATE)
/
