ALTER TABLE CSMRT_OWNER.UM_D_CLASS_EXAM
  DROP CONSTRAINT PK_UM_D_CLASS_EXAM
/

ALTER TABLE CSMRT_OWNER.UM_D_CLASS_EXAM ADD (
  CONSTRAINT PK_UM_D_CLASS_EXAM
  PRIMARY KEY
  (CRSE_CD, CRSE_OFFER_NUM, TERM_CD, SESSION_CD, CLASS_SECTION_CD, CLASS_EXAM_SEQ, SRC_SYS_ID)
  RELY
  DISABLE NOVALIDATE)
/
