ALTER TABLE CSMRT_OWNER.UM_F_STDNT_TERM_STRUCT_ENRL_MV MODIFY 
  S_NEW_TERM_LIMIT_SID NULL
/

ALTER TABLE CSMRT_OWNER.UM_F_STDNT_TERM_STRUCT_ENRL_MV MODIFY 
  S_NEW_TERM_LIMIT_SID NOT NULL
  ENABLE VALIDATE
/
