ALTER TABLE CSMRT_OWNER.UM_F_ADM_APPL_TERM
  DROP CONSTRAINT PK_UM_F_ADM_APPL_TERM
/

ALTER TABLE CSMRT_OWNER.UM_F_ADM_APPL_TERM ADD (
  CONSTRAINT PK_UM_F_ADM_APPL_TERM
  PRIMARY KEY
  (ADM_APPL_SID, TERM_SID, PERSON_SID, SRC_SYS_ID)
  ENABLE VALIDATE)
/
