ALTER TABLE CSMRT_OWNER.UM_D_PERSON_NAME
  DROP CONSTRAINT PK_UM_D_PERSON_NAME
/

ALTER TABLE CSMRT_OWNER.UM_D_PERSON_NAME ADD (
  CONSTRAINT PK_UM_D_PERSON_NAME
  PRIMARY KEY
  (PERSON_ID, NAME_TYPE, SRC_SYS_ID)
  RELY
  ENABLE VALIDATE)
/
