ALTER TABLE CSMRT_OWNER.PS_D_INSTRCTR_ROLE
  DROP CONSTRAINT PK_PS_D_INSTRCTR_ROLE
/

ALTER TABLE CSMRT_OWNER.PS_D_INSTRCTR_ROLE ADD (
  CONSTRAINT PK_PS_D_INSTRCTR_ROLE
  PRIMARY KEY
  (INSTRCTR_ROLE_SID)
  RELY
  DISABLE NOVALIDATE)
/
