ALTER TABLE CSMRT_OWNER.PS_D_ENRLMT_REAS
  DROP CONSTRAINT PK_PS_D_ENRLMT_REAS
/

ALTER TABLE CSMRT_OWNER.PS_D_ENRLMT_REAS ADD (
  CONSTRAINT PK_PS_D_ENRLMT_REAS
  PRIMARY KEY
  (ENRLMT_REAS_SID)
  RELY
  DISABLE NOVALIDATE)
/
