ALTER TABLE CSMRT_OWNER.PS_D_PROG_ACN_RSN
  DROP CONSTRAINT PK_PS_D_PROG_ACN_RSN
/

ALTER TABLE CSMRT_OWNER.PS_D_PROG_ACN_RSN ADD (
  CONSTRAINT PK_PS_D_PROG_ACN_RSN
  PRIMARY KEY
  (PROG_ACN_RSN_SID)
  RELY
  DISABLE NOVALIDATE)
/
