ALTER TABLE CSMRT_OWNER.UM_D_PERSON_VISA
  DROP CONSTRAINT PK_UM_D_PERSON_VISA
/

ALTER TABLE CSMRT_OWNER.UM_D_PERSON_VISA ADD (
  CONSTRAINT PK_UM_D_PERSON_VISA
  PRIMARY KEY
  (PERSON_ID, DEPENDENT_ID, COUNTRY, VISA_PERMIT_TYPE, SRC_SYS_ID)
  RELY
  ENABLE VALIDATE)
/
