ALTER TABLE CSMRT_OWNER.UM_F_FA_STDNT_PELL_ACTN
  DROP CONSTRAINT PK_UM_F_FA_STDNT_PELL_ACTN
/

ALTER TABLE CSMRT_OWNER.UM_F_FA_STDNT_PELL_ACTN ADD (
  CONSTRAINT PK_UM_F_FA_STDNT_PELL_ACTN
  PRIMARY KEY
  (INSTITUTION_CD, AID_YEAR, PERSON_ID, PELL_ORIG_ID, PELL_ORIG_ACTN_SEQ, PELL_ORIG_MSG_SEQ, SRC_SYS_ID)
  RELY
  ENABLE VALIDATE)
/
