ALTER TABLE CSMRT_OWNER.UM_F_STDNT_DEGREE
  DROP CONSTRAINT PK_UM_F_STDNT_DEGREE
/

ALTER TABLE CSMRT_OWNER.UM_F_STDNT_DEGREE ADD (
  CONSTRAINT PK_UM_F_STDNT_DEGREE
  PRIMARY KEY
  (PERSON_SID, STDNT_CAR_NUM, DEGREE_NBR, HONORS_NBR, TERM_SID, COMPL_TERM_SID, ACAD_PROG_SID, ACAD_PLAN_SID, ACAD_SPLAN_SID, SRC_SYS_ID, PRIM_PROG_MAJOR1_ORDER)
  RELY
  ENABLE VALIDATE)
/
