ALTER TABLE CSMRT_OWNER.PS_R_DEG_HONORS
  DROP CONSTRAINT PK_PS_R_DEG_HONORS
/

ALTER TABLE CSMRT_OWNER.PS_R_DEG_HONORS ADD (
  CONSTRAINT PK_PS_R_DEG_HONORS
  PRIMARY KEY
  (PERSON_SID, STDNT_DEGR_CD, HONORS_NUM, SRC_SYS_ID)
  RELY
  ENABLE VALIDATE)
/
