ALTER TABLE CSMRT_OWNER.UM_F_FA_STDNT_AWRD_PERIOD
  DROP CONSTRAINT PK_UM_F_FA_STDNT_AWRD_PERIOD
/

ALTER TABLE CSMRT_OWNER.UM_F_FA_STDNT_AWRD_PERIOD ADD (
  CONSTRAINT PK_UM_F_FA_STDNT_AWRD_PERIOD
  PRIMARY KEY
  (INSTITUTION_CD, AID_YEAR, PERSON_ID, AWARD_PERIOD, SRC_SYS_ID)
  RELY
  ENABLE VALIDATE)
/
