ALTER TABLE CSMRT_OWNER.UM_F_STDNT_TERM_STRUCT_MV MODIFY 
  S_PLAN_COMPL_TERM_SID NULL
/

ALTER TABLE CSMRT_OWNER.UM_F_STDNT_TERM_STRUCT_MV MODIFY 
  S_PLAN_COMPL_TERM_SID NOT NULL
  ENABLE VALIDATE
/
