ALTER TABLE CSMRT_OWNER.UM_F_FA_STDNT_ANTICIP_AID
  DROP CONSTRAINT PK_UM_F_FA_STDNT_ANT_AID
/

ALTER TABLE CSMRT_OWNER.UM_F_FA_STDNT_ANTICIP_AID ADD (
  CONSTRAINT PK_UM_F_FA_STDNT_ANT_AID
  PRIMARY KEY
  (INSTITUTION_CD, ACAD_CAR_CD, AID_YEAR, PERSON_ID, ITEM_TYPE, DISBURSEMENT_PLAN, DISBURSEMENT_ID, AS_OF_DTTM, SRC_SYS_ID)
  RELY
  ENABLE VALIDATE)
/
