ALTER TABLE CSMRT_OWNER.UM_F_FA_TERM
  DROP CONSTRAINT PK_UM_F_FA_TERM
/

ALTER TABLE CSMRT_OWNER.UM_F_FA_TERM ADD (
  CONSTRAINT PK_UM_F_FA_TERM
  PRIMARY KEY
  (INSTITUTION_CD, ACAD_CAR_CD, AID_YEAR, TERM_CD, PERSON_ID, SRC_SYS_ID)
  RELY
  ENABLE VALIDATE)
/
