ALTER TABLE CSMRT_OWNER.UM_F_SAA_ADB_COND
  DROP CONSTRAINT PK_UM_F_SAA_ADB_COND
/

ALTER TABLE CSMRT_OWNER.UM_F_SAA_ADB_COND ADD (
  CONSTRAINT PK_UM_F_SAA_ADB_COND
  PRIMARY KEY
  (EMPLID, ANALYSIS_DB_SEQ, SAA_CAREER_RPT, COND_CODE, COND_DATA, SRC_SYS_ID)
  RELY
  ENABLE VALIDATE)
/
