ALTER TABLE CSMRT_OWNER.PS_D_ACAD_CAR
  DROP CONSTRAINT PK_PS_D_ACAD_CAR
/

ALTER TABLE CSMRT_OWNER.PS_D_ACAD_CAR ADD (
  CONSTRAINT PK_PS_D_ACAD_CAR
  PRIMARY KEY
  (ACAD_CAR_SID)
  RELY
  DISABLE NOVALIDATE)
/
