ALTER TABLE CSMRT_OWNER.UM_F_ADM_APPL_CLASS_ENRLMT MODIFY 
  PRI_CLASS_INSTRCTR_SID NULL
/

ALTER TABLE CSMRT_OWNER.UM_F_ADM_APPL_CLASS_ENRLMT MODIFY 
  PRI_CLASS_INSTRCTR_SID NOT NULL
  ENABLE VALIDATE
/
