DROP TABLE CSMRT_OWNER.UM_D_TRANSFER_DICT CASCADE CONSTRAINTS
/

--
-- UM_D_TRANSFER_DICT  (Table) 
--
CREATE TABLE CSMRT_OWNER.UM_D_TRANSFER_DICT
(
  TRNSFR_DICT_SID           INTEGER             NOT NULL,
  INSTITUTION_CD            VARCHAR2(5 BYTE)    NOT NULL,
  TRNSFR_SRC_ID             VARCHAR2(11 BYTE)   NOT NULL,
  COMP_SUBJECT_AREA         VARCHAR2(16 BYTE)   NOT NULL,
  TRNSFR_EQVLNCY_CMP        VARCHAR2(4 BYTE)    NOT NULL,
  TRNSFR_CMP_SEQ            INTEGER             NOT NULL,
  CRSE_ID                   VARCHAR2(6 BYTE)    NOT NULL,
  SRC_SYS_ID                VARCHAR2(5 BYTE)    NOT NULL,
  EFFDT                     DATE,
  EFF_STATUS                VARCHAR2(1 BYTE)    NOT NULL,
  TRNSFR_SUBJ_DESCR         VARCHAR2(30 BYTE)   NOT NULL,
  TRNSFR_COMP_DESCR         VARCHAR2(30 BYTE)   NOT NULL,
  CRSE_SID                  INTEGER             NOT NULL,
  EXT_CRSE_SID              INTEGER             NOT NULL,
  EXT_ORG_SID               INTEGER             NOT NULL,
  EXT_CRSE_OFFER_NBR        INTEGER             NOT NULL,
  EXT_TERM_TYPE             VARCHAR2(4 BYTE)    NOT NULL,
  EXT_TERM_TYPE_SD          VARCHAR2(10 BYTE)   NOT NULL,
  EXT_TERM_TYPE_LD          VARCHAR2(30 BYTE)   NOT NULL,
  GRADE_PTS_MIN             NUMBER(9,3)         NOT NULL,
  GRADE_PTS_MAX             NUMBER(9,3)         NOT NULL,
  INP_CRSE_CNT              INTEGER             NOT NULL,
  INT_TRANSFER_FLG          VARCHAR2(1 BYTE)    NOT NULL,
  SCHOOL_SUBJECT            VARCHAR2(8 BYTE)    NOT NULL,
  SCHOOL_CRSE_NBR           VARCHAR2(10 BYTE)   NOT NULL,
  SSR_MAX_AGE               INTEGER             NOT NULL,
  TRNSFR_CRSE_FLG           VARCHAR2(1 BYTE)    NOT NULL,
  TRNSFR_CRSE_STATUS        VARCHAR2(10 BYTE)   NOT NULL,
  TRNSFR_GRADE_FLG          VARCHAR2(1 BYTE)    NOT NULL,
  UM_CRSE_ID                VARCHAR2(6 BYTE)    NOT NULL,
  UM_CRSE_OFFER_NBR         INTEGER             NOT NULL,
  UM_SSR_TR_DEF_GRD_TYP     VARCHAR2(1 BYTE)    NOT NULL,
  UM_SSR_TR_DEF_GRD_TYP_SD  VARCHAR2(10 BYTE)   NOT NULL,
  UM_SSR_TR_DEF_GRD_TYP_LD  VARCHAR2(30 BYTE)   NOT NULL,
  UM_SSR_TR_DEF_GRD_SEQ     VARCHAR2(4 BYTE)    NOT NULL,
  UM_UNIT_TAKEN             NUMBER(5,2)         NOT NULL,
  UNITS_MINIMUM             NUMBER(5,2)         NOT NULL,
  UNITS_MAXIMUM             NUMBER(5,2)         NOT NULL,
  UNT_TRNSFR_SRC            VARCHAR2(1 BYTE)    NOT NULL,
  UNT_TRNSFR_SRC_SD         VARCHAR2(10 BYTE)   NOT NULL,
  UNT_TRNSFR_SRC_LD         VARCHAR2(30 BYTE)   NOT NULL,
  XS_CRSE_FLG               VARCHAR2(1 BYTE)    NOT NULL,
  DATA_ORIGIN               VARCHAR2(1 BYTE)    NOT NULL,
  CREATED_EW_DTTM           DATE,
  LASTUPD_EW_DTTM           DATE
)
COMPRESS BASIC
/


ALTER TABLE CSMRT_OWNER.UM_D_TRANSFER_DICT ADD (
  CONSTRAINT PK_UM_D_TRANSFER_DICT
  PRIMARY KEY
  (TRNSFR_DICT_SID)
  RELY
  ENABLE VALIDATE)
/
