CREATE TABLE UM_D_RQ_GRP
(
  RQRMNT_GROUP_SID  INTEGER,
  RQRMNT_GROUP      VARCHAR2(6 BYTE),
  SRC_SYS_ID        VARCHAR2(5 BYTE),
  EFFDT             DATE,
  EFF_STATUS        VARCHAR2(1 BYTE),
  DESCR             VARCHAR2(30 BYTE),
  DESCRSHORT        VARCHAR2(10 BYTE),
  INSTITUTION_CD    VARCHAR2(5 BYTE),
  ACAD_CAR_CD       VARCHAR2(4 BYTE),
  ACAD_PROG_CD      VARCHAR2(5 BYTE),
  ACAD_PLAN_CD      VARCHAR2(10 BYTE),
  ACAD_SPLAN_CD     VARCHAR2(10 BYTE),
  SUBJECT           VARCHAR2(8 BYTE),
  CATALOG_NBR       VARCHAR2(10 BYTE),
  GRADE_POINTS_MIN  NUMBER(9,2),
  GPA_REQUIRED      NUMBER(6,3),
  MIN_UNITS_REQD    NUMBER(6,2),
  MIN_CRSES_REQD    NUMBER(5,2),
  RQRMNT_USEAGE     VARCHAR2(4 BYTE),
  RQRMNT_USEAGE_SD  VARCHAR2(10 BYTE),
  RQRMNT_USEAGE_LD  VARCHAR2(30 BYTE),
  RQRMNT_LIST_SEQ   INTEGER,
  RQ_CONNECT_TYPE   VARCHAR2(3 BYTE),
  SAA_DESCR80       VARCHAR2(80 BYTE),
  DESCR254          VARCHAR2(254 BYTE),
  DESCRLONG         VARCHAR2(4000 BYTE),
  DATA_ORIGIN       VARCHAR2(1 BYTE),
  CREATED_EW_DTTM   DATE,
  LASTUPD_EW_DTTM   DATE,
  SQL_STR_PRE       CLOB,
  SQL_STR_CO        CLOB
)
NOLOGGING 
COMPRESS BASIC
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
