CREATE TABLE UM_A_SRVC_IND
(
  AUDIT_OPRID         VARCHAR2(30 BYTE),
  AUDIT_STAMP         TIMESTAMP(6),
  AUDIT_ACTN          VARCHAR2(1 BYTE),
  PERSON_ID           VARCHAR2(11 BYTE),
  SRVC_IND_DTTM       TIMESTAMP(6),
  SRC_SYS_ID          VARCHAR2(5 BYTE),
  INSTITUTION_CD      VARCHAR2(5 BYTE),
  INSTITUTION_SID     INTEGER,
  PERSON_SID          INTEGER,
  AMOUNT              NUMBER(26,3),
  AUDIT_ACTN_SD       VARCHAR2(10 BYTE),
  AUDIT_ACTN_LD       VARCHAR2(30 BYTE),
  CONTACT             VARCHAR2(30 BYTE),
  CONTACT_ID          VARCHAR2(15 BYTE),
  DEPTID              VARCHAR2(10 BYTE),
  OPRID               VARCHAR2(30 BYTE),
  PLACED_METHOD       VARCHAR2(30 BYTE),
  PLACED_PERSON       VARCHAR2(30 BYTE),
  PLACED_PERSON_ID    VARCHAR2(11 BYTE),
  PLACED_PROCESS      VARCHAR2(8 BYTE),
  POS_SRVC_INDICATOR  VARCHAR2(9 BYTE),
  PROCESS_INSTANCE    NUMBER(10),
  RELEASE_PROCESS     VARCHAR2(8 BYTE),
  SCC_SI_END_TERM     VARCHAR2(4 BYTE),
  SCC_SI_END_DT       DATE,
  SRVC_IND_ACT_TERM   VARCHAR2(4 BYTE),
  SRVC_IND_ACTIVE_DT  DATE,
  SRVC_IND_REFRNCE    VARCHAR2(30 BYTE),
  SRVC_IND_CD         VARCHAR2(3 BYTE),
  SRVC_IND_SD         VARCHAR2(10 BYTE),
  SRVC_IND_LD         VARCHAR2(30 BYTE),
  SRVC_IND_REASON     VARCHAR2(5 BYTE),
  SRVC_IND_REASON_SD  VARCHAR2(10 BYTE),
  SRVC_IND_REASON_LD  VARCHAR2(30 BYTE),
  COMM_COMMENTS       VARCHAR2(4000 BYTE),
  DATA_ORIGIN         VARCHAR2(1 BYTE),
  CREATED_EW_DTTM     DATE,
  LASTUPD_EW_DTTM     DATE
)
NOLOGGING 
COMPRESS BASIC
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
