DROP TABLE CSMRT_OWNER.UM_D_PERSON_VISA CASCADE CONSTRAINTS
/

--
-- UM_D_PERSON_VISA  (Table) 
--
CREATE TABLE CSMRT_OWNER.UM_D_PERSON_VISA
(
  PERSON_ID              VARCHAR2(11 BYTE)      NOT NULL,
  DEPENDENT_ID           VARCHAR2(2 BYTE)       NOT NULL,
  COUNTRY                VARCHAR2(3 BYTE)       NOT NULL,
  VISA_PERMIT_TYPE       VARCHAR2(3 BYTE)       NOT NULL,
  SRC_SYS_ID             VARCHAR2(5 BYTE)       NOT NULL,
  EFFDT                  DATE,
  PERSON_SID             INTEGER                NOT NULL,
  VISA_PERMIT_SID        INTEGER                NOT NULL,
  DURATION_TIME          NUMBER(5,1)            NOT NULL,
  DURATION_TYPE          VARCHAR2(1 BYTE)       NOT NULL,
  DURATION_TYPE_SD       VARCHAR2(10 BYTE)      NOT NULL,
  DURATION_TYPE_LD       VARCHAR2(30 BYTE)      NOT NULL,
  ENTRY_DT               DATE,
  EXPIRATN_DT            DATE,
  DT_ISSUED              DATE,
  PLACE_ISSUED           VARCHAR2(30 BYTE)      NOT NULL,
  ISSUING_AUTHORITY      VARCHAR2(50 BYTE)      NOT NULL,
  VISA_PERMIT_TYPE_LD    VARCHAR2(30 BYTE)      NOT NULL,
  VISA_WRKPMT_NBR        VARCHAR2(15 BYTE)      NOT NULL,
  VISA_WRKPMT_STATUS     VARCHAR2(1 BYTE)       NOT NULL,
  VISA_WRKPMT_STATUS_SD  VARCHAR2(10 BYTE)      NOT NULL,
  VISA_WRKPMT_STATUS_LD  VARCHAR2(30 BYTE)      NOT NULL,
  STATUS_DT              DATE,
  VISA_ORDER             INTEGER                NOT NULL,
  DATA_ORIGIN            VARCHAR2(1 BYTE)       NOT NULL,
  CREATED_EW_DTTM        DATE,
  LASTUPD_EW_DTTM        DATE
)
COMPRESS BASIC
/


ALTER TABLE CSMRT_OWNER.UM_D_PERSON_VISA ADD (
  CONSTRAINT PK_UM_D_PERSON_VISA
  PRIMARY KEY
  (PERSON_ID, DEPENDENT_ID, COUNTRY, VISA_PERMIT_TYPE, SRC_SYS_ID)
  RELY
  ENABLE VALIDATE)
/
