CREATE TABLE UM_D_EVENT_MTG
(
  EVENT_MTG_SID       INTEGER,
  CAMPUS_EVENT_NBR    VARCHAR2(9 BYTE),
  EVENT_MTG_NBR       INTEGER,
  SRC_SYS_ID          VARCHAR2(5 BYTE),
  INSTITUTION_CD      VARCHAR2(5 BYTE),
  DESCRSHORT          VARCHAR2(10 BYTE),
  DESCR               VARCHAR2(30 BYTE),
  CAMPUS_EVENT_SID    INTEGER,
  MEETING_DT          DATE,
  MEETING_TIME_START  DATE,
  MEETING_TIME_END    DATE,
  DAY_OF_WK           VARCHAR2(2 BYTE),
  CAMPUS_MTG_LOC      VARCHAR2(1 BYTE),
  CAMPUS_MTG_TYPE     VARCHAR2(4 BYTE),
  CONTACT_MINUTES     INTEGER,
  MAX_ATTENDEE        INTEGER,
  PROJECTED_ATTEND    INTEGER,
  COMMENTS            VARCHAR2(4000 BYTE),
  DATA_ORIGIN         VARCHAR2(1 BYTE),
  CREATED_EW_DTTM     DATE,
  LASTUPD_EW_DTTM     DATE
)
NOLOGGING 
COMPRESS BASIC
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
