DROP TABLE CSMRT_OWNER.UM_F_ADM_APPL_TESTSCORE_AGG CASCADE CONSTRAINTS
/

--
-- UM_F_ADM_APPL_TESTSCORE_AGG  (Table) 
--
CREATE TABLE CSMRT_OWNER.UM_F_ADM_APPL_TESTSCORE_AGG
(
  PERSON_ID                  VARCHAR2(11 BYTE)  NOT NULL,
  ACAD_CAR_CD                VARCHAR2(4 BYTE)   NOT NULL,
  STU_CAR_NBR                INTEGER            NOT NULL,
  ADM_APPL_NBR               VARCHAR2(8 BYTE)   NOT NULL,
  SRC_SYS_ID                 VARCHAR2(5 BYTE)   NOT NULL,
  INSTITUTION_CD             VARCHAR2(5 BYTE)   NOT NULL,
  INSTITUTION_SID            INTEGER            NOT NULL,
  ACAD_CAR_SID               INTEGER            NOT NULL,
  APPLCNT_SID                INTEGER            NOT NULL,
  UM_CA_TESTING_PLAN         VARCHAR2(200 BYTE),
  ACT_COMP_SCORE             NUMBER,
  ACT_MATH_SCORE             NUMBER,
  ACT_VERB_SCORE             NUMBER,
  ACT_WR_SCORE               NUMBER,
  ACT_CONV_SCORE             NUMBER,
  GMAT_ANLY_SCORE            NUMBER,
  GMAT_QUAN_SCORE            NUMBER,
  GMAT_VERB_SCORE            NUMBER,
  GMAT_IR_SCORE              NUMBER,
  GMAT_TOTAL_SCORE           NUMBER,
  GRE_COMB_DECILE            NUMBER,
  GRE_ANLY_SCORE             NUMBER,
  GRE_QUAN_SCORE             NUMBER,
  GRE_VERB_SCORE             NUMBER,
  IELTS_BAND_SCORE           NUMBER,
  LSAT_COMP_SCORE            NUMBER,
  SAT_AHSSC_SCORE            NUMBER,
  SAT_ASC_SCORE              NUMBER,
  SAT_CE_SCORE               NUMBER,
  SAT_COMB_DECILE            NUMBER,
  SAT_CONV_SCORE             NUMBER,
  SAT_CONV_2016_SCORE        NUMBER,
  SAT_EI_SCORE               NUMBER,
  SAT_ERWS_SCORE             NUMBER,
  SAT_ERWS_CONV_SCORE        NUMBER,
  SAT_ESA_SCORE              NUMBER,
  SAT_ESR_SCORE              NUMBER,
  SAT_ESW_SCORE              NUMBER,
  SAT_HA_SCORE               NUMBER,
  SAT_MATH_SCORE             NUMBER,
  SAT_MSS_SCORE              NUMBER,
  SAT_MSS_CONV_SCORE         NUMBER,
  SAT_MT_SCORE               NUMBER,
  SAT_MT_CONV_SCORE          NUMBER,
  SAT_PAM_SCORE              NUMBER,
  SAT_PSDA_SCORE             NUMBER,
  SAT_RT_SCORE               NUMBER,
  SAT_RT_CONV_SCORE          NUMBER,
  SAT_RWC_SCORE              NUMBER,
  SAT_SEC_SCORE              NUMBER,
  SAT_TOTAL_SCORE            NUMBER,
  SAT_TOTAL_1600_CONV_SCORE  NUMBER,
  SAT_TOTAL_2400_CONV_SCORE  NUMBER,
  SAT_TOTAL_UM_SCORE         NUMBER,
  SAT_VERB_SCORE             NUMBER,
  SAT_WLT_SCORE              NUMBER,
  SAT_WLT_CONV_SCORE         NUMBER,
  SAT_WR_SCORE               NUMBER,
  TOEFL_COMPP_SCORE          NUMBER,
  TOEFL_IBTT_SCORE           NUMBER,
  UMDAR_INDEX_SCORE          NUMBER,
  UMLOW_INDEX_SCORE          NUMBER,
  UMBOS_BEST_HS_GPA          NUMBER(6,3),
  UMDAR_BEST_HS_GPA          NUMBER(6,3),
  UMLOW_BEST_HS_GPA          NUMBER(6,3)
)
COMPRESS BASIC
/


ALTER TABLE CSMRT_OWNER.UM_F_ADM_APPL_TESTSCORE_AGG ADD (
  CONSTRAINT PK_UM_F_ADM_APPL_TESTSCORE_AGG
  PRIMARY KEY
  (PERSON_ID, ACAD_CAR_CD, STU_CAR_NBR, ADM_APPL_NBR, SRC_SYS_ID)
  RELY
  ENABLE VALIDATE)
/
