CREATE TABLE UM_D_PERSON_TENURE
(
  PERSON_SID            INTEGER,
  EMPLID                VARCHAR2(11 BYTE),
  SRC_SYS_ID            VARCHAR2(5 BYTE),
  EG_TRACK_HIRE_DT      DATE,
  EG_ACADEMIC_RANK      VARCHAR2(3 BYTE),
  ACADEMIC_RANK_DESCR   VARCHAR2(30 BYTE),
  TENURE_STATUS         VARCHAR2(3 BYTE),
  TENURE_STATUS_DESCR   VARCHAR2(30 BYTE),
  EG_RNK_CHG_DT         DATE,
  EG_ADJ_RSN1           VARCHAR2(1 BYTE),
  EG_ORIG_TRACK_DT      DATE,
  DEPT_ID_TENURE_HOME   VARCHAR2(10 BYTE),
  DEPT_SID_TENURE_HOME  INTEGER,
  SETID                 VARCHAR2(5 BYTE),
  EG_GROUP              VARCHAR2(6 BYTE),
  EG_MAND_REVW_DT       DATE,
  EG_GRANTED_DT         DATE,
  FTE                   NUMBER(7,6),
  EG_TL_REQ_SVC         NUMBER(10,6),
  EG_ACCR_SVC           NUMBER(10,6),
  EG_ADD_REQ_SVC        NUMBER(10,6),
  EG_TL_EXT_SVC         NUMBER(10,6),
  OPRID                 VARCHAR2(30 BYTE),
  DTTM_STAMP_SEC        DATE,
  LAST_PROC_DT          DATE,
  EG_OVERRIDE_FLAG      VARCHAR2(1 BYTE),
  EG_TERM_YR_FLAG       VARCHAR2(1 BYTE),
  COMMENTS              VARCHAR2(2000 BYTE),
  LOAD_ERROR            VARCHAR2(1 BYTE),
  DATA_ORIGIN           VARCHAR2(1 BYTE),
  CREATED_EW_DTTM       DATE,
  LASTUPD_EW_DTTM       DATE,
  BATCH_SID             NUMBER(10)
)
NOLOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
