CREATE TABLE UM_D_FA_SF_ITEM_TYPE_BRIDGE
(
  INSTITUTION_CD    VARCHAR2(5 BYTE),
  AID_YEAR          VARCHAR2(4 BYTE),
  FA_ITEM_TYPE      VARCHAR2(12 BYTE),
  SF_ITEM_TYPE      VARCHAR2(12 BYTE),
  INSTITUTION_SID   INTEGER,
  FA_ITEM_TYPE_SID  INTEGER,
  SF_ITEM_TYPE_SID  INTEGER,
  EQUTN_VAR_CHAR1   VARCHAR2(20 BYTE),
  SRC_SYS_ID        VARCHAR2(5 CHAR),
  CREATED_EW_DTTM   DATE,
  LASTUPD_EW_DTTM   DATE,
  TREE_NODE_1       VARCHAR2(20 BYTE),
  TREE_NODE_2       VARCHAR2(20 BYTE),
  TREE_NODE_3       VARCHAR2(20 BYTE),
  TREE_NODE_4       VARCHAR2(20 BYTE),
  TREE_NODE_5       VARCHAR2(20 BYTE)
)
NOLOGGING 
COMPRESS BASIC
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
