CREATE TABLE PS_D_ADMIN_FUNC
(
  ADMIN_FUNC_SID     INTEGER,
  ADMIN_FUNCTION     VARCHAR2(4 CHAR),
  SRC_SYS_ID         VARCHAR2(5 CHAR),
  EFFDT              DATE,
  EFF_STATUS         VARCHAR2(1 CHAR),
  ADMIN_FUNCTION_SD  VARCHAR2(10 CHAR),
  ADMIN_FUNCTION_LD  VARCHAR2(30 CHAR),
  DATA_ORIGIN        VARCHAR2(1 CHAR),
  CREATED_EW_DTTM    DATE,
  LASTUPD_EW_DTTM    DATE
)
NOLOGGING 
COMPRESS BASIC
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
