CREATE TABLE UM_F_SF_STDNT_EQUTN_VAR
(
  INSTITUTION_CD   VARCHAR2(5 BYTE),
  BILLING_CAREER   VARCHAR2(4 BYTE),
  TERM_CD          VARCHAR2(4 BYTE),
  PERSON_ID        VARCHAR2(11 BYTE),
  SRC_SYS_ID       VARCHAR2(5 BYTE),
  INSTITUTION_SID  INTEGER,
  BILL_CAR_SID     INTEGER,
  TERM_SID         INTEGER,
  PERSON_SID       INTEGER,
  VARIABLE_CHAR1   VARCHAR2(20 BYTE),
  VARIABLE_CHAR2   VARCHAR2(20 BYTE),
  VARIABLE_CHAR3   VARCHAR2(20 BYTE),
  VARIABLE_CHAR4   VARCHAR2(20 BYTE),
  VARIABLE_CHAR5   VARCHAR2(20 BYTE),
  VARIABLE_CHAR6   VARCHAR2(20 BYTE),
  VARIABLE_CHAR7   VARCHAR2(20 BYTE),
  VARIABLE_CHAR8   VARCHAR2(20 BYTE),
  VARIABLE_CHAR9   VARCHAR2(20 BYTE),
  VARIABLE_CHAR10  VARCHAR2(20 BYTE),
  VARIABLE_FLAG1   VARCHAR2(1 BYTE),
  VARIABLE_FLAG2   VARCHAR2(1 BYTE),
  VARIABLE_FLAG3   VARCHAR2(1 BYTE),
  VARIABLE_FLAG4   VARCHAR2(1 BYTE),
  VARIABLE_FLAG5   VARCHAR2(1 BYTE),
  VARIABLE_FLAG6   VARCHAR2(1 BYTE),
  VARIABLE_FLAG7   VARCHAR2(1 BYTE),
  VARIABLE_FLAG8   VARCHAR2(1 BYTE),
  VARIABLE_FLAG9   VARCHAR2(1 BYTE),
  VARIABLE_FLAG10  VARCHAR2(1 BYTE),
  VARIABLE_NUM1    NUMBER(15,3),
  VARIABLE_NUM2    NUMBER(15,3),
  VARIABLE_NUM3    NUMBER(15,3),
  VARIABLE_NUM4    NUMBER(15,3),
  VARIABLE_NUM5    NUMBER(15,3),
  VARIABLE_NUM6    NUMBER(15,3),
  VARIABLE_NUM7    NUMBER(15,3),
  VARIABLE_NUM8    NUMBER(15,3),
  VARIABLE_NUM9    NUMBER(15,3),
  VARIABLE_NUM10   NUMBER(15,3),
  LOAD_ERROR       VARCHAR2(1 BYTE),
  DATA_ORIGIN      VARCHAR2(1 BYTE),
  CREATED_EW_DTTM  DATE,
  LASTUPD_EW_DTTM  DATE,
  BATCH_SID        INTEGER
)
NOLOGGING 
COMPRESS BASIC
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
