CREATE TABLE UM_D_CLASS_ASSOC
(
  CLASS_ASSOC_SID        INTEGER,
  CRSE_CD                VARCHAR2(6 BYTE),
  CRSE_OFFER_NUM         INTEGER,
  TERM_CD                VARCHAR2(4 BYTE),
  SESSION_CD             VARCHAR2(3 BYTE),
  ASSOCIATED_CLASS       INTEGER,
  SRC_SYS_ID             VARCHAR2(5 BYTE),
  RQRMNT_GROUP_SID       INTEGER,
  SSR_COMP_SID           INTEGER,
  SSR_COMP_PRIM_SID      INTEGER,
  BLIND_GRADING_FLG      VARCHAR2(1 BYTE),
  CATLOG_RQS_FLG         VARCHAR2(1 BYTE),
  GRADING_BASIS          VARCHAR2(3 BYTE),
  GRADE_BASIS_SD         VARCHAR2(10 BYTE),
  GRADE_BASIS_LD         VARCHAR2(30 BYTE),
  GRADE_ROSTER_PRINT     VARCHAR2(1 BYTE),
  GRADE_ROSTER_PRINT_SD  VARCHAR2(10 BYTE),
  GRADE_ROSTER_PRINT_LD  VARCHAR2(30 BYTE),
  INSTRUCTOR_EDIT        VARCHAR2(2 BYTE),
  INSTRUCTOR_EDIT_SD     VARCHAR2(10 BYTE),
  INSTRUCTOR_EDIT_LD     VARCHAR2(30 BYTE),
  RQMNT_DESIGNTN         VARCHAR2(4 BYTE),
  UPD_STDNT_ENRL_FLG     VARCHAR2(1 BYTE),
  BILLING_FACTOR         NUMBER(5,3),
  CRSE_CNT               NUMBER(4,2),
  CRSE_CONTACT_HRS       NUMBER(5,2),
  MIN_UNITS              NUMBER(5,2),
  MAX_UNITS              NUMBER(5,2),
  ACAD_PRGRS_UNITS       NUMBER(5,2),
  FINAID_PRGRS_UNITS     NUMBER(5,2),
  DATA_ORIGIN            VARCHAR2(1 BYTE),
  CREATED_EW_DTTM        DATE,
  LASTUPD_EW_DTTM        DATE
)
NOLOGGING 
COMPRESS BASIC
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
