DROP TABLE CSMRT_OWNER.PS_D_SSR_COMP CASCADE CONSTRAINTS
/

--
-- PS_D_SSR_COMP  (Table) 
--
CREATE TABLE CSMRT_OWNER.PS_D_SSR_COMP
(
  SSR_COMP_SID     INTEGER                      NOT NULL,
  SSR_COMP_CD      VARCHAR2(3 CHAR)             NOT NULL,
  SRC_SYS_ID       VARCHAR2(5 CHAR)             NOT NULL,
  SSR_COMP_SD      VARCHAR2(10 CHAR)            NOT NULL,
  SSR_COMP_LD      VARCHAR2(30 CHAR)            NOT NULL,
  DATA_ORIGIN      VARCHAR2(1 CHAR)             NOT NULL,
  CREATED_EW_DTTM  DATE,
  LASTUPD_EW_DTTM  DATE
)
COMPRESS BASIC
/


ALTER TABLE CSMRT_OWNER.PS_D_SSR_COMP ADD (
  CONSTRAINT PK_PS_D_SSR_COMP
  PRIMARY KEY
  (SSR_COMP_SID)
  RELY
  DISABLE NOVALIDATE)
/
