DROP TABLE CSMRT_OWNER.UM_F_FA_AWARD_SUMM_BY_YEAR CASCADE CONSTRAINTS
/

--
-- UM_F_FA_AWARD_SUMM_BY_YEAR  (Table) 
--
CREATE TABLE CSMRT_OWNER.UM_F_FA_AWARD_SUMM_BY_YEAR
(
  INSTITUTION_CD         VARCHAR2(5 BYTE)       NOT NULL,
  PERSON_ID              VARCHAR2(11 BYTE)      NOT NULL,
  AID_YEAR               VARCHAR2(4 BYTE)       NOT NULL,
  ACAD_CAR_CD            VARCHAR2(4 BYTE)       NOT NULL,
  SRC_SYS_ID             VARCHAR2(5 BYTE)       NOT NULL,
  INSTITUTION_SID        INTEGER                NOT NULL,
  PERSON_SID             INTEGER                NOT NULL,
  ACAD_CAR_SID           INTEGER                NOT NULL,
  FED_NEED               NUMBER(8,2),
  AWARD_AMOUNT           NUMBER(11,2),
  GRANT_AID              NUMBER(11,2),
  GRANT_AID_DECLINED     NUMBER(11,2),
  GRANT_AID_NEED         NUMBER(11,2),
  GRANT_AID_NO_NEED      NUMBER(11,2),
  WORK_AID               NUMBER(11,2),
  WORK_AID_DECLINED      NUMBER(11,2),
  WORK_AID_NEED          NUMBER(11,2),
  WORK_AID_NO_NEED       NUMBER(11,2),
  LOAN_AID               NUMBER(11,2),
  LOAN_AID_DECLINED      NUMBER(11,2),
  LOAN_AID_NEED          NUMBER(11,2),
  LOAN_AID_NO_NEED       NUMBER(11,2),
  TOTAL_PKG_NEED         NUMBER(11,2),
  TOTAL_PKG_NO_NEED      NUMBER(11,2),
  G_FED_AID              NUMBER(11,2),
  G_FED_AID_DECLINED     NUMBER(11,2),
  G_FED_AID_NEED         NUMBER(11,2),
  G_FED_AID_NO_NEED      NUMBER(11,2),
  G_STATE_AID            NUMBER(11,2),
  G_STATE_AID_DECLINED   NUMBER(11,2),
  G_STATE_AID_NEED       NUMBER(11,2),
  G_STATE_AID_NO_NEED    NUMBER(11,2),
  G_INSTIT_AID           NUMBER(11,2),
  G_INSTIT_AID_DECLINED  NUMBER(11,2),
  G_INSTIT_AID_NEED      NUMBER(11,2),
  G_INSTIT_AID_NO_NEED   NUMBER(11,2),
  O_WAIV_AID             NUMBER(11,2),
  O_WAIV_AID_DECLINED    NUMBER(11,2),
  O_WAIV_AID_NEED        NUMBER(11,2),
  O_WAIV_AID_NO_NEED     NUMBER(11,2),
  ATHL_AID               NUMBER(11,2),
  ATHL_AID_DECLINED      NUMBER(11,2),
  ATHL_AID_NEED          NUMBER(11,2),
  ATHL_AID_NO_NEED       NUMBER(11,2),
  G_PRVTE_AID            NUMBER(11,2),
  G_PRVTE_AID_DECLINED   NUMBER(11,2),
  G_PRVTE_AID_NEED       NUMBER(11,2),
  G_PRVTE_AID_NO_NEED    NUMBER(11,2),
  SH_CWP_AID             NUMBER(11,2),
  SH_CWP_AID_DECLINED    NUMBER(11,2),
  SH_CWP_AID_NEED        NUMBER(11,2),
  SH_CWP_AID_NO_NEED     NUMBER(11,2),
  SH_FWS_AID             NUMBER(11,2),
  SH_FWS_AID_DECLINED    NUMBER(11,2),
  SH_FWS_AID_NEED        NUMBER(11,2),
  SH_FWS_AID_NO_NEED     NUMBER(11,2),
  SH_LOAN_AID            NUMBER(11,2),
  SH_LOAN_AID_DECLINED   NUMBER(11,2),
  SH_SLOAN_AID_NEED      NUMBER(11,2),
  SH_SLOAN_AID_NO_NEED   NUMBER(11,2),
  O_PLOAN_AID            NUMBER(11,2),
  O_PLOAN_AID_DECLINED   NUMBER(11,2),
  O_PLOAN_AID_NEED       NUMBER(11,2),
  O_PLOAN_AID_NO_NEED    NUMBER(11,2),
  PARTITION_KEY          VARCHAR2(7 BYTE)       NOT NULL,
  DATA_ORIGIN            VARCHAR2(1 BYTE)       NOT NULL,
  CREATED_EW_DTTM        DATE,
  LASTUPD_EW_DTTM        DATE
)
NOCOMPRESS 
PARTITION BY LIST (PARTITION_KEY)
(  
  PARTITION UMB2017 VALUES ('UMB2017')
    NOCOMPRESS ,  
  PARTITION UMD2017 VALUES ('UMD2017')
    NOCOMPRESS ,  
  PARTITION UML2017 VALUES ('UML2017')
    NOCOMPRESS ,  
  PARTITION UMB2018 VALUES ('UMB2018')
    NOCOMPRESS ,  
  PARTITION UMD2018 VALUES ('UMD2018')
    NOCOMPRESS ,  
  PARTITION UML2018 VALUES ('UML2018')
    NOCOMPRESS ,  
  PARTITION UMB2019 VALUES ('UMB2019')
    NOCOMPRESS ,  
  PARTITION UMD2019 VALUES ('UMD2019')
    NOCOMPRESS ,  
  PARTITION UML2019 VALUES ('UML2019')
    NOCOMPRESS ,  
  PARTITION UMB2020 VALUES ('UMB2020')
    NOCOMPRESS ,  
  PARTITION UMD2020 VALUES ('UMD2020')
    NOCOMPRESS ,  
  PARTITION UML2020 VALUES ('UML2020')
    NOCOMPRESS ,  
  PARTITION UMB2021 VALUES ('UMB2021')
    NOCOMPRESS ,  
  PARTITION UMD2021 VALUES ('UMD2021')
    NOCOMPRESS ,  
  PARTITION UML2021 VALUES ('UML2021')
    NOCOMPRESS ,  
  PARTITION UMB2022 VALUES ('UMB2022')
    NOCOMPRESS ,  
  PARTITION UMD2022 VALUES ('UMD2022')
    NOCOMPRESS ,  
  PARTITION UML2022 VALUES ('UML2022')
    NOCOMPRESS ,  
  PARTITION UMB2023 VALUES ('UMB2023')
    NOCOMPRESS ,  
  PARTITION UMD2023 VALUES ('UMD2023')
    NOCOMPRESS ,  
  PARTITION UML2023 VALUES ('UML2023')
    NOCOMPRESS ,  
  PARTITION UMB2024 VALUES ('UMB2024')
    NOCOMPRESS ,  
  PARTITION UMD20214 VALUES ('UMD2024')
    NOCOMPRESS ,  
  PARTITION UML2024 VALUES ('UML2024')
    NOCOMPRESS ,  
  PARTITION UMB2025 VALUES ('UMB2025')
    NOCOMPRESS ,  
  PARTITION UMD2025 VALUES ('UMD2025')
    NOCOMPRESS ,  
  PARTITION UML2025 VALUES ('UML2025')
    NOCOMPRESS
)
/


ALTER TABLE CSMRT_OWNER.UM_F_FA_AWARD_SUMM_BY_YEAR ADD (
  CONSTRAINT PK_UM_F_FA_AWARD_SUMM_BY_YEAR
  PRIMARY KEY
  (INSTITUTION_CD, PERSON_ID, AID_YEAR, ACAD_CAR_CD, SRC_SYS_ID)
  RELY
  ENABLE VALIDATE)
/
