CREATE TABLE UM_F_ADM_APPL_ACTION
(
  PERSON_ID            VARCHAR2(11 CHAR),
  ADM_APPL_NBR         VARCHAR2(15 CHAR),
  ACN_RSN_KEY          VARCHAR2(30 CHAR),
  ACN_RSN_VAL          VARCHAR2(15 CHAR),
  MAX_TERM_MAX_DT      DATE,
  MAX_TERM_MIN_DT      DATE,
  MAX_DT               DATE,
  MIN_DT               DATE,
  MAX_TERM_MAX_RSN_CD  VARCHAR2(50 CHAR),
  MAX_TERM_MIN_RSN_CD  VARCHAR2(50 CHAR),
  MAX_RSN_CD           VARCHAR2(50 CHAR),
  MIN_RSN_CD           VARCHAR2(50 CHAR),
  DATA_ORIGIN          VARCHAR2(1 CHAR),
  CREATED_EW_DTTM      DATE,
  LASTUPD_EW_DTTM      DATE,
  BATCH_SID            NUMBER(10)
)
NOLOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
