DROP TABLE CSMRT_OWNER.PS_D_GRADE CASCADE CONSTRAINTS
/

--
-- PS_D_GRADE  (Table) 
--
CREATE TABLE CSMRT_OWNER.PS_D_GRADE
(
  GRADE_SID        INTEGER                      NOT NULL,
  SETID            VARCHAR2(5 CHAR)             NOT NULL,
  GRADE_SCHEME_CD  VARCHAR2(3 CHAR)             NOT NULL,
  GRADE_BASIS_CD   VARCHAR2(3 CHAR)             NOT NULL,
  GRADE_CD         VARCHAR2(3 CHAR)             NOT NULL,
  SRC_SYS_ID       VARCHAR2(5 CHAR)             NOT NULL,
  EFFDT            DATE,
  GRADE_SD         VARCHAR2(10 CHAR)            NOT NULL,
  GRADE_LD         VARCHAR2(30 CHAR)            NOT NULL,
  GRADE_SCHEME_SD  VARCHAR2(10 CHAR)            NOT NULL,
  GRADE_SCHEME_LD  VARCHAR2(30 CHAR)            NOT NULL,
  GRADE_BASIS_SD   VARCHAR2(10 CHAR)            NOT NULL,
  GRADE_BASIS_LD   VARCHAR2(30 CHAR)            NOT NULL,
  GRADE_CTGRY_CD   VARCHAR2(4 CHAR)             NOT NULL,
  GRADE_CTGRY_SD   VARCHAR2(10 CHAR)            NOT NULL,
  GRADE_CTGRY_LD   VARCHAR2(30 CHAR)            NOT NULL,
  ERN_CRED_FLG     VARCHAR2(1 CHAR)             NOT NULL,
  INCLUDE_GPA_FLG  VARCHAR2(1 CHAR)             NOT NULL,
  GRADE_PTS        NUMBER(9,3)                  NOT NULL,
  DATA_ORIGIN      VARCHAR2(1 CHAR)             NOT NULL,
  CREATED_EW_DTTM  DATE,
  LASTUPD_EW_DTTM  DATE
)
COMPRESS BASIC
/


ALTER TABLE CSMRT_OWNER.PS_D_GRADE ADD (
  CONSTRAINT PK_PS_D_GRADE
  PRIMARY KEY
  (GRADE_SID)
  RELY
  DISABLE NOVALIDATE)
/
