DROP TABLE CSMRT_OWNER.UM_F_EXT_ACAD_CRSE CASCADE CONSTRAINTS
/

--
-- UM_F_EXT_ACAD_CRSE  (Table) 
--
CREATE TABLE CSMRT_OWNER.UM_F_EXT_ACAD_CRSE
(
  PERSON_ID           VARCHAR2(11 BYTE)         NOT NULL,
  EXT_ORG_ID          VARCHAR2(11 BYTE)         NOT NULL,
  EXT_COURSE_NBR      INTEGER                   NOT NULL,
  SRC_SYS_ID          VARCHAR2(5 BYTE)          NOT NULL,
  INSTITUTION_CD      VARCHAR2(5 BYTE)          NOT NULL,
  EXT_COURSE_DESCR    VARCHAR2(30 BYTE)         NOT NULL,
  PERSON_SID          NUMBER(10)                NOT NULL,
  EXT_ORG_SID         NUMBER(10)                NOT NULL,
  INSTITUTION_SID     NUMBER(10)                NOT NULL,
  EXT_ACAD_CAR_SID    NUMBER(10)                NOT NULL,
  TST_DATA_SRC_SID    NUMBER(10)                NOT NULL,
  ACAD_UNIT_TYPE_SID  NUMBER(10)                NOT NULL,
  EXT_ACAD_LVL_SID    NUMBER(10)                NOT NULL,
  EXT_TERM_SID        NUMBER(10)                NOT NULL,
  BEGIN_DT            DATE,
  END_DT              DATE,
  CAN_TRNS_TYPE       VARCHAR2(2 BYTE)          NOT NULL,
  CAN_TRNS_TYPE_SD    VARCHAR2(10 BYTE)         NOT NULL,
  CAN_TRNS_TYPE_LD    VARCHAR2(30 BYTE)         NOT NULL,
  COURSE_LEVEL        VARCHAR2(2 BYTE)          NOT NULL,
  COURSE_LEVEL_SD     VARCHAR2(10 BYTE)         NOT NULL,
  COURSE_LEVEL_LD     VARCHAR2(30 BYTE)         NOT NULL,
  CRSE_GRADE_INPUT    VARCHAR2(3 BYTE)          NOT NULL,
  CRSE_GRADE_OFF      VARCHAR2(3 BYTE)          NOT NULL,
  EXT_CRSE_TYPE       VARCHAR2(3 BYTE)          NOT NULL,
  EXT_CRSE_TYPE_SD    VARCHAR2(10 BYTE)         NOT NULL,
  EXT_CRSE_TYPE_LD    VARCHAR2(30 BYTE)         NOT NULL,
  EXT_DATA_NBR        INTEGER                   NOT NULL,
  EXT_SUBJECT_AREA    VARCHAR2(4 BYTE)          NOT NULL,
  EXT_TERM_YEAR_SID   NUMBER(10)                NOT NULL,
  GRADING_BASIS       VARCHAR2(3 BYTE)          NOT NULL,
  GRADING_BASIS_SD    VARCHAR2(10 BYTE)         NOT NULL,
  GRADING_BASIS_LD    VARCHAR2(30 BYTE)         NOT NULL,
  GRADING_SCHEME      VARCHAR2(3 BYTE)          NOT NULL,
  GRADING_SCHEME_SD   VARCHAR2(10 BYTE)         NOT NULL,
  GRADING_SCHEME_LD   VARCHAR2(30 BYTE)         NOT NULL,
  SCHOOL_SUBJECT      VARCHAR2(8 BYTE)          NOT NULL,
  SCHOOL_CRSE_NBR     VARCHAR2(10 BYTE)         NOT NULL,
  TRANS_CREDIT_FLAG   VARCHAR2(1 BYTE)          NOT NULL,
  UNT_TAKEN           NUMBER(5,2)               NOT NULL,
  LASTUPDDTTM         DATE,
  LASTUPDOPRID        VARCHAR2(30 BYTE)         NOT NULL,
  LOAD_ERROR          VARCHAR2(1 BYTE)          NOT NULL,
  DATA_ORIGIN         VARCHAR2(1 BYTE)          NOT NULL,
  CREATED_EW_DTTM     DATE,
  LASTUPD_EW_DTTM     DATE,
  BATCH_SID           NUMBER(10)                NOT NULL
)
NOCOMPRESS
/


ALTER TABLE CSMRT_OWNER.UM_F_EXT_ACAD_CRSE ADD (
  CONSTRAINT PK_UM_F_EXT_ACAD_CRSE
  PRIMARY KEY
  (PERSON_ID, EXT_ORG_ID, EXT_COURSE_NBR, SRC_SYS_ID)
  RELY
  ENABLE VALIDATE)
/
