DROP TABLE CSMRT_OWNER.UM_F_FA_STDNT_ANTICIP_AID CASCADE CONSTRAINTS
/

--
-- UM_F_FA_STDNT_ANTICIP_AID  (Table) 
--
CREATE TABLE CSMRT_OWNER.UM_F_FA_STDNT_ANTICIP_AID
(
  INSTITUTION_CD        VARCHAR2(5 BYTE)        NOT NULL,
  ACAD_CAR_CD           VARCHAR2(4 BYTE)        NOT NULL,
  AID_YEAR              VARCHAR2(4 BYTE)        NOT NULL,
  PERSON_ID             VARCHAR2(11 BYTE)       NOT NULL,
  ITEM_TYPE             VARCHAR2(12 BYTE)       NOT NULL,
  DISBURSEMENT_PLAN     VARCHAR2(2 BYTE)        NOT NULL,
  DISBURSEMENT_ID       VARCHAR2(2 BYTE)        NOT NULL,
  AS_OF_DTTM            TIMESTAMP(6),
  SRC_SYS_ID            VARCHAR2(5 BYTE)        NOT NULL,
  INSTITUTION_SID       INTEGER                 NOT NULL,
  ACAD_CAR_SID          INTEGER                 NOT NULL,
  PERSON_SID            INTEGER                 NOT NULL,
  ITEM_TYPE_SID         INTEGER                 NOT NULL,
  TERM_SID              INTEGER                 NOT NULL,
  DISBURSEMENT_PLAN_LD  VARCHAR2(30 BYTE),
  NET_AWARD_AMT         NUMBER(11,2),
  DISB_APPLY_DT         DATE,
  DISB_EXPIRE_DT        DATE,
  CURRENCY_CD           VARCHAR2(3 BYTE),
  LOAD_ERROR            VARCHAR2(1 BYTE),
  DATA_ORIGIN           VARCHAR2(1 BYTE),
  CREATED_EW_DTTM       DATE,
  LASTUPD_EW_DTTM       DATE,
  BATCH_SID             INTEGER
)
COMPRESS BASIC
/


ALTER TABLE CSMRT_OWNER.UM_F_FA_STDNT_ANTICIP_AID ADD (
  CONSTRAINT PK_UM_F_FA_STDNT_ANT_AID
  PRIMARY KEY
  (INSTITUTION_CD, ACAD_CAR_CD, AID_YEAR, PERSON_ID, ITEM_TYPE, DISBURSEMENT_PLAN, DISBURSEMENT_ID, AS_OF_DTTM, SRC_SYS_ID)
  RELY
  ENABLE VALIDATE)
/
