DROP TABLE CSMRT_OWNER.UM_D_GRD_RSTR_TYPE CASCADE CONSTRAINTS
/

--
-- UM_D_GRD_RSTR_TYPE  (Table) 
--
CREATE TABLE CSMRT_OWNER.UM_D_GRD_RSTR_TYPE
(
  GRD_RSTR_TYPE_SID      INTEGER                NOT NULL,
  TERM_CD                VARCHAR2(4 BYTE)       NOT NULL,
  CLASS_NBR              INTEGER                NOT NULL,
  GRD_RSTR_TYPE_SEQ      INTEGER                NOT NULL,
  SRC_SYS_ID             VARCHAR2(5 BYTE)       NOT NULL,
  GRADE_ROSTER_TYPE      VARCHAR2(4 BYTE)       NOT NULL,
  DESCR                  VARCHAR2(30 BYTE)      NOT NULL,
  GRADING_STATUS         VARCHAR2(4 BYTE)       NOT NULL,
  GRADING_STATUS_SD      VARCHAR2(10 BYTE)      NOT NULL,
  GRADING_STATUS_LD      VARCHAR2(30 BYTE)      NOT NULL,
  GR_APPROVAL_STATUS     VARCHAR2(4 BYTE)       NOT NULL,
  GR_APPROVAL_STATUS_SD  VARCHAR2(10 BYTE)      NOT NULL,
  GR_APPROVAL_STATUS_LD  VARCHAR2(30 BYTE)      NOT NULL,
  APPROVAL_DATE          DATE,
  POSTING_DATE           DATE,
  PARTIAL_POST_FLG       VARCHAR2(1 BYTE)       NOT NULL,
  OVRD_GRADE_ROSTER_FLG  VARCHAR2(1 BYTE)       NOT NULL,
  PROCESS_INSTANCE       NUMBER(10)             NOT NULL,
  DATA_ORIGIN            VARCHAR2(1 BYTE)       NOT NULL,
  CREATED_EW_DTTM        DATE,
  LASTUPD_EW_DTTM        DATE
)
COMPRESS BASIC
/


ALTER TABLE CSMRT_OWNER.UM_D_GRD_RSTR_TYPE ADD (
  CONSTRAINT PK_UM_D_GRD_RSTR_TYPE
  PRIMARY KEY
  (GRD_RSTR_TYPE_SID)
  RELY
  DISABLE NOVALIDATE)
/
