DROP TABLE CSMRT_OWNER.PS_D_EXT_TERM CASCADE CONSTRAINTS
/

--
-- PS_D_EXT_TERM  (Table) 
--
CREATE TABLE CSMRT_OWNER.PS_D_EXT_TERM
(
  EXT_TERM_SID      INTEGER                     NOT NULL,
  EXT_TERM_TYPE_ID  VARCHAR2(4 CHAR)            NOT NULL,
  EXT_TERM_ID       VARCHAR2(4 CHAR)            NOT NULL,
  SRC_SYS_ID        VARCHAR2(5 CHAR)            NOT NULL,
  EXT_TERM_TYPE_SD  VARCHAR2(10 CHAR)           NOT NULL,
  EXT_TERM_TYPE_LD  VARCHAR2(30 CHAR)           NOT NULL,
  EXT_TERM_SD       VARCHAR2(10 CHAR)           NOT NULL,
  EXT_TERM_LD       VARCHAR2(30 CHAR)           NOT NULL,
  DATA_ORIGIN       VARCHAR2(1 CHAR)            NOT NULL,
  CREATED_EW_DTTM   DATE,
  LASTUPD_EW_DTTM   DATE
)
COMPRESS BASIC
/


ALTER TABLE CSMRT_OWNER.PS_D_EXT_TERM ADD (
  CONSTRAINT PK_PS_D_EXT_TERM
  PRIMARY KEY
  (EXT_TERM_SID)
  RELY
  DISABLE NOVALIDATE)
/
