DROP TABLE CSMRT_OWNER.UM_F_FA_STDNT_SFA_SAP CASCADE CONSTRAINTS
/

--
-- UM_F_FA_STDNT_SFA_SAP  (Table) 
--
CREATE TABLE CSMRT_OWNER.UM_F_FA_STDNT_SFA_SAP
(
  INSTITUTION_CD        VARCHAR2(5 BYTE)        NOT NULL,
  ACAD_CAR_CD           VARCHAR2(4 BYTE)        NOT NULL,
  AID_YEAR              VARCHAR2(4 BYTE)        NOT NULL,
  PERSON_ID             VARCHAR2(11 BYTE)       NOT NULL,
  PROCESS_DTTM          TIMESTAMP(6)            NOT NULL,
  SRC_SYS_ID            VARCHAR2(5 BYTE)        NOT NULL,
  INSTITUTION_SID       INTEGER                 NOT NULL,
  ACAD_CAR_SID          INTEGER                 NOT NULL,
  PERSON_SID            INTEGER                 NOT NULL,
  ACAD_PROG_SID         INTEGER                 NOT NULL,
  ACAD_PLAN_SID         INTEGER                 NOT NULL,
  STDNT_CAR_NBR         INTEGER,
  SFA_SAP_MAX_ATTUNT    NUMBER(8,3),
  SFA_SAP_MAX_ATTFRM    NUMBER(8,3),
  SFA_SAP_MAX_ATTMPT    NUMBER(8,3),
  SFA_INUSE_FLAG2       VARCHAR2(1 BYTE),
  SFA_SAP_STATUS_C2     VARCHAR2(4 BYTE),
  SFA_FAIL_FLAG2        VARCHAR2(1 BYTE),
  CUR_GPA               NUMBER(8,3),
  CUM_GPA               NUMBER(8,3),
  SFA_SAP_MIN_CUM       NUMBER(4,3),
  SFA_INUSE_FLAG5       VARCHAR2(1 BYTE),
  SFA_SAP_STATUS_C5     VARCHAR2(4 BYTE),
  SFA_FAIL_FLAG5        VARCHAR2(1 BYTE),
  SFA_CUM_ATT_UNITS     NUMBER(8,3),
  SFA_CUM_ERN_UNITS     NUMBER(8,3),
  SFA_SAP_CUM_EARNPC    NUMBER(5,2),
  SFA_INUSE_FLAG7       VARCHAR2(1 BYTE),
  SFA_SAP_STATUS_C7     VARCHAR2(4 BYTE),
  SFA_FAIL_FLAG7        VARCHAR2(1 BYTE),
  SFA_SAP_2YR_GPA       NUMBER(8,3),
  SFA_SAP_CUMERN_PCT    NUMBER(5,2),
  SFA_SAP_STATUS        VARCHAR2(4 BYTE),
  SFA_SAP_STATUS_SD     VARCHAR2(10 BYTE),
  SFA_SAP_STATUS_LD     VARCHAR2(30 BYTE),
  SFA_SAP_STAT_CALC     VARCHAR2(4 BYTE),
  SFA_SAP_STAT_CALC_SD  VARCHAR2(10 BYTE),
  SFA_SAP_STAT_CALC_LD  VARCHAR2(30 BYTE),
  SFA_UPDT_OPRID        VARCHAR2(30 BYTE),
  SFA_UPDT_DTTM         DATE,
  SFA_PROCESS_OPRID     VARCHAR2(30 BYTE),
  SFA_SAP_PROCMSG       VARCHAR2(100 BYTE),
  SFA_SAP_COMMENTS      VARCHAR2(4000 BYTE),
  SFA_SAP_ORDER         INTEGER,
  LOAD_ERROR            VARCHAR2(1 BYTE)        NOT NULL,
  DATA_ORIGIN           VARCHAR2(1 BYTE)        NOT NULL,
  CREATED_EW_DTTM       DATE,
  LASTUPD_EW_DTTM       DATE,
  BATCH_SID             NUMBER(10)              NOT NULL
)
COMPRESS BASIC
/


ALTER TABLE CSMRT_OWNER.UM_F_FA_STDNT_SFA_SAP ADD (
  CONSTRAINT PK_UM_F_FA_STDNT_SFA_SAP
  PRIMARY KEY
  (INSTITUTION_CD, ACAD_CAR_CD, AID_YEAR, PERSON_ID, PROCESS_DTTM, SRC_SYS_ID)
  RELY
  ENABLE VALIDATE)
/
