CREATE TABLE UM_D_PERSON_NAME_AGG
(
  PERSON_ID        VARCHAR2(11 BYTE),
  SRC_SYS_ID       VARCHAR2(5 BYTE),
  PERSON_SID       INTEGER,
  PRI_NAME         VARCHAR2(50 BYTE),
  PRI_FIRST_NAME   VARCHAR2(30 BYTE),
  PRI_MIDDLE_NAME  VARCHAR2(30 BYTE),
  PRI_LAST_NAME    VARCHAR2(30 BYTE),
  PRI_PREFIX       VARCHAR2(4 BYTE),
  PRI_SUFFIX       VARCHAR2(15 BYTE),
  DEG_NAME         VARCHAR2(50 BYTE),
  DEG_FIRST_NAME   VARCHAR2(30 BYTE),
  DEG_MIDDLE_NAME  VARCHAR2(30 BYTE),
  DEG_LAST_NAME    VARCHAR2(30 BYTE),
  DEG_PREFIX       VARCHAR2(4 BYTE),
  DEG_SUFFIX       VARCHAR2(15 BYTE),
  PRF_NAME         VARCHAR2(50 BYTE),
  PRF_FIRST_NAME   VARCHAR2(30 BYTE),
  PRF_MIDDLE_NAME  VARCHAR2(30 BYTE),
  PRF_LAST_NAME    VARCHAR2(30 BYTE),
  PRF_PREFIX       VARCHAR2(4 BYTE),
  PRF_SUFFIX       VARCHAR2(15 BYTE),
  AKA_NAME         VARCHAR2(50 BYTE),
  AKA_FIRST_NAME   VARCHAR2(30 BYTE),
  AKA_MIDDLE_NAME  VARCHAR2(30 BYTE),
  AKA_LAST_NAME    VARCHAR2(30 BYTE),
  AKA_PREFIX       VARCHAR2(4 BYTE),
  AKA_SUFFIX       VARCHAR2(15 BYTE),
  CPS_NAME         VARCHAR2(50 BYTE),
  CPS_FIRST_NAME   VARCHAR2(30 BYTE),
  CPS_MIDDLE_NAME  VARCHAR2(30 BYTE),
  CPS_LAST_NAME    VARCHAR2(30 BYTE),
  CPS_PREFIX       VARCHAR2(4 BYTE),
  CPS_SUFFIX       VARCHAR2(15 BYTE),
  DATA_ORIGIN      VARCHAR2(1 BYTE),
  CREATED_EW_DTTM  DATE,
  LASTUPD_EW_DTTM  DATE
)
NOLOGGING 
COMPRESS BASIC
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
