DROP TABLE CSMRT_OWNER.UM_R_STDNT_GRP CASCADE CONSTRAINTS
/

--
-- UM_R_STDNT_GRP  (Table) 
--
CREATE TABLE CSMRT_OWNER.UM_R_STDNT_GRP
(
  TERM_SID         INTEGER                      NOT NULL,
  PERSON_SID       INTEGER                      NOT NULL,
  STDNT_GRP_SID    INTEGER                      NOT NULL,
  SRC_SYS_ID       VARCHAR2(5 BYTE)             NOT NULL,
  INSTITUTION_CD   VARCHAR2(5 BYTE)             NOT NULL,
  ACAD_CAR_CD      VARCHAR2(5 BYTE)             NOT NULL,
  TERM_CD          VARCHAR2(4 BYTE)             NOT NULL,
  PERSON_ID        VARCHAR2(11 BYTE)            NOT NULL,
  STDNT_GRP_CD     VARCHAR2(4 BYTE)             NOT NULL,
  EFFDT            DATE,
  EFF_STAT_CD      VARCHAR2(1 BYTE)             NOT NULL,
  EFF_START_DT     DATE,
  EFF_END_DT       DATE,
  CURRENT_IND      VARCHAR2(1 BYTE)             NOT NULL,
  HONORS_FLG       VARCHAR2(1 BYTE)             NOT NULL,
  STDNT_GRP_ORDER  INTEGER                      NOT NULL,
  LOAD_ERROR       VARCHAR2(1 BYTE)             NOT NULL,
  DATA_ORIGIN      VARCHAR2(1 BYTE)             NOT NULL,
  CREATED_EW_DTTM  DATE,
  LASTUPD_EW_DTTM  DATE,
  BATCH_SID        INTEGER                      NOT NULL,
  COMMENTS         VARCHAR2(4000 BYTE)
)
COMPRESS BASIC
/


ALTER TABLE CSMRT_OWNER.UM_R_STDNT_GRP ADD (
  CONSTRAINT PK_UM_R_STDNT_GRP
  PRIMARY KEY
  (TERM_SID, PERSON_SID, STDNT_GRP_SID, SRC_SYS_ID)
  RELY
  ENABLE VALIDATE)
/
