DROP TABLE CSMRT_OWNER.UM_F_ACAD_PLAN CASCADE CONSTRAINTS
/

--
-- UM_F_ACAD_PLAN  (Table) 
--
CREATE TABLE CSMRT_OWNER.UM_F_ACAD_PLAN
(
  INSTITUTION_CD                VARCHAR2(5 BYTE) NOT NULL,
  ACAD_CAR_CD                   VARCHAR2(5 BYTE) NOT NULL,
  TERM_CD                       VARCHAR2(4 BYTE) NOT NULL,
  PERSON_ID                     VARCHAR2(11 BYTE) NOT NULL,
  STDNT_CAR_NUM                 INTEGER         NOT NULL,
  ACAD_PROG_CD                  VARCHAR2(5 BYTE) NOT NULL,
  ACAD_PLAN_CD                  VARCHAR2(10 BYTE) NOT NULL,
  ACAD_SPLAN_CD                 VARCHAR2(10 BYTE) NOT NULL,
  SRC_SYS_ID                    VARCHAR2(5 BYTE) NOT NULL,
  EFFDT                         DATE,
  EFFSEQ                        INTEGER         NOT NULL,
  INSTITUTION_SID               INTEGER         NOT NULL,
  ACAD_CAR_SID                  INTEGER         NOT NULL,
  TERM_SID                      INTEGER         NOT NULL,
  PERSON_SID                    INTEGER         NOT NULL,
  ACAD_PROG_SID                 INTEGER         NOT NULL,
  ACAD_PLAN_SID                 INTEGER         NOT NULL,
  ACAD_SPLAN_SID                INTEGER         NOT NULL,
  CALC_TERM_LIMIT_SID           INTEGER         NOT NULL,
  NEW_TERM_LIMIT_SID            INTEGER         NOT NULL,
  PLAN_COMPL_TERM_SID           INTEGER         NOT NULL,
  PLAN_REQ_TERM_SID             INTEGER         NOT NULL,
  SPLAN_REQ_TERM_SID            INTEGER         NOT NULL,
  CERTIFICATE_ONLY_FLG          VARCHAR2(1 BYTE) NOT NULL,
  MAJOR_RANK                    INTEGER         NOT NULL,
  MINOR_RANK                    INTEGER         NOT NULL,
  SPLAN_RANK                    INTEGER         NOT NULL,
  PRIM_STACK_CAREER_RANK        INTEGER         NOT NULL,
  PRIM_STACK_STDNT_RANK         INTEGER         NOT NULL,
  MAJOR_RANK_PIVOT              INTEGER         NOT NULL,
  MINOR_RANK_PIVOT              INTEGER         NOT NULL,
  POS_RANK_PIVOT                INTEGER         NOT NULL,
  D_RANK                        INTEGER         NOT NULL,
  D_RANK_PTYPE                  INTEGER         NOT NULL,
  D_RANK_SPLAN                  INTEGER         NOT NULL,
  DEGREE_SEEKING_FLG            VARCHAR2(1 BYTE) NOT NULL,
  ED_LVL_RANK                   INTEGER         NOT NULL,
  NULL_PLAN_TYPE_FLG            VARCHAR2(1 BYTE) NOT NULL,
  PROGRAM_CATGRY                VARCHAR2(20 BYTE) NOT NULL,
  PLAN_ADVIS_STAT               VARCHAR2(4 BYTE) NOT NULL,
  PLAN_DECLARE_DT               DATE,
  PLAN_SEQUENCE                 INTEGER         NOT NULL,
  PLAN_DEGR_CHKOUT_STAT         VARCHAR2(2 BYTE) NOT NULL,
  PLAN_STDNT_DEGR_CD            VARCHAR2(2 BYTE) NOT NULL,
  SPLAN_DECLARE_DT              DATE,
  DEG_LIMIT_EFFDT               DATE,
  NEW_TERM_LIMIT_CD             VARCHAR2(4 BYTE),
  CALC_TERM_LIMIT_CD            VARCHAR2(4 BYTE),
  DEG_LIMIT_UM_OVRRIDE_EXTENSN  VARCHAR2(1 BYTE),
  DEG_LIMIT_YEARS               INTEGER,
  DEG_LIMIT_COMMENTS_MSGS       VARCHAR2(254 BYTE),
  UMDAR_ED_LVL                  VARCHAR2(3 BYTE) NOT NULL,
  PRIM_PROG_MAJOR_1_CNT         INTEGER         NOT NULL,
  PRIM_PROG_MAJOR_2_CNT         INTEGER         NOT NULL,
  PRIM_PROG_MINOR_1_CNT         INTEGER         NOT NULL,
  PRIM_PROG_MINOR_2_CNT         INTEGER         NOT NULL,
  PRIM_PROG_OTHER_PLAN_CNT      INTEGER         NOT NULL,
  SEC_PROG_MAJOR_1_CNT          INTEGER         NOT NULL,
  SEC_PROG_MAJOR_2_CNT          INTEGER         NOT NULL,
  SEC_PROG_MINOR_1_CNT          INTEGER         NOT NULL,
  SEC_PROG_MINOR_2_CNT          INTEGER         NOT NULL,
  SEC_PROG_OTHER_PLAN_CNT       INTEGER         NOT NULL,
  PP_SUB_PLAN_11_CNT            INTEGER         NOT NULL,
  PP_SUB_PLAN_12_CNT            INTEGER         NOT NULL,
  PP_SUB_PLAN_21_CNT            INTEGER         NOT NULL,
  PP_SUB_PLAN_22_CNT            INTEGER         NOT NULL,
  SP_SUB_PLAN_11_CNT            INTEGER         NOT NULL,
  SP_SUB_PLAN_12_CNT            INTEGER         NOT NULL,
  SP_SUB_PLAN_21_CNT            INTEGER         NOT NULL,
  SP_SUB_PLAN_22_CNT            INTEGER         NOT NULL,
  LOAD_ERROR                    VARCHAR2(1 BYTE) NOT NULL,
  DATA_ORIGIN                   VARCHAR2(1 BYTE) NOT NULL,
  CREATED_EW_DTTM               DATE,
  LASTUPD_EW_DTTM               DATE,
  BATCH_SID                     INTEGER         NOT NULL
)
COMPRESS BASIC
/


ALTER TABLE CSMRT_OWNER.UM_F_ACAD_PLAN ADD (
  CONSTRAINT PK_UM_F_ACAD_PLAN
  PRIMARY KEY
  (INSTITUTION_CD, ACAD_CAR_CD, TERM_CD, PERSON_ID, STDNT_CAR_NUM, ACAD_PROG_CD, ACAD_PLAN_CD, ACAD_SPLAN_CD, SRC_SYS_ID)
  RELY
  ENABLE VALIDATE)
/
