CREATE TABLE PS_D_ACAD_ORG
(
  ACAD_ORG_SID      INTEGER,
  EFFDT             DATE,
  ACAD_ORG_CD       VARCHAR2(10 CHAR),
  SRC_SYS_ID        VARCHAR2(5 CHAR),
  EFFDT_START       DATE,
  EFFDT_END         DATE,
  EFFDT_ORDER       INTEGER,
  EFF_STAT_CD       VARCHAR2(1 CHAR),
  ACAD_ORG_SD       VARCHAR2(10 CHAR),
  ACAD_ORG_LD       VARCHAR2(30 CHAR),
  ACAD_ORG_FD       VARCHAR2(50 CHAR),
  ACAD_ORG_CD_DESC  VARCHAR2(50 CHAR),
  INSTITUTION_CD    VARCHAR2(5 CHAR),
  DATA_ORIGIN       VARCHAR2(1 CHAR),
  CREATED_EW_DTTM   DATE,
  LASTUPD_EW_DTTM   DATE
)
NOLOGGING 
COMPRESS BASIC
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
