CREATE TABLE PS_D_RFRL_SRC
(
  RFRL_SRC_SID     INTEGER,
  RFRL_SRC_ID      VARCHAR2(4 CHAR),
  SRC_SYS_ID       VARCHAR2(5 CHAR),
  EFFDT            DATE,
  EFF_STAT_CD      VARCHAR2(1 CHAR),
  RFRL_SRC_SD      VARCHAR2(10 CHAR),
  RFRL_SRC_LD      VARCHAR2(30 CHAR),
  DATA_ORIGIN      VARCHAR2(1 CHAR),
  CREATED_EW_DTTM  DATE,
  LASTUPD_EW_DTTM  DATE
)
NOLOGGING 
COMPRESS BASIC
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
