CREATE TABLE PS_D_DEG_HONORS
(
  DEG_HONORS_SID   NUMBER(10),
  INSTITUTION_CD   VARCHAR2(5 CHAR),
  HONORS_TYPE_CD   VARCHAR2(2 CHAR),
  HONORS_CD        VARCHAR2(3 CHAR),
  SRC_SYS_ID       VARCHAR2(5 CHAR),
  EFFDT            DATE,
  EFF_STAT_CD      VARCHAR2(1 CHAR),
  HONORS_TYPE_SD   VARCHAR2(10 CHAR),
  HONORS_TYPE_LD   VARCHAR2(30 CHAR),
  HONORS_SD        VARCHAR2(10 CHAR),
  HONORS_LD        VARCHAR2(30 CHAR),
  HONORS_FD        VARCHAR2(50 CHAR),
  DATA_ORIGIN      VARCHAR2(1 CHAR),
  CREATED_EW_DTTM  DATE,
  LASTUPD_EW_DTTM  DATE
)
NOLOGGING 
COMPRESS BASIC
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
