CREATE TABLE UM_F_ADM_APPL_LST_SCHL
(
  APPLCNT_SID          INTEGER,
  INSTITUTION_SID      INTEGER,
  EXT_ORG_SID          INTEGER,
  SRC_SYS_ID           VARCHAR2(5 BYTE),
  PERSON_ID            VARCHAR2(11 BYTE),
  INSTITUTION_CD       VARCHAR2(5 BYTE),
  EXT_ORG_ID           VARCHAR2(11 BYTE),
  EXT_DATA_NBR         INTEGER,
  EXT_ACAD_CAR_ID      VARCHAR2(4 BYTE),
  EXT_SUMM_TYPE_ID     VARCHAR2(4 BYTE),
  CLASS_RANK           INTEGER,
  CLASS_SIZE           INTEGER,
  CLASS_PERCENTILE     INTEGER,
  EXT_GPA              NUMBER(6,3),
  CONVERTED_GPA        NUMBER(6,3),
  UM_CUM_CREDIT        NUMBER(5,2),
  UM_CUM_GPA           NUMBER(5,2),
  UM_CUM_QP            NUMBER(5,2),
  UM_GPA_EXCLUDE_FLG   VARCHAR2(1 BYTE),
  UM_EXT_ORG_CR        NUMBER(5,2),
  UM_EXT_ORG_QP        NUMBER(5,2),
  UM_EXT_ORG_GPA       NUMBER(5,2),
  UM_EXT_ORG_CNV_CR    NUMBER(5,2),
  UM_EXT_ORG_CNV_GPA   NUMBER(5,2),
  UM_EXT_ORG_CNV_QP    NUMBER(5,2),
  UM_GPA_OVRD_FLG      VARCHAR2(1 BYTE),
  UM_1_OVRD_HSGPA_FLG  VARCHAR2(1 BYTE),
  UM_CONVERT_GPA       NUMBER(6,3),
  UM_EXT_OR_MTSC_GPA   NUMBER(6,3),
  MS_CONVERT_GPA       NUMBER(6,3),
  DATA_ORIGIN          VARCHAR2(1 BYTE),
  CREATED_EW_DTTM      DATE,
  LASTUPD_EW_DTTM      DATE
)
NOLOGGING 
COMPRESS BASIC
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
