DROP TABLE CSMRT_OWNER.PS_D_ENRL_RSN CASCADE CONSTRAINTS
/

--
-- PS_D_ENRL_RSN  (Table) 
--
CREATE TABLE CSMRT_OWNER.PS_D_ENRL_RSN
(
  ENRL_ACT_RSN_SID  NUMBER(10)                  NOT NULL,
  SETID             VARCHAR2(5 CHAR)            NOT NULL,
  ACAD_CAR_CD       VARCHAR2(4 CHAR)            NOT NULL,
  ENRL_ACTION       VARCHAR2(2 CHAR)            NOT NULL,
  ENRL_ACT_RSN      VARCHAR2(4 CHAR)            NOT NULL,
  SRC_SYS_ID        VARCHAR2(5 CHAR)            NOT NULL,
  EFFDT             DATE,
  EFF_STAT_CD       VARCHAR2(1 CHAR)            NOT NULL,
  ENRL_ACT_RSN_SD   VARCHAR2(10 CHAR)           NOT NULL,
  ENRL_ACT_RSN_LD   VARCHAR2(30 CHAR)           NOT NULL,
  DATA_ORIGIN       VARCHAR2(1 CHAR)            NOT NULL,
  CREATED_EW_DTTM   DATE,
  LASTUPD_EW_DTTM   DATE
)
COMPRESS BASIC
/


ALTER TABLE CSMRT_OWNER.PS_D_ENRL_RSN ADD (
  CONSTRAINT PK_PS_D_ENRL_RSN
  PRIMARY KEY
  (ENRL_ACT_RSN_SID)
  RELY
  DISABLE NOVALIDATE)
/
