DROP TABLE CSMRT_OWNER.UM_D_CLASS_INSTRCTR CASCADE CONSTRAINTS
/

--
-- UM_D_CLASS_INSTRCTR  (Table) 
--
CREATE TABLE CSMRT_OWNER.UM_D_CLASS_INSTRCTR
(
  CLASS_INSTRCTR_SID    INTEGER,
  CRSE_CD               VARCHAR2(6 BYTE)        NOT NULL,
  CRSE_OFFER_NUM        INTEGER                 NOT NULL,
  TERM_CD               VARCHAR2(4 BYTE)        NOT NULL,
  SESSION_CD            VARCHAR2(3 BYTE)        NOT NULL,
  CLASS_SECTION_CD      VARCHAR2(4 BYTE)        NOT NULL,
  CLASS_MTG_NUM         INTEGER                 NOT NULL,
  INSTRCTR_ASGN_NUM     INTEGER                 NOT NULL,
  SRC_SYS_ID            VARCHAR2(5 BYTE)        NOT NULL,
  CLASS_MTG_PAT_ORDER   INTEGER                 NOT NULL,
  CLASS_INSTRCTR_ORDER  INTEGER                 NOT NULL,
  INSTITUTION_CD        VARCHAR2(5 BYTE)        NOT NULL,
  CLASS_SID             INTEGER                 NOT NULL,
  CLASS_MTG_PAT_SID     INTEGER                 NOT NULL,
  PERSON_SID            INTEGER                 NOT NULL,
  INSTRCTR_ROLE_SID     INTEGER                 NOT NULL,
  GRADE_RSTR_ACCESS     VARCHAR2(1 BYTE),
  GRADE_RSTR_ACCESS_SD  VARCHAR2(10 BYTE),
  GRADE_RSTR_ACCESS_LD  VARCHAR2(30 BYTE),
  CONTACT_MINUTES       INTEGER,
  SCHED_PRINT_INSTR     VARCHAR2(1 BYTE),
  INSTR_LOAD_FACTOR     NUMBER(5,2),
  AUTOCALC_WRKLD_FLG    VARCHAR2(1 BYTE),
  DATA_ORIGIN           VARCHAR2(1 BYTE),
  CREATED_EW_DTTM       DATE,
  LASTUPD_EW_DTTM       DATE
)
COMPRESS BASIC
/


ALTER TABLE CSMRT_OWNER.UM_D_CLASS_INSTRCTR ADD (
  CONSTRAINT PK_UM_D_CLASS_INSTRCTR
  PRIMARY KEY
  (CLASS_INSTRCTR_SID)
  RELY
  ENABLE VALIDATE)
/
