CREATE TABLE PS_D_CAMPUS
(
  CAMPUS_SID       INTEGER,
  INSTITUTION_CD   VARCHAR2(5 BYTE),
  CAMPUS_CD        VARCHAR2(5 BYTE),
  SRC_SYS_ID       VARCHAR2(5 BYTE),
  EFFDT            DATE,
  EFF_STAT_CD      VARCHAR2(1 BYTE),
  CAMPUS_SD        VARCHAR2(10 BYTE),
  CAMPUS_LD        VARCHAR2(30 BYTE),
  DATA_ORIGIN      VARCHAR2(1 BYTE),
  CREATED_EW_DTTM  DATE,
  LASTUPD_EW_DTTM  DATE
)
NOLOGGING 
COMPRESS BASIC
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
