CREATE TABLE PS_D_ITEM_CD
(
  ITEM_CD_SID           INTEGER,
  CHKLST_ITEM_CD        VARCHAR2(6 CHAR),
  SRC_SYS_ID            VARCHAR2(5 CHAR),
  EFFDT                 DATE,
  EFF_STAT_CD           VARCHAR2(1 CHAR),
  ITEM_ASSOCIATION      VARCHAR2(1 CHAR),
  ITEM_CD_SD            VARCHAR2(10 CHAR),
  ITEM_CD_LD            VARCHAR2(30 CHAR),
  UMBOS_INSTITUTION_CD  VARCHAR2(5 CHAR),
  UMDAR_INSTITUTION_CD  VARCHAR2(5 CHAR),
  UMLOW_INSTITUTION_CD  VARCHAR2(5 CHAR),
  LOAD_ERROR            VARCHAR2(1 CHAR),
  DATA_ORIGIN           VARCHAR2(1 CHAR),
  CREATED_EW_DTTM       DATE,
  LASTUPD_EW_DTTM       DATE,
  BATCH_SID             NUMBER(10)
)
NOLOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
