CREATE TABLE PS_D_ETHNICITY
(
  ETHNICITY_SID       INTEGER,
  PERSON_SID          INTEGER,
  ETHNIC_GRP_SID      NUMBER(10),
  EMPLID              VARCHAR2(11 CHAR),
  ETHNIC_GRP_CD       VARCHAR2(8 CHAR),
  REG_REGION          VARCHAR2(5 CHAR),
  SRC_SYS_ID          VARCHAR2(5 CHAR),
  SRC_SETID           VARCHAR2(5 CHAR),
  SETID               VARCHAR2(5 CHAR),
  PRIMARY_FLAG        VARCHAR2(1 CHAR),
  IPEDS_FLG           VARCHAR2(1 CHAR),
  HISP_LATINO_FLG     VARCHAR2(1 CHAR),
  ETHNIC_PCT_NUMRATR  INTEGER,
  ETHNIC_PCT_DENMRTR  INTEGER,
  LASTUPDDTTM         DATE,
  LASTUPDOPRID        VARCHAR2(30 CHAR),
  EFF_START_DT        DATE,
  EFF_END_DT          DATE,
  CURRENT_IND         VARCHAR2(1 CHAR),
  LOAD_ERROR          VARCHAR2(1 CHAR),
  DATA_ORIGIN         VARCHAR2(1 CHAR),
  CREATED_EW_DTTM     DATE,
  LASTUPD_EW_DTTM     DATE,
  BATCH_SID           NUMBER(10)
)
NOLOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
