DROP TABLE CSMRT_OWNER.UM_D_CRSE_COMP CASCADE CONSTRAINTS
/

--
-- UM_D_CRSE_COMP  (Table) 
--
CREATE TABLE CSMRT_OWNER.UM_D_CRSE_COMP
(
  CRSE_COMP_SID          INTEGER                NOT NULL,
  CRSE_CD                VARCHAR2(6 BYTE)       NOT NULL,
  CRSE_OFFER_NUM         INTEGER                NOT NULL,
  SSR_COMP_CD            VARCHAR2(3 BYTE)       NOT NULL,
  SRC_SYS_ID             VARCHAR2(5 BYTE)       NOT NULL,
  EFFDT                  DATE,
  CRSE_SID               INTEGER                NOT NULL,
  SSR_COMP_SID           INTEGER                NOT NULL,
  AUTO_CREATE_CMPNT_FLG  VARCHAR2(1 BYTE)       NOT NULL,
  CONTACT_HOURS          NUMBER(7,3)            NOT NULL,
  DEFAULT_SECT_SIZE      INTEGER                NOT NULL,
  FINAL_EXAM             VARCHAR2(2 BYTE)       NOT NULL,
  GRADED_COMP_FLG        VARCHAR2(1 BYTE)       NOT NULL,
  WEEK_WORKLOAD_HRS      NUMBER(5,2)            NOT NULL,
  DATA_ORIGIN            VARCHAR2(1 BYTE)       NOT NULL,
  CREATED_EW_DTTM        DATE,
  LASTUPD_EW_DTTM        DATE
)
COMPRESS BASIC
/


ALTER TABLE CSMRT_OWNER.UM_D_CRSE_COMP ADD (
  CONSTRAINT PK_UM_D_CRSE_COMP
  PRIMARY KEY
  (CRSE_COMP_SID)
  RELY
  DISABLE NOVALIDATE)
/
