DROP TABLE CSMRT_OWNER.UM_D_VISA_PERMIT CASCADE CONSTRAINTS
/

--
-- UM_D_VISA_PERMIT  (Table) 
--
CREATE TABLE CSMRT_OWNER.UM_D_VISA_PERMIT
(
  VISA_PERMIT_SID       INTEGER                 NOT NULL,
  COUNTRY               VARCHAR2(3 BYTE)        NOT NULL,
  VISA_PERMIT_TYPE      VARCHAR2(3 BYTE)        NOT NULL,
  SRC_SYS_ID            VARCHAR2(5 BYTE)        NOT NULL,
  EFFDT                 DATE,
  EFF_STATUS            VARCHAR2(1 BYTE)        NOT NULL,
  DESCRSHORT            VARCHAR2(10 BYTE)       NOT NULL,
  DESCR                 VARCHAR2(30 BYTE)       NOT NULL,
  VISA_PERMIT_CLASS     VARCHAR2(1 BYTE)        NOT NULL,
  VISA_PERMIT_CLASS_SD  VARCHAR2(10 BYTE)       NOT NULL,
  VISA_PERMIT_CLASS_LD  VARCHAR2(30 BYTE)       NOT NULL,
  COMMENTS              VARCHAR2(4000 BYTE),
  DATA_ORIGIN           VARCHAR2(1 BYTE)        NOT NULL,
  CREATED_EW_DTTM       DATE,
  LASTUPD_EW_DTTM       DATE
)
COMPRESS BASIC
/


ALTER TABLE CSMRT_OWNER.UM_D_VISA_PERMIT ADD (
  CONSTRAINT PK_UM_D_VISA_PERMIT
  PRIMARY KEY
  (VISA_PERMIT_SID)
  RELY
  DISABLE NOVALIDATE)
/
