DROP TABLE CSMRT_OWNER.UM_D_PERSON_ACCOM CASCADE CONSTRAINTS
/

--
-- UM_D_PERSON_ACCOM  (Table) 
--
CREATE TABLE CSMRT_OWNER.UM_D_PERSON_ACCOM
(
  PERSON_SID             INTEGER                NOT NULL,
  EMPLID                 VARCHAR2(11 BYTE)      NOT NULL,
  EMPL_RCD               INTEGER                NOT NULL,
  ACCOMMODATION_ID       INTEGER                NOT NULL,
  ACCOMMODATION_OPT      INTEGER                NOT NULL,
  SRC_SYS_ID             VARCHAR2(5 BYTE)       NOT NULL,
  INSTITUTION_CD         VARCHAR2(5 BYTE)       NOT NULL,
  PERSON_RESP_SID        INTEGER                NOT NULL,
  DT_REQUESTED           DATE,
  REQUEST_STATUS         VARCHAR2(1 BYTE),
  REQUEST_STATUS_SD      VARCHAR2(10 BYTE),
  REQUEST_STATUS_LD      VARCHAR2(30 BYTE),
  REQ_STATUS_DT          DATE,
  ACCOMMODATION_TYPE     VARCHAR2(6 BYTE),
  ACCOMMODATION_TYPE_SD  VARCHAR2(10 BYTE),
  ACCOMMODATION_TYPE_LD  VARCHAR2(30 BYTE),
  ACCOM_STATUS           VARCHAR2(1 BYTE),
  ACCOM_STATUS_SD        VARCHAR2(10 BYTE),
  ACCOM_STATUS_LD        VARCHAR2(30 BYTE),
  ACCOM_STATUS_DT        DATE,
  REQ_COMMENTS           VARCHAR2(4000 BYTE),
  ACCOM_DESCRLONG        VARCHAR2(4000 BYTE),
  LOAD_ERROR             VARCHAR2(1 BYTE),
  DATA_ORIGIN            VARCHAR2(1 BYTE),
  CREATED_EW_DTTM        DATE,
  LASTUPD_EW_DTTM        DATE,
  BATCH_SID              NUMBER(10)
)
COMPRESS BASIC
/
