DROP TABLE CSMRT_OWNER.PS_D_TERM CASCADE CONSTRAINTS
/

--
-- PS_D_TERM  (Table) 
--
CREATE TABLE CSMRT_OWNER.PS_D_TERM
(
  TERM_SID           INTEGER                    NOT NULL,
  INSTITUTION_CD     VARCHAR2(5 CHAR)           NOT NULL,
  ACAD_CAR_CD        VARCHAR2(4 CHAR)           NOT NULL,
  TERM_CD            VARCHAR2(4 CHAR)           NOT NULL,
  SRC_SYS_ID         VARCHAR2(5 CHAR)           NOT NULL,
  TERM_SD            VARCHAR2(10 CHAR)          NOT NULL,
  TERM_LD            VARCHAR2(30 CHAR)          NOT NULL,
  TERM_CD_DESC       VARCHAR2(50 CHAR)          NOT NULL,
  INSTITUTION_SID    INTEGER                    NOT NULL,
  ACAD_CAR_SID       INTEGER                    NOT NULL,
  ACAD_YR_SID        INTEGER                    NOT NULL,
  TERM_BEGIN_DT      DATE,
  TERM_END_DT        DATE,
  EFF_START_DT       DATE,
  EFF_END_DT         DATE,
  CURRENT_TERM_FLG   VARCHAR2(1 CHAR),
  AID_YEAR           VARCHAR2(4 CHAR),
  INSTRCTN_WEEK_NUM  INTEGER,
  SIXTY_PCT_DT       DATE,
  PREV_TERM          VARCHAR2(4 CHAR),
  PREV_TERM_2        VARCHAR2(4 CHAR),
  NEXT_TERM          VARCHAR2(4 CHAR),
  NEXT_TERM_2        VARCHAR2(4 CHAR),
  PREV_FALL          VARCHAR2(4 CHAR),
  PREV_WINTER        VARCHAR2(4 CHAR),
  PREV_SPRING        VARCHAR2(4 CHAR),
  PREV_SUMMER        VARCHAR2(4 CHAR),
  PREV_SUMMER_2      VARCHAR2(4 CHAR),
  NEXT_FALL          VARCHAR2(4 CHAR),
  NEXT_WINTER        VARCHAR2(4 CHAR),
  NEXT_SPRING        VARCHAR2(4 CHAR),
  NEXT_SUMMER        VARCHAR2(4 CHAR),
  NEXT_SUMMER_2      VARCHAR2(4 CHAR),
  DATA_ORIGIN        VARCHAR2(1 CHAR)           NOT NULL,
  CREATED_EW_DTTM    DATE,
  LASTUPD_EW_DTTM    DATE
)
NOCOMPRESS
/


ALTER TABLE CSMRT_OWNER.PS_D_TERM ADD (
  CONSTRAINT PK_PS_D_TERM
  PRIMARY KEY
  (TERM_SID)
  RELY
  DISABLE NOVALIDATE)
/
