DROP TABLE CSMRT_OWNER.UM_F_FA_STDNT_BDGT CASCADE CONSTRAINTS
/

--
-- UM_F_FA_STDNT_BDGT  (Table) 
--
CREATE TABLE CSMRT_OWNER.UM_F_FA_STDNT_BDGT
(
  INSTITUTION_CD         VARCHAR2(5 BYTE)       NOT NULL,
  ACAD_CAR_CD            VARCHAR2(4 BYTE)       NOT NULL,
  AID_YEAR               VARCHAR2(4 BYTE)       NOT NULL,
  TERM_CD                VARCHAR2(4 BYTE)       NOT NULL,
  PERSON_ID              VARCHAR2(11 BYTE)      NOT NULL,
  SRC_SYS_ID             VARCHAR2(5 BYTE)       NOT NULL,
  EFFDT                  DATE,
  EFFSEQ                 INTEGER,
  INSTITUTION_SID        INTEGER                NOT NULL,
  ACAD_CAR_SID           INTEGER                NOT NULL,
  TERM_SID               INTEGER                NOT NULL,
  PERSON_SID             INTEGER                NOT NULL,
  ACAD_PROG_SID          INTEGER                NOT NULL,
  ACAD_PLAN_SID          INTEGER                NOT NULL,
  ACAD_SPLAN_SID         INTEGER                NOT NULL,
  FIN_AID_FED_RES_SID    INTEGER                NOT NULL,
  FIN_AID_ST_RES_SID     INTEGER                NOT NULL,
  FIN_AID_FED_EXCPT_SID  INTEGER                NOT NULL,
  FIN_AID_ST_EXCPT_SID   INTEGER                NOT NULL,
  RESIDENCY_SID          INTEGER                NOT NULL,
  ACAD_LEVEL_BOT         VARCHAR2(3 BYTE),
  ACAD_LEVEL_BOT_LD      VARCHAR2(30 BYTE),
  ACAD_LEVEL_PROJ        VARCHAR2(3 BYTE),
  ACAD_LEVEL_PROJ_LD     VARCHAR2(30 BYTE),
  ACADEMIC_LOAD          VARCHAR2(1 BYTE),
  ACADEMIC_LOAD_LD       VARCHAR2(30 BYTE),
  ACAD_LOAD_APPR         VARCHAR2(1 BYTE),
  ACAD_PROG_PRIMARY      VARCHAR2(5 BYTE),
  ACAD_PLAN              VARCHAR2(10 BYTE),
  ACAD_SUB_PLAN          VARCHAR2(10 BYTE),
  ACAD_PLAN_TYPE         VARCHAR2(3 BYTE),
  AWARD_PERIOD           VARCHAR2(1 BYTE),
  BUDGET_GROUP_CODE      VARCHAR2(6 BYTE),
  BUDGET_GROUP_CODE_LD   VARCHAR2(30 BYTE),
  DEPNDNCY_STAT          VARCHAR2(1 BYTE),
  DEPNDNCY_STAT_LD       VARCHAR2(30 BYTE),
  DESCRSHORT             VARCHAR2(10 BYTE),
  FA_LOAD                VARCHAR2(1 BYTE),
  FA_LOAD_LD             VARCHAR2(30 BYTE),
  FA_LOAD_CURRENT        VARCHAR2(1 BYTE),
  FA_TERM_EFFDT          DATE,
  FA_TERM_EFFSEQ         INTEGER,
  FA_TERM_WEEKS          NUMBER(3,1),
  FA_UNIT_ANTIC          NUMBER(8,3),
  FA_UNIT_COMPLETED      NUMBER(8,3),
  FA_UNIT_IN_PROG        NUMBER(8,3),
  FA_UNIT_CURRENT        NUMBER(8,3),
  FIN_AID_FED_RES        VARCHAR2(5 BYTE),
  FIN_AID_ST_RES         VARCHAR2(5 BYTE),
  FIN_AID_FED_EXCPT      VARCHAR2(5 BYTE),
  FIN_AID_ST_EXCPT       VARCHAR2(5 BYTE),
  FORM_OF_STUDY          VARCHAR2(4 BYTE),
  FORM_OF_STUDY_LD       VARCHAR2(30 BYTE),
  HOUSING_TYPE           VARCHAR2(1 BYTE),
  HOUSING_TYPE_LD        VARCHAR2(30 BYTE),
  MARITAL_STAT           VARCHAR2(1 BYTE),
  MARITAL_STAT_LD        VARCHAR2(30 BYTE),
  NSLDS_LOAN_YEAR        VARCHAR2(1 BYTE),
  NSLDS_LOAN_YEAR_LD     VARCHAR2(30 BYTE),
  NUMBER_IN_FAMILY       VARCHAR2(2 BYTE),
  OPRID                  VARCHAR2(30 BYTE),
  POSTAL                 VARCHAR2(12 BYTE),
  PRORATE_BUDGET         VARCHAR2(1 BYTE),
  RESIDENCY              VARCHAR2(5 BYTE),
  STATE_RESIDENCE        VARCHAR2(6 BYTE),
  APP_STATE_RESIDENC     VARCHAR2(2 BYTE),
  TERM_BEGIN_DT          DATE,
  TERM_END_DT            DATE,
  TERM_BUDGET_FLAG       VARCHAR2(1 BYTE),
  TERM_TYPE              VARCHAR2(1 BYTE),
  TERM_TYPE_LD           VARCHAR2(30 BYTE),
  FED_TERM_COA           NUMBER(8,2),
  INST_TERM_COA          NUMBER(8,2),
  PELL_TERM_COA          NUMBER(8,2),
  SFA_PELTRM_COA_LHT     NUMBER(8,2),
  LOAD_ERROR             VARCHAR2(1 BYTE),
  DATA_ORIGIN            VARCHAR2(1 BYTE),
  CREATED_EW_DTTM        DATE,
  LASTUPD_EW_DTTM        DATE,
  BATCH_SID              INTEGER
)
COMPRESS BASIC
/


ALTER TABLE CSMRT_OWNER.UM_F_FA_STDNT_BDGT ADD (
  CONSTRAINT PK_UM_F_FA_STDNT_BDGT
  PRIMARY KEY
  (INSTITUTION_CD, ACAD_CAR_CD, AID_YEAR, TERM_CD, PERSON_ID, SRC_SYS_ID)
  RELY
  ENABLE VALIDATE)
/
