DROP TABLE CSMRT_OWNER.PS_D_APPL_MTHD CASCADE CONSTRAINTS
/

--
-- PS_D_APPL_MTHD  (Table) 
--
CREATE TABLE CSMRT_OWNER.PS_D_APPL_MTHD
(
  APPL_MTHD_SID    INTEGER                      NOT NULL,
  APPL_MTHD_ID     VARCHAR2(4 CHAR)             NOT NULL,
  SRC_SYS_ID       VARCHAR2(5 CHAR)             NOT NULL,
  APPL_MTHD_SD     VARCHAR2(10 CHAR)            NOT NULL,
  APPL_MTHD_LD     VARCHAR2(30 CHAR)            NOT NULL,
  DATA_ORIGIN      VARCHAR2(1 CHAR)             NOT NULL,
  CREATED_EW_DTTM  DATE,
  LASTUPD_EW_DTTM  DATE
)
COMPRESS BASIC
/


ALTER TABLE CSMRT_OWNER.PS_D_APPL_MTHD ADD (
  CONSTRAINT PK_PS_D_APPL_MTHD
  PRIMARY KEY
  (APPL_MTHD_SID)
  RELY
  DISABLE NOVALIDATE)
/
