DROP TABLE CSMRT_OWNER.UM_M_AF_STDNT_CLASS_ENRL CASCADE CONSTRAINTS
/

--
-- UM_M_AF_STDNT_CLASS_ENRL  (Table) 
--
CREATE TABLE CSMRT_OWNER.UM_M_AF_STDNT_CLASS_ENRL
(
  INSTITUTION_CD      VARCHAR2(5 BYTE),
  TERM_CD             VARCHAR2(4 BYTE),
  TERM_LD             VARCHAR2(50 BYTE),
  FISCAL_YEAR         VARCHAR2(4 BYTE),
  PERSON_ID           VARCHAR2(15 BYTE),
  ACAD_CAR_CD         VARCHAR2(5 BYTE),
  ACAD_CAR_LD         VARCHAR2(30 BYTE),
  RSDNCY_LD           VARCHAR2(50 BYTE),
  RSDNCY_ID           VARCHAR2(5 BYTE),
  TOT_CREDITS         NUMBER,
  DAY_CREDITS         NUMBER,
  CE_CREDITS          NUMBER,
  ONLINE_CREDITS      NUMBER,
  DAY_ONLINE_CREDITS  NUMBER,
  CE_ONLINE_CREDITS   NUMBER,
  TOT_FTE             NUMBER,
  DAY_FTE             NUMBER,
  CE_FTE              NUMBER,
  TOT_FFTE            NUMBER,
  DAY_FFTE            NUMBER,
  CE_FFTE             NUMBER,
  ACAD_PROG_CD        VARCHAR2(5 BYTE),
  ACAD_PROG_LD        VARCHAR2(50 BYTE),
  PROG_GRP_CD         VARCHAR2(30 BYTE),
  PROG_GRP_LD         VARCHAR2(30 BYTE),
  PROG_ORG_CD         VARCHAR2(10 BYTE),
  PROG_ORG_LD         VARCHAR2(50 BYTE),
  ACAD_PLAN_CD        VARCHAR2(10 BYTE),
  ACAD_PLAN_LD        VARCHAR2(50 BYTE),
  PLAN_ORG_CD         VARCHAR2(30 BYTE),
  PLAN_ORG_LD         VARCHAR2(30 BYTE),
  PLAN_PERCENT_OWNED  NUMBER,
  DEGREE_SEEKING_FLG  VARCHAR2(5 BYTE),
  TAKEN_UNIT          NUMBER,
  CLASS_FFTE          NUMBER,
  CLASS_NUM           INTEGER,
  CRSE_CD             VARCHAR2(10 BYTE),
  SBJCT_CD            VARCHAR2(10 BYTE),
  SBJCT_LD            VARCHAR2(50 BYTE),
  CATALOG_NBR         VARCHAR2(50 BYTE),
  CLASS_TITLE         VARCHAR2(50 BYTE),
  CLASS_CAREER_CD     VARCHAR2(4 BYTE),
  CLASS_CAREER_LD     VARCHAR2(50 BYTE),
  CLASS_GRP_CD        VARCHAR2(30 BYTE),
  CLASS_GRP_LD        VARCHAR2(30 BYTE),
  CLASS_ORG_CD        VARCHAR2(50 BYTE),
  CLASS_ORG_LD        VARCHAR2(50 BYTE),
  INSTRCTN_MODE_CD    VARCHAR2(2 BYTE),
  INSTRCTN_MODE_LD    VARCHAR2(50 BYTE),
  CRSE_LVL            VARCHAR2(30 BYTE),
  ROW_NUM             NUMBER,
  INSERT_TIME         DATE
)
COMPRESS BASIC
/
