CREATE TABLE UM_D_EMPLOYEE_HIST
(
  PERSON_SID       INTEGER,
  PERSON_ID        VARCHAR2(11 BYTE),
  EMPL_RCD         INTEGER,
  EFF_START_DT     DATE,
  EFFSEQ           INTEGER,
  SRC_SYS_ID       VARCHAR2(5 BYTE),
  HR_EMPLID        VARCHAR2(11 BYTE),
  EFF_END_DT       DATE,
  CURRENT_IND      VARCHAR2(1 CHAR),
  INSTITUTION_CD   VARCHAR2(5 CHAR),
  EMPL_STAT_CD     VARCHAR2(1 CHAR),
  EMPL_STAT_LD     VARCHAR2(30 CHAR),
  EMPL_TYPE_CD     VARCHAR2(1 CHAR),
  EMPL_TYPE_LD     VARCHAR2(30 CHAR),
  FULL_PT_CD       VARCHAR2(1 CHAR),
  FULL_PT_LD       VARCHAR2(30 CHAR),
  HR_STAT_CD       VARCHAR2(1 CHAR),
  HR_STAT_LD       VARCHAR2(30 CHAR),
  JOBCODE_ID       VARCHAR2(15 CHAR),
  JOBCODE_LD       VARCHAR2(50 CHAR),
  REG_TEMP_CD      VARCHAR2(1 CHAR),
  REG_TEMP_LD      VARCHAR2(30 CHAR),
  LOAD_ERROR       VARCHAR2(1 BYTE),
  DATA_ORIGIN      VARCHAR2(1 BYTE),
  CREATED_EW_DTTM  DATE,
  LASTUPD_EW_DTTM  DATE,
  BATCH_SID        INTEGER
)
NOLOGGING 
COMPRESS BASIC
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
