DROP TABLE CSMRT_OWNER.UM_D_PRSPCT_PROG CASCADE CONSTRAINTS
/

--
-- UM_D_PRSPCT_PROG  (Table) 
--
CREATE TABLE CSMRT_OWNER.UM_D_PRSPCT_PROG
(
  PRSPCT_PROG_SID    NUMBER(10)                 NOT NULL,
  INSTITUTION_CD     VARCHAR2(5 BYTE)           NOT NULL,
  ACAD_CAR_CD        VARCHAR2(4 BYTE)           NOT NULL,
  ADMIT_TERM         VARCHAR2(4 BYTE)           NOT NULL,
  EMPLID             VARCHAR2(11 BYTE)          NOT NULL,
  ACAD_PROG_CD       VARCHAR2(5 BYTE)           NOT NULL,
  SRC_SYS_ID         VARCHAR2(5 BYTE)           NOT NULL,
  ACAD_PROG_SID      NUMBER(10)                 NOT NULL,
  ADM_APPL_NBR       VARCHAR2(8 BYTE)           NOT NULL,
  ADM_RECR_CTR       VARCHAR2(4 BYTE)           NOT NULL,
  CAMPUS_SID         NUMBER(10)                 NOT NULL,
  PRSPCT_CAR_SID     NUMBER(10)                 NOT NULL,
  RECRT_CNTR_SID     NUMBER(10)                 NOT NULL,
  RECRT_STAT_SID     NUMBER(10)                 NOT NULL,
  RECRT_STAT_DT_SID  NUMBER(10),
  LOAD_ERROR         VARCHAR2(1 BYTE)           NOT NULL,
  DATA_ORIGIN        VARCHAR2(1 BYTE)           NOT NULL,
  CREATED_EW_DTTM    DATE,
  LASTUPD_EW_DTTM    DATE,
  BATCH_SID          NUMBER(10)                 NOT NULL
)
NOCOMPRESS
/


ALTER TABLE CSMRT_OWNER.UM_D_PRSPCT_PROG ADD (
  CONSTRAINT PK_UM_D_PRSPCT_PROG
  PRIMARY KEY
  (PRSPCT_PROG_SID)
  RELY
  DISABLE NOVALIDATE)
/
