DROP TABLE CSMRT_OWNER.UM_D_PERSON_NAME CASCADE CONSTRAINTS
/

--
-- UM_D_PERSON_NAME  (Table) 
--
CREATE TABLE CSMRT_OWNER.UM_D_PERSON_NAME
(
  PERSON_ID         VARCHAR2(11 BYTE)           NOT NULL,
  NAME_TYPE         VARCHAR2(4 BYTE)            NOT NULL,
  SRC_SYS_ID        VARCHAR2(5 BYTE)            NOT NULL,
  EFFDT             DATE,
  EFF_STATUS        VARCHAR2(1 BYTE)            NOT NULL,
  PERSON_SID        INTEGER                     NOT NULL,
  NAME              VARCHAR2(50 BYTE),
  NAME_INITIALS     VARCHAR2(6 BYTE),
  NAME_PREFIX       VARCHAR2(4 BYTE),
  NAME_SUFFIX       VARCHAR2(15 BYTE),
  NAME_TITLE        VARCHAR2(30 BYTE),
  LAST_NAME_SRCH    VARCHAR2(30 BYTE),
  FIRST_NAME_SRCH   VARCHAR2(30 BYTE),
  LAST_NAME         VARCHAR2(30 BYTE),
  FIRST_NAME        VARCHAR2(30 BYTE),
  MIDDLE_NAME       VARCHAR2(30 BYTE),
  PREF_FIRST_NAME   VARCHAR2(30 BYTE),
  NAME_DISPLAY      VARCHAR2(50 BYTE),
  NAME_FORMAL       VARCHAR2(60 BYTE),
  LAST_NAME_FORMER  VARCHAR2(30 BYTE),
  NAME_FORMER       VARCHAR2(50 BYTE),
  LASTUPDDTTM       DATE,
  LASTUPDOPRID      VARCHAR2(30 BYTE),
  NAME_ORDER        INTEGER                     NOT NULL,
  AKA_ORDER         INTEGER                     NOT NULL,
  CPS_ORDER         INTEGER                     NOT NULL,
  DEG_ORDER         INTEGER                     NOT NULL,
  PRF_ORDER         INTEGER                     NOT NULL,
  PRI_ORDER         INTEGER                     NOT NULL,
  DATA_ORIGIN       VARCHAR2(1 BYTE)            NOT NULL,
  CREATED_EW_DTTM   DATE,
  LASTUPD_EW_DTTM   DATE
)
COMPRESS BASIC
/


ALTER TABLE CSMRT_OWNER.UM_D_PERSON_NAME ADD (
  CONSTRAINT PK_UM_D_PERSON_NAME
  PRIMARY KEY
  (PERSON_ID, NAME_TYPE, SRC_SYS_ID)
  RELY
  ENABLE VALIDATE)
/
