CREATE TABLE UM_F_FA_AWARD_DISB
(
  INSTITUTION_CD      VARCHAR2(5 BYTE),
  ACAD_CAR_CD         VARCHAR2(4 BYTE),
  AID_YEAR            VARCHAR2(4 BYTE),
  TERM_CD             VARCHAR2(4 BYTE),
  PERSON_ID           VARCHAR2(11 BYTE),
  ITEM_TYPE           VARCHAR2(12 BYTE),
  SRC_SYS_ID          VARCHAR2(5 BYTE),
  INSTITUTION_SID     INTEGER,
  ACAD_CAR_SID        INTEGER,
  TERM_SID            INTEGER,
  PERSON_SID          INTEGER,
  ITEM_TYPE_SID       INTEGER,
  OFFER_BALANCE       NUMBER(11,2),
  ACCEPT_BALANCE      NUMBER(11,2),
  AUTHORIZED_BALANCE  NUMBER(11,2),
  DISBURSED_BALANCE   NUMBER(11,2),
  NET_DISB_BALANCE    NUMBER(11,2),
  NET_AWARD_AMT_SF    NUMBER(11,2),
  LOAD_ERROR          VARCHAR2(1 BYTE),
  DATA_ORIGIN         VARCHAR2(1 BYTE),
  CREATED_EW_DTTM     DATE,
  LASTUPD_EW_DTTM     DATE,
  BATCH_SID           INTEGER
)
NOLOGGING 
COMPRESS BASIC
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
