DROP TABLE CSMRT_OWNER.UM_F_PRSPCT_RFRL CASCADE CONSTRAINTS
/

--
-- UM_F_PRSPCT_RFRL  (Table) 
--
CREATE TABLE CSMRT_OWNER.UM_F_PRSPCT_RFRL
(
  INSTITUTION_CD   VARCHAR2(5 BYTE)             NOT NULL,
  ACAD_CAR_CD      VARCHAR2(4 BYTE)             NOT NULL,
  ADMIT_TERM       VARCHAR2(4 BYTE)             NOT NULL,
  EMPLID           VARCHAR2(11 BYTE)            NOT NULL,
  RFRL_GRP         VARCHAR2(4 BYTE)             NOT NULL,
  RFRL_DTL         VARCHAR2(4 BYTE)             NOT NULL,
  RFRL_DT          DATE,
  UM_ADM_REC_NBR   VARCHAR2(15 BYTE)            NOT NULL,
  SRC_SYS_ID       VARCHAR2(5 BYTE)             NOT NULL,
  INSTITUTION_SID  INTEGER                      NOT NULL,
  ACAD_CAR_SID     INTEGER                      NOT NULL,
  ADMIT_TERM_SID   INTEGER                      NOT NULL,
  PERSON_SID       INTEGER                      NOT NULL,
  PRSPCT_CAR_SID   NUMBER(10)                   NOT NULL,
  RECRT_CNTR_SID   NUMBER(10)                   NOT NULL,
  RFRL_DTL_SID     NUMBER(10)                   NOT NULL,
  ADM_RECR_CTR     VARCHAR2(4 BYTE)             NOT NULL,
  LOAD_ERROR       VARCHAR2(1 BYTE)             NOT NULL,
  DATA_ORIGIN      VARCHAR2(1 BYTE)             NOT NULL,
  CREATED_EW_DTTM  DATE,
  LASTUPD_EW_DTTM  DATE,
  BATCH_SID        NUMBER(10)                   NOT NULL
)
COMPRESS BASIC
/


ALTER TABLE CSMRT_OWNER.UM_F_PRSPCT_RFRL ADD (
  CONSTRAINT PK_UM_F_PRSPCT_RFRL
  PRIMARY KEY
  (INSTITUTION_CD, ACAD_CAR_CD, ADMIT_TERM, EMPLID, RFRL_GRP, RFRL_DTL, RFRL_DT, UM_ADM_REC_NBR, SRC_SYS_ID)
  RELY
  ENABLE VALIDATE)
/
