CREATE TABLE UM_F_EXT_TESTSCORE
(
  PERSON_SID          INTEGER,
  EXT_TST_CMPNT_SID   INTEGER,
  EXT_TST_DT          DATE,
  TST_DATA_SRC_SID    INTEGER,
  SRC_SYS_ID          VARCHAR2(5 BYTE),
  PERSON_ID           VARCHAR2(11 BYTE),
  TEST_ID             VARCHAR2(11 BYTE),
  TEST_CMPNT_ID       VARCHAR2(5 BYTE),
  TEST_DATA_SRC_ID    VARCHAR2(4 BYTE),
  EXT_ACAD_LVL_SID    INTEGER,
  NUMERIC_SCORE       NUMBER(6,2),
  LETTER_SCORE        VARCHAR2(4 BYTE),
  SCORE_PERCENTILE    INTEGER,
  LOAD_DT             DATE,
  TEST_ADMIN          VARCHAR2(1 BYTE),
  TEST_INDEX          NUMBER(6,1),
  MAX_SCORE           NUMBER(6,2),
  MIN_SCORE           NUMBER(6,2),
  TEST_CMPNT_ORDER    INTEGER,
  TEST_DT_ORDER       INTEGER,
  TEST_SUM_ORDER      INTEGER,
  TEST_SOURCE_ORDER   INTEGER,
  BEST_SCORE_FLG      VARCHAR2(1 BYTE),
  HIGHEST_SCORE_FLG   VARCHAR2(1 BYTE),
  LATEST_TEST_DT_FLG  VARCHAR2(1 BYTE),
  CONV_FLG            VARCHAR2(1 BYTE)
)
NOLOGGING 
COMPRESS BASIC
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
