DROP TABLE CSMRT_OWNER.UM_F_HOUSING CASCADE CONSTRAINTS
/

--
-- UM_F_HOUSING  (Table) 
--
CREATE TABLE CSMRT_OWNER.UM_F_HOUSING
(
  INSTITUTION_CD   VARCHAR2(5 BYTE)             NOT NULL,
  PERSON_ID        VARCHAR2(11 BYTE)            NOT NULL,
  ACAD_YEAR_LD     VARCHAR2(254 BYTE)           NOT NULL,
  HOUSING_TERM_CD  VARCHAR2(4 BYTE)             NOT NULL,
  SRC_SYS_ID       VARCHAR2(5 BYTE)             NOT NULL,
  INSTITUTION_SID  INTEGER                      NOT NULL,
  TERM_SID         INTEGER                      NOT NULL,
  PERSON_SID       INTEGER                      NOT NULL,
  APPLIED_DT       DATE,
  COMPLETED_DT     DATE,
  AGREEMENT_DT     DATE,
  HOUSING_TERM_LD  VARCHAR2(254 BYTE),
  HOUSING_LOAD_DT  DATE,
  DATA_ORIGIN      VARCHAR2(1 BYTE),
  CREATED_EW_DTTM  DATE,
  LASTUPD_EW_DTTM  DATE
)
COMPRESS BASIC
/


ALTER TABLE CSMRT_OWNER.UM_F_HOUSING ADD (
  CONSTRAINT PK_UM_F_HOUSING
  PRIMARY KEY
  (INSTITUTION_CD, PERSON_ID, ACAD_YEAR_LD, HOUSING_TERM_CD, SRC_SYS_ID)
  RELY
  ENABLE VALIDATE)
/
