DROP TABLE CSMRT_OWNER.PS_D_EXT_ACAD_CAR CASCADE CONSTRAINTS
/

--
-- PS_D_EXT_ACAD_CAR  (Table) 
--
CREATE TABLE CSMRT_OWNER.PS_D_EXT_ACAD_CAR
(
  EXT_ACAD_CAR_SID  INTEGER                     NOT NULL,
  EXT_ACAD_CAR_ID   VARCHAR2(4 CHAR)            NOT NULL,
  SRC_SYS_ID        VARCHAR2(5 CHAR)            NOT NULL,
  EXT_ACAD_CAR_SD   VARCHAR2(10 CHAR)           NOT NULL,
  EXT_ACAD_CAR_LD   VARCHAR2(30 CHAR)           NOT NULL,
  DATA_ORIGIN       VARCHAR2(1 CHAR)            NOT NULL,
  CREATED_EW_DTTM   DATE,
  LASTUPD_EW_DTTM   DATE
)
COMPRESS BASIC
/


ALTER TABLE CSMRT_OWNER.PS_D_EXT_ACAD_CAR ADD (
  CONSTRAINT PK_PS_D_EXT_ACAD_CAR
  PRIMARY KEY
  (EXT_ACAD_CAR_SID)
  RELY
  DISABLE NOVALIDATE)
/
