DROP TABLE CSMRT_OWNER.UM_M_AF_STDNT_SF_DETAIL CASCADE CONSTRAINTS
/

--
-- UM_M_AF_STDNT_SF_DETAIL  (Table) 
--
CREATE TABLE CSMRT_OWNER.UM_M_AF_STDNT_SF_DETAIL
(
  INSTITUTION_CD     VARCHAR2(10 BYTE)          NOT NULL,
  ACAD_CAR_CD        VARCHAR2(10 BYTE),
  PERSON_ID          VARCHAR2(25 BYTE)          NOT NULL,
  FISCAL_YEAR        NUMBER(22),
  ITEM_TERM          VARCHAR2(10 BYTE)          NOT NULL,
  ITEM_TERM_LD       VARCHAR2(50 BYTE),
  ITEM_TYPE          VARCHAR2(25 BYTE),
  ITEM_TYPE_LD       VARCHAR2(75 BYTE),
  KEYWORD1           VARCHAR2(25 CHAR),
  KEYWORD2           VARCHAR2(25 CHAR),
  KEYWORD3           VARCHAR2(25 CHAR),
  ITEM_NBR           VARCHAR2(25 BYTE)          NOT NULL,
  ITEM_AMT           NUMBER(16,2),
  RUN_DT             DATE,
  SEQNUM             INTEGER                    NOT NULL,
  SF_LINE_NBR        INTEGER                    NOT NULL,
  JOURNAL_DATE       DATE,
  ACCOUNT            VARCHAR2(20 BYTE)          NOT NULL,
  FUND_CODE          VARCHAR2(10 BYTE)          NOT NULL,
  DEPTID             VARCHAR2(20 BYTE)          NOT NULL,
  MONETARY_AMOUNT    NUMBER(15,2)               NOT NULL,
  LINE_DESCR         VARCHAR2(50 BYTE)          NOT NULL,
  JOURNAL_LINE_DATE  DATE,
  ACCOUNTING_DT      DATE,
  LEDGER             VARCHAR2(20 BYTE)          NOT NULL,
  NEED_BASED         VARCHAR2(5 BYTE),
  FA_SOURCE          VARCHAR2(5 BYTE),
  FA_SOURCE_LD       VARCHAR2(50 BYTE),
  FIN_AID_TYPE       VARCHAR2(10 BYTE),
  FIN_AID_TYPE_LD    VARCHAR2(40 BYTE),
  AGGREGATE_AREA     VARCHAR2(20 BYTE),
  SF_CATEGORY_CALC   VARCHAR2(20 BYTE),
  FA_SOURCE_CALC     VARCHAR2(50 BYTE),
  INSERT_TIME        DATE
)
COMPRESS FOR OLTP
/
