DROP TABLE CSMRT_OWNER.PS_D_ACAD_STNDNG CASCADE CONSTRAINTS
/

--
-- PS_D_ACAD_STNDNG  (Table) 
--
CREATE TABLE CSMRT_OWNER.PS_D_ACAD_STNDNG
(
  ACAD_STNDNG_SID     NUMBER(10)                NOT NULL,
  INSTITUTION_CD      VARCHAR2(5 CHAR)          NOT NULL,
  ACAD_CAR_CD         VARCHAR2(4 CHAR)          NOT NULL,
  ACAD_STNDNG_ACN_CD  VARCHAR2(4 CHAR)          NOT NULL,
  SRC_SYS_ID          VARCHAR2(5 CHAR)          NOT NULL,
  EFFDT               DATE,
  ACAD_STNDNG_ACN_SD  VARCHAR2(10 CHAR)         NOT NULL,
  ACAD_STNDNG_ACN_LD  VARCHAR2(30 CHAR)         NOT NULL,
  ACAD_STNDNG_ACN_FD  VARCHAR2(50 CHAR)         NOT NULL,
  STNDNG_STAT_CD      VARCHAR2(4 CHAR)          NOT NULL,
  STNDNG_STAT_SD      VARCHAR2(10 CHAR)         NOT NULL,
  STNDNG_STAT_LD      VARCHAR2(30 CHAR)         NOT NULL,
  DATA_ORIGIN         VARCHAR2(1 CHAR)          NOT NULL,
  CREATED_EW_DTTM     DATE,
  LASTUPD_EW_DTTM     DATE
)
COMPRESS BASIC
/


ALTER TABLE CSMRT_OWNER.PS_D_ACAD_STNDNG ADD (
  CONSTRAINT PK_PS_D_ACAD_STNDNG
  PRIMARY KEY
  (ACAD_STNDNG_SID)
  RELY
  DISABLE NOVALIDATE)
/
