DROP TABLE CSMRT_OWNER.UM_F_FA_STDNT_ISIR_STG CASCADE CONSTRAINTS
/

--
-- UM_F_FA_STDNT_ISIR_STG  (Table) 
--
CREATE TABLE CSMRT_OWNER.UM_F_FA_STDNT_ISIR_STG
(
  INSTITUTION_CD       VARCHAR2(5 BYTE)         NOT NULL,
  PERSON_ID            VARCHAR2(11 BYTE)        NOT NULL,
  AID_YEAR             VARCHAR2(4 BYTE)         NOT NULL,
  ECQUEUEINSTANCE      INTEGER                  NOT NULL,
  ISIR_SEQ_NO          INTEGER                  NOT NULL,
  SRC_SYS_ID           VARCHAR2(5 BYTE)         NOT NULL,
  INSTITUTION_SID      INTEGER                  NOT NULL,
  PERSON_SID           INTEGER                  NOT NULL,
  ISIR_LOAD_STATUS     VARCHAR2(1 BYTE),
  ISIR_LOAD_STATUS_SD  VARCHAR2(10 BYTE),
  ISIR_LOAD_STATUS_LD  VARCHAR2(30 BYTE),
  ISIR_LOAD_ACTION     VARCHAR2(1 BYTE),
  ISIR_LOAD_ACTION_SD  VARCHAR2(10 BYTE),
  ISIR_LOAD_ACTION_LD  VARCHAR2(30 BYTE),
  ADMIT_LVL            VARCHAR2(1 BYTE),
  ADMIT_LVL_SD         VARCHAR2(10 BYTE),
  ADMIT_LVL_LD         VARCHAR2(30 BYTE),
  ORIG_SSN             VARCHAR2(9 BYTE),
  SSN                  VARCHAR2(9 BYTE),
  IWD_STD_LAST_NAME    VARCHAR2(16 BYTE),
  IWD_STD_FIRST_NM02   VARCHAR2(12 BYTE),
  IWD_STU_MI           VARCHAR2(1 BYTE),
  IWD_PERM_ADDR02      VARCHAR2(35 BYTE),
  IWD_CITY             VARCHAR2(16 BYTE),
  IWD_STATE            VARCHAR2(2 BYTE),
  IWD_ZIP              VARCHAR2(5 BYTE),
  BIRTHDATE            DATE,
  IWD_PERM_PHONE       VARCHAR2(10 BYTE),
  TRANS_RECEIPT_DT     DATE,
  SUSPEND_REASON       VARCHAR2(1 BYTE),
  SUSPEND_REASON_SD    VARCHAR2(10 BYTE),
  SUSPEND_REASON_LD    VARCHAR2(30 BYTE),
  IWD_TRANS_NBR        VARCHAR2(2 BYTE),
  DEPNDNCY_STAT        VARCHAR2(1 BYTE),
  DEPNDNCY_STAT_SD     VARCHAR2(10 BYTE),
  DEPNDNCY_STAT_LD     VARCHAR2(30 BYTE),
  TRANS_PROCESS_DT     DATE,
  IWD_PRIMARY_EFC      VARCHAR2(6 BYTE),
  IWD_STD_EMAIL        VARCHAR2(50 BYTE),
  IWD_SOURCE_CORR      VARCHAR2(1 BYTE),
  IWD_EFC_CHNG_FLAG    VARCHAR2(1 BYTE),
  ISIR_SAR_C_CHNG      VARCHAR2(1 BYTE),
  LOAD_ERROR           VARCHAR2(1 BYTE)         NOT NULL,
  DATA_ORIGIN          VARCHAR2(1 BYTE)         NOT NULL,
  CREATED_EW_DTTM      DATE,
  LASTUPD_EW_DTTM      DATE,
  BATCH_SID            NUMBER(10)               NOT NULL
)
COMPRESS BASIC
/


ALTER TABLE CSMRT_OWNER.UM_F_FA_STDNT_ISIR_STG ADD (
  CONSTRAINT PK_UM_F_FA_STDNT_ISIR_STG
  PRIMARY KEY
  (INSTITUTION_CD, PERSON_ID, AID_YEAR, ECQUEUEINSTANCE, ISIR_SEQ_NO, SRC_SYS_ID)
  RELY
  ENABLE VALIDATE)
/
