DROP TABLE CSMRT_OWNER.UM_F_FA_ISIR_COMMENTS CASCADE CONSTRAINTS
/

--
-- UM_F_FA_ISIR_COMMENTS  (Table) 
--
CREATE TABLE CSMRT_OWNER.UM_F_FA_ISIR_COMMENTS
(
  INSTITUTION_CD    VARCHAR2(5 BYTE)            NOT NULL,
  PERSON_ID         VARCHAR2(11 BYTE)           NOT NULL,
  AID_YEAR          VARCHAR2(4 BYTE)            NOT NULL,
  COMMENT_CODE      VARCHAR2(3 BYTE)            NOT NULL,
  SRC_SYS_ID        VARCHAR2(5 BYTE)            NOT NULL,
  EFFDT             DATE,
  EFFSEQ            INTEGER,
  INSTITUTION_SID   INTEGER                     NOT NULL,
  PERSON_SID        INTEGER                     NOT NULL,
  SFA_DB_MATCH_USE  VARCHAR2(2 BYTE),
  SEVERITY_LVL      VARCHAR2(1 BYTE),
  SEVERITY_LVL_LD   VARCHAR2(30 BYTE),
  DESCRLONG         VARCHAR2(4000 BYTE),
  LOAD_ERROR        VARCHAR2(1 BYTE),
  DATA_ORIGIN       VARCHAR2(1 BYTE),
  CREATED_EW_DTTM   DATE,
  LASTUPD_EW_DTTM   DATE,
  BATCH_SID         INTEGER
)
COMPRESS BASIC
/


ALTER TABLE CSMRT_OWNER.UM_F_FA_ISIR_COMMENTS ADD (
  CONSTRAINT PK_UM_F_FA_ISIR_COMMENTS
  PRIMARY KEY
  (INSTITUTION_CD, PERSON_ID, AID_YEAR, COMMENT_CODE, SRC_SYS_ID)
  RELY
  ENABLE VALIDATE)
/
