DROP TABLE CSMRT_OWNER.UM_A_SRVC_IND CASCADE CONSTRAINTS
/

--
-- UM_A_SRVC_IND  (Table) 
--
CREATE TABLE CSMRT_OWNER.UM_A_SRVC_IND
(
  AUDIT_OPRID         VARCHAR2(30 BYTE)         NOT NULL,
  AUDIT_STAMP         TIMESTAMP(6),
  AUDIT_ACTN          VARCHAR2(1 BYTE)          NOT NULL,
  PERSON_ID           VARCHAR2(11 BYTE)         NOT NULL,
  SRVC_IND_DTTM       TIMESTAMP(6),
  SRC_SYS_ID          VARCHAR2(5 BYTE)          NOT NULL,
  INSTITUTION_CD      VARCHAR2(5 BYTE)          NOT NULL,
  INSTITUTION_SID     INTEGER                   NOT NULL,
  PERSON_SID          INTEGER                   NOT NULL,
  AMOUNT              NUMBER(26,3),
  AUDIT_ACTN_SD       VARCHAR2(10 BYTE),
  AUDIT_ACTN_LD       VARCHAR2(30 BYTE),
  CONTACT             VARCHAR2(30 BYTE),
  CONTACT_ID          VARCHAR2(15 BYTE),
  DEPTID              VARCHAR2(10 BYTE),
  OPRID               VARCHAR2(30 BYTE),
  PLACED_METHOD       VARCHAR2(30 BYTE),
  PLACED_PERSON       VARCHAR2(30 BYTE),
  PLACED_PERSON_ID    VARCHAR2(11 BYTE),
  PLACED_PROCESS      VARCHAR2(8 BYTE),
  POS_SRVC_INDICATOR  VARCHAR2(9 BYTE),
  PROCESS_INSTANCE    NUMBER(10),
  RELEASE_PROCESS     VARCHAR2(8 BYTE),
  SCC_SI_END_TERM     VARCHAR2(4 BYTE),
  SCC_SI_END_DT       DATE,
  SRVC_IND_ACT_TERM   VARCHAR2(4 BYTE),
  SRVC_IND_ACTIVE_DT  DATE,
  SRVC_IND_REFRNCE    VARCHAR2(30 BYTE),
  SRVC_IND_CD         VARCHAR2(3 BYTE)          NOT NULL,
  SRVC_IND_SD         VARCHAR2(10 BYTE)         NOT NULL,
  SRVC_IND_LD         VARCHAR2(30 BYTE)         NOT NULL,
  SRVC_IND_REASON     VARCHAR2(5 BYTE)          NOT NULL,
  SRVC_IND_REASON_SD  VARCHAR2(10 BYTE)         NOT NULL,
  SRVC_IND_REASON_LD  VARCHAR2(30 BYTE)         NOT NULL,
  COMM_COMMENTS       VARCHAR2(4000 BYTE),
  DATA_ORIGIN         VARCHAR2(1 BYTE)          NOT NULL,
  CREATED_EW_DTTM     DATE,
  LASTUPD_EW_DTTM     DATE
)
COMPRESS BASIC
/


ALTER TABLE CSMRT_OWNER.UM_A_SRVC_IND ADD (
  CONSTRAINT PK_UM_A_SRVC_IND
  PRIMARY KEY
  (AUDIT_OPRID, AUDIT_STAMP, AUDIT_ACTN, PERSON_ID, SRVC_IND_DTTM, SRC_SYS_ID)
  RELY
  ENABLE VALIDATE)
/
