DROP TABLE CSMRT_OWNER.CHAINED_PLUS CASCADE CONSTRAINTS
/

--
-- CHAINED_PLUS  (Table) 
--
CREATE TABLE CSMRT_OWNER.CHAINED_PLUS
(
  TABLE_NAME       VARCHAR2(30 BYTE),
  CHAINED_ROWS     NUMBER,
  TABLE_ROW_COUNT  NUMBER
)
COMPRESS FOR OLTP
/
