CREATE TABLE UM_D_CRSE_ATTR_VAL
(
  CRSE_ATTR_VAL_SID   INTEGER,
  CRSE_CD             VARCHAR2(6 BYTE),
  CRSE_OFFER_NUM      INTEGER,
  CRSE_ATTR           VARCHAR2(4 BYTE),
  CRSE_ATTR_VALUE     VARCHAR2(10 BYTE),
  SRC_SYS_ID          VARCHAR2(5 BYTE),
  EFFDT               DATE,
  CRSE_SID            NUMBER(10),
  CRSE_ATTR_SD        VARCHAR2(10 BYTE),
  CRSE_ATTR_LD        VARCHAR2(30 BYTE),
  CRSE_ATTR_VALUE_LD  VARCHAR2(30 BYTE),
  CRSE_ATTR_VALUE_FD  VARCHAR2(50 BYTE),
  CATALOG_PRINT_FLG   VARCHAR2(1 BYTE),
  SCHEDULE_PRINT_FLG  VARCHAR2(1 BYTE),
  DATA_ORIGIN         VARCHAR2(1 BYTE),
  CREATED_EW_DTTM     DATE,
  LASTUPD_EW_DTTM     DATE
)
NOLOGGING 
COMPRESS BASIC
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
