CREATE TABLE UM_F_FA_AWARD_SUMM_BY_YEAR
(
  INSTITUTION_CD         VARCHAR2(5 BYTE),
  PERSON_ID              VARCHAR2(11 BYTE),
  AID_YEAR               VARCHAR2(4 BYTE),
  ACAD_CAR_CD            VARCHAR2(4 BYTE),
  SRC_SYS_ID             VARCHAR2(5 BYTE),
  INSTITUTION_SID        INTEGER,
  PERSON_SID             INTEGER,
  ACAD_CAR_SID           INTEGER,
  FED_NEED               NUMBER(8,2),
  AWARD_AMOUNT           NUMBER(11,2),
  GRANT_AID              NUMBER(11,2),
  GRANT_AID_DECLINED     NUMBER(11,2),
  GRANT_AID_NEED         NUMBER(11,2),
  GRANT_AID_NO_NEED      NUMBER(11,2),
  WORK_AID               NUMBER(11,2),
  WORK_AID_DECLINED      NUMBER(11,2),
  WORK_AID_NEED          NUMBER(11,2),
  WORK_AID_NO_NEED       NUMBER(11,2),
  LOAN_AID               NUMBER(11,2),
  LOAN_AID_DECLINED      NUMBER(11,2),
  LOAN_AID_NEED          NUMBER(11,2),
  LOAN_AID_NO_NEED       NUMBER(11,2),
  TOTAL_PKG_NEED         NUMBER(11,2),
  TOTAL_PKG_NO_NEED      NUMBER(11,2),
  G_FED_AID              NUMBER(11,2),
  G_FED_AID_DECLINED     NUMBER(11,2),
  G_FED_AID_NEED         NUMBER(11,2),
  G_FED_AID_NO_NEED      NUMBER(11,2),
  G_STATE_AID            NUMBER(11,2),
  G_STATE_AID_DECLINED   NUMBER(11,2),
  G_STATE_AID_NEED       NUMBER(11,2),
  G_STATE_AID_NO_NEED    NUMBER(11,2),
  G_INSTIT_AID           NUMBER(11,2),
  G_INSTIT_AID_DECLINED  NUMBER(11,2),
  G_INSTIT_AID_NEED      NUMBER(11,2),
  G_INSTIT_AID_NO_NEED   NUMBER(11,2),
  O_WAIV_AID             NUMBER(11,2),
  O_WAIV_AID_DECLINED    NUMBER(11,2),
  O_WAIV_AID_NEED        NUMBER(11,2),
  O_WAIV_AID_NO_NEED     NUMBER(11,2),
  ATHL_AID               NUMBER(11,2),
  ATHL_AID_DECLINED      NUMBER(11,2),
  ATHL_AID_NEED          NUMBER(11,2),
  ATHL_AID_NO_NEED       NUMBER(11,2),
  G_PRVTE_AID            NUMBER(11,2),
  G_PRVTE_AID_DECLINED   NUMBER(11,2),
  G_PRVTE_AID_NEED       NUMBER(11,2),
  G_PRVTE_AID_NO_NEED    NUMBER(11,2),
  SH_CWP_AID             NUMBER(11,2),
  SH_CWP_AID_DECLINED    NUMBER(11,2),
  SH_CWP_AID_NEED        NUMBER(11,2),
  SH_CWP_AID_NO_NEED     NUMBER(11,2),
  SH_FWS_AID             NUMBER(11,2),
  SH_FWS_AID_DECLINED    NUMBER(11,2),
  SH_FWS_AID_NEED        NUMBER(11,2),
  SH_FWS_AID_NO_NEED     NUMBER(11,2),
  SH_LOAN_AID            NUMBER(11,2),
  SH_LOAN_AID_DECLINED   NUMBER(11,2),
  SH_SLOAN_AID_NEED      NUMBER(11,2),
  SH_SLOAN_AID_NO_NEED   NUMBER(11,2),
  O_PLOAN_AID            NUMBER(11,2),
  O_PLOAN_AID_DECLINED   NUMBER(11,2),
  O_PLOAN_AID_NEED       NUMBER(11,2),
  O_PLOAN_AID_NO_NEED    NUMBER(11,2),
  PARTITION_KEY          VARCHAR2(7 BYTE),
  DATA_ORIGIN            VARCHAR2(1 BYTE),
  CREATED_EW_DTTM        DATE,
  LASTUPD_EW_DTTM        DATE
)
NOCOMPRESS 
NO INMEMORY
PARTITION BY LIST (PARTITION_KEY)
(  
  PARTITION UMB2017 VALUES ('UMB2017')
    READ WRITE
    NO INMEMORY
    NOLOGGING
    NOCOMPRESS ,  
  PARTITION UMD2017 VALUES ('UMD2017')
    READ WRITE
    NO INMEMORY
    NOLOGGING
    NOCOMPRESS ,  
  PARTITION UML2017 VALUES ('UML2017')
    READ WRITE
    NO INMEMORY
    NOLOGGING
    NOCOMPRESS ,  
  PARTITION UMB2018 VALUES ('UMB2018')
    READ WRITE
    NO INMEMORY
    NOLOGGING
    NOCOMPRESS ,  
  PARTITION UMD2018 VALUES ('UMD2018')
    READ WRITE
    NO INMEMORY
    NOLOGGING
    NOCOMPRESS ,  
  PARTITION UML2018 VALUES ('UML2018')
    READ WRITE
    NO INMEMORY
    NOLOGGING
    NOCOMPRESS ,  
  PARTITION UMB2019 VALUES ('UMB2019')
    READ WRITE
    NO INMEMORY
    NOLOGGING
    NOCOMPRESS ,  
  PARTITION UMD2019 VALUES ('UMD2019')
    READ WRITE
    NO INMEMORY
    NOLOGGING
    NOCOMPRESS ,  
  PARTITION UML2019 VALUES ('UML2019')
    READ WRITE
    NO INMEMORY
    NOLOGGING
    NOCOMPRESS ,  
  PARTITION UMB2020 VALUES ('UMB2020')
    READ WRITE
    NO INMEMORY
    NOLOGGING
    NOCOMPRESS ,  
  PARTITION UMD2020 VALUES ('UMD2020')
    READ WRITE
    NO INMEMORY
    NOLOGGING
    NOCOMPRESS ,  
  PARTITION UML2020 VALUES ('UML2020')
    READ WRITE
    NO INMEMORY
    NOLOGGING
    NOCOMPRESS ,  
  PARTITION UMB2021 VALUES ('UMB2021')
    READ WRITE
    NO INMEMORY
    NOLOGGING
    NOCOMPRESS ,  
  PARTITION UMD2021 VALUES ('UMD2021')
    READ WRITE
    NO INMEMORY
    NOLOGGING
    NOCOMPRESS ,  
  PARTITION UML2021 VALUES ('UML2021')
    READ WRITE
    NO INMEMORY
    NOLOGGING
    NOCOMPRESS ,  
  PARTITION UMB2022 VALUES ('UMB2022')
    READ WRITE
    NO INMEMORY
    NOLOGGING
    NOCOMPRESS ,  
  PARTITION UMD2022 VALUES ('UMD2022')
    READ WRITE
    NO INMEMORY
    NOLOGGING
    NOCOMPRESS ,  
  PARTITION UML2022 VALUES ('UML2022')
    READ WRITE
    NO INMEMORY
    NOLOGGING
    NOCOMPRESS ,  
  PARTITION UMB2023 VALUES ('UMB2023')
    READ WRITE
    NO INMEMORY
    NOLOGGING
    NOCOMPRESS ,  
  PARTITION UMD2023 VALUES ('UMD2023')
    READ WRITE
    NO INMEMORY
    NOLOGGING
    NOCOMPRESS ,  
  PARTITION UML2023 VALUES ('UML2023')
    READ WRITE
    NO INMEMORY
    NOLOGGING
    NOCOMPRESS ,  
  PARTITION UMB2024 VALUES ('UMB2024')
    READ WRITE
    NO INMEMORY
    NOLOGGING
    NOCOMPRESS ,  
  PARTITION UMD20214 VALUES ('UMD2024')
    READ WRITE
    NO INMEMORY
    NOLOGGING
    NOCOMPRESS ,  
  PARTITION UML2024 VALUES ('UML2024')
    READ WRITE
    NO INMEMORY
    NOLOGGING
    NOCOMPRESS ,  
  PARTITION UMB2025 VALUES ('UMB2025')
    READ WRITE
    NO INMEMORY
    NOLOGGING
    NOCOMPRESS ,  
  PARTITION UMD2025 VALUES ('UMD2025')
    READ WRITE
    NO INMEMORY
    NOLOGGING
    NOCOMPRESS ,  
  PARTITION UML2025 VALUES ('UML2025')
    READ WRITE
    NO INMEMORY
    NOLOGGING
    NOCOMPRESS
)
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
