DROP TABLE CSMRT_OWNER.STUDENT_TAB_LIST CASCADE CONSTRAINTS
/

--
-- STUDENT_TAB_LIST  (Table) 
--
CREATE TABLE CSMRT_OWNER.STUDENT_TAB_LIST
(
  OWNER      VARCHAR2(128 BYTE),
  TABLENAME  VARCHAR2(30 BYTE)
)
NOCOMPRESS
/
