DROP TABLE CSMRT_OWNER.PS_D_ITEM_CD CASCADE CONSTRAINTS
/

--
-- PS_D_ITEM_CD  (Table) 
--
CREATE TABLE CSMRT_OWNER.PS_D_ITEM_CD
(
  ITEM_CD_SID           INTEGER                 NOT NULL,
  CHKLST_ITEM_CD        VARCHAR2(6 CHAR)        NOT NULL,
  SRC_SYS_ID            VARCHAR2(5 CHAR)        NOT NULL,
  EFFDT                 DATE                    NOT NULL,
  EFF_STAT_CD           VARCHAR2(1 CHAR)        NOT NULL,
  ITEM_ASSOCIATION      VARCHAR2(1 CHAR)        NOT NULL,
  ITEM_CD_SD            VARCHAR2(10 CHAR)       NOT NULL,
  ITEM_CD_LD            VARCHAR2(30 CHAR)       NOT NULL,
  UMBOS_INSTITUTION_CD  VARCHAR2(5 CHAR)        NOT NULL,
  UMDAR_INSTITUTION_CD  VARCHAR2(5 CHAR)        NOT NULL,
  UMLOW_INSTITUTION_CD  VARCHAR2(5 CHAR)        NOT NULL,
  LOAD_ERROR            VARCHAR2(1 CHAR)        NOT NULL,
  DATA_ORIGIN           VARCHAR2(1 CHAR)        NOT NULL,
  CREATED_EW_DTTM       DATE,
  LASTUPD_EW_DTTM       DATE,
  BATCH_SID             NUMBER(10)              NOT NULL
)
NOCOMPRESS
/


ALTER TABLE CSMRT_OWNER.PS_D_ITEM_CD ADD (
  CONSTRAINT PK_PS_D_ITEM_CD
  PRIMARY KEY
  (ITEM_CD_SID)
  RELY
  DISABLE NOVALIDATE)
/
