CREATE TABLE UM_R_FA_UMBOS_SF_TREE
(
  INSTITUTION_CD   VARCHAR2(5 BYTE),
  ACAD_CAR_CD      VARCHAR2(5 BYTE),
  TERM_CD          VARCHAR2(4 BYTE),
  PERSON_ID        VARCHAR2(11 BYTE),
  SELECT_VALUE     VARCHAR2(30 BYTE),
  ACCOUNT_TYPE_SF  VARCHAR2(3 BYTE),
  WAIVER_CODE      VARCHAR2(6 BYTE),
  ITEM_TYPE        VARCHAR2(12 BYTE),
  TREE_NAME        VARCHAR2(18 BYTE),
  TREE_NODE        VARCHAR2(20 BYTE),
  TREE_NODE_NUM    NUMBER(38),
  SRC_SYS_ID       VARCHAR2(5 BYTE),
  EFFDT            DATE,
  EFF_STATUS       VARCHAR2(1 BYTE),
  DESCR            VARCHAR2(30 BYTE),
  TERM_SID         INTEGER,
  PERSON_SID       INTEGER,
  DATA_ORIGIN      VARCHAR2(1 CHAR),
  CREATED_EW_DTTM  DATE,
  LASTUPD_EW_DTTM  DATE
)
NOLOGGING 
COMPRESS BASIC
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
