DROP TABLE CSMRT_OWNER.UM_D_RQ_GRP_CLOB_CO CASCADE CONSTRAINTS
/

--
-- UM_D_RQ_GRP_CLOB_CO  (Table) 
--
CREATE TABLE CSMRT_OWNER.UM_D_RQ_GRP_CLOB_CO
(
  RQRMNT_GROUP  VARCHAR2(6 BYTE)                NOT NULL,
  SRC_SYS_ID    VARCHAR2(5 BYTE)                NOT NULL,
  INSERT_DTTM   DATE,
  SQL_STR_CO    CLOB
)
LOB (SQL_STR_CO) STORE AS SECUREFILE (
  TABLESPACE  CSMRT_DATA1
  ENABLE      STORAGE IN ROW
  CHUNK       16384
  RETENTION
  STORAGE    (
              INITIAL          1M
              NEXT             1M
              MINEXTENTS       1
              MAXEXTENTS       UNLIMITED
              PCTINCREASE      0
              BUFFER_POOL      DEFAULT
             ))
COMPRESS BASIC
/
