CREATE TABLE UM_F_FA_STDNT_WS_ERN
(
  EMPLID           VARCHAR2(11 BYTE),
  INSTITUTION      VARCHAR2(5 BYTE),
  AID_YEAR         VARCHAR2(4 BYTE),
  PAY_END_DT       DATE,
  EMPL_RCD         INTEGER,
  ACCT_CD          VARCHAR2(25 BYTE),
  DEPTID           VARCHAR2(10 BYTE),
  ITEM_TYPE        VARCHAR2(12 BYTE),
  LAST_RUN_DT      DATE,
  ERN_BEGIN_DT     DATE,
  ERN_END_DT       DATE,
  SRC_SYS_ID       VARCHAR2(5 BYTE),
  INSTITUTION_SID  INTEGER,
  PERSON_SID       INTEGER,
  DEPT_SID         INTEGER,
  ITEM_TYPE_SID    INTEGER,
  HOURLY_RT        NUMBER(18,6),
  RATE_USED        VARCHAR2(1 BYTE),
  REG_HRS          NUMBER(6,2),
  REG_EARNS        NUMBER(10,2),
  UM_REG_EARNS     NUMBER(14,6),
  LOAD_ERROR       VARCHAR2(1 BYTE),
  DATA_ORIGIN      VARCHAR2(1 BYTE),
  CREATED_EW_DTTM  DATE,
  LASTUPD_EW_DTTM  DATE,
  BATCH_SID        NUMBER(10)
)
NOLOGGING 
COMPRESS BASIC
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
