CREATE TABLE UM_F_STDNT_GRADE_RSTR
(
  TERM_CD                VARCHAR2(4 BYTE),
  CLASS_NBR              INTEGER,
  GRD_RSTR_TYPE_SEQ      INTEGER,
  PERSON_ID              VARCHAR2(11 BYTE),
  ACAD_CAR_CD            VARCHAR2(4 BYTE),
  SRC_SYS_ID             VARCHAR2(5 BYTE),
  INSTITUTION_CD         VARCHAR2(5 BYTE),
  INSTITUTION_SID        INTEGER,
  ACAD_CAR_SID           INTEGER,
  TERM_SID               INTEGER,
  PERSON_SID             INTEGER,
  GRD_RSTR_TYPE_SID      INTEGER,
  BLIND_GRADING_ID       INTEGER,
  LAST_NAME_SRCH         VARCHAR2(30 BYTE),
  FIRST_NAME_SRCH        VARCHAR2(30 BYTE),
  CRSE_GRADE_INPUT       VARCHAR2(3 BYTE),
  RQMNT_DESIGNTN_GRD     VARCHAR2(1 BYTE),
  RQMNT_DESIGNTN_GRD_SD  VARCHAR2(10 BYTE),
  RQMNT_DESIGNTN_GRD_LD  VARCHAR2(30 BYTE),
  TSCRPT_NOTE_ID         VARCHAR2(4 BYTE),
  TSCRPT_NOTE_EXISTS     VARCHAR2(1 BYTE),
  GRADE_ROSTER_STAT      VARCHAR2(1 BYTE),
  GRADE_ROSTER_STAT_SD   VARCHAR2(10 BYTE),
  GRADE_ROSTER_STAT_LD   VARCHAR2(30 BYTE),
  INSTRUCTOR_ID          VARCHAR2(11 BYTE),
  GRADING_SCHEME         VARCHAR2(3 BYTE),
  GRADING_BASIS_ENRL     VARCHAR2(3 BYTE),
  DYN_CLASS_NBR          INTEGER,
  LOAD_ERROR             VARCHAR2(1 BYTE),
  DATA_ORIGIN            VARCHAR2(1 BYTE),
  CREATED_EW_DTTM        DATE,
  LASTUPD_EW_DTTM        DATE,
  BATCH_SID              NUMBER(10)
)
NOLOGGING 
COMPRESS BASIC
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
