DROP TABLE CSMRT_OWNER.UM_D_ACAD_PLAN CASCADE CONSTRAINTS
/

--
-- UM_D_ACAD_PLAN  (Table) 
--
CREATE TABLE CSMRT_OWNER.UM_D_ACAD_PLAN
(
  ACAD_PLAN_SID           INTEGER               NOT NULL,
  EFFDT                   DATE                  NOT NULL,
  INSTITUTION_CD          VARCHAR2(5 BYTE)      NOT NULL,
  ACAD_PLAN_CD            VARCHAR2(10 BYTE)     NOT NULL,
  SRC_SYS_ID              VARCHAR2(5 BYTE)      NOT NULL,
  EFFDT_START             DATE                  NOT NULL,
  EFFDT_END               DATE                  NOT NULL,
  EFFDT_ORDER             INTEGER               NOT NULL,
  EFF_STAT_CD             VARCHAR2(1 BYTE)      NOT NULL,
  ACAD_PLAN_SD            VARCHAR2(10 BYTE)     NOT NULL,
  ACAD_PLAN_LD            VARCHAR2(30 BYTE)     NOT NULL,
  ACAD_PLAN_CD_DESC       VARCHAR2(50 BYTE)     NOT NULL,
  ACAD_CAR_SID            INTEGER               NOT NULL,
  ACAD_PROG_SID           INTEGER               NOT NULL,
  DEG_SID                 INTEGER               NOT NULL,
  INSTITUTION_SID         INTEGER               NOT NULL,
  ACAD_PLAN_TYPE_CD       VARCHAR2(3 BYTE)      NOT NULL,
  ACAD_PLAN_TYPE_SD       VARCHAR2(10 BYTE)     NOT NULL,
  ACAD_PLAN_TYPE_LD       VARCHAR2(30 BYTE)     NOT NULL,
  ACAD_PLAN_TYPE_CD_DESC  VARCHAR2(50 BYTE)     NOT NULL,
  CIP_CD                  VARCHAR2(13 BYTE)     NOT NULL,
  CIP_LD                  VARCHAR2(30 BYTE)     NOT NULL,
  DIPLOMA_DESCR           VARCHAR2(100 BYTE)    NOT NULL,
  DIPLOMA_PRINT_FLG       VARCHAR2(1 BYTE)      NOT NULL,
  EDU_LVL_CTGRY           VARCHAR2(30 BYTE)     NOT NULL,
  EVALUATE_PLAN_FLG       VARCHAR2(1 BYTE)      NOT NULL,
  PLAN_REQTRM_DFLT        VARCHAR2(1 BYTE)      NOT NULL,
  PLAN_REQTRM_DFLT_SD     VARCHAR2(10 BYTE)     NOT NULL,
  PLAN_REQTRM_DFLT_LD     VARCHAR2(30 BYTE)     NOT NULL,
  SAA_WHIF_DISP_ADVR_FLG  VARCHAR2(1 BYTE)      NOT NULL,
  SAA_WHIF_DISP_PREM_FLG  VARCHAR2(1 BYTE)      NOT NULL,
  SAA_WHIF_DISP_STD_FLG   VARCHAR2(1 BYTE)      NOT NULL,
  SSR_NSC_CRD_LVL         VARCHAR2(1 BYTE)      NOT NULL,
  SSR_NSC_CRD_LVL_SD      VARCHAR2(10 BYTE)     NOT NULL,
  SSR_NSC_CRD_LVL_LD      VARCHAR2(30 BYTE)     NOT NULL,
  SSR_NSC_INCL_PLAN_FLG   VARCHAR2(1 BYTE)      NOT NULL,
  SSR_PROG_LEN_TYPE       VARCHAR2(1 BYTE)      NOT NULL,
  SSR_PROG_LEN_TYPE_SD    VARCHAR2(10 BYTE)     NOT NULL,
  SSR_PROG_LEN_TYPE_LD    VARCHAR2(30 BYTE)     NOT NULL,
  SSR_PROG_LENGTH         NUMBER(6,3)           NOT NULL,
  SEV_VALID_CIP_FLG       VARCHAR2(1 BYTE)      NOT NULL,
  TRNSCR_DESCR            VARCHAR2(100 BYTE)    NOT NULL,
  TRNSCR_PRINT_FLG        VARCHAR2(1 BYTE)      NOT NULL,
  UM_STEM_FLG             VARCHAR2(1 BYTE)      NOT NULL,
  DATA_ORIGIN             VARCHAR2(1 BYTE)      NOT NULL,
  CREATED_EW_DTTM         DATE,
  LASTUPD_EW_DTTM         DATE
)
NOCOMPRESS
/


ALTER TABLE CSMRT_OWNER.UM_D_ACAD_PLAN ADD (
  CONSTRAINT PK_UM_D_ACAD_PLAN
  PRIMARY KEY
  (ACAD_PLAN_SID)
  RELY
  DISABLE NOVALIDATE)
/
