DROP TABLE CSMRT_OWNER.UM_R_FA_STDNT_SR CASCADE CONSTRAINTS
/

--
-- UM_R_FA_STDNT_SR  (Table) 
--
CREATE TABLE CSMRT_OWNER.UM_R_FA_STDNT_SR
(
  INSTITUTION_CD  VARCHAR2(5 BYTE)              NOT NULL,
  PERSON_ID       VARCHAR2(11 BYTE)             NOT NULL,
  SRC_SYS_ID      VARCHAR2(5 BYTE)              NOT NULL,
  TERM_SID        INTEGER                       NOT NULL,
  PERSON_SID      INTEGER                       NOT NULL
)
COMPRESS BASIC
/


ALTER TABLE CSMRT_OWNER.UM_R_FA_STDNT_SR ADD (
  CONSTRAINT PK_UM_R_FA_STDNT_SR
  PRIMARY KEY
  (INSTITUTION_CD, PERSON_ID, SRC_SYS_ID, TERM_SID)
  RELY
  ENABLE VALIDATE)
/
