CREATE TABLE UM_D_RQ_LINE
(
  RQRMNT_LINE_SID   INTEGER,
  REQUIREMENT       VARCHAR2(9 BYTE),
  RQ_LINE_NBR       VARCHAR2(4 BYTE),
  SRC_SYS_ID        VARCHAR2(4 BYTE),
  RQ_LINE_KEY_NBR   VARCHAR2(4 BYTE),
  EFFDT             DATE,
  DESCR             VARCHAR2(30 BYTE),
  DESCRSHORT        VARCHAR2(10 BYTE),
  GRADE_POINTS_MIN  NUMBER(9,2),
  GPA_REQUIRED      NUMBER(6,3),
  GPA_MAXIMUM       NUMBER(6,3),
  MIN_UNITS_REQD    NUMBER(6,2),
  MIN_CRSES_REQD    NUMBER(5,2),
  MAX_UNITS_ALLOWD  NUMBER(6,2),
  MAX_CRSES_ALLOWD  NUMBER(6,2),
  REQ_LINE_TYPE     VARCHAR2(3 BYTE),
  RQ_REPORTING      VARCHAR2(4 BYTE),
  RQ_REPORTING_SD   VARCHAR2(10 BYTE),
  RQ_REPORTING_LD   VARCHAR2(30 BYTE),
  SAA_HIDE_STATUS   VARCHAR2(1 BYTE),
  SAA_DESCR80       VARCHAR2(80 BYTE),
  DESCR254          VARCHAR2(254 BYTE),
  DESCRLONG         VARCHAR2(4000 BYTE),
  DATA_ORIGIN       VARCHAR2(1 BYTE),
  CREATED_EW_DTTM   DATE,
  LASTUPD_EW_DTTM   DATE
)
NOLOGGING 
COMPRESS BASIC
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
