DROP TABLE CSMRT_OWNER.PS_D_TST_DATA_SRC CASCADE CONSTRAINTS
/

--
-- PS_D_TST_DATA_SRC  (Table) 
--
CREATE TABLE CSMRT_OWNER.PS_D_TST_DATA_SRC
(
  TST_DATA_SRC_SID  INTEGER                     NOT NULL,
  TST_DATA_SRC_ID   VARCHAR2(4 CHAR)            NOT NULL,
  SRC_SYS_ID        VARCHAR2(5 CHAR)            NOT NULL,
  TST_DATA_SRC_SD   VARCHAR2(10 CHAR)           NOT NULL,
  TST_DATA_SRC_LD   VARCHAR2(30 CHAR)           NOT NULL,
  DATA_ORIGIN       VARCHAR2(1 CHAR)            NOT NULL,
  CREATED_EW_DTTM   DATE,
  LASTUPD_EW_DTTM   DATE
)
COMPRESS BASIC
/


ALTER TABLE CSMRT_OWNER.PS_D_TST_DATA_SRC ADD (
  CONSTRAINT PK_PS_D_TST_DATA_SRC
  PRIMARY KEY
  (TST_DATA_SRC_SID)
  RELY
  DISABLE NOVALIDATE)
/
