CREATE TABLE PS_D_ITEM_TYPE
(
  ITEM_TYPE_SID     INTEGER,
  SETID             VARCHAR2(5 CHAR),
  ITEM_TYPE_ID      VARCHAR2(12 CHAR),
  SRC_SYS_ID        VARCHAR2(5 CHAR),
  EFFDT             DATE,
  EFF_STAT_CD       VARCHAR2(1 CHAR),
  ITEM_TYPE_SD      VARCHAR2(30 BYTE),
  ITEM_TYPE_LD      VARCHAR2(50 BYTE),
  ITEM_CLS_TYPE_ID  VARCHAR2(1 CHAR),
  ITEM_CLS_TYPE_SD  VARCHAR2(10 CHAR),
  ITEM_CLS_TYPE_LD  VARCHAR2(30 CHAR),
  KEYWORD1          VARCHAR2(10 CHAR),
  KEYWORD2          VARCHAR2(10 CHAR),
  KEYWORD3          VARCHAR2(10 CHAR),
  REFUND_FLG        VARCHAR2(1 CHAR),
  TAXABLE_FLG       VARCHAR2(1 CHAR),
  DATA_ORIGIN       VARCHAR2(1 CHAR),
  CREATED_EW_DTTM   DATE,
  LASTUPD_EW_DTTM   DATE
)
NOLOGGING 
COMPRESS BASIC
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
