DROP TABLE CSMRT_OWNER.PS_D_INSTRCTR_LOAD CASCADE CONSTRAINTS
/

--
-- PS_D_INSTRCTR_LOAD  (Table) 
--
CREATE TABLE CSMRT_OWNER.PS_D_INSTRCTR_LOAD
(
  INSTRCTR_LOAD_SID  NUMBER(10)                 NOT NULL,
  INSTRCTR_LOAD_CD   VARCHAR2(4 CHAR)           NOT NULL,
  INSTRCTR_LOAD_SD   VARCHAR2(10 CHAR)          NOT NULL,
  INSTRCTR_LOAD_LD   VARCHAR2(30 CHAR)          NOT NULL,
  EFF_START_DT       DATE,
  EFF_END_DT         DATE,
  CURRENT_IND        VARCHAR2(1 CHAR)           NOT NULL,
  SRC_SYS_ID         VARCHAR2(5 CHAR)           NOT NULL,
  LOAD_ERROR         VARCHAR2(1 CHAR)           NOT NULL,
  DATA_ORIGIN        VARCHAR2(1 CHAR)           NOT NULL,
  CREATED_EW_DTTM    DATE,
  LASTUPD_EW_DTTM    DATE,
  BATCH_SID          NUMBER(10)                 NOT NULL
)
NOCOMPRESS
/


ALTER TABLE CSMRT_OWNER.PS_D_INSTRCTR_LOAD ADD (
  CONSTRAINT PK_PS_D_INSTRCTR_LOAD
  PRIMARY KEY
  (INSTRCTR_LOAD_SID)
  RELY
  DISABLE NOVALIDATE)
/
