DROP TABLE CSMRT_OWNER.UM_F_FA_STDNT_RTN_TIV CASCADE CONSTRAINTS
/

--
-- UM_F_FA_STDNT_RTN_TIV  (Table) 
--
CREATE TABLE CSMRT_OWNER.UM_F_FA_STDNT_RTN_TIV
(
  INSTITUTION_CD         VARCHAR2(5 BYTE)       NOT NULL,
  AID_YEAR               VARCHAR2(4 BYTE)       NOT NULL,
  TERM_CD                VARCHAR2(4 BYTE)       NOT NULL,
  PERSON_ID              VARCHAR2(11 BYTE)      NOT NULL,
  SRC_SYS_ID             VARCHAR2(5 BYTE)       NOT NULL,
  INSTITUTION_SID        INTEGER                NOT NULL,
  PERSON_SID             INTEGER                NOT NULL,
  RTRN_TIV_STATUS        VARCHAR2(1 BYTE)       NOT NULL,
  RTRN_TIV_STATUS_SD     VARCHAR2(10 BYTE)      NOT NULL,
  RTRN_TIV_WSTAT_DT      DATE                   NOT NULL,
  RTRN_TIV_PERIOD_TP     VARCHAR2(1 BYTE)       NOT NULL,
  RTRN_TIV_PERIOD_TP_SD  VARCHAR2(10 BYTE)      NOT NULL,
  RTRN_TIV_FORM_DT       DATE,
  WITHDRAW_DATE          DATE,
  PERIOD_START_DT        DATE                   NOT NULL,
  PERIOD_END_DT          DATE                   NOT NULL,
  RTRN_TIV_COMP_DAYS     INTEGER                NOT NULL,
  RTRN_TIV_TOT_DAYS      INTEGER                NOT NULL,
  RTRN_TIV_CAL_PCT       NUMBER(5,2)            NOT NULL,
  TIV_AID_UNEARN_PCT     NUMBER(5,2)            NOT NULL,
  RTRN_TIV_DAYS_PAST     INTEGER                NOT NULL,
  LAST_UPDATE_DTTM       DATE,
  OPRID                  VARCHAR2(30 BYTE)      NOT NULL,
  SFA_HERA_FLG           VARCHAR2(1 BYTE)       NOT NULL,
  SFA_RTIV_CHD_OVRDE     VARCHAR2(1 BYTE)       NOT NULL,
  LOAD_ERROR             VARCHAR2(1 BYTE)       NOT NULL,
  DATA_ORIGIN            VARCHAR2(1 BYTE)       NOT NULL,
  CREATED_EW_DTTM        DATE,
  LASTUPD_EW_DTTM        DATE,
  BATCH_SID              NUMBER(10)             NOT NULL
)
COMPRESS BASIC
/


ALTER TABLE CSMRT_OWNER.UM_F_FA_STDNT_RTN_TIV ADD (
  CONSTRAINT PK_UM_F_FA_STDNT_RTN_TIV
  PRIMARY KEY
  (INSTITUTION_CD, TERM_CD, AID_YEAR, PERSON_ID, SRC_SYS_ID)
  RELY
  ENABLE VALIDATE)
/
