DROP TABLE CSMRT_OWNER.UM_R_ENRL_MSG_LOG CASCADE CONSTRAINTS
/

--
-- UM_R_ENRL_MSG_LOG  (Table) 
--
CREATE TABLE CSMRT_OWNER.UM_R_ENRL_MSG_LOG
(
  ENRL_REQUEST_ID    VARCHAR2(10 BYTE)          NOT NULL,
  ENRL_REQ_DETL_SEQ  INTEGER                    NOT NULL,
  MESSAGE_SEQ        INTEGER                    NOT NULL,
  SRC_SYS_ID         VARCHAR2(5 BYTE)           NOT NULL,
  MESSAGE_SET_NBR    INTEGER                    NOT NULL,
  MESSAGE_NBR        INTEGER                    NOT NULL,
  MSG_SEVERITY       VARCHAR2(1 BYTE)           NOT NULL,
  DTTM_STAMP_SEC     DATE,
  DATA_ORIGIN        VARCHAR2(1 BYTE)           NOT NULL,
  CREATED_EW_DTTM    DATE,
  LASTUPD_EW_DTTM    DATE
)
COMPRESS BASIC
/


ALTER TABLE CSMRT_OWNER.UM_R_ENRL_MSG_LOG ADD (
  CONSTRAINT PK_PK_UM_R_ENRL_MSG_LOG
  PRIMARY KEY
  (ENRL_REQUEST_ID, ENRL_REQ_DETL_SEQ, MESSAGE_SEQ, SRC_SYS_ID)
  RELY
  ENABLE VALIDATE)
/
