CREATE TABLE UM_D_CLASS_COMP
(
  CRSE_CD            VARCHAR2(6 BYTE),
  CRSE_OFFER_NUM     INTEGER,
  TERM_CD            VARCHAR2(4 BYTE),
  SESSION_CD         VARCHAR2(3 BYTE),
  ASSOCIATED_CLASS   INTEGER,
  SSR_COMP_CD        VARCHAR2(3 BYTE),
  SRC_SYS_ID         VARCHAR2(5 BYTE),
  CLASS_ASSOC_SID    INTEGER,
  SSR_COMP_SID       INTEGER,
  OPTIONAL_SECTION   VARCHAR2(1 BYTE),
  CONTACT_HOURS      NUMBER(7,3),
  FINAL_EXAM         VARCHAR2(2 BYTE),
  AUTO_CREATE_CMPNT  VARCHAR2(1 BYTE),
  WEEK_WORKLOAD_HRS  NUMBER(5,2),
  DATA_ORIGIN        VARCHAR2(1 BYTE),
  CREATED_EW_DTTM    DATE,
  LASTUPD_EW_DTTM    DATE
)
NOLOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
