DROP TABLE CSMRT_OWNER.UM_D_CRSE_ATTR_VAL CASCADE CONSTRAINTS
/

--
-- UM_D_CRSE_ATTR_VAL  (Table) 
--
CREATE TABLE CSMRT_OWNER.UM_D_CRSE_ATTR_VAL
(
  CRSE_ATTR_VAL_SID   INTEGER                   NOT NULL,
  CRSE_CD             VARCHAR2(6 BYTE)          NOT NULL,
  CRSE_OFFER_NUM      INTEGER                   NOT NULL,
  CRSE_ATTR           VARCHAR2(4 BYTE)          NOT NULL,
  CRSE_ATTR_VALUE     VARCHAR2(10 BYTE)         NOT NULL,
  SRC_SYS_ID          VARCHAR2(5 BYTE)          NOT NULL,
  EFFDT               DATE,
  CRSE_SID            NUMBER(10)                NOT NULL,
  CRSE_ATTR_SD        VARCHAR2(10 BYTE)         NOT NULL,
  CRSE_ATTR_LD        VARCHAR2(30 BYTE)         NOT NULL,
  CRSE_ATTR_VALUE_LD  VARCHAR2(30 BYTE)         NOT NULL,
  CRSE_ATTR_VALUE_FD  VARCHAR2(50 BYTE)         NOT NULL,
  CATALOG_PRINT_FLG   VARCHAR2(1 BYTE)          NOT NULL,
  SCHEDULE_PRINT_FLG  VARCHAR2(1 BYTE)          NOT NULL,
  DATA_ORIGIN         VARCHAR2(1 BYTE)          NOT NULL,
  CREATED_EW_DTTM     DATE,
  LASTUPD_EW_DTTM     DATE
)
COMPRESS BASIC
/


ALTER TABLE CSMRT_OWNER.UM_D_CRSE_ATTR_VAL ADD (
  CONSTRAINT PK_UM_D_CRSE_ATTR_VAL
  PRIMARY KEY
  (CRSE_ATTR_VAL_SID)
  RELY
  ENABLE VALIDATE)
/
