CREATE TABLE UM_F_FA_STDNT_PELL_ACTN
(
  INSTITUTION_CD      VARCHAR2(5 BYTE),
  AID_YEAR            VARCHAR2(4 BYTE),
  PERSON_ID           VARCHAR2(11 BYTE),
  PELL_ORIG_ID        VARCHAR2(23 BYTE),
  PELL_ORIG_ACTN_SEQ  INTEGER,
  PELL_ORIG_MSG_SEQ   INTEGER,
  SRC_SYS_ID          VARCHAR2(5 BYTE),
  INSTITUTION_SID     INTEGER,
  PERSON_SID          INTEGER,
  PELL_ACTION_CD      VARCHAR2(4 BYTE),
  PELL_ACTION_SD      VARCHAR2(10 BYTE),
  PELL_ACTION_LD      VARCHAR2(30 BYTE),
  PELL_ACTION_DT      DATE,
  PELL_BATCH_NBR      VARCHAR2(26 BYTE),
  OPRID               VARCHAR2(30 BYTE),
  PROCESS_INSTANCE    NUMBER(10),
  SFA_CR_DOCUMENT_ID  VARCHAR2(34 BYTE),
  PELL_ORIG_ACTN_MSG  VARCHAR2(4 BYTE),
  LOAD_ERROR          VARCHAR2(1 BYTE),
  DATA_ORIGIN         VARCHAR2(1 BYTE),
  CREATED_EW_DTTM     DATE,
  LASTUPD_EW_DTTM     DATE,
  BATCH_SID           INTEGER
)
NOLOGGING 
COMPRESS BASIC
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
