CREATE TABLE UM_W_SR_EXTRACT_CONTROL
(
  INSTITUTION_CD  VARCHAR2(5 BYTE),
  EXTRACT_TYPE    VARCHAR2(10 BYTE),
  TERM_CD         VARCHAR2(4 BYTE),
  LASTUPD_BY      VARCHAR2(11 BYTE)             DEFAULT 'UNKNOWN',
  LASTUPD_DTTM    DATE                          DEFAULT sysdate
)
NOLOGGING 
COMPRESS BASIC
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
