DROP TABLE CSMRT_OWNER.PS_D_EXT_ORG CASCADE CONSTRAINTS
/

--
-- PS_D_EXT_ORG  (Table) 
--
CREATE TABLE CSMRT_OWNER.PS_D_EXT_ORG
(
  EXT_ORG_SID         INTEGER                   NOT NULL,
  EXT_ORG_ID          VARCHAR2(11 BYTE)         NOT NULL,
  SRC_SYS_ID          VARCHAR2(5 BYTE)          NOT NULL,
  EFFDT               DATE,
  EFF_STAT_CD         VARCHAR2(1 BYTE)          NOT NULL,
  EXT_ORG_SD          VARCHAR2(10 BYTE)         NOT NULL,
  EXT_ORG_LD          VARCHAR2(30 BYTE)         NOT NULL,
  EXT_ORG_FD          VARCHAR2(50 BYTE)         NOT NULL,
  EXT_ORG_TYPE_ID     VARCHAR2(4 BYTE)          NOT NULL,
  EXT_ORG_TYPE_SD     VARCHAR2(10 BYTE)         NOT NULL,
  EXT_ORG_TYPE_LD     VARCHAR2(30 BYTE)         NOT NULL,
  SCHOOL_TYPE_ID      VARCHAR2(3 BYTE)          NOT NULL,
  SCHOOL_TYPE_SD      VARCHAR2(10 BYTE)         NOT NULL,
  SCHOOL_TYPE_LD      VARCHAR2(30 BYTE)         NOT NULL,
  ADDR1_LD            VARCHAR2(55 BYTE)         NOT NULL,
  ADDR2_LD            VARCHAR2(55 BYTE)         NOT NULL,
  ADDR3_LD            VARCHAR2(55 BYTE)         NOT NULL,
  ADDR4_LD            VARCHAR2(55 BYTE)         NOT NULL,
  CITY_NM             VARCHAR2(30 BYTE)         NOT NULL,
  CNTY_NM             VARCHAR2(30 BYTE)         NOT NULL,
  STATE_ID            VARCHAR2(6 BYTE)          NOT NULL,
  STATE_LD            VARCHAR2(30 BYTE)         NOT NULL,
  POSTAL_CD           VARCHAR2(12 BYTE)         NOT NULL,
  CNTRY_ID            VARCHAR2(3 BYTE)          NOT NULL,
  CNTRY_SD            VARCHAR2(10 BYTE)         NOT NULL,
  CNTRY_LD            VARCHAR2(30 BYTE)         NOT NULL,
  ACCREDITED_FLG      VARCHAR2(1 BYTE)          NOT NULL,
  ATP_CD              VARCHAR2(6 BYTE)          NOT NULL,
  EXT_CAREER          VARCHAR2(4 BYTE)          NOT NULL,
  EXT_CAREER_SD       VARCHAR2(10 BYTE)         NOT NULL,
  EXT_CAREER_LD       VARCHAR2(30 BYTE)         NOT NULL,
  EXT_TERM_TYPE       VARCHAR2(4 BYTE)          NOT NULL,
  EXT_TERM_TYPE_SD    VARCHAR2(10 BYTE)         NOT NULL,
  EXT_TERM_TYPE_LD    VARCHAR2(30 BYTE)         NOT NULL,
  OFFERS_COURSES_FLG  VARCHAR2(1 BYTE)          NOT NULL,
  ORG_LOCATION        INTEGER                   NOT NULL,
  PROPRIETORSHIP      VARCHAR2(4 BYTE)          NOT NULL,
  PROPRIETORSHIP_SD   VARCHAR2(10 BYTE)         NOT NULL,
  PROPRIETORSHIP_LD   VARCHAR2(30 BYTE)         NOT NULL,
  SHARED_CATALOG_FLG  VARCHAR2(1 BYTE)          NOT NULL,
  UNT_TYPE            VARCHAR2(3 BYTE)          NOT NULL,
  UNT_TYPE_SD         VARCHAR2(10 BYTE)         NOT NULL,
  UNT_TYPE_LD         VARCHAR2(30 BYTE)         NOT NULL,
  DATA_ORIGIN         VARCHAR2(1 BYTE)          NOT NULL,
  CREATED_EW_DTTM     DATE,
  LASTUPD_EW_DTTM     DATE,
  INACTIVE_FLAG       VARCHAR2(1 BYTE)
)
COMPRESS BASIC
/


ALTER TABLE CSMRT_OWNER.PS_D_EXT_ORG ADD (
  CONSTRAINT PK_PS_D_EXT_ORG
  PRIMARY KEY
  (EXT_ORG_SID)
  RELY
  DISABLE NOVALIDATE)
/
