CREATE TABLE UM_F_HOUSING
(
  INSTITUTION_CD   VARCHAR2(5 BYTE),
  PERSON_ID        VARCHAR2(11 BYTE),
  ACAD_YEAR_LD     VARCHAR2(254 BYTE),
  HOUSING_TERM_CD  VARCHAR2(4 BYTE),
  SRC_SYS_ID       VARCHAR2(5 BYTE),
  INSTITUTION_SID  INTEGER,
  TERM_SID         INTEGER,
  PERSON_SID       INTEGER,
  APPLIED_DT       DATE,
  COMPLETED_DT     DATE,
  AGREEMENT_DT     DATE,
  HOUSING_TERM_LD  VARCHAR2(254 BYTE),
  HOUSING_LOAD_DT  DATE,
  DATA_ORIGIN      VARCHAR2(1 BYTE),
  CREATED_EW_DTTM  DATE,
  LASTUPD_EW_DTTM  DATE
)
NOLOGGING 
COMPRESS BASIC
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
