CREATE TABLE UM_D_CLASS_INSTRCTR
(
  CLASS_INSTRCTR_SID    INTEGER,
  CRSE_CD               VARCHAR2(6 BYTE),
  CRSE_OFFER_NUM        INTEGER,
  TERM_CD               VARCHAR2(4 BYTE),
  SESSION_CD            VARCHAR2(3 BYTE),
  CLASS_SECTION_CD      VARCHAR2(4 BYTE),
  CLASS_MTG_NUM         INTEGER,
  INSTRCTR_ASGN_NUM     INTEGER,
  SRC_SYS_ID            VARCHAR2(5 BYTE),
  CLASS_MTG_PAT_ORDER   INTEGER,
  CLASS_INSTRCTR_ORDER  INTEGER,
  INSTITUTION_CD        VARCHAR2(5 BYTE),
  CLASS_SID             INTEGER,
  CLASS_MTG_PAT_SID     INTEGER,
  PERSON_SID            INTEGER,
  INSTRCTR_ROLE_SID     INTEGER,
  GRADE_RSTR_ACCESS     VARCHAR2(1 BYTE),
  GRADE_RSTR_ACCESS_SD  VARCHAR2(10 BYTE),
  GRADE_RSTR_ACCESS_LD  VARCHAR2(30 BYTE),
  CONTACT_MINUTES       INTEGER,
  SCHED_PRINT_INSTR     VARCHAR2(1 BYTE),
  INSTR_LOAD_FACTOR     NUMBER(5,2),
  AUTOCALC_WRKLD_FLG    VARCHAR2(1 BYTE),
  DATA_ORIGIN           VARCHAR2(1 BYTE),
  CREATED_EW_DTTM       DATE,
  LASTUPD_EW_DTTM       DATE
)
NOLOGGING 
COMPRESS BASIC
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
