DROP TABLE CSMRT_OWNER.UM_D_CAMPUS_EVENT CASCADE CONSTRAINTS
/

--
-- UM_D_CAMPUS_EVENT  (Table) 
--
CREATE TABLE CSMRT_OWNER.UM_D_CAMPUS_EVENT
(
  CAMPUS_EVENT_SID   INTEGER                    NOT NULL,
  CAMPUS_EVENT_NBR   VARCHAR2(9 BYTE)           NOT NULL,
  SRC_SYS_ID         VARCHAR2(5 BYTE)           NOT NULL,
  INSTITUTION_CD     VARCHAR2(5 BYTE)           NOT NULL,
  DESCRSHORT         VARCHAR2(10 BYTE)          NOT NULL,
  DESCR              VARCHAR2(30 BYTE)          NOT NULL,
  CAMPUS_EVENT_TYPE  VARCHAR2(4 BYTE)           NOT NULL,
  COMMENTS           VARCHAR2(4000 BYTE),
  DATA_ORIGIN        VARCHAR2(1 BYTE)           NOT NULL,
  CREATED_EW_DTTM    DATE,
  LASTUPD_EW_DTTM    DATE
)
COMPRESS BASIC
/


ALTER TABLE CSMRT_OWNER.UM_D_CAMPUS_EVENT ADD (
  CONSTRAINT PK_UM_D_CAMPUS_EVENT
  PRIMARY KEY
  (CAMPUS_EVENT_SID)
  RELY
  DISABLE NOVALIDATE)
/
