DROP TABLE CSMRT_OWNER.UM_F_STDNT_GRADE_RSTR CASCADE CONSTRAINTS
/

--
-- UM_F_STDNT_GRADE_RSTR  (Table) 
--
CREATE TABLE CSMRT_OWNER.UM_F_STDNT_GRADE_RSTR
(
  TERM_CD                VARCHAR2(4 BYTE)       NOT NULL,
  CLASS_NBR              INTEGER                NOT NULL,
  GRD_RSTR_TYPE_SEQ      INTEGER                NOT NULL,
  PERSON_ID              VARCHAR2(11 BYTE)      NOT NULL,
  ACAD_CAR_CD            VARCHAR2(4 BYTE)       NOT NULL,
  SRC_SYS_ID             VARCHAR2(5 BYTE)       NOT NULL,
  INSTITUTION_CD         VARCHAR2(5 BYTE)       NOT NULL,
  INSTITUTION_SID        INTEGER                NOT NULL,
  ACAD_CAR_SID           INTEGER                NOT NULL,
  TERM_SID               INTEGER                NOT NULL,
  PERSON_SID             INTEGER                NOT NULL,
  GRD_RSTR_TYPE_SID      INTEGER                NOT NULL,
  BLIND_GRADING_ID       INTEGER                NOT NULL,
  LAST_NAME_SRCH         VARCHAR2(30 BYTE)      NOT NULL,
  FIRST_NAME_SRCH        VARCHAR2(30 BYTE)      NOT NULL,
  CRSE_GRADE_INPUT       VARCHAR2(3 BYTE)       NOT NULL,
  RQMNT_DESIGNTN_GRD     VARCHAR2(1 BYTE)       NOT NULL,
  RQMNT_DESIGNTN_GRD_SD  VARCHAR2(10 BYTE)      NOT NULL,
  RQMNT_DESIGNTN_GRD_LD  VARCHAR2(30 BYTE)      NOT NULL,
  TSCRPT_NOTE_ID         VARCHAR2(4 BYTE)       NOT NULL,
  TSCRPT_NOTE_EXISTS     VARCHAR2(1 BYTE)       NOT NULL,
  GRADE_ROSTER_STAT      VARCHAR2(1 BYTE)       NOT NULL,
  GRADE_ROSTER_STAT_SD   VARCHAR2(10 BYTE)      NOT NULL,
  GRADE_ROSTER_STAT_LD   VARCHAR2(30 BYTE)      NOT NULL,
  INSTRUCTOR_ID          VARCHAR2(11 BYTE)      NOT NULL,
  GRADING_SCHEME         VARCHAR2(3 BYTE)       NOT NULL,
  GRADING_BASIS_ENRL     VARCHAR2(3 BYTE)       NOT NULL,
  DYN_CLASS_NBR          INTEGER                NOT NULL,
  LOAD_ERROR             VARCHAR2(1 BYTE)       NOT NULL,
  DATA_ORIGIN            VARCHAR2(1 BYTE)       NOT NULL,
  CREATED_EW_DTTM        DATE,
  LASTUPD_EW_DTTM        DATE,
  BATCH_SID              NUMBER(10)             NOT NULL
)
COMPRESS BASIC
/


ALTER TABLE CSMRT_OWNER.UM_F_STDNT_GRADE_RSTR ADD (
  CONSTRAINT PK_UM_F_STDNT_GRADE_RSTR
  PRIMARY KEY
  (TERM_CD, CLASS_NBR, GRD_RSTR_TYPE_SEQ, PERSON_ID, ACAD_CAR_CD, SRC_SYS_ID)
  RELY
  ENABLE VALIDATE)
/
