DROP TABLE CSMRT_OWNER.UM_H_ACAD_ORG_TREE CASCADE CONSTRAINTS
/

--
-- UM_H_ACAD_ORG_TREE  (Table) 
--
CREATE TABLE CSMRT_OWNER.UM_H_ACAD_ORG_TREE
(
  TREE_NAME        VARCHAR2(30 CHAR)            NOT NULL,
  EFFDT            DATE,
  SRC_SYS_ID       VARCHAR2(5 CHAR)             NOT NULL,
  ACAD_PLAN_SID    NUMBER(10)                   NOT NULL,
  ACAD_ORG_L6_SID  NUMBER(10)                   NOT NULL,
  ACAD_ORG_L5_SID  NUMBER(10)                   NOT NULL,
  ACAD_ORG_L4_SID  NUMBER(10)                   NOT NULL,
  ACAD_ORG_L3_SID  NUMBER(10)                   NOT NULL,
  ACAD_ORG_L2_SID  NUMBER(10)                   NOT NULL,
  ACAD_ORG_L1_SID  NUMBER(10)                   NOT NULL,
  PERCENT_OWNED    NUMBER(6,3)                  NOT NULL,
  LOAD_ERROR       VARCHAR2(1 CHAR)             NOT NULL,
  DATA_ORIGIN      VARCHAR2(1 CHAR)             NOT NULL,
  CREATED_EW_DTTM  DATE,
  LASTUPD_EW_DTTM  DATE,
  BATCH_SID        NUMBER(10)                   NOT NULL
)
NOCOMPRESS
/
