DROP TABLE CSMRT_OWNER.UM_D_EXT_SUBJECT_AREA CASCADE CONSTRAINTS
/

--
-- UM_D_EXT_SUBJECT_AREA  (Table) 
--
CREATE TABLE CSMRT_OWNER.UM_D_EXT_SUBJECT_AREA
(
  EXT_SUBJECT_AREA_SID  INTEGER                 NOT NULL,
  EXT_SUBJECT_AREA      VARCHAR2(4 BYTE)        NOT NULL,
  SRC_SYS_ID            VARCHAR2(5 BYTE)        NOT NULL,
  EFFDT                 DATE,
  EFF_STATUS            VARCHAR2(1 BYTE)        NOT NULL,
  DESCRSHORT            VARCHAR2(10 BYTE)       NOT NULL,
  DESCR                 VARCHAR2(30 BYTE)       NOT NULL,
  ACAD_INTEREST_FLG     VARCHAR2(1 BYTE)        NOT NULL,
  DATA_ORIGIN           VARCHAR2(1 BYTE)        NOT NULL,
  CREATED_EW_DTTM       DATE,
  LASTUPD_EW_DTTM       DATE
)
COMPRESS BASIC
/


ALTER TABLE CSMRT_OWNER.UM_D_EXT_SUBJECT_AREA ADD (
  CONSTRAINT PK_UM_D_EXT_SUBJECT_AREA
  PRIMARY KEY
  (EXT_SUBJECT_AREA_SID)
  RELY
  DISABLE NOVALIDATE)
/
