DROP TABLE CSMRT_OWNER.UM_M_AF_STDNT_BDL CASCADE CONSTRAINTS
/

--
-- UM_M_AF_STDNT_BDL  (Table) 
--
CREATE TABLE CSMRT_OWNER.UM_M_AF_STDNT_BDL
(
  INSTITUTION_CD      VARCHAR2(5 BYTE)          NOT NULL,
  ACAD_CAR_CD         VARCHAR2(5 BYTE)          NOT NULL,
  TERM_CD             VARCHAR2(4 BYTE)          NOT NULL,
  PERSON_ID           VARCHAR2(11 BYTE)         NOT NULL,
  SRC_SYS_ID          VARCHAR2(5 BYTE)          NOT NULL,
  ACAD_YR_SID         INTEGER,
  AID_YEAR            VARCHAR2(4 BYTE),
  TERM_LD             VARCHAR2(30 BYTE),
  ACAD_PROG_CD        VARCHAR2(5 BYTE),
  ACAD_PROG_LD        VARCHAR2(30 BYTE),
  PROG_CIP_CD         VARCHAR2(13 BYTE),
  ACAD_PLAN_CD        VARCHAR2(10 BYTE),
  ACAD_PLAN_LD        VARCHAR2(30 BYTE),
  PLAN_CIP_CD         VARCHAR2(13 BYTE),
  CE_ONLY_FLG         VARCHAR2(1 BYTE),
  NEW_CONT_IND        VARCHAR2(10 BYTE),
  ONLINE_HYBRID_FLG   VARCHAR2(1 BYTE),
  ONLINE_ONLY_FLG     VARCHAR2(1 BYTE),
  RSDNCY_ID           VARCHAR2(5 BYTE),
  RSDNCY_LD           VARCHAR2(30 BYTE),
  IS_RSDNCY_FLG       VARCHAR2(1 BYTE),
  ONLINE_FTE          NUMBER,
  TOT_FTE             NUMBER,
  ONLINE_CREDITS      NUMBER,
  NON_ONLINE_CREDITS  NUMBER,
  CE_CREDITS          NUMBER,
  NON_CE_CREDITS      NUMBER,
  TOT_CREDITS         NUMBER,
  ENROLL_CNT          NUMBER,
  ONLINE_CNT          NUMBER,
  CE_CNT              NUMBER,
  CREATED_EW_DTTM     DATE
)
COMPRESS BASIC
/


ALTER TABLE CSMRT_OWNER.UM_M_AF_STDNT_BDL ADD (
  CONSTRAINT PK_UM_M_AF_STDNT_BDL
  PRIMARY KEY
  (INSTITUTION_CD, ACAD_CAR_CD, TERM_CD, PERSON_ID, SRC_SYS_ID)
  RELY
  ENABLE VALIDATE)
/
