DROP TABLE CSMRT_OWNER.PS_D_ENRL_ACTION CASCADE CONSTRAINTS
/

--
-- PS_D_ENRL_ACTION  (Table) 
--
CREATE TABLE CSMRT_OWNER.PS_D_ENRL_ACTION
(
  ENRL_REQ_ACTN_SID   NUMBER(10)                NOT NULL,
  ENRL_REQ_ACTION     VARCHAR2(2 CHAR)          NOT NULL,
  SRC_SYS_ID          VARCHAR2(5 CHAR)          NOT NULL,
  ENRL_REQ_ACTION_SD  VARCHAR2(10 CHAR)         NOT NULL,
  ENRL_REQ_ACTION_LD  VARCHAR2(30 CHAR)         NOT NULL,
  DATA_ORIGIN         VARCHAR2(1 CHAR)          NOT NULL,
  CREATED_EW_DTTM     DATE,
  LASTUPD_EW_DTTM     DATE
)
COMPRESS BASIC
/


ALTER TABLE CSMRT_OWNER.PS_D_ENRL_ACTION ADD (
  CONSTRAINT PK_PS_D_ENRL_ACTION
  PRIMARY KEY
  (ENRL_REQ_ACTN_SID)
  RELY
  DISABLE NOVALIDATE)
/
