DROP TABLE CSMRT_OWNER.UM_F_STDNT_ENRL_APPT CASCADE CONSTRAINTS
/

--
-- UM_F_STDNT_ENRL_APPT  (Table) 
--
CREATE TABLE CSMRT_OWNER.UM_F_STDNT_ENRL_APPT
(
  INSTITUTION_CD      VARCHAR2(5 BYTE)          NOT NULL,
  ACAD_CAR_CD         VARCHAR2(4 BYTE)          NOT NULL,
  TERM_CD             VARCHAR2(4 BYTE)          NOT NULL,
  PERSON_ID           VARCHAR2(11 BYTE)         NOT NULL,
  SESSION_CODE        VARCHAR2(3 BYTE)          NOT NULL,
  SSR_APPT_BLOCK      VARCHAR2(6 BYTE)          NOT NULL,
  APPOINTMENT_NBR     VARCHAR2(4 BYTE)          NOT NULL,
  SRC_SYS_ID          VARCHAR2(5 BYTE)          NOT NULL,
  INSTITUTION_SID     INTEGER                   NOT NULL,
  ACAD_CAR_SID        INTEGER                   NOT NULL,
  TERM_SID            INTEGER                   NOT NULL,
  PERSON_SID          INTEGER                   NOT NULL,
  SESSION_SID         INTEGER                   NOT NULL,
  APPT_START_DTTM     DATE,
  APPT_END_DTTM       DATE,
  SSR_SELECT_LIMIT    VARCHAR2(1 BYTE),
  APPT_LIMIT_ID       VARCHAR2(4 BYTE),
  MAX_TOTAL_UNIT      NUMBER(5,2),
  MAX_NOGPA_UNIT      NUMBER(5,2),
  MAX_AUDIT_UNIT      NUMBER(5,2),
  MAX_WAIT_UNIT       NUMBER(5,2),
  SSR_APPT_STDT_BLCK  VARCHAR2(6 BYTE),
  INCL_WAIT_IN_TOT    VARCHAR2(1 BYTE),
  LOAD_ERROR          VARCHAR2(1 CHAR)          NOT NULL,
  DATA_ORIGIN         VARCHAR2(1 CHAR)          NOT NULL,
  CREATED_EW_DTTM     DATE,
  LASTUPD_EW_DTTM     DATE,
  BATCH_SID           NUMBER(10)                NOT NULL
)
COMPRESS BASIC
/


ALTER TABLE CSMRT_OWNER.UM_F_STDNT_ENRL_APPT ADD (
  CONSTRAINT PK_UM_F_STDNT_ENRL_APPT
  PRIMARY KEY
  (INSTITUTION_CD, ACAD_CAR_CD, TERM_CD, PERSON_ID, SESSION_CODE, SSR_APPT_BLOCK, APPOINTMENT_NBR, SRC_SYS_ID)
  RELY
  ENABLE VALIDATE)
/
