CREATE TABLE UM_D_PERSON_CITIZEN
(
  PERSON_ID                  VARCHAR2(11 BYTE),
  DEPENDENT_ID               VARCHAR2(2 BYTE),
  COUNTRY                    VARCHAR2(3 BYTE),
  SRC_SYS_ID                 VARCHAR2(5 BYTE),
  PERSON_SID                 INTEGER,
  CITIZENSHIP_STATUS         VARCHAR2(1 BYTE),
  CITIZENSHIP_STATUS_SD      VARCHAR2(10 BYTE),
  CITIZENSHIP_STATUS_LD      VARCHAR2(30 BYTE),
  COUNTRY_SD                 VARCHAR2(10 BYTE),
  COUNTRY_LD                 VARCHAR2(30 BYTE),
  COUNTRY_2CHAR              VARCHAR2(2 BYTE),
  EU_MEMBER_STATE            VARCHAR2(1 BYTE),
  CITIZENSHIP_STATUS_USA     VARCHAR2(1 BYTE),
  CITIZENSHIP_STATUS_SD_USA  VARCHAR2(10 BYTE),
  CITIZENSHIP_STATUS_LD_USA  VARCHAR2(30 BYTE),
  CIT_ORDER                  INTEGER,
  DATA_ORIGIN                VARCHAR2(1 BYTE),
  CREATED_EW_DTTM            DATE,
  LASTUPD_EW_DTTM            DATE
)
NOLOGGING 
COMPRESS BASIC
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
