CREATE TABLE UM_D_PERSON_ATHL
(
  PERSON_ID        VARCHAR2(11 BYTE),
  SPORT            VARCHAR2(3 BYTE),
  SRC_SYS_ID       VARCHAR2(5 BYTE),
  EFFDT            DATE,
  PERSON_SID       INTEGER,
  INSTITUTION_CD   VARCHAR2(5 BYTE),
  SPORT_SD         VARCHAR2(10 BYTE),
  SPORT_LD         VARCHAR2(30 BYTE),
  ATHL_PARTIC_CD   VARCHAR2(5 BYTE),
  ATHL_PARTIC_SD   VARCHAR2(10 BYTE),
  ATHL_PARTIC_LD   VARCHAR2(30 BYTE),
  NCAA_ELIGIBLE    VARCHAR2(1 BYTE),
  CUR_PARTICIPANT  VARCHAR2(1 BYTE),
  DESCRLONG        VARCHAR2(4000 BYTE),
  ATHL_ORDER       INTEGER,
  DATA_ORIGIN      VARCHAR2(1 BYTE),
  CREATED_EW_DTTM  DATE,
  LASTUPD_EW_DTTM  DATE
)
NOLOGGING 
COMPRESS BASIC
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
