CREATE TABLE PS_D_RECRT_STAT
(
  RECRT_STAT_SID   INTEGER,
  RECRT_STAT_ID    VARCHAR2(4 CHAR),
  SRC_SYS_ID       VARCHAR2(5 CHAR),
  RECRT_STAT_SD    VARCHAR2(10 CHAR),
  RECRT_STAT_LD    VARCHAR2(30 CHAR),
  DATA_ORIGIN      VARCHAR2(1 CHAR),
  CREATED_EW_DTTM  DATE,
  LASTUPD_EW_DTTM  DATE
)
NOLOGGING 
COMPRESS BASIC
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
