DROP TABLE CSMRT_OWNER.UM_F_FA_STDNT_LOAN_ORIG_ACN CASCADE CONSTRAINTS
/

--
-- UM_F_FA_STDNT_LOAN_ORIG_ACN  (Table) 
--
CREATE TABLE CSMRT_OWNER.UM_F_FA_STDNT_LOAN_ORIG_ACN
(
  INSTITUTION_CD       VARCHAR2(5 BYTE)         NOT NULL,
  ACAD_CAR_CD          VARCHAR2(4 BYTE)         NOT NULL,
  AID_YEAR             VARCHAR2(4 BYTE)         NOT NULL,
  PERSON_ID            VARCHAR2(11 BYTE)        NOT NULL,
  LOAN_TYPE            VARCHAR2(4 BYTE)         NOT NULL,
  LN_APPL_SEQ          INTEGER                  NOT NULL,
  ITEM_TYPE            VARCHAR2(12 BYTE)        NOT NULL,
  LN_ORIG_ACTN_SEQ     INTEGER                  NOT NULL,
  LNORIG_MSG_SEQ       INTEGER                  NOT NULL,
  SRC_SYS_ID           VARCHAR2(5 BYTE)         NOT NULL,
  INSTITUTION_SID      INTEGER                  NOT NULL,
  ACAD_CAR_SID         INTEGER                  NOT NULL,
  PERSON_SID           INTEGER                  NOT NULL,
  ITEM_TYPE_SID        INTEGER                  NOT NULL,
  LOAN_TYPE_SD         VARCHAR2(10 BYTE),
  LOAN_TYPE_LD         VARCHAR2(30 BYTE),
  LN_ACTION_CD         VARCHAR2(4 BYTE),
  LN_ACTION_DT         DATE,
  TRNSFR_BATCH         VARCHAR2(23 BYTE),
  LN_ACTION_STATUS     VARCHAR2(1 BYTE),
  LN_ACTION_STATUS_SD  VARCHAR2(10 BYTE),
  LN_ACTION_STATUS_LD  VARCHAR2(30 BYTE),
  LN_ACTNSTAT_DT       DATE,
  OPRID                VARCHAR2(30 BYTE),
  PROCESS_INSTANCE     NUMBER(10),
  SFA_CR_DOCUMENT_ID   VARCHAR2(34 BYTE),
  LN_ACTION_MSG        VARCHAR2(4 BYTE),
  LOAD_ERROR           VARCHAR2(1 BYTE),
  DATA_ORIGIN          VARCHAR2(1 BYTE),
  CREATED_EW_DTTM      DATE,
  LASTUPD_EW_DTTM      DATE,
  BATCH_SID            INTEGER
)
COMPRESS BASIC
/


ALTER TABLE CSMRT_OWNER.UM_F_FA_STDNT_LOAN_ORIG_ACN ADD (
  CONSTRAINT PK_UM_F_FA_STDNT_LOAN_ORIG_ACN
  PRIMARY KEY
  (INSTITUTION_CD, ACAD_CAR_CD, AID_YEAR, PERSON_ID, LOAN_TYPE, LN_APPL_SEQ, ITEM_TYPE, LN_ORIG_ACTN_SEQ, LNORIG_MSG_SEQ, SRC_SYS_ID)
  RELY
  ENABLE VALIDATE)
/
