DROP TABLE CSMRT_OWNER.UM_D_RFRL_DTL CASCADE CONSTRAINTS
/

--
-- UM_D_RFRL_DTL  (Table) 
--
CREATE TABLE CSMRT_OWNER.UM_D_RFRL_DTL
(
  RFRL_DTL_SID     INTEGER                      NOT NULL,
  INSTITUTION_CD   VARCHAR2(5 BYTE)             NOT NULL,
  RFRL_GRP         VARCHAR2(4 BYTE)             NOT NULL,
  RFRL_DTL         VARCHAR2(4 BYTE)             NOT NULL,
  SRC_SYS_ID       VARCHAR2(5 BYTE)             NOT NULL,
  DESCR            VARCHAR2(30 BYTE)            NOT NULL,
  RFRL_DATE        DATE,
  RFRL_GRP_SID     NUMBER(10)                   NOT NULL,
  RFRL_DTL_STATUS  VARCHAR2(1 BYTE)             NOT NULL,
  DATA_ORIGIN      VARCHAR2(1 BYTE)             NOT NULL,
  CREATED_EW_DTTM  DATE,
  LASTUPD_EW_DTTM  DATE
)
COMPRESS BASIC
/


ALTER TABLE CSMRT_OWNER.UM_D_RFRL_DTL ADD (
  CONSTRAINT PK_UM_D_RFRL_DTL
  PRIMARY KEY
  (RFRL_DTL_SID)
  RELY
  DISABLE NOVALIDATE)
/
