DROP TABLE CSMRT_OWNER.UM_W_RA_PREDICT_CONTROL CASCADE CONSTRAINTS
/

--
-- UM_W_RA_PREDICT_CONTROL  (Table) 
--
CREATE TABLE CSMRT_OWNER.UM_W_RA_PREDICT_CONTROL
(
  INSTITUTION_CD   VARCHAR2(5 BYTE)             NOT NULL,
  ACAD_CAR_CD      VARCHAR2(5 BYTE)             NOT NULL,
  TERM_CD          VARCHAR2(4 BYTE)             NOT NULL,
  ACAD_PROG_CD     VARCHAR2(5 BYTE)             NOT NULL,
  ACAD_PLAN_CD     VARCHAR2(10 BYTE),
  ACAD_SPLAN_CD    VARCHAR2(10 BYTE),
  SCENARIO         VARCHAR2(30 BYTE),
  ACT_COMP_SCORE   NUMBER,
  SAT_MATH_SCORE   NUMBER,
  SAT_VERB_SCORE   NUMBER,
  SAT_TOTAL_SCORE  NUMBER,
  HS_GPA           NUMBER,
  LASTUPD_BY       VARCHAR2(11 BYTE),
  LASTUPD_DTTM     DATE
)
COMPRESS BASIC
/
