DROP TABLE CSMRT_OWNER.PS_D_ADMIT_TYPE CASCADE CONSTRAINTS
/

--
-- PS_D_ADMIT_TYPE  (Table) 
--
CREATE TABLE CSMRT_OWNER.PS_D_ADMIT_TYPE
(
  ADMIT_TYPE_SID   INTEGER                      NOT NULL,
  INSTITUTION_CD   VARCHAR2(5 CHAR)             NOT NULL,
  ADMIT_TYPE_ID    VARCHAR2(3 CHAR)             NOT NULL,
  SRC_SYS_ID       VARCHAR2(5 CHAR)             NOT NULL,
  EFFDT            DATE,
  EFF_STAT_CD      VARCHAR2(1 CHAR)             NOT NULL,
  ADMIT_TYPE_SD    VARCHAR2(10 CHAR)            NOT NULL,
  ADMIT_TYPE_LD    VARCHAR2(30 CHAR)            NOT NULL,
  ADMIT_TYPE_GRP   VARCHAR2(30 CHAR)            NOT NULL,
  DATA_ORIGIN      VARCHAR2(1 CHAR)             NOT NULL,
  CREATED_EW_DTTM  DATE,
  LASTUPD_EW_DTTM  DATE
)
COMPRESS BASIC
/


ALTER TABLE CSMRT_OWNER.PS_D_ADMIT_TYPE ADD (
  CONSTRAINT PK_PS_D_ADMIT_TYPE
  PRIMARY KEY
  (ADMIT_TYPE_SID)
  RELY
  DISABLE NOVALIDATE)
/
