DROP TABLE CSMRT_OWNER.UM_D_FA_NCAA_VALUES CASCADE CONSTRAINTS
/

--
-- UM_D_FA_NCAA_VALUES  (Table) 
--
CREATE TABLE CSMRT_OWNER.UM_D_FA_NCAA_VALUES
(
  INSTITUTION_CD  VARCHAR2(5 BYTE)              NOT NULL,
  UM_SPORT_CD     VARCHAR2(3 BYTE)              NOT NULL,
  SPORT           VARCHAR2(3 BYTE)              NOT NULL,
  DESCR           VARCHAR2(30 BYTE)             NOT NULL
)
COMPRESS BASIC
/
