CREATE TABLE UM_D_XLATITEM
(
  FIELDNAME        VARCHAR2(30 BYTE),
  FIELDVALUE       VARCHAR2(4 BYTE),
  SRC_SYS_ID       VARCHAR2(5 BYTE),
  XLATLONGNAME     VARCHAR2(30 BYTE),
  XLATSHORTNAME    VARCHAR2(10 BYTE),
  DATA_ORIGIN      VARCHAR2(1 BYTE),
  CREATED_EW_DTTM  DATE,
  LASTUPD_EW_DTTM  DATE
)
NOLOGGING 
COMPRESS BASIC
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
