DROP TABLE CSMRT_OWNER.PS_D_CUR_TERM CASCADE CONSTRAINTS
/

--
-- PS_D_CUR_TERM  (Table) 
--
CREATE TABLE CSMRT_OWNER.PS_D_CUR_TERM
(
  INSTITUTION_CD        VARCHAR2(5 CHAR)        NOT NULL,
  ACAD_CAR_CD           VARCHAR2(4 CHAR)        NOT NULL,
  CURRENT_TERM          VARCHAR2(4 CHAR)        NOT NULL,
  SRC_SYS_ID            VARCHAR2(5 CHAR)        NOT NULL,
  PREVIOUS_WINTER_TERM  VARCHAR2(4 CHAR),
  PREVIOUS_FALL_TERM    VARCHAR2(4 CHAR),
  PREVIOUS_SPRING_TERM  VARCHAR2(4 CHAR),
  PREVIOUS_SUMMER_TERM  VARCHAR2(4 CHAR),
  PREVIOUS_TRI_TERM     VARCHAR2(4 CHAR),
  PREVIOUS_TERM         VARCHAR2(4 CHAR),
  NEXT_TERM             VARCHAR2(4 CHAR),
  NEXT_WINTER_TERM      VARCHAR2(4 CHAR),
  NEXT_FALL_TERM        VARCHAR2(4 CHAR),
  NEXT_SPRING_TERM      VARCHAR2(4 CHAR),
  NEXT_SUMMER_TERM      VARCHAR2(4 CHAR),
  NEXT_TRI_TERM         VARCHAR2(4 CHAR),
  DATA_ORIGIN           VARCHAR2(1 CHAR)        NOT NULL,
  CREATED_EW_DTTM       DATE,
  LASTUPD_EW_DTTM       DATE
)
NOCOMPRESS
/


ALTER TABLE CSMRT_OWNER.PS_D_CUR_TERM ADD (
  CONSTRAINT PK_PS_D_CUR_TERM
  PRIMARY KEY
  (INSTITUTION_CD, ACAD_CAR_CD, CURRENT_TERM, SRC_SYS_ID)
  RELY
  ENABLE VALIDATE)
/
