DROP TABLE CSMRT_OWNER.UM_D_XLATITEM CASCADE CONSTRAINTS
/

--
-- UM_D_XLATITEM  (Table) 
--
CREATE TABLE CSMRT_OWNER.UM_D_XLATITEM
(
  FIELDNAME        VARCHAR2(30 BYTE)            NOT NULL,
  FIELDVALUE       VARCHAR2(4 BYTE)             NOT NULL,
  SRC_SYS_ID       VARCHAR2(5 BYTE)             NOT NULL,
  XLATLONGNAME     VARCHAR2(30 BYTE)            NOT NULL,
  XLATSHORTNAME    VARCHAR2(10 BYTE)            NOT NULL,
  DATA_ORIGIN      VARCHAR2(1 BYTE)             NOT NULL,
  CREATED_EW_DTTM  DATE,
  LASTUPD_EW_DTTM  DATE
)
COMPRESS BASIC
/


ALTER TABLE CSMRT_OWNER.UM_D_XLATITEM ADD (
  CONSTRAINT PK_UM_D_XLATITEM
  PRIMARY KEY
  (FIELDNAME, FIELDVALUE, SRC_SYS_ID)
  RELY
  DISABLE NOVALIDATE)
/
