DROP TABLE CSMRT_OWNER.UM_F_ADM_APPL_ENRL CASCADE CONSTRAINTS
/

--
-- UM_F_ADM_APPL_ENRL  (Table) 
--
CREATE TABLE CSMRT_OWNER.UM_F_ADM_APPL_ENRL
(
  ADM_APPL_SID     INTEGER                      NOT NULL,
  INSTITUTION_CD   VARCHAR2(5 BYTE)             NOT NULL,
  ACAD_CAR_CD      VARCHAR2(4 BYTE)             NOT NULL,
  ADMIT_TERM_CD    VARCHAR2(4 BYTE)             NOT NULL,
  SRC_SYS_ID       VARCHAR2(5 BYTE)             NOT NULL,
  PREV_TERM_CD     VARCHAR2(4 BYTE),
  PREV_TERM_SID    INTEGER,
  NEXT_TERM_CD     VARCHAR2(4 BYTE),
  NEXT_TERM_SID    INTEGER,
  ENROLL_CNT       INTEGER,
  PREV_ENROLL_CNT  INTEGER,
  NEXT_ENROLL_CNT  INTEGER
)
COMPRESS BASIC
/


ALTER TABLE CSMRT_OWNER.UM_F_ADM_APPL_ENRL ADD (
  CONSTRAINT PK_UM_F_ADM_APPL_ENRL
  PRIMARY KEY
  (ADM_APPL_SID)
  RELY
  ENABLE VALIDATE)
/
