DROP TABLE CSMRT_OWNER.UM_D_FA_SF_ITEM_TYPE_BRIDGE CASCADE CONSTRAINTS
/

--
-- UM_D_FA_SF_ITEM_TYPE_BRIDGE  (Table) 
--
CREATE TABLE CSMRT_OWNER.UM_D_FA_SF_ITEM_TYPE_BRIDGE
(
  INSTITUTION_CD    VARCHAR2(5 BYTE)            NOT NULL,
  AID_YEAR          VARCHAR2(4 BYTE)            NOT NULL,
  FA_ITEM_TYPE      VARCHAR2(12 BYTE)           NOT NULL,
  SF_ITEM_TYPE      VARCHAR2(12 BYTE),
  INSTITUTION_SID   INTEGER                     NOT NULL,
  FA_ITEM_TYPE_SID  INTEGER                     NOT NULL,
  SF_ITEM_TYPE_SID  INTEGER,
  EQUTN_VAR_CHAR1   VARCHAR2(20 BYTE),
  SRC_SYS_ID        VARCHAR2(5 CHAR)            NOT NULL,
  CREATED_EW_DTTM   DATE,
  LASTUPD_EW_DTTM   DATE,
  TREE_NODE_1       VARCHAR2(20 BYTE),
  TREE_NODE_2       VARCHAR2(20 BYTE),
  TREE_NODE_3       VARCHAR2(20 BYTE),
  TREE_NODE_4       VARCHAR2(20 BYTE),
  TREE_NODE_5       VARCHAR2(20 BYTE)
)
COMPRESS BASIC
/
