CREATE TABLE PS_D_CHKLST_STAT
(
  CHKLIST_STAT_SID  INTEGER,
  CHKLIST_STAT_ID   VARCHAR2(4 BYTE),
  SRC_SYS_ID        VARCHAR2(5 BYTE),
  CHKLIST_STAT_SD   VARCHAR2(10 BYTE),
  CHKLIST_STAT_LD   VARCHAR2(30 BYTE),
  DATA_ORIGIN       VARCHAR2(1 BYTE),
  CREATED_EW_DTTM   DATE,
  LASTUPD_EW_DTTM   DATE
)
NOLOGGING 
COMPRESS BASIC
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
