DROP TABLE CSMRT_OWNER.UM_D_PRSPCT_PLAN CASCADE CONSTRAINTS
/

--
-- UM_D_PRSPCT_PLAN  (Table) 
--
CREATE TABLE CSMRT_OWNER.UM_D_PRSPCT_PLAN
(
  PRSPCT_PLAN_SID  NUMBER(10)                   NOT NULL,
  INSTITUTION_CD   VARCHAR2(5 BYTE)             NOT NULL,
  ACAD_CAR_CD      VARCHAR2(4 BYTE)             NOT NULL,
  ADMIT_TERM       VARCHAR2(4 BYTE)             NOT NULL,
  EMPLID           VARCHAR2(11 BYTE)            NOT NULL,
  ACAD_PROG_CD     VARCHAR2(5 BYTE)             NOT NULL,
  ACAD_PLAN_CD     VARCHAR2(10 BYTE)            NOT NULL,
  SRC_SYS_ID       VARCHAR2(5 BYTE)             NOT NULL,
  ACAD_PLAN_SID    NUMBER(10)                   NOT NULL,
  ACAD_PROG_SID    NUMBER(10)                   NOT NULL,
  ADM_RECR_CTR     VARCHAR2(4 BYTE)             NOT NULL,
  PRSPCT_PROG_SID  NUMBER(10)                   NOT NULL,
  RECRT_CNTR_SID   NUMBER(10)                   NOT NULL,
  LOAD_ERROR       VARCHAR2(1 BYTE)             NOT NULL,
  DATA_ORIGIN      VARCHAR2(1 BYTE)             NOT NULL,
  CREATED_EW_DTTM  DATE,
  LASTUPD_EW_DTTM  DATE,
  BATCH_SID        NUMBER(10)                   NOT NULL
)
NOCOMPRESS
/


ALTER TABLE CSMRT_OWNER.UM_D_PRSPCT_PLAN ADD (
  CONSTRAINT PK_UM_D_PRSPCT_PLAN
  PRIMARY KEY
  (PRSPCT_PLAN_SID)
  RELY
  DISABLE NOVALIDATE)
/
