CREATE TABLE UM_D_EXT_CRSE
(
  EXT_CRSE_SID          INTEGER,
  EXT_ORG_ID            VARCHAR2(11 BYTE),
  SCHOOL_SUBJECT        VARCHAR2(8 BYTE),
  SCHOOL_CRSE_NBR       VARCHAR2(10 BYTE),
  SRC_SYS_ID            VARCHAR2(5 BYTE),
  EFFDT                 DATE,
  EFF_STATUS            VARCHAR2(1 BYTE),
  DESCRSHORT            VARCHAR2(10 BYTE),
  DESCR                 VARCHAR2(30 BYTE),
  EXT_SUBJECT_AREA_SID  INTEGER,
  COURSE_LEVEL          VARCHAR2(2 BYTE),
  EXT_CAREER            VARCHAR2(4 BYTE),
  EXT_CAREER_SD         VARCHAR2(10 BYTE),
  EXT_CAREER_LD         VARCHAR2(30 BYTE),
  EXT_CRSE_TYPE         VARCHAR2(3 BYTE),
  EXT_CRSE_TYPE_SD      VARCHAR2(10 BYTE),
  EXT_CRSE_TYPE_LD      VARCHAR2(30 BYTE),
  EXT_UNITS             NUMBER(5,2),
  DATA_ORIGIN           VARCHAR2(1 BYTE),
  CREATED_EW_DTTM       DATE,
  LASTUPD_EW_DTTM       DATE
)
NOLOGGING 
COMPRESS BASIC
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
