DROP TABLE CSMRT_OWNER.PS_D_AWD CASCADE CONSTRAINTS
/

--
-- PS_D_AWD  (Table) 
--
CREATE TABLE CSMRT_OWNER.PS_D_AWD
(
  AWD_SID          INTEGER                      NOT NULL,
  INSTITUTION_CD   VARCHAR2(5 CHAR)             NOT NULL,
  AWD_CD           VARCHAR2(6 CHAR)             NOT NULL,
  SRC_SYS_ID       VARCHAR2(5 CHAR)             NOT NULL,
  EFFDT            DATE,
  EFF_STAT_CD      VARCHAR2(1 CHAR)             NOT NULL,
  AWD_SD           VARCHAR2(10 CHAR)            NOT NULL,
  AWD_LD           VARCHAR2(30 CHAR)            NOT NULL,
  AWD_FD           VARCHAR2(50 CHAR)            NOT NULL,
  INT_EXT_CD       VARCHAR2(1 CHAR)             NOT NULL,
  INT_EXT_SD       VARCHAR2(10 CHAR)            NOT NULL,
  INT_EXT_LD       VARCHAR2(30 CHAR)            NOT NULL,
  GRANTOR_NM       VARCHAR2(20 CHAR)            NOT NULL,
  DATA_ORIGIN      VARCHAR2(1 CHAR)             NOT NULL,
  CREATED_EW_DTTM  DATE,
  LASTUPD_EW_DTTM  DATE
)
COMPRESS BASIC
/


ALTER TABLE CSMRT_OWNER.PS_D_AWD ADD (
  CONSTRAINT PK_PS_D_AWD
  PRIMARY KEY
  (AWD_SID)
  RELY
  DISABLE NOVALIDATE)
/
