DROP TABLE CSMRT_OWNER.UM_F_STDNT_RESPONSE CASCADE CONSTRAINTS
/

--
-- UM_F_STDNT_RESPONSE  (Table) 
--
CREATE TABLE CSMRT_OWNER.UM_F_STDNT_RESPONSE
(
  PERSON_ID        VARCHAR2(11 BYTE)            NOT NULL,
  ACAD_CAR_CD      VARCHAR2(5 BYTE)             NOT NULL,
  STU_CAR_NBR      INTEGER                      NOT NULL,
  ADM_APPL_NBR     VARCHAR2(8 BYTE)             NOT NULL,
  SEQNUM           INTEGER                      NOT NULL,
  SRC_SYS_ID       VARCHAR2(5 BYTE)             NOT NULL,
  INSTITUTION_CD   VARCHAR2(5 BYTE)             NOT NULL,
  INSTITUTION_SID  INTEGER                      NOT NULL,
  PERSON_SID       INTEGER                      NOT NULL,
  ACAD_CAR_SID     INTEGER                      NOT NULL,
  EXT_ORG_SID      INTEGER                      NOT NULL,
  RESPONSE_REASON  VARCHAR2(4 BYTE),
  RESPONSE_DT      DATE,
  EXT_ORG_ID       VARCHAR2(11 BYTE),
  DESCR            VARCHAR2(30 BYTE),
  RSN_DESCR        VARCHAR2(30 BYTE),
  RSN_DESCRSHORT   VARCHAR2(10 BYTE),
  LOAD_ERROR       VARCHAR2(1 BYTE),
  DATA_ORIGIN      VARCHAR2(1 BYTE),
  CREATED_EW_DTTM  DATE,
  LASTUPD_EW_DTTM  DATE,
  BATCH_SID        INTEGER
)
COMPRESS BASIC
/


ALTER TABLE CSMRT_OWNER.UM_F_STDNT_RESPONSE ADD (
  CONSTRAINT PK_UM_F_STDNT_RESPONSE
  PRIMARY KEY
  (PERSON_ID, ACAD_CAR_CD, STU_CAR_NBR, ADM_APPL_NBR, SEQNUM, SRC_SYS_ID)
  RELY
  ENABLE VALIDATE)
/
