DROP TABLE CSMRT_OWNER.UM_F_EXT_TESTSCORE CASCADE CONSTRAINTS
/

--
-- UM_F_EXT_TESTSCORE  (Table) 
--
CREATE TABLE CSMRT_OWNER.UM_F_EXT_TESTSCORE
(
  PERSON_SID          INTEGER                   NOT NULL,
  EXT_TST_CMPNT_SID   INTEGER                   NOT NULL,
  EXT_TST_DT          DATE,
  TST_DATA_SRC_SID    INTEGER                   NOT NULL,
  SRC_SYS_ID          VARCHAR2(5 BYTE)          NOT NULL,
  PERSON_ID           VARCHAR2(11 BYTE)         NOT NULL,
  TEST_ID             VARCHAR2(11 BYTE)         NOT NULL,
  TEST_CMPNT_ID       VARCHAR2(5 BYTE)          NOT NULL,
  TEST_DATA_SRC_ID    VARCHAR2(4 BYTE)          NOT NULL,
  EXT_ACAD_LVL_SID    INTEGER                   NOT NULL,
  NUMERIC_SCORE       NUMBER(6,2),
  LETTER_SCORE        VARCHAR2(4 BYTE),
  SCORE_PERCENTILE    INTEGER,
  LOAD_DT             DATE,
  TEST_ADMIN          VARCHAR2(1 BYTE),
  TEST_INDEX          NUMBER(6,1),
  MAX_SCORE           NUMBER(6,2),
  MIN_SCORE           NUMBER(6,2),
  TEST_CMPNT_ORDER    INTEGER,
  TEST_DT_ORDER       INTEGER,
  TEST_SUM_ORDER      INTEGER,
  TEST_SOURCE_ORDER   INTEGER,
  BEST_SCORE_FLG      VARCHAR2(1 BYTE),
  HIGHEST_SCORE_FLG   VARCHAR2(1 BYTE),
  LATEST_TEST_DT_FLG  VARCHAR2(1 BYTE),
  CONV_FLG            VARCHAR2(1 BYTE)
)
COMPRESS BASIC
/


ALTER TABLE CSMRT_OWNER.UM_F_EXT_TESTSCORE ADD (
  CONSTRAINT PK_UM_F_EXT_TESTSCORE
  PRIMARY KEY
  (PERSON_SID, EXT_TST_CMPNT_SID, EXT_TST_DT, TST_DATA_SRC_SID, SRC_SYS_ID)
  RELY
  ENABLE VALIDATE)
/
