CREATE TABLE UM_D_PRSPCT_SBPLAN
(
  PRSPCT_SPLAN_SID  INTEGER,
  INSTITUTION_CD    VARCHAR2(5 BYTE),
  ACAD_CAR_CD       VARCHAR2(4 BYTE),
  EMPLID            VARCHAR2(11 BYTE),
  ACAD_PROG_CD      VARCHAR2(5 BYTE),
  ACAD_PLAN_CD      VARCHAR2(10 BYTE),
  ACAD_SUB_PLAN_CD  VARCHAR2(10 BYTE),
  SRC_SYS_ID        VARCHAR2(5 BYTE),
  PRSPCT_PLAN_SID   INTEGER,
  ACAD_SPLAN_SID    INTEGER,
  LOAD_ERROR        VARCHAR2(1 BYTE),
  DATA_ORIGIN       VARCHAR2(1 BYTE),
  CREATED_EW_DTTM   DATE,
  LASTUPD_EW_DTTM   DATE,
  BATCH_SID         NUMBER(10)
)
NOLOGGING 
COMPRESS BASIC
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
