DROP TABLE CSMRT_OWNER.UM_D_CRSE_TOPIC CASCADE CONSTRAINTS
/

--
-- UM_D_CRSE_TOPIC  (Table) 
--
CREATE TABLE CSMRT_OWNER.UM_D_CRSE_TOPIC
(
  CRSE_TOPIC_SID       INTEGER                  NOT NULL,
  CRSE_CD              VARCHAR2(6 BYTE)         NOT NULL,
  CRSE_OFFER_NUM       INTEGER                  NOT NULL,
  CRSE_TOPIC_ID        INTEGER                  NOT NULL,
  SRC_SYS_ID           VARCHAR2(5 BYTE)         NOT NULL,
  EFFDT                DATE,
  DESCRSHORT           VARCHAR2(10 BYTE)        NOT NULL,
  DESCR                VARCHAR2(30 BYTE)        NOT NULL,
  DESCRFORMAL          VARCHAR2(50 BYTE)        NOT NULL,
  CRSE_SID             INTEGER                  NOT NULL,
  CRSE_REPEATABLE_FLG  VARCHAR2(1 BYTE)         NOT NULL,
  CRSE_REPEAT_LIMIT    INTEGER                  NOT NULL,
  CRS_TOPIC_LINK       INTEGER                  NOT NULL,
  UNITS_REPEAT_LIMIT   NUMBER(5,2)              NOT NULL,
  DATA_ORIGIN          VARCHAR2(1 BYTE)         NOT NULL,
  CREATED_EW_DTTM      DATE,
  LASTUPD_EW_DTTM      DATE
)
COMPRESS BASIC
/


ALTER TABLE CSMRT_OWNER.UM_D_CRSE_TOPIC ADD (
  CONSTRAINT PK_UM_D_CRSE_TOPIC
  PRIMARY KEY
  (CRSE_TOPIC_SID)
  RELY
  ENABLE VALIDATE)
/
