DROP TABLE CSMRT_OWNER.PS_D_RECRTR CASCADE CONSTRAINTS
/

--
-- PS_D_RECRTR  (Table) 
--
CREATE TABLE CSMRT_OWNER.PS_D_RECRTR
(
  RECRTR_SID         INTEGER                    NOT NULL,
  INSTITUTION_CD     VARCHAR2(5 CHAR)           NOT NULL,
  ACAD_CAR_CD        VARCHAR2(4 CHAR)           NOT NULL,
  RECRUITER_ID       VARCHAR2(11 CHAR)          NOT NULL,
  SRC_SYS_ID         VARCHAR2(5 CHAR)           NOT NULL,
  RECRUITER_NAME     VARCHAR2(50 CHAR)          NOT NULL,
  RECRUITER_TYPE     VARCHAR2(4 CHAR)           NOT NULL,
  RECRUITER_TYPE_SD  VARCHAR2(10 CHAR)          NOT NULL,
  RECRUITER_TYPE_LD  VARCHAR2(30 CHAR)          NOT NULL,
  DATA_ORIGIN        VARCHAR2(1 CHAR)           NOT NULL,
  CREATED_EW_DTTM    DATE,
  LASTUPD_EW_DTTM    DATE
)
COMPRESS BASIC
/


ALTER TABLE CSMRT_OWNER.PS_D_RECRTR ADD (
  CONSTRAINT PK_PS_D_RECRTR
  PRIMARY KEY
  (RECRTR_SID)
  RELY
  DISABLE NOVALIDATE)
/
