DROP TABLE CSMRT_OWNER.UM_S_SF_ITEM_LINE CASCADE CONSTRAINTS
/

--
-- UM_S_SF_ITEM_LINE  (Table) 
--
CREATE TABLE CSMRT_OWNER.UM_S_SF_ITEM_LINE
(
  UM_FISCAL_YEAR      INTEGER,
  INSTITUTION_CD      VARCHAR2(5 BYTE)          NOT NULL,
  PERSON_ID           VARCHAR2(11 BYTE)         NOT NULL,
  SA_ID_TYPE          VARCHAR2(1 BYTE)          NOT NULL,
  ITEM_NBR            VARCHAR2(15 BYTE)         NOT NULL,
  LINE_SEQ_NBR        INTEGER                   NOT NULL,
  SRC_SYS_ID          VARCHAR2(5 BYTE)          NOT NULL,
  INSTITUTION_SID     INTEGER                   NOT NULL,
  ACAD_CAR_SID        INTEGER                   NOT NULL,
  PERSON_SID          INTEGER                   NOT NULL,
  ITEM_TERM_SID       INTEGER                   NOT NULL,
  ACCOUNT_TERM_SID    INTEGER                   NOT NULL,
  ITEM_TYPE_SID       INTEGER                   NOT NULL,
  ACAD_CAREER         VARCHAR2(4 BYTE)          NOT NULL,
  ACCOUNT_NBR         VARCHAR2(10 BYTE),
  ACCOUNT_TERM        VARCHAR2(4 BYTE),
  ACCOUNT_TERM_LD     VARCHAR2(30 BYTE),
  ITEM_TERM           VARCHAR2(4 BYTE),
  ITEM_TERM_LD        VARCHAR2(30 BYTE),
  AGING_DT            DATE,
  ACTUAL_BILLING_DT   DATE,
  BILLING_DT          DATE,
  BILLING_FLAG        VARCHAR2(1 BYTE),
  CLASS_NBR           INTEGER,
  CLASS_PRICE_DTTM    DATE,
  DESCR               VARCHAR2(30 BYTE),
  DUE_AMT             NUMBER(16,2),
  DUE_DT              DATE,
  DUE_DATE_BY         VARCHAR2(3 BYTE),
  DUE_DATE_BY_SD      VARCHAR2(10 BYTE),
  DUE_DATE_BY_LD      VARCHAR2(30 BYTE),
  ENCUMBRANCE_DT      DATE,
  FEE_CD              VARCHAR2(6 BYTE),
  FINANCE_CHARGE      VARCHAR2(8 BYTE),
  GL_POSTING_DTTM     DATE,
  ITEM_EFFECTIVE_DT   DATE,
  ITEM_TYPE_CD        VARCHAR2(1 BYTE),
  ITEM_TYPE_SD        VARCHAR2(10 BYTE),
  ITEM_TYPE_LD        VARCHAR2(30 BYTE),
  LINE_AMT            NUMBER(16,2),
  LINE_STATUS         VARCHAR2(1 BYTE),
  LINE_STATUS_SD      VARCHAR2(10 BYTE),
  LINE_STATUS_LD      VARCHAR2(30 BYTE),
  LINE_ACTION         VARCHAR2(4 BYTE),
  LINE_ACTION_SD      VARCHAR2(10 BYTE),
  LINE_ACTION_LD      VARCHAR2(30 BYTE),
  LINE_REASON_CD      VARCHAR2(4 BYTE),
  LINE_REASON_SD      VARCHAR2(10 BYTE),
  LINE_REASON_LD      VARCHAR2(30 BYTE),
  OPRID               VARCHAR2(30 BYTE),
  ORIG_DUE_DATE       DATE,
  PAYMENT_ID_NBR      NUMBER(12),
  POSTED_DATE         DATE,
  REF1_DESCR          VARCHAR2(30 BYTE),
  REFUND_NBR          NUMBER(12),
  REFUND_EMPLID       VARCHAR2(11 BYTE),
  SEL_GROUP           VARCHAR2(10 BYTE),
  SESSION_CODE        VARCHAR2(3 BYTE),
  STDNT_CAR_NBR       INTEGER,
  SCC_ROW_ADD_OPRID   VARCHAR2(30 BYTE),
  SCC_ROW_ADD_DTTM    DATE,
  SCC_ROW_UPD_OPRID   VARCHAR2(30 BYTE),
  SCC_ROW_UPD_DTTM    DATE,
  ACCOUNT_TYPE_SF     VARCHAR2(3 BYTE),
  ACCT_STATUS         VARCHAR2(1 BYTE),
  OPEN_DT             DATE,
  CLOSE_DT            DATE,
  ACCOUNT_BALANCE     NUMBER(16,2),
  LAST_AGING_DT       DATE,
  LAST_ACCT_DT_AGED   DATE,
  BILL_REQ_ID         VARCHAR2(10 BYTE),
  OVERR_BILL_REQ_ID   VARCHAR2(10 BYTE),
  INCLUDE_IN_BALANCE  VARCHAR2(1 BYTE),
  INCLUDE_BILLING     VARCHAR2(1 BYTE),
  INCLUDE_TRANSFER    VARCHAR2(1 BYTE),
  INCLUDE_PREPAY      VARCHAR2(1 BYTE),
  LOAD_ERROR          VARCHAR2(1 BYTE)          NOT NULL,
  DATA_ORIGIN         VARCHAR2(1 BYTE)          NOT NULL,
  CREATED_EW_DTTM     DATE,
  LASTUPD_EW_DTTM     DATE,
  BATCH_SID           NUMBER(10)                NOT NULL,
  UM_SNAPSHOT_DT      DATE
)
NOCOMPRESS 
PARTITION BY LIST (UM_FISCAL_YEAR)
(  
  PARTITION FY_2021 VALUES (2021)
    NOCOMPRESS
)
/


ALTER TABLE CSMRT_OWNER.UM_S_SF_ITEM_LINE ADD (
  CONSTRAINT PK_UM_S_SF_ITEM_LINE
  PRIMARY KEY
  (INSTITUTION_CD, PERSON_ID, SA_ID_TYPE, ITEM_NBR, LINE_SEQ_NBR, SRC_SYS_ID, UM_FISCAL_YEAR)
  RELY
  ENABLE VALIDATE)
/
