DROP TABLE CSMRT_OWNER.PS_F_DEGREES CASCADE CONSTRAINTS
/

--
-- PS_F_DEGREES  (Table) 
--
CREATE TABLE CSMRT_OWNER.PS_F_DEGREES
(
  PERSON_ID           VARCHAR2(11 BYTE)         NOT NULL,
  DEGREE_NBR          INTEGER                   NOT NULL,
  ACAD_PLAN_CD        VARCHAR2(10 BYTE)         NOT NULL,
  ACAD_SPLAN_CD       VARCHAR2(10 BYTE)         NOT NULL,
  SRC_SYS_ID          VARCHAR2(5 BYTE)          NOT NULL,
  INSTITUTION_CD      VARCHAR2(5 BYTE)          NOT NULL,
  ACAD_CAR_CD         VARCHAR2(8 BYTE)          NOT NULL,
  DEG_CD              VARCHAR2(8 BYTE)          NOT NULL,
  INSTITUTION_SID     INTEGER                   NOT NULL,
  ACAD_CAR_SID        INTEGER                   NOT NULL,
  PERSON_SID          INTEGER                   NOT NULL,
  DEG_SID             INTEGER                   NOT NULL,
  ACAD_PLAN_SID       INTEGER                   NOT NULL,
  ACAD_SPLAN_SID      INTEGER                   NOT NULL,
  ACAD_DEGR_STAT_SID  INTEGER                   NOT NULL,
  ACAD_PLAN_CAR_SID   INTEGER                   NOT NULL,
  COMPL_TERM_SID      INTEGER                   NOT NULL,
  HONORS_PREFIX_SID   INTEGER                   NOT NULL,
  HONORS_SUFFIX_SID   INTEGER                   NOT NULL,
  PLN_HONRS_PREF_SID  INTEGER                   NOT NULL,
  PLN_HONRS_SUFF_SID  INTEGER                   NOT NULL,
  SPLN_HNRS_PREF_SID  INTEGER                   NOT NULL,
  SPLN_HNRS_SUFF_SID  INTEGER                   NOT NULL,
  CLASS_RANK_NBR      INTEGER                   NOT NULL,
  CLASS_RANK_TOT      INTEGER                   NOT NULL,
  CONF_DT             DATE,
  DEGR_STAT_DT        DATE,
  GPA_DEGREE          NUMBER(9,3)               NOT NULL,
  GPA_PLAN            NUMBER(9,3)               NOT NULL,
  PLN_CLASS_RANK_NBR  INTEGER                   NOT NULL,
  PLN_CLASS_RANK_TOT  INTEGER                   NOT NULL,
  PLAN_DEGR_STATUS    VARCHAR2(1 CHAR)          NOT NULL,
  PLN_DEG_ST_DT       DATE,
  PLAN_DIPLOMA_DESCR  VARCHAR2(100 CHAR)        NOT NULL,
  PLAN_OVERRIDE_FLG   VARCHAR2(1 CHAR)          NOT NULL,
  PLAN_SEQUENCE       INTEGER                   NOT NULL,
  PLAN_TRNSCR_DESCR   VARCHAR2(100 CHAR)        NOT NULL,
  SPLAN_DIPLOMA_DESC  VARCHAR2(100 CHAR)        NOT NULL,
  SPLAN_OVERRIDE_FLG  VARCHAR2(1 CHAR)          NOT NULL,
  SPLAN_SEQUENCE      INTEGER                   NOT NULL,
  SPLAN_TRNSCR_DESCR  VARCHAR2(100 CHAR)        NOT NULL,
  STDNT_CAR_NBR       INTEGER                   NOT NULL,
  DEGREE_COUNT_AWD    INTEGER                   NOT NULL,
  DEGREE_COUNT_RVK    INTEGER                   NOT NULL,
  DEGREE_COUNT        INTEGER                   NOT NULL,
  LOAD_ERROR          VARCHAR2(1 CHAR)          NOT NULL,
  DATA_ORIGIN         VARCHAR2(1 CHAR)          NOT NULL,
  CREATED_EW_DTTM     DATE,
  LASTUPD_EW_DTTM     DATE,
  BATCH_SID           NUMBER(10)                NOT NULL
)
COMPRESS BASIC
/


ALTER TABLE CSMRT_OWNER.PS_F_DEGREES ADD (
  CONSTRAINT PK_PS_F_DEGREES
  PRIMARY KEY
  (PERSON_ID, DEGREE_NBR, ACAD_PLAN_CD, ACAD_SPLAN_CD, SRC_SYS_ID)
  RELY
  ENABLE VALIDATE)
/
