DROP TABLE CSMRT_OWNER.UM_F_SAA_ADB_COND CASCADE CONSTRAINTS
/

--
-- UM_F_SAA_ADB_COND  (Table) 
--
CREATE TABLE CSMRT_OWNER.UM_F_SAA_ADB_COND
(
  EMPLID           VARCHAR2(11 BYTE)            NOT NULL,
  ANALYSIS_DB_SEQ  INTEGER                      NOT NULL,
  SAA_CAREER_RPT   VARCHAR2(4 BYTE)             NOT NULL,
  COND_CODE        VARCHAR2(10 BYTE),
  COND_DATA        VARCHAR2(20 BYTE),
  SRC_SYS_ID       VARCHAR2(4 BYTE)             NOT NULL,
  INSTITUTION_CD   VARCHAR2(5 BYTE),
  CREATED_EW_DTTM  DATE
)
COMPRESS BASIC
/


ALTER TABLE CSMRT_OWNER.UM_F_SAA_ADB_COND ADD (
  CONSTRAINT PK_UM_F_SAA_ADB_COND
  PRIMARY KEY
  (EMPLID, ANALYSIS_DB_SEQ, SAA_CAREER_RPT, COND_CODE, COND_DATA, SRC_SYS_ID)
  RELY
  ENABLE VALIDATE)
/
