DROP TABLE CSMRT_OWNER.UM_F_STDNT_TRNS_TEST_DTL CASCADE CONSTRAINTS
/

--
-- UM_F_STDNT_TRNS_TEST_DTL  (Table) 
--
CREATE TABLE CSMRT_OWNER.UM_F_STDNT_TRNS_TEST_DTL
(
  ARTICULATION_TERM_SID  INTEGER                NOT NULL,
  PERSON_SID             INTEGER                NOT NULL,
  MODEL_NBR              INTEGER                NOT NULL,
  TRNSFR_EQVLNCY_GRP     INTEGER                NOT NULL,
  TRNSFR_EQVLNCY_SEQ     INTEGER                NOT NULL,
  SRC_SYS_ID             VARCHAR2(5 BYTE)       NOT NULL,
  INSTITUTION_CD         VARCHAR2(5 BYTE)       NOT NULL,
  ACAD_CAR_CD            VARCHAR2(4 BYTE)       NOT NULL,
  ARTICULATION_TERM      NUMBER(4)              NOT NULL,
  PERSON_ID              VARCHAR2(11 BYTE)      NOT NULL,
  INSTITUTION_SID        INTEGER                NOT NULL,
  ACAD_CAR_SID           INTEGER                NOT NULL,
  CRSE_SID               INTEGER                NOT NULL,
  OPRID_SID              INTEGER                NOT NULL,
  CRSE_GRADE_OFF         VARCHAR2(3 BYTE),
  DESCR                  VARCHAR2(30 BYTE),
  EARN_CREDIT            VARCHAR2(1 BYTE),
  FREEZE_REC_FL          VARCHAR2(1 BYTE),
  GRADE_CATEGORY         VARCHAR2(4 BYTE),
  GRADING_SCHEME         VARCHAR2(3 BYTE),
  GRADING_SCHEME_SD      VARCHAR2(10 BYTE),
  GRADING_SCHEME_LD      VARCHAR2(30 BYTE),
  GRADING_BASIS          VARCHAR2(3 BYTE),
  GRADING_BASIS_SD       VARCHAR2(10 BYTE),
  GRADING_BASIS_LD       VARCHAR2(30 BYTE),
  GRD_PTS_PER_UNIT       NUMBER(9,3),
  INCLUDE_IN_GPA         VARCHAR2(1 BYTE),
  INPUT_CHG_FL           VARCHAR2(1 BYTE),
  LS_DATA_SOURCE         VARCHAR2(3 BYTE),
  OVRD_RSN               VARCHAR2(50 BYTE),
  OVRD_TRCR_FL           VARCHAR2(1 BYTE),
  PERCENTILE             INTEGER,
  REJECT_REASON          VARCHAR2(2 BYTE),
  REPEAT_CODE            VARCHAR2(4 BYTE),
  RQMNT_DESIGNTN         VARCHAR2(4 BYTE),
  RQMNT_DESIGNTN_LD      VARCHAR2(30 BYTE),
  SCORE                  NUMBER(6,2),
  SSR_FAWI_INCL          VARCHAR2(1 BYTE),
  TEST_DT                DATE,
  TST_EQVLNCY            VARCHAR2(6 BYTE),
  TEST_ID                VARCHAR2(11 BYTE),
  TEST_ID_LD             VARCHAR2(30 BYTE),
  TEST_COMPONENT         VARCHAR2(5 BYTE),
  TEST_COMPONENT_LD      VARCHAR2(30 BYTE),
  TRNSFR_EQVLNCY_CMP     VARCHAR2(4 BYTE),
  TRNSFR_STAT            VARCHAR2(1 BYTE),
  TRNSFR_STAT_SD         VARCHAR2(30 BYTE),
  TRNSFR_STAT_LD         VARCHAR2(30 BYTE),
  UNITS_ATTEMPTED        VARCHAR2(1 BYTE),
  UNT_TRNSFR             NUMBER(8,3),
  VALID_ATTEMPT          VARCHAR2(1 BYTE),
  COMMENTS               VARCHAR2(4000 BYTE),
  LOAD_ERROR             VARCHAR2(1 BYTE)       NOT NULL,
  DATA_ORIGIN            VARCHAR2(1 BYTE)       NOT NULL,
  CREATED_EW_DTTM        DATE                   NOT NULL,
  LASTUPD_EW_DTTM        DATE                   NOT NULL,
  BATCH_SID              NUMBER(10)             NOT NULL
)
COMPRESS BASIC
/


ALTER TABLE CSMRT_OWNER.UM_F_STDNT_TRNS_TEST_DTL ADD (
  CONSTRAINT PK_UM_F_STDNT_TRNS_TEST_DTL
  PRIMARY KEY
  (ARTICULATION_TERM, PERSON_ID, ACAD_CAR_CD, INSTITUTION_CD, MODEL_NBR, TRNSFR_EQVLNCY_GRP, TRNSFR_EQVLNCY_SEQ, SRC_SYS_ID)
  RELY
  ENABLE VALIDATE)
/
