CREATE TABLE PS_D_EXT_ACAD_LVL
(
  EXT_ACAD_LVL_SID  INTEGER,
  EXT_ACAD_LVL_ID   VARCHAR2(4 CHAR),
  SRC_SYS_ID        VARCHAR2(5 CHAR),
  EXT_ACAD_LVL_SD   VARCHAR2(10 CHAR),
  EXT_ACAD_LVL_LD   VARCHAR2(30 CHAR),
  DATA_ORIGIN       VARCHAR2(1 CHAR),
  CREATED_EW_DTTM   DATE,
  LASTUPD_EW_DTTM   DATE
)
NOLOGGING 
COMPRESS BASIC
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
