CREATE TABLE UM_F_ADM_APPL_EXT_DEG
(
  APPLCNT_SID             INTEGER,
  INSTITUTION_SID         INTEGER,
  EXT_ORG_SID             INTEGER,
  EXT_ACAD_CAR_SID        INTEGER,
  EXT_DATA_NBR            INTEGER,
  EXT_DEG_NBR             INTEGER,
  SRC_SYS_ID              VARCHAR2(5 BYTE),
  INSTITUTION_CD          VARCHAR2(5 BYTE),
  EMPLID                  VARCHAR2(11 BYTE),
  EXT_ORG_ID              VARCHAR2(11 BYTE),
  EXT_ACAD_CAR_ID         VARCHAR2(4 BYTE),
  DESCR                   VARCHAR2(30 BYTE),
  EXT_DEG_SID             INTEGER,
  EXT_DATA_SRC_SID        INTEGER,
  EXT_SUBJECT_AREA_SID_1  INTEGER,
  EXT_SUBJECT_AREA_SID_2  INTEGER,
  EXT_CAREER              VARCHAR2(4 BYTE),
  EXT_CAREER_SD           VARCHAR2(10 BYTE),
  EXT_CAREER_LD           VARCHAR2(30 BYTE),
  EXT_DEG_DT              DATE,
  EXT_DEG_STAT_ID         VARCHAR2(1 BYTE),
  EXT_DEG_STAT_SD         VARCHAR2(10 BYTE),
  EXT_DEG_STAT_LD         VARCHAR2(30 BYTE),
  FIELD_OF_STUDY_1        VARCHAR2(30 BYTE),
  FIELD_OF_STUDY_2        VARCHAR2(30 BYTE),
  HONORS_CATEGORY         VARCHAR2(4 BYTE),
  HONORS_CATEGORY_SD      VARCHAR2(10 BYTE),
  HONORS_CATEGORY_LD      VARCHAR2(30 BYTE)
)
NOLOGGING 
COMPRESS BASIC
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
