CREATE TABLE UM_F_FA_STDNT_AWRD_ACTV
(
  INSTITUTION_CD        VARCHAR2(5 BYTE),
  ACAD_CAR_CD           VARCHAR2(4 BYTE),
  AID_YEAR              VARCHAR2(4 BYTE),
  PERSON_ID             VARCHAR2(11 BYTE),
  ITEM_TYPE             VARCHAR2(12 BYTE),
  ACTION_DTTM           TIMESTAMP(6),
  SRC_SYS_ID            VARCHAR2(5 BYTE),
  INSTITUTION_SID       INTEGER,
  ACAD_CAR_SID          INTEGER,
  PERSON_SID            INTEGER,
  ITEM_TYPE_SID         INTEGER,
  DISBURSEMENT_PLAN     VARCHAR2(2 BYTE),
  SPLIT_CODE            VARCHAR2(2 BYTE),
  DISBURSEMENT_ID       VARCHAR2(2 BYTE),
  OPRID                 VARCHAR2(30 BYTE),
  AWARD_DISB_ACTION     VARCHAR2(1 BYTE),
  AWARD_DISB_ACTION_LD  VARCHAR2(30 BYTE),
  OFFER_AMOUNT          NUMBER(11,2),
  ACCEPT_AMOUNT         NUMBER(11,2),
  AUTHORIZED_AMOUNT     NUMBER(11,2),
  DISB_AMOUNT           NUMBER(11,2),
  CURRENCY_CD           VARCHAR2(3 BYTE),
  BUSINESS_UNIT         VARCHAR2(5 BYTE),
  ADJUST_REASON_CD      VARCHAR2(3 BYTE),
  ADJUST_REASON_LD      VARCHAR2(50 BYTE),
  ADJUST_AMOUNT         NUMBER(11,2),
  LOAN_ADJUST_CD        VARCHAR2(1 BYTE),
  LOAN_ADJUST_LD        VARCHAR2(30 BYTE),
  DISB_TO_DATE          NUMBER(11,2),
  AUTH_TO_DATE          NUMBER(11,2),
  PKG_APP_DATA_USED     VARCHAR2(1 BYTE),
  LOAD_ERROR            VARCHAR2(1 BYTE),
  DATA_ORIGIN           VARCHAR2(1 BYTE),
  CREATED_EW_DTTM       DATE,
  LASTUPD_EW_DTTM       DATE,
  BATCH_SID             INTEGER
)
NOLOGGING 
COMPRESS BASIC
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
