DROP TABLE CSMRT_OWNER.PS_D_ACAD_ORG CASCADE CONSTRAINTS
/

--
-- PS_D_ACAD_ORG  (Table) 
--
CREATE TABLE CSMRT_OWNER.PS_D_ACAD_ORG
(
  ACAD_ORG_SID      INTEGER                     NOT NULL,
  EFFDT             DATE                        NOT NULL,
  ACAD_ORG_CD       VARCHAR2(10 CHAR)           NOT NULL,
  SRC_SYS_ID        VARCHAR2(5 CHAR)            NOT NULL,
  EFFDT_START       DATE                        NOT NULL,
  EFFDT_END         DATE                        NOT NULL,
  EFFDT_ORDER       INTEGER                     NOT NULL,
  EFF_STAT_CD       VARCHAR2(1 CHAR)            NOT NULL,
  ACAD_ORG_SD       VARCHAR2(10 CHAR)           NOT NULL,
  ACAD_ORG_LD       VARCHAR2(30 CHAR)           NOT NULL,
  ACAD_ORG_FD       VARCHAR2(50 CHAR)           NOT NULL,
  ACAD_ORG_CD_DESC  VARCHAR2(50 CHAR)           NOT NULL,
  INSTITUTION_CD    VARCHAR2(5 CHAR)            NOT NULL,
  DATA_ORIGIN       VARCHAR2(1 CHAR)            NOT NULL,
  CREATED_EW_DTTM   DATE,
  LASTUPD_EW_DTTM   DATE
)
COMPRESS BASIC
/


ALTER TABLE CSMRT_OWNER.PS_D_ACAD_ORG ADD (
  CONSTRAINT PK_PS_D_ACAD_ORG
  PRIMARY KEY
  (ACAD_ORG_SID, EFFDT)
  RELY
  DISABLE NOVALIDATE)
/
