DROP INDEX DLMRT_OWNER.NK_IR_PERSON_PRELIM
/

--
-- NK_IR_PERSON_PRELIM  (Index) 
--
CREATE UNIQUE INDEX DLMRT_OWNER.NK_IR_PERSON_PRELIM ON DLMRT_OWNER.IR_PERSON_PRELIM
(INSTITUTION, CENSUS_PERIOD, CENSUS_SEQ, PERSON_ID)
/
