DROP INDEX DLMRT_OWNER.NK_CENSUS_STATUS
/

--
-- NK_CENSUS_STATUS  (Index) 
--
CREATE UNIQUE INDEX DLMRT_OWNER.NK_CENSUS_STATUS ON DLMRT_OWNER.CENSUS_STATUS
(UPLOAD_TYPE, INSTITUTION, CENSUS_PERIOD, CENSUS_SEQ)
/
