DROP INDEX DLMRT_OWNER.NK_IR_CITIZENSHIP_DTL_PRELIM
/

--
-- NK_IR_CITIZENSHIP_DTL_PRELIM  (Index) 
--
CREATE UNIQUE INDEX DLMRT_OWNER.NK_IR_CITIZENSHIP_DTL_PRELIM ON DLMRT_OWNER.IR_CITIZENSHIP_DTL_PRELIM
(INSTITUTION, CENSUS_PERIOD, CENSUS_SEQ, PERSON_ID, COUNTRY_2CHAR)
/
