DROP VIEW DLMRT_OWNER.IR_CITIZENSHIP_DTL
/

--
-- IR_CITIZENSHIP_DTL  (View) 
--
CREATE OR REPLACE VIEW DLMRT_OWNER.IR_CITIZENSHIP_DTL
BEQUEATH DEFINER
AS 
SELECT  "UPLOAD_STATUS","INSTITUTION","CAMPUS","CENSUS_PERIOD","CENSUS_PERIOD_DESCR","CENSUS_SEQ","PERSON_ID","COUNTRY_2CHAR","COUNTRY_DESCR","CITIZENSHIP_CODE","CITIZENSHIP_STATUS","INSERT_TIME"
  FROM  DLMRT_OWNER.DL_CITIZENSHIP_DTL
/
