DROP VIEW DLMRT_OWNER.FIN_PLANNING_ENROLLMENT_VW
/

--
-- FIN_PLANNING_ENROLLMENT_VW  (View) 
--
CREATE OR REPLACE VIEW DLMRT_OWNER.FIN_PLANNING_ENROLLMENT_VW
BEQUEATH DEFINER
AS 
Select 
    INSTITUTION_CD,
    TERM_CD,
    TERM_LD,
    FISCAL_YEAR,
    PERSON_ID,
    ACAD_CAR_CD,
    ACAD_CAR_LD,
    RSDNCY_LD,
    RSDNCY_ID,
    TOT_CREDITS,
    DAY_CREDITS,
    CE_CREDITS,
    ONLINE_CREDITS,
    DAY_ONLINE_CREDITS,
    CE_ONLINE_CREDITS,
    TOT_FTE,
    DAY_FTE,
    CE_FTE,
    TOT_FFTE,
    DAY_FFTE,
    CE_FFTE,
    ACAD_PROG_CD,
    ACAD_PROG_LD,
    PROG_GRP_CD,
    PROG_GRP_LD,
    PROG_ORG_CD,
    PROG_ORG_LD,
    ACAD_PLAN_CD,
    ACAD_PLAN_LD,
    PLAN_ORG_CD,
    PLAN_ORG_LD,
    PLAN_PERCENT_OWNED,
    DEGREE_SEEKING_FLG,
    TAKEN_UNIT,
    CLASS_FFTE,
    CLASS_NUM,
    CRSE_CD,
    SBJCT_CD,
    SBJCT_LD,
    CATALOG_NBR,
    CLASS_TITLE,
    CLASS_CAREER_CD,
    CLASS_CAREER_LD,
    CLASS_GRP_CD,
    CLASS_GRP_LD,
    CLASS_ORG_CD,
    CLASS_ORG_LD,
    INSTRCTN_MODE_CD,
    INSTRCTN_MODE_LD,
    CRSE_LVL,
    ROW_NUM
    from CSMRT_OWNER.UM_M_AF_STDNT_CLASS_ENRL
/
