DROP VIEW DLMRT_OWNER.GWA_TEST_VW
/

--
-- GWA_TEST_VW  (View) 
--
CREATE OR REPLACE VIEW DLMRT_OWNER.GWA_TEST_VW
BEQUEATH DEFINER
AS 
select /*+ parallel(16) inline no_use_nl(TERM UMBOS) */
       'UMBOS' INSTITUTION_CD, PK1, EVENT_TYPE, USER_PK1, COURSE_PK1, GROUP_PK1, FORUM_PK1, INTERNAL_HANDLE, CONTENT_PK1, DATA, TIMESTAMP, STATUS, SESSION_ID,   -- Remove columns not needed
       TERM.TERM_CD
  from CSSTG_OWNER.BB_ACTIVITY_ACCUMULATOR_UMBOS UMBOS
  join CSMRT_OWNER.PS_D_TERM TERM
    on TERM.INSTITUTION_CD = 'UMBOS'
   and trunc(TIMESTAMP) between TERM.TERM_BEGIN_DT and TERM.TERM_END_DT
 where TERM.ACAD_CAR_CD = 'UGRD'
   and substr(TERM.TERM_CD,3,2) not in ('50','90')
   and TERM.EFF_START_DT between '01-JAN-2021' and '31-DEC-2050'
   and UMBOS.EVENT_TYPE NOT IN ('SESSION_TIMEOUT', 'START_IMPERSONATION')
   and UMBOS.USER_PK1 IS NOT NULL
   and UMBOS.COURSE_PK1 IS NOT NULL
/
