DROP TABLE DLMRT_OWNER.CIP CASCADE CONSTRAINTS
/

--
-- CIP  (Table) 
--
CREATE TABLE DLMRT_OWNER.CIP
(
  CIP_CODE                 VARCHAR2(7 BYTE),
  CIP_YEAR                 INTEGER,
  CIP_DESCR                VARCHAR2(30 BYTE),
  CIP_DESCR254             VARCHAR2(254 BYTE),
  UMPO_STEM                VARCHAR2(1 BYTE),
  CIP_CODE_FAMILY          VARCHAR2(3 BYTE),
  CIP_DESCR_FAMILY         VARCHAR2(30 BYTE),
  CIP_DESCR254_FAMILY      VARCHAR2(254 BYTE),
  CIP_CODE_DISCIPLINE      VARCHAR2(5 BYTE),
  CIP_DESCR_DISCIPLINE     VARCHAR2(30 BYTE),
  CIP_DESCR254_DISCIPLINE  VARCHAR2(254 BYTE),
  INSERT_TIME              DATE                 DEFAULT SYSDATE
)
COMPRESS BASIC
/

COMMENT ON TABLE DLMRT_OWNER.CIP IS 'Flattened Classification of Instructional Programs (CIP) data.'
/


ALTER TABLE DLMRT_OWNER.CIP ADD (
  CONSTRAINT PK_CIP
  PRIMARY KEY
  (CIP_CODE, CIP_YEAR)
  RELY
  ENABLE VALIDATE)
/
