DROP INDEX CSMRT_OWNER.AK_UM_F_STDNT_GRADE_RSTR8
/

--
-- AK_UM_F_STDNT_GRADE_RSTR8  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_STDNT_GRADE_RSTR8 ON CSMRT_OWNER.UM_F_STDNT_GRADE_RSTR
(INSTITUTION_SID)
/
