DROP INDEX CSMRT_OWNER.AK_F_ADM_APPL_ACAD_STRUCT_SPLN
/

--
-- AK_F_ADM_APPL_ACAD_STRUCT_SPLN  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_F_ADM_APPL_ACAD_STRUCT_SPLN ON CSMRT_OWNER.UM_F_ADM_APPL_ACAD_STRUCT
(ACAD_SPLAN_SID)
/
