DROP INDEX CSMRT_OWNER.FK_UM_F_ADM_APPL_ACAD_STRUCT22
/

--
-- FK_UM_F_ADM_APPL_ACAD_STRUCT22  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_ADM_APPL_ACAD_STRUCT22 ON CSMRT_OWNER.UM_F_ADM_APPL_ACAD_STRUCT
(COMPL_TERM_SID)
/
