DROP INDEX CSMRT_OWNER.AK_UM_F_FA_IR_CDS_DATA2
/

--
-- AK_UM_F_FA_IR_CDS_DATA2  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_FA_IR_CDS_DATA2 ON CSMRT_OWNER.UM_F_FA_IR_CDS_DATA
(INSTITUTION_SID)
/
