DROP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_AWARDS8
/

--
-- AK_UM_F_FA_STDNT_AWARDS8  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_AWARDS8 ON CSMRT_OWNER.UM_F_FA_STDNT_AWARDS
(ACAD_CAR_SID)
/
