DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_MV248
/

--
-- FK_UM_F_STDNT_TERM_STRUCT_MV248  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_MV248 ON CSMRT_OWNER.UM_F_STDNT_TERM_STRUCT_MV
(S_STACK_BEGIN_TERM_SID)
/
