DROP INDEX CSMRT_OWNER.AK_UM_F_STDNT_RESPONSE10
/

--
-- AK_UM_F_STDNT_RESPONSE10  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_STDNT_RESPONSE10 ON CSMRT_OWNER.UM_F_STDNT_RESPONSE
(ACAD_CAR_SID)
/
