DROP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_AWRD_ACTV11
/

--
-- AK_UM_F_FA_STDNT_AWRD_ACTV11  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_AWRD_ACTV11 ON CSMRT_OWNER.UM_F_FA_STDNT_AWRD_ACTV
(ITEM_TYPE_SID)
/
