DROP INDEX CSMRT_OWNER.PK_UM_F_FA_STDNT_BDGT
/

--
-- PK_UM_F_FA_STDNT_BDGT  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.PK_UM_F_FA_STDNT_BDGT ON CSMRT_OWNER.UM_F_FA_STDNT_BDGT
(INSTITUTION_CD, ACAD_CAR_CD, AID_YEAR, TERM_CD, PERSON_ID, 
SRC_SYS_ID)
/
