DROP INDEX CSMRT_OWNER.AK_UM_F_ADM_APPL_EXT21
/

--
-- AK_UM_F_ADM_APPL_EXT21  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_ADM_APPL_EXT21 ON CSMRT_OWNER.UM_F_ADM_APPL_EXT
(D_EXT_ACAD_LVL_SID)
/
