DROP INDEX CSMRT_OWNER.AK_UM_F_ADM_APPL_EXT11
/

--
-- AK_UM_F_ADM_APPL_EXT11  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_ADM_APPL_EXT11 ON CSMRT_OWNER.UM_F_ADM_APPL_EXT
(ACAD_UNIT_TYPE_SID)
/
