DROP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_SFA_SAP8
/

--
-- AK_UM_F_FA_STDNT_SFA_SAP8  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_SFA_SAP8 ON CSMRT_OWNER.UM_F_FA_STDNT_SFA_SAP
(ACAD_CAR_SID)
/
