DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_ADVR_MV262
/

--
-- FK_UM_F_STDNT_TERM_STRUCT_ADVR_MV262  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_ADVR_MV262 ON CSMRT_OWNER.UM_F_STDNT_TERM_STRUCT_ADVR_MV
(A_ACAD_PROG_SID)
/
