DROP INDEX CSMRT_OWNER.PK_UM_F_STDNT_ENRL_APPT
/

--
-- PK_UM_F_STDNT_ENRL_APPT  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.PK_UM_F_STDNT_ENRL_APPT ON CSMRT_OWNER.UM_F_STDNT_ENRL_APPT
(INSTITUTION_CD, ACAD_CAR_CD, TERM_CD, PERSON_ID, SESSION_CODE, 
SSR_APPT_BLOCK, APPOINTMENT_NBR, SRC_SYS_ID)
/
