DROP INDEX CSMRT_OWNER.AK_UM_D_PERSON_SRVC_IND6
/

--
-- AK_UM_D_PERSON_SRVC_IND6  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_D_PERSON_SRVC_IND6 ON CSMRT_OWNER.UM_D_PERSON_SRVC_IND
(INSTITUTION_SID)
/
