DROP INDEX CSMRT_OWNER.PK_UM_F_STDNT_TRANSFER
/

--
-- PK_UM_F_STDNT_TRANSFER  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.PK_UM_F_STDNT_TRANSFER ON CSMRT_OWNER.UM_F_STDNT_TRANSFER
(ARTICULATION_TERM_SID, PERSON_SID, MODEL_NBR, TRNSFR_EQVLNCY_GRP, TRNSFR_EQVLNCY_SEQ, 
SRC_SYS_ID)
/
