DROP INDEX CSMRT_OWNER.AK_UM_F_EXT_ACAD_CRSE11
/

--
-- AK_UM_F_EXT_ACAD_CRSE11  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_EXT_ACAD_CRSE11 ON CSMRT_OWNER.UM_F_EXT_ACAD_CRSE
(TST_DATA_SRC_SID)
/
