DROP INDEX CSMRT_OWNER.AK_UM_S_SF_ITEM_LINE7
/

--
-- AK_UM_S_SF_ITEM_LINE7  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_S_SF_ITEM_LINE7 ON CSMRT_OWNER.UM_S_SF_ITEM_LINE
(INSTITUTION_SID)
  LOCAL (  
  PARTITION FY_2021
)
/
