DROP INDEX CSMRT_OWNER.AK_F_ADM_APPL_ACAD_STRUCT_PER
/

--
-- AK_F_ADM_APPL_ACAD_STRUCT_PER  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_F_ADM_APPL_ACAD_STRUCT_PER ON CSMRT_OWNER.UM_F_ADM_APPL_ACAD_STRUCT
(PERSON_SID)
/
