DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_MV195
/

--
-- FK_UM_F_STDNT_TERM_MV195  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_MV195 ON CSMRT_OWNER.UM_F_STDNT_TERM_MV
(ENRLMT_PREV_TERM_SID)
/
