DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_MV48
/

--
-- FK_UM_F_STDNT_TERM_MV48  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_MV48 ON CSMRT_OWNER.UM_F_STDNT_TERM_MV
(TERM_ACAD_STNDNG_SID)
/
