DROP INDEX CSMRT_OWNER.UM_F_SAA_RES_CRSEAVL_MV10
/

--
-- UM_F_SAA_RES_CRSEAVL_MV10  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.UM_F_SAA_RES_CRSEAVL_MV10 ON CSMRT_OWNER.UM_F_SAA_RES_CRSEAVL_MV
(R_PERSON_SID)
/
