DROP INDEX CSMRT_OWNER.AK_F_ADM_APPL_TERM_ADV
/

--
-- AK_F_ADM_APPL_TERM_ADV  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_F_ADM_APPL_TERM_ADV ON CSMRT_OWNER.UM_F_ADM_APPL_TERM
(ACAD_GRP_ADVIS_SID)
/
