DROP INDEX CSMRT_OWNER.PK_UM_D_PERSON_PHONE
/

--
-- PK_UM_D_PERSON_PHONE  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.PK_UM_D_PERSON_PHONE ON CSMRT_OWNER.UM_D_PERSON_PHONE
(PERSON_ID, PHONE_TYPE, SRC_SYS_ID)
/
