DROP INDEX CSMRT_OWNER.AK_UM_D_CLASS_INSTRCTR15
/

--
-- AK_UM_D_CLASS_INSTRCTR15  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_D_CLASS_INSTRCTR15 ON CSMRT_OWNER.UM_D_CLASS_INSTRCTR
(PERSON_SID)
/
