DROP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_WS_AWARDS12
/

--
-- AK_UM_F_FA_STDNT_WS_AWARDS12  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_WS_AWARDS12 ON CSMRT_OWNER.UM_F_FA_STDNT_WS_AWARDS
(ITEM_TYPE_SID)
/
