DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_ACAD_STRUCT30
/

--
-- FK_UM_F_STDNT_ACAD_STRUCT30  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_ACAD_STRUCT30 ON CSMRT_OWNER.UM_F_STDNT_ACAD_STRUCT
(CALC_TERM_LIMIT_SID)
/
