DROP INDEX CSMRT_OWNER.AK_UM_D_PRSPCT_PROG_KEY
/

--
-- AK_UM_D_PRSPCT_PROG_KEY  (Index) 
--
CREATE INDEX CSMRT_OWNER.AK_UM_D_PRSPCT_PROG_KEY ON CSMRT_OWNER.UM_D_PRSPCT_PROG
(PRSPCT_CAR_SID, ACAD_PROG_SID)
/
