DROP INDEX CSMRT_OWNER.AK_UM_R_PERSON_RSDNCY13
/

--
-- AK_UM_R_PERSON_RSDNCY13  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_R_PERSON_RSDNCY13 ON CSMRT_OWNER.UM_R_PERSON_RSDNCY
(ADM_RSDNCY_SID)
/
