DROP INDEX CSMRT_OWNER.AK_UM_D_PERSON_ACCOM_PERS
/

--
-- AK_UM_D_PERSON_ACCOM_PERS  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_D_PERSON_ACCOM_PERS ON CSMRT_OWNER.UM_D_PERSON_ACCOM
(PERSON_SID)
/
