DROP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_AWRD_PERIO6
/

--
-- AK_UM_F_FA_STDNT_AWRD_PERIO6  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_AWRD_PERIO6 ON CSMRT_OWNER.UM_F_FA_STDNT_AWRD_PERIOD
(INSTITUTION_SID)
/
