DROP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_SFA_SAP7
/

--
-- AK_UM_F_FA_STDNT_SFA_SAP7  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_SFA_SAP7 ON CSMRT_OWNER.UM_F_FA_STDNT_SFA_SAP
(INSTITUTION_SID)
/
