DROP INDEX CSMRT_OWNER.AK_UM_F_ADM_APPL_ACAD_STRUC21
/

--
-- AK_UM_F_ADM_APPL_ACAD_STRUC21  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_ADM_APPL_ACAD_STRUC21 ON CSMRT_OWNER.UM_F_ADM_APPL_ACAD_STRUCT
(CAMPUS_SID)
/
