DROP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_PELL_DISB2
/

--
-- AK_UM_F_FA_STDNT_PELL_DISB2  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_PELL_DISB2 ON CSMRT_OWNER.UM_F_FA_STDNT_PELL_DISB
(PERSON_SID)
/
