DROP INDEX CSMRT_OWNER.PK_UM_F_FA_STDNT_AWARDS
/

--
-- PK_UM_F_FA_STDNT_AWARDS  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.PK_UM_F_FA_STDNT_AWARDS ON CSMRT_OWNER.UM_F_FA_STDNT_AWARDS
(INSTITUTION_CD, ACAD_CAR_CD, AID_YEAR, PERSON_ID, ITEM_TYPE, 
SRC_SYS_ID)
/
