DROP INDEX CSMRT_OWNER.AK_FA_ITEM_TYPE_CTGRY5
/

--
-- AK_FA_ITEM_TYPE_CTGRY5  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_FA_ITEM_TYPE_CTGRY5 ON CSMRT_OWNER.UM_D_FA_ITEM_TYPE_CTGRY
(ITEM_TYPE_SID)
/
