DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_ENRL_MV22
/

--
-- FK_UM_F_STDNT_TERM_STRUCT_ENRL_MV22  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_ENRL_MV22 ON CSMRT_OWNER.UM_F_STDNT_TERM_STRUCT_ENRL_MV
(T_MAJ1_ACAD_PLAN_SID)
/
