DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_MV18
/

--
-- FK_UM_F_STDNT_TERM_MV18  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_MV18 ON CSMRT_OWNER.UM_F_STDNT_TERM_MV
(PS_EXP_GRAD_TERM_SID)
/
