DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_ADVR_MV222
/

--
-- FK_UM_F_STDNT_TERM_STRUCT_ADVR_MV222  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_ADVR_MV222 ON CSMRT_OWNER.UM_F_STDNT_TERM_STRUCT_ADVR_MV
(S_PERSON_SID)
/
