DROP INDEX CSMRT_OWNER.AK_PS_F_EXT_ACAD_SUMM19
/

--
-- AK_PS_F_EXT_ACAD_SUMM19  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_PS_F_EXT_ACAD_SUMM19 ON CSMRT_OWNER.PS_F_EXT_ACAD_SUMM
(D_EXT_ACAD_LVL_SID)
/
