DROP INDEX CSMRT_OWNER.AK_UM_F_EXT_TESTSCORE4
/

--
-- AK_UM_F_EXT_TESTSCORE4  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_EXT_TESTSCORE4 ON CSMRT_OWNER.UM_F_EXT_TESTSCORE
(TST_DATA_SRC_SID)
/
