DROP INDEX CSMRT_OWNER.PK_UM_M_AF_STDNT_ENRL_BDL
/

--
-- PK_UM_M_AF_STDNT_ENRL_BDL  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.PK_UM_M_AF_STDNT_ENRL_BDL ON CSMRT_OWNER.UM_M_AF_STDNT_ENRL_BDL
(INSTITUTION_CD, ACAD_CAR_CD, TERM_CD, PERSON_ID, SRC_SYS_ID)
/
