DROP INDEX CSMRT_OWNER.PK_UM_R_FA_STDNT_SR
/

--
-- PK_UM_R_FA_STDNT_SR  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.PK_UM_R_FA_STDNT_SR ON CSMRT_OWNER.UM_R_FA_STDNT_SR
(INSTITUTION_CD, PERSON_ID, SRC_SYS_ID, TERM_SID)
/
