DROP INDEX CSMRT_OWNER.PK_UM_F_STDNT_TRNS_TEST_DTL
/

--
-- PK_UM_F_STDNT_TRNS_TEST_DTL  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.PK_UM_F_STDNT_TRNS_TEST_DTL ON CSMRT_OWNER.UM_F_STDNT_TRNS_TEST_DTL
(ARTICULATION_TERM, PERSON_ID, ACAD_CAR_CD, INSTITUTION_CD, MODEL_NBR, 
TRNSFR_EQVLNCY_GRP, TRNSFR_EQVLNCY_SEQ, SRC_SYS_ID)
/
