DROP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_AID_CHK18
/

--
-- AK_UM_F_FA_STDNT_AID_CHK18  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_AID_CHK18 ON CSMRT_OWNER.UM_F_FA_STDNT_AID_CHK
(DEPT_SID)
/
