DROP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_AID_ADM18
/

--
-- AK_UM_F_FA_STDNT_AID_ADM18  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_AID_ADM18 ON CSMRT_OWNER.UM_F_FA_STDNT_AID_ADM
(ACAD_LOAD_SID)
/
