DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_ENRL_MV342
/

--
-- FK_UM_F_STDNT_TERM_STRUCT_ENRL_MV342  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_ENRL_MV342 ON CSMRT_OWNER.UM_F_STDNT_TERM_STRUCT_ENRL_MV
(E_ENRLMT_STAT_SID)
/
