DROP INDEX CSMRT_OWNER.AK_UM_R_PERSON_RSDNCY27
/

--
-- AK_UM_R_PERSON_RSDNCY27  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_R_PERSON_RSDNCY27 ON CSMRT_OWNER.UM_R_PERSON_RSDNCY
(ADM_EXCPT_SID)
/
