DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_TRANSFER_MV238
/

--
-- FK_UM_F_STDNT_TERM_TRANSFER_MV238  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_TRANSFER_MV238 ON CSMRT_OWNER.UM_F_STDNT_TERM_TRANSFER_MV
(TRF_EXT_ORG_SID)
/
