DROP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_AWARDS_MV426
/

--
-- AK_UM_F_FA_STDNT_AWARDS_MV426  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_AWARDS_MV426 ON CSMRT_OWNER.UM_F_FA_STDNT_AWARDS_MV
(D_INSTITUTION_SID)
/
