DROP INDEX CSMRT_OWNER.PK_UM_D_STDNT_ATTR_VAL
/

--
-- PK_UM_D_STDNT_ATTR_VAL  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.PK_UM_D_STDNT_ATTR_VAL ON CSMRT_OWNER.UM_D_STDNT_ATTR_VAL
(PERSON_ID, ACAD_CAR_CD, STDNT_CAR_NUM, STDNT_ATTR, STDNT_ATTR_VALUE, 
SRC_SYS_ID)
/
