DROP INDEX CSMRT_OWNER.PK_PS_R_ADM_RECRTR
/

--
-- PK_PS_R_ADM_RECRTR  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.PK_PS_R_ADM_RECRTR ON CSMRT_OWNER.PS_R_ADM_RECRTR
(INSTITUTION_CD, ACAD_CAR_CD, PERSON_ID, STDNT_CAR_NUM, ADM_APPL_NBR, 
RECRT_CTGRY_ID, RECRTR_ID, SRC_SYS_ID)
/
