DROP INDEX CSMRT_OWNER.UM_M_AF_STDNT_ENRL_BDL7
/

--
-- UM_M_AF_STDNT_ENRL_BDL7  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.UM_M_AF_STDNT_ENRL_BDL7 ON CSMRT_OWNER.UM_M_AF_STDNT_ENRL_BDL
(AID_YEAR)
/
