DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_MV4
/

--
-- FK_UM_F_STDNT_TERM_STRUCT_MV4  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_MV4 ON CSMRT_OWNER.UM_F_STDNT_TERM_STRUCT_MV
(T_INSTITUTION_CD)
/
