DROP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_ISIR_STG7
/

--
-- AK_UM_F_FA_STDNT_ISIR_STG7  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_ISIR_STG7 ON CSMRT_OWNER.UM_F_FA_STDNT_ISIR_STG
(PERSON_SID)
/
