DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_MV45
/

--
-- FK_UM_F_STDNT_TERM_MV45  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_MV45 ON CSMRT_OWNER.UM_F_STDNT_TERM_MV
(PRI_ACAD_PROG_SID)
/
