DROP INDEX CSMRT_OWNER.AK_UM_F_STDNT_TRANSFER12
/

--
-- AK_UM_F_STDNT_TRANSFER12  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_STDNT_TRANSFER12 ON CSMRT_OWNER.UM_F_STDNT_TRANSFER
(ACAD_CAR_SID)
/
