DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_ENRL_MV250
/

--
-- FK_UM_F_STDNT_TERM_STRUCT_ENRL_MV250  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_ENRL_MV250 ON CSMRT_OWNER.UM_F_STDNT_TERM_STRUCT_ENRL_MV
(S_CALC_TERM_LIMIT_SID)
/
