DROP INDEX CSMRT_OWNER.AK_F_ADM_APPL_TERM_BCAR
/

--
-- AK_F_ADM_APPL_TERM_BCAR  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_F_ADM_APPL_TERM_BCAR ON CSMRT_OWNER.UM_F_ADM_APPL_TERM
(BILL_CAR_SID)
/
