DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_ENRL_MV329
/

--
-- FK_UM_F_STDNT_TERM_STRUCT_ENRL_MV329  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_ENRL_MV329 ON CSMRT_OWNER.UM_F_STDNT_TERM_STRUCT_ENRL_MV
(E_TERM_SID)
/
