DROP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_AID_ADM26
/

--
-- AK_UM_F_FA_STDNT_AID_ADM26  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_AID_ADM26 ON CSMRT_OWNER.UM_F_FA_STDNT_AID_ADM
(EXT_DEG_SID)
/
