DROP INDEX CSMRT_OWNER.AK_F_ADM_APPL_TERM_PLVL
/

--
-- AK_F_ADM_APPL_TERM_PLVL  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_F_ADM_APPL_TERM_PLVL ON CSMRT_OWNER.UM_F_ADM_APPL_TERM
(PRJTD_ACAD_LVL_SID)
/
