DROP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_AID_ADM16
/

--
-- AK_UM_F_FA_STDNT_AID_ADM16  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_AID_ADM16 ON CSMRT_OWNER.UM_F_FA_STDNT_AID_ADM
(ADMIT_TYPE_SID)
/
