DROP INDEX CSMRT_OWNER.AK_F_ADM_APPL_PRSPCT_CPPS_PLN
/

--
-- AK_F_ADM_APPL_PRSPCT_CPPS_PLN  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_F_ADM_APPL_PRSPCT_CPPS_PLN ON CSMRT_OWNER.UM_F_ADM_APPL_PRSPCT_CPPS
(ACAD_PLAN_SID)
/
