DROP INDEX CSMRT_OWNER.PK_UM_F_ADM_APPL_EXT
/

--
-- PK_UM_F_ADM_APPL_EXT  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.PK_UM_F_ADM_APPL_EXT ON CSMRT_OWNER.UM_F_ADM_APPL_EXT
(APPLCNT_SID, INSTITUTION_SID, EXT_ORG_SID, EXT_ACAD_CAR_SID, EXT_DATA_NBR, 
EXT_SUMM_TYPE_SID, SRC_SYS_ID)
/
