DROP INDEX CSMRT_OWNER.AK_UM_S_SF_ITEM_LINE8
/

--
-- AK_UM_S_SF_ITEM_LINE8  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_S_SF_ITEM_LINE8 ON CSMRT_OWNER.UM_S_SF_ITEM_LINE
(ACAD_CAR_SID)
  LOCAL (  
  PARTITION FY_2021
)
/
