DROP INDEX CSMRT_OWNER.FK_UM_F_ADM_APPL_ACAD_STRUCT20
/

--
-- FK_UM_F_ADM_APPL_ACAD_STRUCT20  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_ADM_APPL_ACAD_STRUCT20 ON CSMRT_OWNER.UM_F_ADM_APPL_ACAD_STRUCT
(ADMIT_TERM_SID)
/
