DROP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_AWARDS_MV399
/

--
-- AK_UM_F_FA_STDNT_AWARDS_MV399  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_AWARDS_MV399 ON CSMRT_OWNER.UM_F_FA_STDNT_AWARDS_MV
(A_PERSON_SID)
/
