DROP INDEX CSMRT_OWNER.PK_UM_F_CLASS_ENRLMT
/

--
-- PK_UM_F_CLASS_ENRLMT  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.PK_UM_F_CLASS_ENRLMT ON CSMRT_OWNER.UM_F_CLASS_ENRLMT
(TERM_SID, PERSON_SID, CLASS_NUM, SRC_SYS_ID)
/
