DROP INDEX CSMRT_OWNER.PK_UM_F_STDNT
/

--
-- PK_UM_F_STDNT  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.PK_UM_F_STDNT ON CSMRT_OWNER.UM_F_STDNT
(INSTITUTION_CD, ACAD_CAR_CD, PERSON_ID, SRC_SYS_ID)
/
