DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_ACAD_STRUCT33
/

--
-- FK_UM_F_STDNT_ACAD_STRUCT33  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_ACAD_STRUCT33 ON CSMRT_OWNER.UM_F_STDNT_ACAD_STRUCT
(PLAN_REQ_TERM_SID)
/
