DROP INDEX CSMRT_OWNER.AK_PS_F_CHKLST_PERSON13
/

--
-- AK_PS_F_CHKLST_PERSON13  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_PS_F_CHKLST_PERSON13 ON CSMRT_OWNER.PS_F_CHKLST_PERSON
(VAR_DATA_SID)
/
