DROP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_AWARDS_MV398
/

--
-- AK_UM_F_FA_STDNT_AWARDS_MV398  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_AWARDS_MV398 ON CSMRT_OWNER.UM_F_FA_STDNT_AWARDS_MV
(A_ACAD_CAR_SID)
/
