DROP INDEX CSMRT_OWNER.AK_F_ADM_APPL_TERM_LOAD
/

--
-- AK_F_ADM_APPL_TERM_LOAD  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_F_ADM_APPL_TERM_LOAD ON CSMRT_OWNER.UM_F_ADM_APPL_TERM
(ACAD_LOAD_SID)
/
