DROP INDEX CSMRT_OWNER.AK_UM_R_FA_STDNT_SR_MV394
/

--
-- AK_UM_R_FA_STDNT_SR_MV394  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_R_FA_STDNT_SR_MV394 ON CSMRT_OWNER.UM_R_FA_STDNT_SR_MV
(R_TERM_SID)
/
