DROP INDEX CSMRT_OWNER.AK_F_ADM_APPL_PRSPCT_CPPS_PRG
/

--
-- AK_F_ADM_APPL_PRSPCT_CPPS_PRG  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_F_ADM_APPL_PRSPCT_CPPS_PRG ON CSMRT_OWNER.UM_F_ADM_APPL_PRSPCT_CPPS
(ACAD_PROG_SID)
/
