DROP INDEX CSMRT_OWNER.AK_UM_S_SF_ITEM_LINE9
/

--
-- AK_UM_S_SF_ITEM_LINE9  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_S_SF_ITEM_LINE9 ON CSMRT_OWNER.UM_S_SF_ITEM_LINE
(PERSON_SID)
  LOCAL (  
  PARTITION FY_2021
)
/
