DROP INDEX CSMRT_OWNER.FK_UM_R_PERSON_RSDNCY25
/

--
-- FK_UM_R_PERSON_RSDNCY25  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_R_PERSON_RSDNCY25 ON CSMRT_OWNER.UM_R_PERSON_RSDNCY
(RSDNCY_TERM_SID)
/
