DROP INDEX CSMRT_OWNER.FK_UM_F_SF_STDNT_EQUTN_VAR8
/

--
-- FK_UM_F_SF_STDNT_EQUTN_VAR8  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_SF_STDNT_EQUTN_VAR8 ON CSMRT_OWNER.UM_F_SF_STDNT_EQUTN_VAR
(TERM_SID)
/
