DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_ENRL_MV341
/

--
-- FK_UM_F_STDNT_TERM_STRUCT_ENRL_MV341  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_ENRL_MV341 ON CSMRT_OWNER.UM_F_STDNT_TERM_STRUCT_ENRL_MV
(E_CLASS_SID)
/
