DROP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_LOAN_ORIG4
/

--
-- AK_UM_F_FA_STDNT_LOAN_ORIG4  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_LOAN_ORIG4 ON CSMRT_OWNER.UM_F_FA_STDNT_LOAN_ORIG
(ACAD_CAR_SID)
/
