DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_ENRL_MV236
/

--
-- FK_UM_F_STDNT_TERM_ENRL_MV236  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_ENRL_MV236 ON CSMRT_OWNER.UM_F_STDNT_TERM_ENRL_MV
(E_ENRL_ACN_LAST_SID)
/
