DROP INDEX CSMRT_OWNER.AK_UM_F_STDNT_DEGREE54
/

--
-- AK_UM_F_STDNT_DEGREE54  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_STDNT_DEGREE54 ON CSMRT_OWNER.UM_F_STDNT_DEGREE
(SPLN_HNRS_PREF_SID)
/
