DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_MV36
/

--
-- FK_UM_F_STDNT_TERM_STRUCT_MV36  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_MV36 ON CSMRT_OWNER.UM_F_STDNT_TERM_STRUCT_MV
(T_MIN4_ACAD_PLAN_SID)
/
