DROP INDEX CSMRT_OWNER.PK_PS_R_CHKLST_ITEM
/

--
-- PK_PS_R_CHKLST_ITEM  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.PK_PS_R_CHKLST_ITEM ON CSMRT_OWNER.PS_R_CHKLST_ITEM
(COMMON_ID, SEQ_3C, CHECKLIST_SEQ, SRC_SYS_ID)
/
