DROP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_LN_ORIG_ACN2
/

--
-- AK_UM_F_FA_STDNT_LN_ORIG_ACN2  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_LN_ORIG_ACN2 ON CSMRT_OWNER.UM_F_FA_STDNT_LOAN_ORIG_ACN
(PERSON_SID)
/
