DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_ENRL_MV31
/

--
-- FK_UM_F_STDNT_TERM_ENRL_MV31  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_ENRL_MV31 ON CSMRT_OWNER.UM_F_STDNT_TERM_ENRL_MV
(T_MAJ3_SPLAN1_SID)
/
