DROP INDEX CSMRT_OWNER.PK_UM_F_FA_STDNT_PELL_ORIG
/

--
-- PK_UM_F_FA_STDNT_PELL_ORIG  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.PK_UM_F_FA_STDNT_PELL_ORIG ON CSMRT_OWNER.UM_F_FA_STDNT_PELL_ORIG
(INSTITUTION_CD, AID_YEAR, PERSON_ID, PELL_ORIG_ID, PELL_ORIG_SEQ_NBR, 
SRC_SYS_ID)
/
