DROP INDEX CSMRT_OWNER.AK_F_ADM_APPL_CLS_ENRL_CAR
/

--
-- AK_F_ADM_APPL_CLS_ENRL_CAR  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_F_ADM_APPL_CLS_ENRL_CAR ON CSMRT_OWNER.UM_F_ADM_APPL_CLASS_ENRLMT
(ACAD_CAR_SID)
/
