DROP INDEX CSMRT_OWNER.AK_UM_D_STDNT_ATTR_VAL12
/

--
-- AK_UM_D_STDNT_ATTR_VAL12  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_D_STDNT_ATTR_VAL12 ON CSMRT_OWNER.UM_D_STDNT_ATTR_VAL
(PERSON_SID)
/
