DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_ADVR_MV49
/

--
-- FK_UM_F_STDNT_TERM_STRUCT_ADVR_MV49  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_ADVR_MV49 ON CSMRT_OWNER.UM_F_STDNT_TERM_STRUCT_ADVR_MV
(T_BILL_CAR_SID)
/
