DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TRNS_TEST_DTL13
/

--
-- FK_UM_F_STDNT_TRNS_TEST_DTL13  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TRNS_TEST_DTL13 ON CSMRT_OWNER.UM_F_STDNT_TRNS_TEST_DTL
(CRSE_SID)
/
