DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_ENRL_MV225
/

--
-- FK_UM_F_STDNT_TERM_STRUCT_ENRL_MV225  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_ENRL_MV225 ON CSMRT_OWNER.UM_F_STDNT_TERM_STRUCT_ENRL_MV
(S_ACAD_SPLAN_SID)
/
