DROP INDEX CSMRT_OWNER.PK_UM_F_FA_STDNT_AWRD_PERIOD
/

--
-- PK_UM_F_FA_STDNT_AWRD_PERIOD  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.PK_UM_F_FA_STDNT_AWRD_PERIOD ON CSMRT_OWNER.UM_F_FA_STDNT_AWRD_PERIOD
(INSTITUTION_CD, AID_YEAR, PERSON_ID, AWARD_PERIOD, SRC_SYS_ID)
/
