DROP INDEX CSMRT_OWNER.AK_UM_F_ADM_APPL_TRANSFER14
/

--
-- AK_UM_F_ADM_APPL_TRANSFER14  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_ADM_APPL_TRANSFER14 ON CSMRT_OWNER.UM_F_ADM_APPL_TRANSFER
(CRSE_SID)
/
