DROP INDEX CSMRT_OWNER.NK_UM_D_CLASS_INSTRCTR
/

--
-- NK_UM_D_CLASS_INSTRCTR  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.NK_UM_D_CLASS_INSTRCTR ON CSMRT_OWNER.UM_D_CLASS_INSTRCTR
(CRSE_CD, CRSE_OFFER_NUM, TERM_CD, SESSION_CD, CLASS_SECTION_CD, 
CLASS_MTG_NUM, INSTRCTR_ASGN_NUM, SRC_SYS_ID)
/
