DROP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_AID_ADM35
/

--
-- AK_UM_F_FA_STDNT_AID_ADM35  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_AID_ADM35 ON CSMRT_OWNER.UM_F_FA_STDNT_AID_ADM
(LST_SCHL_ATTND_SID)
/
