DROP INDEX CSMRT_OWNER.NK_PS_D_EXT_ACAD_CAR
/

--
-- NK_PS_D_EXT_ACAD_CAR  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.NK_PS_D_EXT_ACAD_CAR ON CSMRT_OWNER.PS_D_EXT_ACAD_CAR
(EXT_ACAD_CAR_ID, SRC_SYS_ID)
/
