DROP INDEX CSMRT_OWNER.AK_UM_F_EXT_TESTSCORE25
/

--
-- AK_UM_F_EXT_TESTSCORE25  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_EXT_TESTSCORE25 ON CSMRT_OWNER.UM_F_EXT_TESTSCORE
(LATEST_TEST_DT_FLG)
/
