DROP INDEX CSMRT_OWNER.AK_UM_F_ADM_APPL_EXT_DEG8
/

--
-- AK_UM_F_ADM_APPL_EXT_DEG8  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_ADM_APPL_EXT_DEG8 ON CSMRT_OWNER.UM_F_ADM_APPL_EXT_DEG
(EXT_DEG_SID)
/
