DROP INDEX CSMRT_OWNER.PK_UM_F_ADM_APPL_TERM
/

--
-- PK_UM_F_ADM_APPL_TERM  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.PK_UM_F_ADM_APPL_TERM ON CSMRT_OWNER.UM_F_ADM_APPL_TERM
(ADM_APPL_SID, TERM_SID, PERSON_SID, SRC_SYS_ID)
/
