DROP INDEX CSMRT_OWNER.AK_UM_F_ADM_APPL_TRANSFER1
/

--
-- AK_UM_F_ADM_APPL_TRANSFER1  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_ADM_APPL_TRANSFER1 ON CSMRT_OWNER.UM_F_ADM_APPL_TRANSFER
(APPLCNT_SID)
/
