DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_MV52
/

--
-- FK_UM_F_STDNT_TERM_MV52  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_MV52 ON CSMRT_OWNER.UM_F_STDNT_TERM_MV
(PERSON_SRVC_IND_SID)
/
