DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_ENRL_MV234
/

--
-- FK_UM_F_STDNT_TERM_ENRL_MV234  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_ENRL_MV234 ON CSMRT_OWNER.UM_F_STDNT_TERM_ENRL_MV
(E_ENRLMT_STAT_SID)
/
