DROP INDEX CSMRT_OWNER.PK_UM_F_FA_AWARD_DISB
/

--
-- PK_UM_F_FA_AWARD_DISB  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.PK_UM_F_FA_AWARD_DISB ON CSMRT_OWNER.UM_F_FA_AWARD_DISB
(INSTITUTION_CD, ACAD_CAR_CD, AID_YEAR, TERM_CD, PERSON_ID, 
ITEM_TYPE, SRC_SYS_ID)
/
