DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_TRANSFER_MV236
/

--
-- FK_UM_F_STDNT_TERM_TRANSFER_MV236  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_TRANSFER_MV236 ON CSMRT_OWNER.UM_F_STDNT_TERM_TRANSFER_MV
(TRF_CRSE_SID)
/
