DROP INDEX CSMRT_OWNER.FK_UM_F_ADM_APPL_ACAD_STRUCT32
/

--
-- FK_UM_F_ADM_APPL_ACAD_STRUCT32  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_ADM_APPL_ACAD_STRUCT32 ON CSMRT_OWNER.UM_F_ADM_APPL_ACAD_STRUCT
(STACK_BEGIN_TERM_SID)
/
