DROP INDEX CSMRT_OWNER.PK_UM_F_STDNT_TERM
/

--
-- PK_UM_F_STDNT_TERM  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.PK_UM_F_STDNT_TERM ON CSMRT_OWNER.UM_F_STDNT_TERM
(TERM_SID, PERSON_SID, SRC_SYS_ID)
/
