DROP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_LN_ORIG_ACN3
/

--
-- AK_UM_F_FA_STDNT_LN_ORIG_ACN3  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_LN_ORIG_ACN3 ON CSMRT_OWNER.UM_F_FA_STDNT_LOAN_ORIG_ACN
(INSTITUTION_SID)
/
