DROP INDEX CSMRT_OWNER.AK_UM_F_FA_AWARD_DISB9
/

--
-- AK_UM_F_FA_AWARD_DISB9  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_FA_AWARD_DISB9 ON CSMRT_OWNER.UM_F_FA_AWARD_DISB
(INSTITUTION_SID)
/
