DROP INDEX CSMRT_OWNER.AK_UM_D_PERSON_ACCOM_RESP
/

--
-- AK_UM_D_PERSON_ACCOM_RESP  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_D_PERSON_ACCOM_RESP ON CSMRT_OWNER.UM_D_PERSON_ACCOM
(PERSON_RESP_SID)
/
