DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_ADVR_MV244
/

--
-- FK_UM_F_STDNT_TERM_STRUCT_ADVR_MV244  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_ADVR_MV244 ON CSMRT_OWNER.UM_F_STDNT_TERM_STRUCT_ADVR_MV
(S_REQ_TERM_SID)
/
