DROP INDEX CSMRT_OWNER.AK_UM_R_FA_PERSON_RSDNCY9
/

--
-- AK_UM_R_FA_PERSON_RSDNCY9  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_R_FA_PERSON_RSDNCY9 ON CSMRT_OWNER.UM_R_FA_PERSON_RSDNCY
(INSTITUTION_SID)
/
