DROP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_AID_CHK14
/

--
-- AK_UM_F_FA_STDNT_AID_CHK14  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_AID_CHK14 ON CSMRT_OWNER.UM_F_FA_STDNT_AID_CHK
(CHKLIST_STAT_SID)
/
