DROP INDEX CSMRT_OWNER.FK_UM_F_ADM_APPL_STAT23
/

--
-- FK_UM_F_ADM_APPL_STAT23  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_ADM_APPL_STAT23 ON CSMRT_OWNER.UM_F_ADM_APPL_STAT
(ADMIT_TERM_SID)
/
