DROP INDEX CSMRT_OWNER.AK_UM_F_STDNT_REQ_REPEAT
/

--
-- AK_UM_F_STDNT_REQ_REPEAT  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_STDNT_REQ_REPEAT ON CSMRT_OWNER.UM_F_STDNT_ENRL_REQ
(REPEAT_SID)
/
