DROP INDEX CSMRT_OWNER.AK_F_ADM_APPL_PRSPCT_CPPS_PER
/

--
-- AK_F_ADM_APPL_PRSPCT_CPPS_PER  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_F_ADM_APPL_PRSPCT_CPPS_PER ON CSMRT_OWNER.UM_F_ADM_APPL_PRSPCT_CPPS
(PERSON_SID)
/
