DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_ENRL_MV26
/

--
-- FK_UM_F_STDNT_TERM_ENRL_MV26  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_ENRL_MV26 ON CSMRT_OWNER.UM_F_STDNT_TERM_ENRL_MV
(T_MAJ1_SPLAN3_SID)
/
