DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_MV16
/

--
-- FK_UM_F_STDNT_TERM_MV16  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_MV16 ON CSMRT_OWNER.UM_F_STDNT_TERM_MV
(PS_PROG_ACN_RSN_SID)
/
