DROP INDEX CSMRT_OWNER.AK_UM_R_PERSON_ASSOC20
/

--
-- AK_UM_R_PERSON_ASSOC20  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_R_PERSON_ASSOC20 ON CSMRT_OWNER.UM_R_PERSON_ASSOC
(PERSON_SRVC_IND_SID)
/
