DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_MV55
/

--
-- FK_UM_F_STDNT_TERM_STRUCT_MV55  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_MV55 ON CSMRT_OWNER.UM_F_STDNT_TERM_STRUCT_MV
(T_ACAD_YR_SID)
/
