DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_ENRL_MV28
/

--
-- FK_UM_F_STDNT_TERM_ENRL_MV28  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_ENRL_MV28 ON CSMRT_OWNER.UM_F_STDNT_TERM_ENRL_MV
(T_MAJ2_ACAD_PLAN_SID)
/
