DROP INDEX CSMRT_OWNER.UM_F_SAA_RES_CRSEAVL_MV51
/

--
-- UM_F_SAA_RES_CRSEAVL_MV51  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.UM_F_SAA_RES_CRSEAVL_MV51 ON CSMRT_OWNER.UM_F_SAA_RES_CRSEAVL_MV
(A_PLAN_TERM_SID)
/
