DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_MV25
/

--
-- FK_UM_F_STDNT_TERM_MV25  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_MV25 ON CSMRT_OWNER.UM_F_STDNT_TERM_MV
(MAJ1_SPLAN2_SID)
/
