DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_TRANSFER_MV42
/

--
-- FK_UM_F_STDNT_TERM_TRANSFER_MV42  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_TRANSFER_MV42 ON CSMRT_OWNER.UM_F_STDNT_TERM_TRANSFER_MV
(T_STRT_ACAD_LVL_SID)
/
