DROP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_BDGT16
/

--
-- AK_UM_F_FA_STDNT_BDGT16  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_BDGT16 ON CSMRT_OWNER.UM_F_FA_STDNT_BDGT
(FIN_AID_FED_RES_SID)
/
