DROP INDEX CSMRT_OWNER.PK_UM_F_STDNT_ENRL
/

--
-- PK_UM_F_STDNT_ENRL  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.PK_UM_F_STDNT_ENRL ON CSMRT_OWNER.UM_F_STDNT_ENRL
(TERM_SID, PERSON_SID, CLASS_NUM, SRC_SYS_ID)
/
