DROP INDEX CSMRT_OWNER.NK_UM_D_ACAD_SPLAN
/

--
-- NK_UM_D_ACAD_SPLAN  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.NK_UM_D_ACAD_SPLAN ON CSMRT_OWNER.UM_D_ACAD_SPLAN
(INSTITUTION_CD, ACAD_PLAN_CD, ACAD_SPLAN_CD, EFFDT, SRC_SYS_ID)
/
