DROP INDEX CSMRT_OWNER.PK_UM_F_EXT_TESTSCORE
/

--
-- PK_UM_F_EXT_TESTSCORE  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.PK_UM_F_EXT_TESTSCORE ON CSMRT_OWNER.UM_F_EXT_TESTSCORE
(PERSON_SID, EXT_TST_CMPNT_SID, EXT_TST_DT, TST_DATA_SRC_SID, SRC_SYS_ID)
/
