DROP INDEX CSMRT_OWNER.NK_PS_D_ACAD_STNDNG
/

--
-- NK_PS_D_ACAD_STNDNG  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.NK_PS_D_ACAD_STNDNG ON CSMRT_OWNER.PS_D_ACAD_STNDNG
(INSTITUTION_CD, ACAD_CAR_CD, ACAD_STNDNG_ACN_CD, SRC_SYS_ID)
/
