DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_ADVR_MV8
/

--
-- FK_UM_F_STDNT_TERM_STRUCT_ADVR_MV8  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_ADVR_MV8 ON CSMRT_OWNER.UM_F_STDNT_TERM_STRUCT_ADVR_MV
(T_INSTITUTION_SID)
/
