DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_ADVR_MV239
/

--
-- FK_UM_F_STDNT_TERM_STRUCT_ADVR_MV239  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_ADVR_MV239 ON CSMRT_OWNER.UM_F_STDNT_TERM_STRUCT_ADVR_MV
(S_ADMIT_TERM_SID)
/
