DROP INDEX CSMRT_OWNER.PK_UM_F_FA_STDNT_AID_ISIR
/

--
-- PK_UM_F_FA_STDNT_AID_ISIR  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.PK_UM_F_FA_STDNT_AID_ISIR ON CSMRT_OWNER.UM_F_FA_STDNT_AID_ISIR
(INSTITUTION_CD, PERSON_ID, AID_YEAR, SRC_SYS_ID)
/
