DROP INDEX CSMRT_OWNER.NK_PS_D_ENRLMT_REAS
/

--
-- NK_PS_D_ENRLMT_REAS  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.NK_PS_D_ENRLMT_REAS ON CSMRT_OWNER.PS_D_ENRLMT_REAS
(ENRLMT_REAS_ID, SRC_SYS_ID)
/
