DROP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_WS_AWARDS11
/

--
-- AK_UM_F_FA_STDNT_WS_AWARDS11  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_WS_AWARDS11 ON CSMRT_OWNER.UM_F_FA_STDNT_WS_AWARDS
(PERSON_SID)
/
