DROP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_BDGT10
/

--
-- AK_UM_F_FA_STDNT_BDGT10  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_BDGT10 ON CSMRT_OWNER.UM_F_FA_STDNT_BDGT
(ACAD_CAR_SID)
/
