DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_ENRL_MV29
/

--
-- FK_UM_F_STDNT_TERM_ENRL_MV29  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_ENRL_MV29 ON CSMRT_OWNER.UM_F_STDNT_TERM_ENRL_MV
(T_MAJ2_SPLAN1_SID)
/
