DROP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_AWRD_ACTV9
/

--
-- AK_UM_F_FA_STDNT_AWRD_ACTV9  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_AWRD_ACTV9 ON CSMRT_OWNER.UM_F_FA_STDNT_AWRD_ACTV
(ACAD_CAR_SID)
/
