DROP INDEX CSMRT_OWNER.AK_UM_D_PERSON_NAME_AGG3
/

--
-- AK_UM_D_PERSON_NAME_AGG3  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_D_PERSON_NAME_AGG3 ON CSMRT_OWNER.UM_D_PERSON_NAME_AGG_OLD
(PERSON_SID)
/
