DROP INDEX CSMRT_OWNER.AK_UM_D_PERSON_ETHNICITY6
/

--
-- AK_UM_D_PERSON_ETHNICITY6  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_D_PERSON_ETHNICITY6 ON CSMRT_OWNER.UM_D_PERSON_ETHNICITY
(ETHNIC_GRP_SID)
/
