DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_TRANSFER_MV222
/

--
-- FK_UM_F_STDNT_TERM_TRANSFER_MV222  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_TRANSFER_MV222 ON CSMRT_OWNER.UM_F_STDNT_TERM_TRANSFER_MV
(TRF_PERSON_SID)
/
