DROP INDEX CSMRT_OWNER.AK_UM_F_SF_STDNT_EQ_VAR_PERS
/

--
-- AK_UM_F_SF_STDNT_EQ_VAR_PERS  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_SF_STDNT_EQ_VAR_PERS ON CSMRT_OWNER.UM_F_SF_STDNT_EQUTN_VAR
(PERSON_SID)
/
