DROP INDEX CSMRT_OWNER.AK_UM_F_ADM_APPL_TRANSFER15
/

--
-- AK_UM_F_ADM_APPL_TRANSFER15  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_ADM_APPL_TRANSFER15 ON CSMRT_OWNER.UM_F_ADM_APPL_TRANSFER
(EXT_CRSE_SID)
/
