DROP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_SFA_SAP9
/

--
-- AK_UM_F_FA_STDNT_SFA_SAP9  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_SFA_SAP9 ON CSMRT_OWNER.UM_F_FA_STDNT_SFA_SAP
(PERSON_SID)
/
