DROP INDEX CSMRT_OWNER.PK_UM_F_SF_TUITION_WAIVER_DTL
/

--
-- PK_UM_F_SF_TUITION_WAIVER_DTL  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.PK_UM_F_SF_TUITION_WAIVER_DTL ON CSMRT_OWNER.UM_F_SF_TUITION_WAIVER_DTL
(INSTITUTION_CD, PERSON_ID, ITEM_TERM, ITEM_TYPE, ACAD_CAREER)
/
