DROP INDEX CSMRT_OWNER.AK_PS_R_PRSPCT_RECRTR11
/

--
-- AK_PS_R_PRSPCT_RECRTR11  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_PS_R_PRSPCT_RECRTR11 ON CSMRT_OWNER.PS_R_PRSPCT_RECRTR
(RECRT_CTGRY_SID)
/
