DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_ACAD_STRUCT1
/

--
-- FK_UM_F_STDNT_ACAD_STRUCT1  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_ACAD_STRUCT1 ON CSMRT_OWNER.UM_F_STDNT_ACAD_STRUCT
(TERM_SID)
/
