DROP INDEX CSMRT_OWNER.NK_D_TRANSFER_DICT
/

--
-- NK_D_TRANSFER_DICT  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.NK_D_TRANSFER_DICT ON CSMRT_OWNER.UM_D_TRANSFER_DICT
(INSTITUTION_CD, TRNSFR_SRC_ID, COMP_SUBJECT_AREA, TRNSFR_EQVLNCY_CMP, TRNSFR_CMP_SEQ, 
CRSE_ID, SRC_SYS_ID)
/
