DROP INDEX CSMRT_OWNER.PK_UM_F_SAA_ADB_CRSEAVL
/

--
-- PK_UM_F_SAA_ADB_CRSEAVL  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.PK_UM_F_SAA_ADB_CRSEAVL ON CSMRT_OWNER.UM_F_SAA_ADB_CRSEAVL
(EMPLID, ANALYSIS_DB_SEQ, SAA_CAREER_RPT, SAA_ENTRY_SEQ, SAA_COURSE_SEQ, 
SRC_SYS_ID)
/
