DROP INDEX CSMRT_OWNER.AK_UM_R_FA_PERSON_RSDNCY18
/

--
-- AK_UM_R_FA_PERSON_RSDNCY18  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_R_FA_PERSON_RSDNCY18 ON CSMRT_OWNER.UM_R_FA_PERSON_RSDNCY
(FA_ST_EXCPT_SID)
/
