DROP INDEX CSMRT_OWNER.PK_UM_R_STDNT_GRP
/

--
-- PK_UM_R_STDNT_GRP  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.PK_UM_R_STDNT_GRP ON CSMRT_OWNER.UM_R_STDNT_GRP
(TERM_SID, PERSON_SID, STDNT_GRP_SID, SRC_SYS_ID)
/
