DROP INDEX CSMRT_OWNER.AK_UM_R_FA_PERSON_RSDNCY16
/

--
-- AK_UM_R_FA_PERSON_RSDNCY16  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_R_FA_PERSON_RSDNCY16 ON CSMRT_OWNER.UM_R_FA_PERSON_RSDNCY
(ADM_EXCPT_SID)
/
