DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TRANSFER1
/

--
-- FK_UM_F_STDNT_TRANSFER1  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TRANSFER1 ON CSMRT_OWNER.UM_F_STDNT_TRANSFER
(ARTICULATION_TERM_SID)
/
