DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_ACAD_STRUCT29
/

--
-- FK_UM_F_STDNT_ACAD_STRUCT29  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_ACAD_STRUCT29 ON CSMRT_OWNER.UM_F_STDNT_ACAD_STRUCT
(STACK_READMIT_TERM_SID)
/
