DROP INDEX CSMRT_OWNER.AK_UM_F_ADM_APPL_LST_SCHL1
/

--
-- AK_UM_F_ADM_APPL_LST_SCHL1  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_ADM_APPL_LST_SCHL1 ON CSMRT_OWNER.UM_F_ADM_APPL_LST_SCHL
(APPLCNT_SID)
/
