DROP INDEX CSMRT_OWNER.AK_UM_R_PERSON_RSDNCY16
/

--
-- AK_UM_R_PERSON_RSDNCY16  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_R_PERSON_RSDNCY16 ON CSMRT_OWNER.UM_R_PERSON_RSDNCY
(FA_FED_RSDNCY_SID)
/
