DROP INDEX CSMRT_OWNER.FK_UM_F_ADM_APPL_ACAD_STRUCT33
/

--
-- FK_UM_F_ADM_APPL_ACAD_STRUCT33  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_ADM_APPL_ACAD_STRUCT33 ON CSMRT_OWNER.UM_F_ADM_APPL_ACAD_STRUCT
(STACK_READMIT_TERM_SID)
/
