DROP INDEX CSMRT_OWNER.AK_FA_SF_ITEM_TYPE_BRIDGE6
/

--
-- AK_FA_SF_ITEM_TYPE_BRIDGE6  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_FA_SF_ITEM_TYPE_BRIDGE6 ON CSMRT_OWNER.UM_D_FA_SF_ITEM_TYPE_BRIDGE
(FA_ITEM_TYPE_SID)
/
