DROP INDEX CSMRT_OWNER.AK_UM_F_EXT_ACAD_CRSE9
/

--
-- AK_UM_F_EXT_ACAD_CRSE9  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_EXT_ACAD_CRSE9 ON CSMRT_OWNER.UM_F_EXT_ACAD_CRSE
(INSTITUTION_SID)
/
