DROP INDEX CSMRT_OWNER.NK_PS_D_ACAD_GRP
/

--
-- NK_PS_D_ACAD_GRP  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.NK_PS_D_ACAD_GRP ON CSMRT_OWNER.PS_D_ACAD_GRP
(INSTITUTION_CD, ACAD_GRP_CD, EFFDT, SRC_SYS_ID)
/
