DROP INDEX CSMRT_OWNER.FK_UM_F_SAA_RES_CRSEAVL_MV9
/

--
-- FK_UM_F_SAA_RES_CRSEAVL_MV9  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_SAA_RES_CRSEAVL_MV9 ON CSMRT_OWNER.UM_F_SAA_RES_CRSEAVL_MV
(R_TERM_SID)
/
