DROP INDEX CSMRT_OWNER.PK_UM_R_PERSON_ASSOC
/

--
-- PK_UM_R_PERSON_ASSOC  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.PK_UM_R_PERSON_ASSOC ON CSMRT_OWNER.UM_R_PERSON_ASSOC
(INSTITUTION_CD, PERSON_ID, SRC_SYS_ID)
/
