DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_MV41
/

--
-- FK_UM_F_STDNT_TERM_MV41  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_MV41 ON CSMRT_OWNER.UM_F_STDNT_TERM_MV
(ACAD_LOAD_SID)
/
