DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_MV1
/

--
-- FK_UM_F_STDNT_TERM_STRUCT_MV1  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_MV1 ON CSMRT_OWNER.UM_F_STDNT_TERM_STRUCT_MV
(T_TERM_SID)
/
