DROP INDEX CSMRT_OWNER.AK_UM_S_SF_ITEM15
/

--
-- AK_UM_S_SF_ITEM15  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_S_SF_ITEM15 ON CSMRT_OWNER.UM_S_SF_ITEM
(ACCOUNT_TERM_SID)
  LOCAL (  
  PARTITION FY_2021
)
/
