DROP INDEX CSMRT_OWNER.PK_UM_F_FA_TERM
/

--
-- PK_UM_F_FA_TERM  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.PK_UM_F_FA_TERM ON CSMRT_OWNER.UM_F_FA_TERM
(INSTITUTION_CD, ACAD_CAR_CD, AID_YEAR, TERM_CD, PERSON_ID, 
SRC_SYS_ID)
/
