DROP INDEX CSMRT_OWNER.AK_UM_F_ADM_APPL_STAT39
/

--
-- AK_UM_F_ADM_APPL_STAT39  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_ADM_APPL_STAT39 ON CSMRT_OWNER.UM_F_ADM_APPL_STAT
(PROG_STAT_SID)
/
