DROP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_AWRD_PERIO7
/

--
-- AK_UM_F_FA_STDNT_AWRD_PERIO7  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_AWRD_PERIO7 ON CSMRT_OWNER.UM_F_FA_STDNT_AWRD_PERIOD
(PERSON_SID)
/
