DROP INDEX CSMRT_OWNER.AK_UM_F_ADM_APPL_STAT35
/

--
-- AK_UM_F_ADM_APPL_STAT35  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_ADM_APPL_STAT35 ON CSMRT_OWNER.UM_F_ADM_APPL_STAT
(PERSON_ATHL_SID)
/
