DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_ADVR_MV360
/

--
-- FK_UM_F_STDNT_TERM_STRUCT_ADVR_MV360  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_ADVR_MV360 ON CSMRT_OWNER.UM_F_STDNT_TERM_STRUCT_ADVR_MV
(A_INSTITUTION_SID)
/
