DROP INDEX CSMRT_OWNER.AK_UM_D_CLASS_INSTRCTR13
/

--
-- AK_UM_D_CLASS_INSTRCTR13  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_D_CLASS_INSTRCTR13 ON CSMRT_OWNER.UM_D_CLASS_INSTRCTR
(CLASS_SID)
/
