DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_ACAD_STRUCT21
/

--
-- FK_UM_F_STDNT_ACAD_STRUCT21  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_ACAD_STRUCT21 ON CSMRT_OWNER.UM_F_STDNT_ACAD_STRUCT
(COMPL_TERM_SID)
/
