DROP INDEX CSMRT_OWNER.AK_UM_F_EXT_ACAD_CRSE12
/

--
-- AK_UM_F_EXT_ACAD_CRSE12  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_EXT_ACAD_CRSE12 ON CSMRT_OWNER.UM_F_EXT_ACAD_CRSE
(ACAD_UNIT_TYPE_SID)
/
