DROP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_AID_COMM23
/

--
-- AK_UM_F_FA_STDNT_AID_COMM23  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_AID_COMM23 ON CSMRT_OWNER.UM_F_FA_STDNT_AID_COMM
(PERSON_COMPLETED_SID)
/
