DROP INDEX CSMRT_OWNER.PK_UM_F_ADM_APPL_TRANSFER
/

--
-- PK_UM_F_ADM_APPL_TRANSFER  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.PK_UM_F_ADM_APPL_TRANSFER ON CSMRT_OWNER.UM_F_ADM_APPL_TRANSFER
(APPLCNT_SID, ADMIT_TERM_SID, MODEL_NBR, TRNSFR_EQVLNCY_GRP, TRNSFR_EQVLNCY_SEQ, 
SRC_SYS_ID)
/
