DROP INDEX CSMRT_OWNER.AK_PS_F_CHKLST_PERSON9
/

--
-- AK_PS_F_CHKLST_PERSON9  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_PS_F_CHKLST_PERSON9 ON CSMRT_OWNER.PS_F_CHKLST_PERSON
(INSTITUTION_SID)
/
