DROP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_AID_ADM24
/

--
-- AK_UM_F_FA_STDNT_AID_ADM24  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_AID_ADM24 ON CSMRT_OWNER.UM_F_FA_STDNT_AID_ADM
(APPL_CNTR_SID)
/
