DROP INDEX CSMRT_OWNER.NK_PS_D_ENRL_ACTION
/

--
-- NK_PS_D_ENRL_ACTION  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.NK_PS_D_ENRL_ACTION ON CSMRT_OWNER.PS_D_ENRL_ACTION
(ENRL_REQ_ACTION, SRC_SYS_ID)
/
