DROP INDEX CSMRT_OWNER.UM_F_SAA_RES_CRSEAVL_MV7
/

--
-- UM_F_SAA_RES_CRSEAVL_MV7  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.UM_F_SAA_RES_CRSEAVL_MV7 ON CSMRT_OWNER.UM_F_SAA_RES_CRSEAVL_MV
(R_INSTITUTION_SID)
/
