DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_TRANSFER_MV33
/

--
-- FK_UM_F_STDNT_TERM_TRANSFER_MV33  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_TRANSFER_MV33 ON CSMRT_OWNER.UM_F_STDNT_TERM_TRANSFER_MV
(T_MIN1_ACAD_PLAN_SID)
/
