DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_ENRL_MV349
/

--
-- FK_UM_F_STDNT_TERM_STRUCT_ENRL_MV349  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_ENRL_MV349 ON CSMRT_OWNER.UM_F_STDNT_TERM_STRUCT_ENRL_MV
(E_REPEAT_SID)
/
