DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_ENRL_MV339
/

--
-- FK_UM_F_STDNT_TERM_STRUCT_ENRL_MV339  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_ENRL_MV339 ON CSMRT_OWNER.UM_F_STDNT_TERM_STRUCT_ENRL_MV
(E_ACAD_CAR_SID)
/
