DROP INDEX CSMRT_OWNER.AK_UM_F_STDNT_DEGREE27
/

--
-- AK_UM_F_STDNT_DEGREE27  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_STDNT_DEGREE27 ON CSMRT_OWNER.UM_F_STDNT_DEGREE
(HONORS_SUFFIX_SID)
/
