DROP INDEX CSMRT_OWNER.NK_PS_D_APPL_CNTR
/

--
-- NK_PS_D_APPL_CNTR  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.NK_PS_D_APPL_CNTR ON CSMRT_OWNER.PS_D_APPL_CNTR
(INSTITUTION_CD, APPL_CNTR_ID, SRC_SYS_ID)
/
