DROP INDEX CSMRT_OWNER.AK_PS_F_EXT_ACAD_SUMM18
/

--
-- AK_PS_F_EXT_ACAD_SUMM18  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_PS_F_EXT_ACAD_SUMM18 ON CSMRT_OWNER.PS_F_EXT_ACAD_SUMM
(GPA_TYPE_SID)
/
