DROP INDEX CSMRT_OWNER.PK_UM_D_ENRL_MSG
/

--
-- PK_UM_D_ENRL_MSG  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.PK_UM_D_ENRL_MSG ON CSMRT_OWNER.UM_D_ENRL_MSG
(MESSAGE_SET_NBR, MESSAGE_NBR, SRC_SYS_ID)
/
