DROP INDEX CSMRT_OWNER.FK_UM_UM_F_FA_IR_CDS_DATA4
/

--
-- FK_UM_UM_F_FA_IR_CDS_DATA4  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_UM_F_FA_IR_CDS_DATA4 ON CSMRT_OWNER.UM_F_FA_IR_CDS_DATA
(TERM_SID)
/
