DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_ENRL_MV231
/

--
-- FK_UM_F_STDNT_TERM_ENRL_MV231  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_ENRL_MV231 ON CSMRT_OWNER.UM_F_STDNT_TERM_ENRL_MV
(E_ACAD_CAR_SID)
/
