DROP INDEX CSMRT_OWNER.PK_UM_M_AF_STDNT_ENRL_AMH
/

--
-- PK_UM_M_AF_STDNT_ENRL_AMH  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.PK_UM_M_AF_STDNT_ENRL_AMH ON CSMRT_OWNER.UM_M_AF_STDNT_ENRL_AMH
(INSTITUTION_CD, ACAD_CAR_CD, TERM_CD, PERSON_ID, SRC_SYS_ID)
/
