DROP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_AID_COMM6
/

--
-- AK_UM_F_FA_STDNT_AID_COMM6  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_AID_COMM6 ON CSMRT_OWNER.UM_F_FA_STDNT_AID_COMM
(INSTITUTION_SID)
/
