DROP INDEX CSMRT_OWNER.AK_UM_R_PERSON_RSDNCY19
/

--
-- AK_UM_R_PERSON_RSDNCY19  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_R_PERSON_RSDNCY19 ON CSMRT_OWNER.UM_R_PERSON_RSDNCY
(FA_ST_RSDNCY_SID)
/
