DROP INDEX CSMRT_OWNER.PK_UM_F_FA_STDNT_BDGT_ITEM
/

--
-- PK_UM_F_FA_STDNT_BDGT_ITEM  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.PK_UM_F_FA_STDNT_BDGT_ITEM ON CSMRT_OWNER.UM_F_FA_STDNT_BDGT_ITEM
(INSTITUTION_CD, ACAD_CAR_CD, AID_YEAR, TERM_CD, PERSON_ID, 
BGT_ITEM_CATEGORY, SRC_SYS_ID)
/
