DROP INDEX CSMRT_OWNER.AK_F_ADM_APPL_CLS_ENRL_REAS
/

--
-- AK_F_ADM_APPL_CLS_ENRL_REAS  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_F_ADM_APPL_CLS_ENRL_REAS ON CSMRT_OWNER.UM_F_ADM_APPL_CLASS_ENRLMT
(ENRLMT_REAS_SID)
/
