DROP INDEX CSMRT_OWNER.AK_UM_F_ADM_APPL_EXT_PER
/

--
-- AK_UM_F_ADM_APPL_EXT_PER  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_ADM_APPL_EXT_PER ON CSMRT_OWNER.UM_F_ADM_APPL_EXT_DEG
(APPLCNT_SID)
/
