DROP INDEX CSMRT_OWNER.NK_PS_D_EXT_ACAD_LVL
/

--
-- NK_PS_D_EXT_ACAD_LVL  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.NK_PS_D_EXT_ACAD_LVL ON CSMRT_OWNER.PS_D_EXT_ACAD_LVL
(EXT_ACAD_LVL_ID, SRC_SYS_ID)
/
