DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_MV37
/

--
-- FK_UM_F_STDNT_TERM_MV37  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_MV37 ON CSMRT_OWNER.UM_F_STDNT_TERM_MV
(OTH1_ACAD_PLAN_SID)
/
