DROP INDEX CSMRT_OWNER.AK_F_ADM_APPL_ACAD_STRUCT_SCAR
/

--
-- AK_F_ADM_APPL_ACAD_STRUCT_SCAR  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_F_ADM_APPL_ACAD_STRUCT_SCAR ON CSMRT_OWNER.UM_F_ADM_APPL_ACAD_STRUCT
(STDNT_CAR_NUM)
/
