DROP INDEX CSMRT_OWNER.NK_UM_D_EXT_SUBJECT_AREA
/

--
-- NK_UM_D_EXT_SUBJECT_AREA  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.NK_UM_D_EXT_SUBJECT_AREA ON CSMRT_OWNER.UM_D_EXT_SUBJECT_AREA
(EXT_SUBJECT_AREA, SRC_SYS_ID)
/
