DROP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_ANT_AID4
/

--
-- AK_UM_F_FA_STDNT_ANT_AID4  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_ANT_AID4 ON CSMRT_OWNER.UM_F_FA_STDNT_ANTICIP_AID
(ITEM_TYPE_SID)
/
