DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_ENRL_MV237
/

--
-- FK_UM_F_STDNT_TERM_ENRL_MV237  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_ENRL_MV237 ON CSMRT_OWNER.UM_F_STDNT_TERM_ENRL_MV
(E_ENRL_ACN_RSN_LAST_SID)
/
