DROP INDEX CSMRT_OWNER.AK_F_ADM_APPL_CLS_ENRL_SESS
/

--
-- AK_F_ADM_APPL_CLS_ENRL_SESS  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_F_ADM_APPL_CLS_ENRL_SESS ON CSMRT_OWNER.UM_F_ADM_APPL_CLASS_ENRLMT
(SESSION_SID)
/
