DROP INDEX CSMRT_OWNER.AK_F_ADM_APPL_TERM_SLVL
/

--
-- AK_F_ADM_APPL_TERM_SLVL  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_F_ADM_APPL_TERM_SLVL ON CSMRT_OWNER.UM_F_ADM_APPL_TERM
(STRT_ACAD_LVL_SID)
/
