DROP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_AWARDS_MV427
/

--
-- AK_UM_F_FA_STDNT_AWARDS_MV427  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_AWARDS_MV427 ON CSMRT_OWNER.UM_F_FA_STDNT_AWARDS_MV
(D_ACAD_CAR_SID)
/
