DROP INDEX CSMRT_OWNER.UM_M_AF_STDNT_ENRL_BDL16
/

--
-- UM_M_AF_STDNT_ENRL_BDL16  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.UM_M_AF_STDNT_ENRL_BDL16 ON CSMRT_OWNER.UM_M_AF_STDNT_ENRL_BDL
(NEW_CONT_IND)
/
