DROP INDEX CSMRT_OWNER.AK_UM_F_ADM_APPL_STAT37
/

--
-- AK_UM_F_ADM_APPL_STAT37  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_ADM_APPL_STAT37 ON CSMRT_OWNER.UM_F_ADM_APPL_STAT
(DUAL_ACAD_PROG_SID)
/
