DROP INDEX CSMRT_OWNER.AK_UM_F_EXT_TESTSCORE23
/

--
-- AK_UM_F_EXT_TESTSCORE23  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_EXT_TESTSCORE23 ON CSMRT_OWNER.UM_F_EXT_TESTSCORE
(BEST_SCORE_FLG)
/
