DROP INDEX CSMRT_OWNER.PK_UM_F_ADM_APPL_EXT_DEG
/

--
-- PK_UM_F_ADM_APPL_EXT_DEG  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.PK_UM_F_ADM_APPL_EXT_DEG ON CSMRT_OWNER.UM_F_ADM_APPL_EXT_DEG
(APPLCNT_SID, INSTITUTION_SID, EXT_ORG_SID, EXT_ACAD_CAR_SID, EXT_DATA_NBR, 
EXT_DEG_NBR, SRC_SYS_ID)
/
