DROP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_AID_COMM22
/

--
-- AK_UM_F_FA_STDNT_AID_COMM22  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_AID_COMM22 ON CSMRT_OWNER.UM_F_FA_STDNT_AID_COMM
(PERSON_ASSIGNED_SID)
/
