DROP INDEX CSMRT_OWNER.PK_UM_F_CLASS_PERM
/

--
-- PK_UM_F_CLASS_PERM  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.PK_UM_F_CLASS_PERM ON CSMRT_OWNER.UM_F_CLASS_PERM
(CRSE_CD, CRSE_OFFER_NUM, TERM_CD, SESSION_CD, CLASS_SECTION_CD, 
PERMISSION_TYPE, CLASS_PRMSN_SEQ, SRC_SYS_ID)
/
