DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_ENRL_HIST7
/

--
-- FK_UM_F_STDNT_ENRL_HIST7  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_ENRL_HIST7 ON CSMRT_OWNER.UM_F_STDNT_ENRL_HIST
(TERM_SID)
/
