DROP INDEX CSMRT_OWNER.PK_PS_R_ACAD_PLAN_OWNER
/

--
-- PK_PS_R_ACAD_PLAN_OWNER  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.PK_PS_R_ACAD_PLAN_OWNER ON CSMRT_OWNER.PS_R_ACAD_PLAN_OWNER
(INSTITUTION_CD, ACAD_PLAN_CD, EFFDT, ACAD_ORG_CD, SRC_SYS_ID)
/
