DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_ADVR_MV6
/

--
-- FK_UM_F_STDNT_TERM_STRUCT_ADVR_MV6  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_ADVR_MV6 ON CSMRT_OWNER.UM_F_STDNT_TERM_STRUCT_ADVR_MV
(T_TERM_CD)
/
