DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TRNS_TEST_DTL2
/

--
-- FK_UM_F_STDNT_TRNS_TEST_DTL2  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TRNS_TEST_DTL2 ON CSMRT_OWNER.UM_F_STDNT_TRNS_TEST_DTL
(PERSON_SID)
/
