DROP INDEX CSMRT_OWNER.FK_UM_F_ADM_APPL_PRSPCT_CPPS11
/

--
-- FK_UM_F_ADM_APPL_PRSPCT_CPPS11  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_ADM_APPL_PRSPCT_CPPS11 ON CSMRT_OWNER.UM_F_ADM_APPL_PRSPCT_CPPS
(ADMIT_TERM_SID)
/
