DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_MV35
/

--
-- FK_UM_F_STDNT_TERM_STRUCT_MV35  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_MV35 ON CSMRT_OWNER.UM_F_STDNT_TERM_STRUCT_MV
(T_MIN3_ACAD_PLAN_SID)
/
