DROP INDEX CSMRT_OWNER.PK_UM_F_ACAD_PROG
/

--
-- PK_UM_F_ACAD_PROG  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.PK_UM_F_ACAD_PROG ON CSMRT_OWNER.UM_F_ACAD_PROG
(INSTITUTION_CD, ACAD_CAR_CD, TERM_CD, PERSON_ID, STDNT_CAR_NUM, 
SRC_SYS_ID)
/
