DROP INDEX CSMRT_OWNER.AK_UM_F_SF_ITEM_LINE11
/

--
-- AK_UM_F_SF_ITEM_LINE11  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_SF_ITEM_LINE11 ON CSMRT_OWNER.UM_F_SF_ITEM_LINE
(ACCOUNT_TERM_SID)
/
