DROP INDEX CSMRT_OWNER.AK_UM_R_FA_PERSON_RSDNCY17
/

--
-- AK_UM_R_FA_PERSON_RSDNCY17  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_R_FA_PERSON_RSDNCY17 ON CSMRT_OWNER.UM_R_FA_PERSON_RSDNCY
(FA_FED_EXCPT_SID)
/
