DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_MV17
/

--
-- FK_UM_F_STDNT_TERM_STRUCT_MV17  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_MV17 ON CSMRT_OWNER.UM_F_STDNT_TERM_STRUCT_MV
(T_PS_ADMIT_TERM_SID)
/
