DROP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_AWRD_ACTV8
/

--
-- AK_UM_F_FA_STDNT_AWRD_ACTV8  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_AWRD_ACTV8 ON CSMRT_OWNER.UM_F_FA_STDNT_AWRD_ACTV
(INSTITUTION_SID)
/
