DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_TRANSFER_MV237
/

--
-- FK_UM_F_STDNT_TERM_TRANSFER_MV237  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_TRANSFER_MV237 ON CSMRT_OWNER.UM_F_STDNT_TERM_TRANSFER_MV
(TRF_EXT_CRSE_SID)
/
