DROP INDEX CSMRT_OWNER.NK_PS_D_EXT_SUMM_TYP
/

--
-- NK_PS_D_EXT_SUMM_TYP  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.NK_PS_D_EXT_SUMM_TYP ON CSMRT_OWNER.PS_D_EXT_SUMM_TYP
(EXT_SUMM_TYPE_ID, SRC_SYS_ID)
/
