DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_ENRL_MV32
/

--
-- FK_UM_F_STDNT_TERM_STRUCT_ENRL_MV32  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_ENRL_MV32 ON CSMRT_OWNER.UM_F_STDNT_TERM_STRUCT_ENRL_MV
(T_MAJ4_ACAD_PLAN_SID)
/
