DROP INDEX CSMRT_OWNER.PK_UM_D_CLASS_EXAM
/

--
-- PK_UM_D_CLASS_EXAM  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.PK_UM_D_CLASS_EXAM ON CSMRT_OWNER.UM_D_CLASS_EXAM
(CRSE_CD, CRSE_OFFER_NUM, TERM_CD, SESSION_CD, CLASS_SECTION_CD, 
CLASS_EXAM_SEQ, SRC_SYS_ID)
/
