DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_ADVR_MV343
/

--
-- FK_UM_F_STDNT_TERM_STRUCT_ADVR_MV343  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_ADVR_MV343 ON CSMRT_OWNER.UM_F_STDNT_TERM_STRUCT_ADVR_MV
(A_PERSON_SID)
/
