DROP INDEX CSMRT_OWNER.AK_PS_F_EXT_ACAD_SUMM15
/

--
-- AK_PS_F_EXT_ACAD_SUMM15  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_PS_F_EXT_ACAD_SUMM15 ON CSMRT_OWNER.PS_F_EXT_ACAD_SUMM
(EXT_ACAD_LVL_SID)
/
