DROP INDEX CSMRT_OWNER.NK_PS_D_RECRT_CNTR
/

--
-- NK_PS_D_RECRT_CNTR  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.NK_PS_D_RECRT_CNTR ON CSMRT_OWNER.PS_D_RECRT_CNTR
(INSTITUTION_CD, RECRT_CNTR_ID, SRC_SYS_ID)
/
