DROP INDEX CSMRT_OWNER.NK_PS_D_ACAD_UNIT_TYP
/

--
-- NK_PS_D_ACAD_UNIT_TYP  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.NK_PS_D_ACAD_UNIT_TYP ON CSMRT_OWNER.PS_D_ACAD_UNIT_TYP
(ACAD_UNIT_TYPE_ID, SRC_SYS_ID)
/
