DROP INDEX CSMRT_OWNER.PK_UM_F_ADM_APPL_LST_SCHL
/

--
-- PK_UM_F_ADM_APPL_LST_SCHL  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.PK_UM_F_ADM_APPL_LST_SCHL ON CSMRT_OWNER.UM_F_ADM_APPL_LST_SCHL
(APPLCNT_SID, INSTITUTION_SID, EXT_ORG_SID, SRC_SYS_ID)
/
