DROP INDEX CSMRT_OWNER.NK_UM_D_RQ_GRP_CLOB_PRE
/

--
-- NK_UM_D_RQ_GRP_CLOB_PRE  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.NK_UM_D_RQ_GRP_CLOB_PRE ON CSMRT_OWNER.UM_D_RQ_GRP_CLOB_PRE
(RQRMNT_GROUP, SRC_SYS_ID)
/
