DROP INDEX CSMRT_OWNER.AK_UM_S_SF_ITEM9
/

--
-- AK_UM_S_SF_ITEM9  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_S_SF_ITEM9 ON CSMRT_OWNER.UM_S_SF_ITEM
(ITEM_TERM)
  LOCAL (  
  PARTITION FY_2021
)
/
