DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_ENRL_MV233
/

--
-- FK_UM_F_STDNT_TERM_ENRL_MV233  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_ENRL_MV233 ON CSMRT_OWNER.UM_F_STDNT_TERM_ENRL_MV
(E_CLASS_SID)
/
