DROP INDEX CSMRT_OWNER.PK_UM_F_SF_STDNT_EQUTN_VAR
/

--
-- PK_UM_F_SF_STDNT_EQUTN_VAR  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.PK_UM_F_SF_STDNT_EQUTN_VAR ON CSMRT_OWNER.UM_F_SF_STDNT_EQUTN_VAR
(INSTITUTION_CD, BILLING_CAREER, TERM_CD, PERSON_ID, SRC_SYS_ID)
/
