DROP INDEX CSMRT_OWNER.FK_UM_F_ADM_APPL_STAT25
/

--
-- FK_UM_F_ADM_APPL_STAT25  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_ADM_APPL_STAT25 ON CSMRT_OWNER.UM_F_ADM_APPL_STAT
(EXP_GRAD_TERM_SID)
/
