DROP INDEX CSMRT_OWNER.FK_UM_F_ADM_APPL_CLASS_ENRLMT9
/

--
-- FK_UM_F_ADM_APPL_CLASS_ENRLMT9  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_ADM_APPL_CLASS_ENRLMT9 ON CSMRT_OWNER.UM_F_ADM_APPL_CLASS_ENRLMT
(TERM_SID)
/
