DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_ENRL_MV38
/

--
-- FK_UM_F_STDNT_TERM_ENRL_MV38  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_ENRL_MV38 ON CSMRT_OWNER.UM_F_STDNT_TERM_ENRL_MV
(T_OTH2_ACAD_PLAN_SID)
/
