DROP INDEX CSMRT_OWNER.AK_PS_R_ACAD_ORG_FS_OWN10
/

--
-- AK_PS_R_ACAD_ORG_FS_OWN10  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_PS_R_ACAD_ORG_FS_OWN10 ON CSMRT_OWNER.PS_R_ACAD_ORG_FS_OWN
(DEPTID)
/
