DROP INDEX CSMRT_OWNER.AK_UM_F_ADM_APPL_STAT28
/

--
-- AK_UM_F_ADM_APPL_STAT28  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_ADM_APPL_STAT28 ON CSMRT_OWNER.UM_F_ADM_APPL_STAT
(ACAD_LOAD_SID)
/
