DROP INDEX CSMRT_OWNER.AK_UM_F_STDNT_GRADE_RSTR9
/

--
-- AK_UM_F_STDNT_GRADE_RSTR9  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_STDNT_GRADE_RSTR9 ON CSMRT_OWNER.UM_F_STDNT_GRADE_RSTR
(ACAD_CAR_SID)
/
