DROP INDEX CSMRT_OWNER.AK_UM_F_EXT_TESTSCORE10
/

--
-- AK_UM_F_EXT_TESTSCORE10  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_EXT_TESTSCORE10 ON CSMRT_OWNER.UM_F_EXT_TESTSCORE
(EXT_ACAD_LVL_SID)
/
