DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_MV193
/

--
-- FK_UM_F_STDNT_TERM_STRUCT_MV193  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_MV193 ON CSMRT_OWNER.UM_F_STDNT_TERM_STRUCT_MV
(T_ENRLMT_MIN_TERM_SID)
/
