DROP INDEX CSMRT_OWNER.AK_PS_F_EXT_ACAD_SUMM16
/

--
-- AK_PS_F_EXT_ACAD_SUMM16  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_PS_F_EXT_ACAD_SUMM16 ON CSMRT_OWNER.PS_F_EXT_ACAD_SUMM
(EXT_TERM_SID)
/
