DROP INDEX CSMRT_OWNER.AK_UM_F_ADM_APPL_STAT27
/

--
-- AK_UM_F_ADM_APPL_STAT27  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_ADM_APPL_STAT27 ON CSMRT_OWNER.UM_F_ADM_APPL_STAT
(ACAD_LVL_SID)
/
