DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_ADVR_MV263
/

--
-- FK_UM_F_STDNT_TERM_STRUCT_ADVR_MV263  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_ADVR_MV263 ON CSMRT_OWNER.UM_F_STDNT_TERM_STRUCT_ADVR_MV
(A_STUDENT_ADVISOR_SID)
/
