DROP INDEX CSMRT_OWNER.AK_UM_F_EXT_TESTSCORE2
/

--
-- AK_UM_F_EXT_TESTSCORE2  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_EXT_TESTSCORE2 ON CSMRT_OWNER.UM_F_EXT_TESTSCORE
(EXT_TST_CMPNT_SID)
/
