DROP INDEX CSMRT_OWNER.AK_UM_S_SF_ITEM_LINE12
/

--
-- AK_UM_S_SF_ITEM_LINE12  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_S_SF_ITEM_LINE12 ON CSMRT_OWNER.UM_S_SF_ITEM_LINE
(ITEM_TYPE_SID)
  LOCAL (  
  PARTITION FY_2021
)
/
