DROP INDEX CSMRT_OWNER.PK_UM_D_EMPLOYEE_HIST
/

--
-- PK_UM_D_EMPLOYEE_HIST  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.PK_UM_D_EMPLOYEE_HIST ON CSMRT_OWNER.UM_D_EMPLOYEE_HIST
(PERSON_ID, EMPL_RCD, EFF_START_DT, EFFSEQ, SRC_SYS_ID)
/
