DROP INDEX CSMRT_OWNER.AK_PS_R_ACAD_ORG_FS_OWN9
/

--
-- AK_PS_R_ACAD_ORG_FS_OWN9  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_PS_R_ACAD_ORG_FS_OWN9 ON CSMRT_OWNER.PS_R_ACAD_ORG_FS_OWN
(INSTITUTION_SID)
/
