DROP INDEX CSMRT_OWNER.NK_UM_D_CRSE_TOPIC
/

--
-- NK_UM_D_CRSE_TOPIC  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.NK_UM_D_CRSE_TOPIC ON CSMRT_OWNER.UM_D_CRSE_TOPIC
(CRSE_CD, CRSE_OFFER_NUM, CRSE_TOPIC_ID, SRC_SYS_ID)
/
