DROP INDEX CSMRT_OWNER.AK_FA_ITEM_TYPE_CTGRY4
/

--
-- AK_FA_ITEM_TYPE_CTGRY4  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_FA_ITEM_TYPE_CTGRY4 ON CSMRT_OWNER.UM_D_FA_ITEM_TYPE_CTGRY
(INSTITUTION_SID)
/
