DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_ADVR_MV12
/

--
-- FK_UM_F_STDNT_TERM_STRUCT_ADVR_MV12  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_ADVR_MV12 ON CSMRT_OWNER.UM_F_STDNT_TERM_STRUCT_ADVR_MV
(T_PS_PROG_SID)
/
