DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_ADVR_MV361
/

--
-- FK_UM_F_STDNT_TERM_STRUCT_ADVR_MV361  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_ADVR_MV361 ON CSMRT_OWNER.UM_F_STDNT_TERM_STRUCT_ADVR_MV
(A_ACAD_CAR_SID)
/
