DROP INDEX CSMRT_OWNER.FK_UM_F_ADM_APPL_ACAD_STRUCT25
/

--
-- FK_UM_F_ADM_APPL_ACAD_STRUCT25  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_ADM_APPL_ACAD_STRUCT25 ON CSMRT_OWNER.UM_F_ADM_APPL_ACAD_STRUCT
(REQ_TERM_SID)
/
