DROP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_ANT_AID1
/

--
-- AK_UM_F_FA_STDNT_ANT_AID1  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_ANT_AID1 ON CSMRT_OWNER.UM_F_FA_STDNT_ANTICIP_AID
(INSTITUTION_SID)
/
