DROP INDEX CSMRT_OWNER.AK_UM_D_PRSPCT_PLAN_KEY
/

--
-- AK_UM_D_PRSPCT_PLAN_KEY  (Index) 
--
CREATE INDEX CSMRT_OWNER.AK_UM_D_PRSPCT_PLAN_KEY ON CSMRT_OWNER.UM_D_PRSPCT_PLAN
(PRSPCT_PROG_SID, ACAD_PLAN_SID)
/
