DROP INDEX CSMRT_OWNER.AK_UM_R_PERSON_RSDNCY36
/

--
-- AK_UM_R_PERSON_RSDNCY36  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_R_PERSON_RSDNCY36 ON CSMRT_OWNER.UM_R_PERSON_RSDNCY
(TUITION_EXCPT_SID)
/
