DROP INDEX CSMRT_OWNER.PK_UM_F_FA_STDNT_AID_COMM
/

--
-- PK_UM_F_FA_STDNT_AID_COMM  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.PK_UM_F_FA_STDNT_AID_COMM ON CSMRT_OWNER.UM_F_FA_STDNT_AID_COMM
(INSTITUTION_CD, PERSON_ID, AID_YEAR, SEQ_3C, SRC_SYS_ID)
/
