DROP INDEX CSMRT_OWNER.AK_UM_D_CLASS_INSTRCTR14
/

--
-- AK_UM_D_CLASS_INSTRCTR14  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_D_CLASS_INSTRCTR14 ON CSMRT_OWNER.UM_D_CLASS_INSTRCTR
(CLASS_MTG_PAT_SID)
/
