DROP INDEX CSMRT_OWNER.AK_UM_F_FA_AWARD_DISB10
/

--
-- AK_UM_F_FA_AWARD_DISB10  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_FA_AWARD_DISB10 ON CSMRT_OWNER.UM_F_FA_AWARD_DISB
(ACAD_CAR_SID)
/
