DROP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_ISIR_STG8
/

--
-- AK_UM_F_FA_STDNT_ISIR_STG8  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_ISIR_STG8 ON CSMRT_OWNER.UM_F_FA_STDNT_ISIR_STG
(INSTITUTION_SID)
/
