DROP INDEX CSMRT_OWNER.UM_M_AF_STDNT_ENRL_BDL21
/

--
-- UM_M_AF_STDNT_ENRL_BDL21  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.UM_M_AF_STDNT_ENRL_BDL21 ON CSMRT_OWNER.UM_M_AF_STDNT_ENRL_BDL
(IS_RSDNCY_FLG)
/
