DROP INDEX CSMRT_OWNER.AK_F_ADM_APPL_CLS_ENRL_APPL
/

--
-- AK_F_ADM_APPL_CLS_ENRL_APPL  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_F_ADM_APPL_CLS_ENRL_APPL ON CSMRT_OWNER.UM_F_ADM_APPL_CLASS_ENRLMT
(ADM_APPL_SID)
/
