DROP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_ANT_AID2
/

--
-- AK_UM_F_FA_STDNT_ANT_AID2  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_ANT_AID2 ON CSMRT_OWNER.UM_F_FA_STDNT_ANTICIP_AID
(ACAD_CAR_SID)
/
