DROP INDEX CSMRT_OWNER.AK_F_ADM_APPL_CLS_ENRL_INS
/

--
-- AK_F_ADM_APPL_CLS_ENRL_INS  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_F_ADM_APPL_CLS_ENRL_INS ON CSMRT_OWNER.UM_F_ADM_APPL_CLASS_ENRLMT
(PRI_CLASS_INSTRCTR_SID)
/
