DROP INDEX CSMRT_OWNER.AK_UM_F_STDNT_DEGREE55
/

--
-- AK_UM_F_STDNT_DEGREE55  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_STDNT_DEGREE55 ON CSMRT_OWNER.UM_F_STDNT_DEGREE
(SPLN_HNRS_SUFF_SID)
/
