DROP INDEX CSMRT_OWNER.AK_PS_F_EXT_ACAD_SUMM11
/

--
-- AK_PS_F_EXT_ACAD_SUMM11  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_PS_F_EXT_ACAD_SUMM11 ON CSMRT_OWNER.PS_F_EXT_ACAD_SUMM
(EXT_ACAD_CAR_SID)
/
