DROP INDEX CSMRT_OWNER.AK_UM_F_FA_ISIR_COMMENTS9
/

--
-- AK_UM_F_FA_ISIR_COMMENTS9  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_FA_ISIR_COMMENTS9 ON CSMRT_OWNER.UM_F_FA_ISIR_COMMENTS
(PERSON_SID)
/
