DROP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_BDGT18
/

--
-- AK_UM_F_FA_STDNT_BDGT18  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_BDGT18 ON CSMRT_OWNER.UM_F_FA_STDNT_BDGT
(FIN_AID_FED_EXCPT_SID)
/
