DROP INDEX CSMRT_OWNER.PK_UM_F_ADM_APPL_ACTION
/

--
-- PK_UM_F_ADM_APPL_ACTION  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.PK_UM_F_ADM_APPL_ACTION ON CSMRT_OWNER.UM_F_ADM_APPL_ACTION
(PERSON_ID, ADM_APPL_NBR, ACN_RSN_KEY, ACN_RSN_VAL)
/
