DROP INDEX CSMRT_OWNER.AK_UM_F_ADM_APPL_TRANSFER17
/

--
-- AK_UM_F_ADM_APPL_TRANSFER17  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_ADM_APPL_TRANSFER17 ON CSMRT_OWNER.UM_F_ADM_APPL_TRANSFER
(EXT_TERM_SID)
/
