DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_ENRL_MV246
/

--
-- FK_UM_F_STDNT_TERM_STRUCT_ENRL_MV246  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_ENRL_MV246 ON CSMRT_OWNER.UM_F_STDNT_TERM_STRUCT_ENRL_MV
(S_PROG_ACN_SID)
/
