DROP INDEX CSMRT_OWNER.AK_UM_F_STDNT_REQ_INST
/

--
-- AK_UM_F_STDNT_REQ_INST  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_STDNT_REQ_INST ON CSMRT_OWNER.UM_F_STDNT_ENRL_REQ
(INSTITUTION_SID)
/
