DROP INDEX CSMRT_OWNER.AK_UM_D_STDNT_ATTR_VAL11
/

--
-- AK_UM_D_STDNT_ATTR_VAL11  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_D_STDNT_ATTR_VAL11 ON CSMRT_OWNER.UM_D_STDNT_ATTR_VAL
(ACAD_CAR_SID)
/
