DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_ENRL_MV108
/

--
-- FK_UM_F_STDNT_TERM_STRUCT_ENRL_MV108  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_ENRL_MV108 ON CSMRT_OWNER.UM_F_STDNT_TERM_STRUCT_ENRL_MV
(T_TERM_ACTV_MAX_TERM_SID)
/
