DROP INDEX CSMRT_OWNER.AK_UM_F_ADM_APPL_STAT3
/

--
-- AK_UM_F_ADM_APPL_STAT3  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_ADM_APPL_STAT3 ON CSMRT_OWNER.UM_F_ADM_APPL_STAT
(INSTITUTION_SID)
/
