DROP INDEX CSMRT_OWNER.UM_F_ADM_APPL_TESTSCORE_AGG1
/

--
-- UM_F_ADM_APPL_TESTSCORE_AGG1  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.UM_F_ADM_APPL_TESTSCORE_AGG1 ON CSMRT_OWNER.UM_F_ADM_APPL_TESTSCORE_AGG
(INSTITUTION_SID)
/
