DROP INDEX CSMRT_OWNER.PK_UM_F_STDNT_GRADE_RSTR
/

--
-- PK_UM_F_STDNT_GRADE_RSTR  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.PK_UM_F_STDNT_GRADE_RSTR ON CSMRT_OWNER.UM_F_STDNT_GRADE_RSTR
(TERM_CD, CLASS_NBR, GRD_RSTR_TYPE_SEQ, PERSON_ID, ACAD_CAR_CD, 
SRC_SYS_ID)
/
