DROP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_AID_COMM10
/

--
-- AK_UM_F_FA_STDNT_AID_COMM10  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_AID_COMM10 ON CSMRT_OWNER.UM_F_FA_STDNT_AID_COMM
(ADMIN_FUNC_SID)
/
