DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TRNS_TEST_DTL11
/

--
-- FK_UM_F_STDNT_TRNS_TEST_DTL11  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TRNS_TEST_DTL11 ON CSMRT_OWNER.UM_F_STDNT_TRNS_TEST_DTL
(INSTITUTION_SID)
/
