DROP INDEX CSMRT_OWNER.UM_F_ADM_APPL_TESTSCORE_AGG3
/

--
-- UM_F_ADM_APPL_TESTSCORE_AGG3  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.UM_F_ADM_APPL_TESTSCORE_AGG3 ON CSMRT_OWNER.UM_F_ADM_APPL_TESTSCORE_AGG
(APPLCNT_SID)
/
