DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_ENRL_MV194
/

--
-- FK_UM_F_STDNT_TERM_STRUCT_ENRL_MV194  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_ENRL_MV194 ON CSMRT_OWNER.UM_F_STDNT_TERM_STRUCT_ENRL_MV
(T_ENRLMT_MIN_PERSON_TERM_SID)
/
