DROP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_AID_ADM19
/

--
-- AK_UM_F_FA_STDNT_AID_ADM19  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_FA_STDNT_AID_ADM19 ON CSMRT_OWNER.UM_F_FA_STDNT_AID_ADM
(PROG_STAT_SID)
/
