DROP INDEX CSMRT_OWNER.AK_UM_R_PERSON_RSDNCY6
/

--
-- AK_UM_R_PERSON_RSDNCY6  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_R_PERSON_RSDNCY6 ON CSMRT_OWNER.UM_R_PERSON_RSDNCY
(INSTITUTION_SID)
/
