DROP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_ENRL_MV14
/

--
-- FK_UM_F_STDNT_TERM_STRUCT_ENRL_MV14  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.FK_UM_F_STDNT_TERM_STRUCT_ENRL_MV14 ON CSMRT_OWNER.UM_F_STDNT_TERM_STRUCT_ENRL_MV
(T_PS_PROG_STAT_SID)
/
