DROP INDEX CSMRT_OWNER.AK_UM_F_SAA_ADB_COND2
/

--
-- AK_UM_F_SAA_ADB_COND2  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_SAA_ADB_COND2 ON CSMRT_OWNER.UM_F_SAA_ADB_COND
(EMPLID, ANALYSIS_DB_SEQ, SAA_CAREER_RPT)
/
