DROP INDEX CSMRT_OWNER.AK_UM_F_STDNT_ACAD_STRUCT26
/

--
-- AK_UM_F_STDNT_ACAD_STRUCT26  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.AK_UM_F_STDNT_ACAD_STRUCT26 ON CSMRT_OWNER.UM_F_STDNT_ACAD_STRUCT
(PROG_ACN_SID)
/
