DROP INDEX CSMRT_OWNER.PK_UM_F_SF_ITEM_LINE
/

--
-- PK_UM_F_SF_ITEM_LINE  (Index) 
--
CREATE UNIQUE INDEX CSMRT_OWNER.PK_UM_F_SF_ITEM_LINE ON CSMRT_OWNER.UM_F_SF_ITEM_LINE
(INSTITUTION_CD, PERSON_ID, SA_ID_TYPE, ITEM_NBR, LINE_SEQ_NBR, 
SRC_SYS_ID)
/
