DROP INDEX CSMRT_OWNER.UM_M_AF_STDNT_ENRL_AMH21
/

--
-- UM_M_AF_STDNT_ENRL_AMH21  (Index) 
--
CREATE BITMAP INDEX CSMRT_OWNER.UM_M_AF_STDNT_ENRL_AMH21 ON CSMRT_OWNER.UM_M_AF_STDNT_ENRL_AMH
(IS_RSDNCY_FLG)
/
