CREATE OR REPLACE VIEW UM_R_FA_STDNT_SR_VW
BEQUEATH DEFINER
AS 
select /*+ OPT_ESTIMATE(TABLE UM_F_FA_STDNT_SR MIN=100000) */
       INSTITUTION_CD, 
       PERSON_ID, 
       SRC_SYS_ID,
--       AID_YEAR, 
       TERM_SID, 
       PERSON_SID
  from UM_R_FA_STDNT_SR;
