CREATE OR REPLACE VIEW UM_D_XLATITEM_VW
BEQUEATH DEFINER
AS 
select FIELDNAME, FIELDVALUE, SRC_SYS_ID, 
       XLATLONGNAME, XLATSHORTNAME,
       DATA_ORIGIN, CREATED_EW_DTTM, LASTUPD_EW_DTTM
  from UM_D_XLATITEM;
