CREATE OR REPLACE VIEW UM_D_EXT_CRSE_VW
BEQUEATH DEFINER
AS 
select EXT_CRSE_SID, EXT_ORG_ID, SCHOOL_SUBJECT, SCHOOL_CRSE_NBR, SRC_SYS_ID, 
       EFFDT, EFF_STATUS, DESCRSHORT, DESCR, 
       EXT_SUBJECT_AREA_SID, COURSE_LEVEL, EXT_CAREER, EXT_CAREER_SD, EXT_CAREER_LD, 
       EXT_CRSE_TYPE, EXT_CRSE_TYPE_SD, EXT_CRSE_TYPE_LD, EXT_UNITS, 
       DATA_ORIGIN, CREATED_EW_DTTM, LASTUPD_EW_DTTM
  from UM_D_EXT_CRSE;
