CREATE OR REPLACE VIEW UM_D_EXT_SUBJECT_AREA_VW
BEQUEATH DEFINER
AS 
select EXT_SUBJECT_AREA_SID, EXT_SUBJECT_AREA, SRC_SYS_ID, EFFDT, EFF_STATUS, 
       DESCRSHORT, DESCR, ACAD_INTEREST_FLG,
       DATA_ORIGIN, CREATED_EW_DTTM, LASTUPD_EW_DTTM
  from UM_D_EXT_SUBJECT_AREA;
