DROP VIEW CSMRT_OWNER.UM_D_ENRL_DTL_STAT_VW
/

--
-- UM_D_ENRL_DTL_STAT_VW  (View) 
--
CREATE OR REPLACE VIEW CSMRT_OWNER.UM_D_ENRL_DTL_STAT_VW
BEQUEATH DEFINER
AS 
select ENRL_DETL_STAT_SID,ENRL_REQ_DETL_STAT,DTL_STATUS_SD,DTL_STATUS_LD,SRC_SYS_ID,EFF_START_DT,EFF_END_DT,CURRENT_IND,LOAD_ERROR,DATA_ORIGIN,CREATED_EW_DTTM,LASTUPD_EW_DTTM,BATCH_SID from CSMRT_OWNER.PS_D_ENRL_DTL_STAT
/
