CREATE OR REPLACE VIEW UM_R_FA_UMBOS_SF_TREE_VW
BEQUEATH DEFINER
AS 
select INSTITUTION_CD, ACAD_CAR_CD, TERM_CD, PERSON_ID, SELECT_VALUE, ACCOUNT_TYPE_SF, WAIVER_CODE, ITEM_TYPE, TREE_NAME, TREE_NODE, TREE_NODE_NUM, SRC_SYS_ID, 
       EFFDT, EFF_STATUS, DESCR, TERM_SID, PERSON_SID, 
       DATA_ORIGIN, CREATED_EW_DTTM, LASTUPD_EW_DTTM
  from CSMRT_OWNER.UM_R_FA_UMBOS_SF_TREE;
