CREATE OR REPLACE VIEW UM_D_CLASS_INSTRCTR_VW
BEQUEATH DEFINER
AS 
select CLASS_INSTRCTR_SID, CRSE_CD, CRSE_OFFER_NUM, TERM_CD, SESSION_CD, CLASS_SECTION_CD, CLASS_MTG_NUM, INSTRCTR_ASGN_NUM, SRC_SYS_ID, 
       CLASS_MTG_PAT_ORDER, CLASS_INSTRCTR_ORDER, INSTITUTION_CD, CLASS_SID, CLASS_MTG_PAT_SID, PERSON_SID, INSTRCTR_ROLE_SID, 
       GRADE_RSTR_ACCESS, GRADE_RSTR_ACCESS_SD, GRADE_RSTR_ACCESS_LD, CONTACT_MINUTES, SCHED_PRINT_INSTR, INSTR_LOAD_FACTOR, AUTOCALC_WRKLD_FLG, 
       DATA_ORIGIN, CREATED_EW_DTTM, LASTUPD_EW_DTTM
  from UM_D_CLASS_INSTRCTR;
