CREATE OR REPLACE VIEW UM_D_DEG_VW
BEQUEATH DEFINER
AS 
select DEG_SID, DEG_CD, SRC_SYS_ID, EFFDT, EFF_STAT_CD, DEG_SD, DEG_LD, DEG_FD, 
       EDU_LVL_CD, EDU_LVL_SD, EDU_LVL_LD, INTERNAL_DEG_FLG, YRS_OF_EDU_NUM,
       DATA_ORIGIN, CREATED_EW_DTTM, LASTUPD_EW_DTTM
  from CSMRT_OWNER.PS_D_DEG;
