CREATE OR REPLACE VIEW UM_D_ENRLMT_STAT_VW
BEQUEATH DEFINER
AS 
select ENRLMT_STAT_SID, ENRLMT_STAT_ID, SRC_SYS_ID, ENRLMT_STAT_SD, ENRLMT_STAT_LD, 
       DATA_ORIGIN, CREATED_EW_DTTM, LASTUPD_EW_DTTM
  from PS_D_ENRLMT_STAT;
