CREATE OR REPLACE VIEW UM_F_FA_ISIR_COMMENTS_VW
BEQUEATH DEFINER
AS 
SELECT INSTITUTION_CD, PERSON_ID, AID_YEAR, COMMENT_CODE, SRC_SYS_ID, 
           EFFDT, EFFSEQ, INSTITUTION_SID, PERSON_SID, 
           SFA_DB_MATCH_USE, SEVERITY_LVL, SEVERITY_LVL_LD, DESCRLONG, 
           LOAD_ERROR, DATA_ORIGIN, CREATED_EW_DTTM, LASTUPD_EW_DTTM, BATCH_SID
      FROM UM_F_FA_ISIR_COMMENTS;
