CREATE OR REPLACE VIEW UM_D_INSTRCTR_ROLE_VW
BEQUEATH DEFINER
AS 
select INSTRCTR_ROLE_SID, INSTRCTR_ROLE_CD, SRC_SYS_ID, 
       INSTRCTR_ROLE_SD, INSTRCTR_ROLE_LD,
       DATA_ORIGIN, CREATED_EW_DTTM, LASTUPD_EW_DTTM
  from PS_D_INSTRCTR_ROLE;
