DROP VIEW CSMRT_OWNER.UM_D_ADMIN_FUNC_VW
/

--
-- UM_D_ADMIN_FUNC_VW  (View) 
--
CREATE OR REPLACE VIEW CSMRT_OWNER.UM_D_ADMIN_FUNC_VW
BEQUEATH DEFINER
AS 
select ADMIN_FUNC_SID, ADMIN_FUNCTION, SRC_SYS_ID, EFFDT, EFF_STATUS, 
       ADMIN_FUNCTION_SD, ADMIN_FUNCTION_LD, 
       DATA_ORIGIN, CREATED_EW_DTTM, LASTUPD_EW_DTTM
  from PS_D_ADMIN_FUNC
/
