CREATE OR REPLACE VIEW UM_D_FCLTY_VW
BEQUEATH DEFINER
AS 
select FCLTY_SID, SETID, FCLTY_ID, SRC_SYS_ID, EFFDT, EFF_STAT_CD, 
       FCLTY_SD, FCLTY_LD, LOC_SID, BLDG_CD, BLDG_SD, BLDG_LD, 
       FCLTY_TYPE_CD, FCLTY_TYPE_SD, FCLTY_TYPE_LD, ROOM_NM, ROOM_CAPACITY_NUM,
       DATA_ORIGIN, CREATED_EW_DTTM, LASTUPD_EW_DTTM
  from PS_D_FCLTY;
