CREATE OR REPLACE VIEW UM_R_ENRL_MSG_LOG_VW
BEQUEATH DEFINER
AS 
select ENRL_REQUEST_ID, ENRL_REQ_DETL_SEQ, MESSAGE_SEQ, SRC_SYS_ID, 
       MESSAGE_SET_NBR, MESSAGE_NBR, MSG_SEVERITY, DTTM_STAMP_SEC, 
       DATA_ORIGIN, CREATED_EW_DTTM, LASTUPD_EW_DTTM
  from UM_R_ENRL_MSG_LOG;
