CREATE OR REPLACE VIEW UM_D_ACAD_ORG_VW
BEQUEATH DEFINER
AS 
select ACAD_ORG_SID, EFFDT, ACAD_ORG_CD, SRC_SYS_ID, 
       EFFDT_START, EFFDT_END, EFFDT_ORDER, EFF_STAT_CD, 
       ACAD_ORG_SD, ACAD_ORG_LD, ACAD_ORG_FD, ACAD_ORG_CD_DESC, INSTITUTION_CD, 
       DATA_ORIGIN, CREATED_EW_DTTM, LASTUPD_EW_DTTM
  from PS_D_ACAD_ORG
 where EFFDT_ORDER = 1		-- Remove when PRD has been modified for effective dating.
;
