CREATE OR REPLACE VIEW UM_D_CRSE_ATTR_VAL_VW
BEQUEATH DEFINER
AS 
select CRSE_ATTR_VAL_SID, CRSE_CD, CRSE_OFFER_NUM, CRSE_ATTR, CRSE_ATTR_VALUE, SRC_SYS_ID, 
       EFFDT, CRSE_SID, CRSE_ATTR_SD, CRSE_ATTR_LD, CRSE_ATTR_VALUE_LD, CRSE_ATTR_VALUE_FD, 
       CATALOG_PRINT_FLG, SCHEDULE_PRINT_FLG, 
       DATA_ORIGIN, CREATED_EW_DTTM, LASTUPD_EW_DTTM
  from UM_D_CRSE_ATTR_VAL;
