DROP VIEW CSMRT_OWNER.UM_D_ACAD_UNIT_TYP_VW
/

--
-- UM_D_ACAD_UNIT_TYP_VW  (View) 
--
CREATE OR REPLACE VIEW CSMRT_OWNER.UM_D_ACAD_UNIT_TYP_VW
BEQUEATH DEFINER
AS 
select ACAD_UNIT_TYPE_SID, ACAD_UNIT_TYPE_ID, SRC_SYS_ID, 
       ACAD_UNIT_TYPE_SD, ACAD_UNIT_TYPE_LD, 
       DATA_ORIGIN, CREATED_EW_DTTM, LASTUPD_EW_DTTM
  from PS_D_ACAD_UNIT_TYP
/
