DROP VIEW CSMRT_OWNER.UM_D_DEG_STAT_VW
/

--
-- UM_D_DEG_STAT_VW  (View) 
--
CREATE OR REPLACE VIEW CSMRT_OWNER.UM_D_DEG_STAT_VW
BEQUEATH DEFINER
AS 
select DEG_STAT_SID, DEG_STAT_CD, SRC_SYS_ID, DEG_STAT_SD, DEG_STAT_LD, 
       DATA_ORIGIN, CREATED_EW_DTTM, LASTUPD_EW_DTTM
  from PS_D_DEG_STAT
/
