CREATE OR REPLACE VIEW C_UM_D_XLATITEM_VW
BEQUEATH DEFINER
AS 
SELECT FIELDNAME, 
		   FIELDVALUE, 
		   SRC_SYS_ID, 
		   XLATLONGNAME, 
		   XLATSHORTNAME
	 FROM  CSMRT_OWNER.UM_D_XLATITEM
	WHERE DATA_ORIGIN <> 'D';
