CREATE OR REPLACE VIEW UM_D_RECRT_STAT_VW
BEQUEATH DEFINER
AS 
select RECRT_STAT_SID, RECRT_STAT_ID, SRC_SYS_ID, RECRT_STAT_SD, RECRT_STAT_LD, 
       DATA_ORIGIN, CREATED_EW_DTTM, LASTUPD_EW_DTTM
  from PS_D_RECRT_STAT;
