CREATE OR REPLACE VIEW UM_D_SCTN_CMBND_VW
BEQUEATH DEFINER
AS 
select SCTN_COMBINED_SID, INSTITUTION_CD, TERM_CD, SESSION_CD, SCTN_COMBINED_ID, SRC_SYS_ID, 
       DESCRSHORT, DESCR, ENRL_CAP, ENRL_TOT, WAIT_CAP, WAIT_TOT, ROOM_CAP_REQUEST, 
       PERM_COMBINATION, COMBINATION_TYPE, SKIP_MTGPAT_EDIT, 
       DATA_ORIGIN, CREATED_EW_DTTM, LASTUPD_EW_DTTM
  from UM_D_SCTN_CMBND;
