DROP VIEW CSMRT_OWNER.UM_D_YEAR_VW
/

--
-- UM_D_YEAR_VW  (View) 
--
CREATE OR REPLACE VIEW CSMRT_OWNER.UM_D_YEAR_VW
BEQUEATH DEFINER
AS 
SELECT DISTINCT YEAR_SID, YEAR_NUM, YEAR_DESCR
      FROM PS_D_DAY
    UNION ALL
    SELECT 0, 0, 'Unknown' FROM DUAL
/
