DROP VIEW CSMRT_OWNER.UM_D_RSDNCY_EXCPT_VW
/

--
-- UM_D_RSDNCY_EXCPT_VW  (View) 
--
CREATE OR REPLACE VIEW CSMRT_OWNER.UM_D_RSDNCY_EXCPT_VW
BEQUEATH DEFINER
AS 
select RSDNCY_EXCPT_SID, RSDNCY_EXCPTN, SRC_SYS_ID, EFFDT, EFF_STATUS, 
       RSDNCY_EXCPTN_SD, RSDNCY_EXCPTN_LD,
       DATA_ORIGIN, CREATED_EW_DTTM, LASTUPD_EW_DTTM
  from PS_D_RSDNCY_EXCPT
/
