CREATE OR REPLACE VIEW UM_D_CAMPUS_VW
BEQUEATH DEFINER
AS 
select CAMPUS_SID, INSTITUTION_CD, CAMPUS_CD, SRC_SYS_ID, EFFDT, EFF_STAT_CD, 
       CAMPUS_SD, CAMPUS_LD,
       DATA_ORIGIN, CREATED_EW_DTTM, LASTUPD_EW_DTTM
  from PS_D_CAMPUS;
