CREATE OR REPLACE VIEW UM_F_STDNT_GRAD_TRACK_HONOR_VW
BEQUEATH DEFINER
AS 
select PERSON_ID, INSTITUTION_CD, ACAD_CAR_CD, STDNT_CAR_NUM, ACAD_PROG_CD, EXP_GRAD_TERM, DEG_CD, SEQNUM, SRC_SYS_ID,
       HONORS_CODE, DESCR,
       DATA_ORIGIN, CREATED_EW_DTTM, LASTUPD_EW_DTTM
  from CSMRT_OWNER.UM_F_STDNT_GRAD_TRACK_HONOR;
