CREATE OR REPLACE VIEW UM_D_CRSE_COMP_VW
BEQUEATH DEFINER
AS 
select CRSE_COMP_SID, CRSE_CD, CRSE_OFFER_NUM, SSR_COMP_CD, SRC_SYS_ID, 
       EFFDT, CRSE_SID, SSR_COMP_SID, AUTO_CREATE_CMPNT_FLG, CONTACT_HOURS, 
       DEFAULT_SECT_SIZE, FINAL_EXAM, GRADED_COMP_FLG, WEEK_WORKLOAD_HRS, 
       DATA_ORIGIN, CREATED_EW_DTTM, LASTUPD_EW_DTTM
  from UM_D_CRSE_COMP;
