CREATE OR REPLACE VIEW UM_D_STDNT_GRP_VW
BEQUEATH DEFINER
AS 
select STDNT_GRP_SID, INSTITUTION_CD, STDNT_GRP_CD, SRC_SYS_ID, EFFDT, EFF_STAT_CD, 
       STDNT_GRP_SD, STDNT_GRP_LD,
       DATA_ORIGIN, CREATED_EW_DTTM, LASTUPD_EW_DTTM
  from PS_D_STDNT_GRP;
