DROP INDEX CSSTG_OWNER.PK_PS_PERS_DATA_EFFDT
/

--
-- PK_PS_PERS_DATA_EFFDT  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_PERS_DATA_EFFDT ON CSSTG_OWNER.PS_PERS_DATA_EFFDT
(EMPLID, EFFDT, SRC_SYS_ID)
/
