DROP INDEX CSSTG_OWNER.PK_PS_DEGR_HONORS_TBL
/

--
-- PK_PS_DEGR_HONORS_TBL  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_DEGR_HONORS_TBL ON CSSTG_OWNER.PS_DEGR_HONORS_TBL
(INSTITUTION, HONORS_TYPE, HONORS_CODE, EFFDT, SRC_SYS_ID)
/
