DROP INDEX CSSTG_OWNER.PK_PS_STDNT_CAR_TERM
/

--
-- PK_PS_STDNT_CAR_TERM  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_STDNT_CAR_TERM ON CSSTG_OWNER.PS_STDNT_CAR_TERM
(EMPLID, ACAD_CAREER, INSTITUTION, STRM, SRC_SYS_ID)
/
