DROP INDEX CSSTG_OWNER.PK_PS_ACAD_ORG_FS_OWN
/

--
-- PK_PS_ACAD_ORG_FS_OWN  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_ACAD_ORG_FS_OWN ON CSSTG_OWNER.PS_ACAD_ORG_FS_OWN
(ACAD_ORG, BUSINESS_UNIT, DEPTID, EFFDT, SRC_SYS_ID)
/
