DROP INDEX CSSTG_OWNER.PK_PS_STDNT_EQUTN_VAR
/

--
-- PK_PS_STDNT_EQUTN_VAR  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_STDNT_EQUTN_VAR ON CSSTG_OWNER.PS_STDNT_EQUTN_VAR
(EMPLID, BILLING_CAREER, INSTITUTION, STRM, SRC_SYS_ID)
/
