DROP INDEX CSSTG_OWNER.BB_COURSE_CONTENTS_S1_AK1
/

--
-- BB_COURSE_CONTENTS_S1_AK1  (Index) 
--
CREATE INDEX CSSTG_OWNER.BB_COURSE_CONTENTS_S1_AK1 ON CSSTG_OWNER.BB_COURSE_CONTENTS_S1
(BB_SOURCE, DTMODIFIED)
/
