DROP INDEX CSSTG_OWNER.PK_PS_ISIR_COMMT_TBL
/

--
-- PK_PS_ISIR_COMMT_TBL  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_ISIR_COMMT_TBL ON CSSTG_OWNER.PS_ISIR_COMMT_TBL
(AID_YEAR, COMMENT_CODE, SRC_SYS_ID)
/
