DROP INDEX CSSTG_OWNER.PK_PS_SF_PAYMENT_LOG
/

--
-- PK_PS_SF_PAYMENT_LOG  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_SF_PAYMENT_LOG ON CSSTG_OWNER.PS_SF_PAYMENT_LOG
(COMMON_ID, SA_ID_TYPE, SF_PMT_REF_NBR, SEQUENCE_NBR_3, SRC_SYS_ID)
/
