DROP INDEX CSSTG_OWNER.PK_PS_CLASS_EXAM
/

--
-- PK_PS_CLASS_EXAM  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_CLASS_EXAM ON CSSTG_OWNER.PS_CLASS_EXAM
(CRSE_ID, CRSE_OFFER_NBR, STRM, SESSION_CODE, CLASS_SECTION, 
CLASS_EXAM_SEQ, SRC_SYS_ID)
/
