DROP INDEX CSSTG_OWNER.PK_UM_CA_UMLOW
/

--
-- PK_UM_CA_UMLOW  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_UM_CA_UMLOW ON CSSTG_OWNER.PS_UM_CA_UMLOW
(UM_ADM_USERID, INSTITUTION, UM_ADM_REC_NBR, DATETIME_CREATED, SRC_SYS_ID)
/
