DROP INDEX CSSTG_OWNER.PK_PS_APPOINTMENT_TBL
/

--
-- PK_PS_APPOINTMENT_TBL  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_APPOINTMENT_TBL ON CSSTG_OWNER.PS_APPOINTMENT_TBL
(INSTITUTION, ACAD_CAREER, STRM, SESSION_CODE, SSR_APPT_BLOCK, 
APPOINTMENT_NBR, SRC_SYS_ID)
/
