DROP INDEX CSSTG_OWNER.PK_PS_PMT_CHRG_TBL
/

--
-- PK_PS_PMT_CHRG_TBL  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_PMT_CHRG_TBL ON CSSTG_OWNER.PS_PMT_CHRG_TBL
(SETID, CHARGE_PRIORITY, EFFDT, SRC_SYS_ID)
/
