DROP INDEX CSSTG_OWNER.PK_PS_ORG_GROUPING
/

--
-- PK_PS_ORG_GROUPING  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_ORG_GROUPING ON CSSTG_OWNER.PS_ORG_GROUPING
(EXT_ORG_ID, INSTITUTION, SRC_SYS_ID)
/
