DROP INDEX CSSTG_OWNER.PK_PS_CLASS_CHRSTC
/

--
-- PK_PS_CLASS_CHRSTC  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_CLASS_CHRSTC ON CSSTG_OWNER.PS_CLASS_CHRSTC
(CRSE_ID, CRSE_OFFER_NBR, STRM, SESSION_CODE, CLASS_SECTION, 
ROOM_CHRSTC, SRC_SYS_ID)
/
