DROP INDEX CSSTG_OWNER.PK_PS_VAR_DATA_AVAK
/

--
-- PK_PS_VAR_DATA_AVAK  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_VAR_DATA_AVAK ON CSSTG_OWNER.PS_VAR_DATA_AVAK
(COMMON_ID, VAR_DATA_SEQ, SRC_SYS_ID)
/
