DROP INDEX CSSTG_OWNER.PK_PS_STDNT_ATTR_VAL
/

--
-- PK_PS_STDNT_ATTR_VAL  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_STDNT_ATTR_VAL ON CSSTG_OWNER.PS_STDNT_ATTR_VAL
(INSTITUTION, STDNT_ATTR, EFFDT, STDNT_ATTR_VALUE, SRC_SYS_ID)
/
