DROP INDEX CSSTG_OWNER.PK_PS_STND_MTGPAT_TBL
/

--
-- PK_PS_STND_MTGPAT_TBL  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_STND_MTGPAT_TBL ON CSSTG_OWNER.PS_STND_MTGPAT_TBL
(INSTITUTION, ACAD_GROUP, EFFDT, STND_MTG_PAT, SRC_SYS_ID)
/
