DROP INDEX CSSTG_OWNER.PK_PS_STUDENT_AID
/

--
-- PK_PS_STUDENT_AID  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_STUDENT_AID ON CSSTG_OWNER.PS_STUDENT_AID
(EMPLID, INSTITUTION, AID_YEAR, SRC_SYS_ID)
/
