DROP INDEX CSSTG_OWNER.PK_PS_ADM_APPL_SBPLAN
/

--
-- PK_PS_ADM_APPL_SBPLAN  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_ADM_APPL_SBPLAN ON CSSTG_OWNER.PS_ADM_APPL_SBPLAN
(EMPLID, ACAD_CAREER, STDNT_CAR_NBR, ADM_APPL_NBR, APPL_PROG_NBR, 
EFFDT, EFFSEQ, ACAD_PLAN, ACAD_SUB_PLAN, SRC_SYS_ID)
/
