DROP INDEX CSSTG_OWNER.PS_UM_CRS_CAF_NTS
/

--
-- PS_UM_CRS_CAF_NTS  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PS_UM_CRS_CAF_NTS ON CSSTG_OWNER.PS_UM_CRS_CAF_NTS
(CRSE_ID, EFFDT, SCC_CAF_ATTR_SEQ)
/
