DROP INDEX CSSTG_OWNER.PK_PS_STDNT_ADVR_HIST
/

--
-- PK_PS_STDNT_ADVR_HIST  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_STDNT_ADVR_HIST ON CSSTG_OWNER.PS_STDNT_ADVR_HIST
(EMPLID, INSTITUTION, EFFDT, ADVISOR_ROLE, STDNT_ADVISOR_NBR, 
SRC_SYS_ID)
/
