DROP INDEX CSSTG_OWNER.PK_PS_SCC_STN_LTR_TBL
/

--
-- PK_PS_SCC_STN_LTR_TBL  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_SCC_STN_LTR_TBL ON CSSTG_OWNER.PS_SCC_STN_LTR_TBL
(SCC_LETTER_CD, SRC_SYS_ID)
/
