DROP INDEX CSSTG_OWNER.BB_ACTIVITY_ACCUMULATOR_UMLOW_PK
/

--
-- BB_ACTIVITY_ACCUMULATOR_UMLOW_PK  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.BB_ACTIVITY_ACCUMULATOR_UMLOW_PK ON CSSTG_OWNER.BB_ACTIVITY_ACCUMULATOR_UMLOW
(PK1)
/
