DROP INDEX CSSTG_OWNER.PK_PS_SESS_TIME_PEROD
/

--
-- PK_PS_SESS_TIME_PEROD  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_SESS_TIME_PEROD ON CSSTG_OWNER.PS_SESS_TIME_PEROD
(INSTITUTION, ACAD_CAREER, STRM, SESSION_CODE, TIME_PERIOD, 
SRC_SYS_ID)
/
