DROP INDEX CSSTG_OWNER.PK_PS_STDNT_AID_ATRBT
/

--
-- PK_PS_STDNT_AID_ATRBT  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_STDNT_AID_ATRBT ON CSSTG_OWNER.PS_STDNT_AID_ATRBT
(EMPLID, INSTITUTION, AID_YEAR, TABLE_ID, SRC_SYS_ID)
/
