DROP INDEX CSSTG_OWNER.UMOL_ACTIVITY_ACCUMULATOR_UMLOW_DAY_PK
/

--
-- UMOL_ACTIVITY_ACCUMULATOR_UMLOW_DAY_PK  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.UMOL_ACTIVITY_ACCUMULATOR_UMLOW_DAY_PK ON CSSTG_OWNER.UMOL_ACTIVITY_ACCUMULATOR_UMLOW_DAY
(PK1)
/
