DROP INDEX CSSTG_OWNER.PK_PS_CLST_MAIN_TBL
/

--
-- PK_PS_CLST_MAIN_TBL  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_CLST_MAIN_TBL ON CSSTG_OWNER.PS_CLST_MAIN_TBL
(COURSE_LIST, EFFDT, SRC_SYS_ID)
/
