DROP INDEX CSSTG_OWNER.BB_ACTIVITY_ACCUMULATOR_UMAMH_PK
/

--
-- BB_ACTIVITY_ACCUMULATOR_UMAMH_PK  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.BB_ACTIVITY_ACCUMULATOR_UMAMH_PK ON CSSTG_OWNER.BB_ACTIVITY_ACCUMULATOR_UMAMH
(PK1)
/
