DROP INDEX CSSTG_OWNER.PK_PS_EXT_COURSE
/

--
-- PK_PS_EXT_COURSE  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_EXT_COURSE ON CSSTG_OWNER.PS_EXT_COURSE
(EMPLID, EXT_ORG_ID, EXT_COURSE_NBR, SRC_SYS_ID)
/
