DROP INDEX CSSTG_OWNER.PK_PS_TERM_FE_CD_TBL
/

--
-- PK_PS_TERM_FE_CD_TBL  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_TERM_FE_CD_TBL ON CSSTG_OWNER.PS_TERM_FE_CD_TBL
(SETID, FEE_CODE, SRC_SYS_ID)
/
