DROP INDEX CSSTG_OWNER.PK_PS_ACAD_SUBPLN_TBL
/

--
-- PK_PS_ACAD_SUBPLN_TBL  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_ACAD_SUBPLN_TBL ON CSSTG_OWNER.PS_ACAD_SUBPLN_TBL
(INSTITUTION, ACAD_PLAN, ACAD_SUB_PLAN, EFFDT, SRC_SYS_ID)
/
