DROP INDEX CSSTG_OWNER.PK_PS_VAR_DATA_PROS
/

--
-- PK_PS_VAR_DATA_PROS  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_VAR_DATA_PROS ON CSSTG_OWNER.PS_VAR_DATA_PROS
(COMMON_ID, VAR_DATA_SEQ, SRC_SYS_ID)
/
