DROP INDEX CSSTG_OWNER.PK_PS_INSTITUTION_TBL
/

--
-- PK_PS_INSTITUTION_TBL  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_INSTITUTION_TBL ON CSSTG_OWNER.PS_INSTITUTION_TBL
(INSTITUTION, EFFDT, SRC_SYS_ID)
/
