DROP INDEX CSSTG_OWNER.PK_PS_SRVC_IMPACT_TBL
/

--
-- PK_PS_SRVC_IMPACT_TBL  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_SRVC_IMPACT_TBL ON CSSTG_OWNER.PS_SRVC_IMPACT_TBL
(INSTITUTION, SERVICE_IMPACT, EFFDT, SRC_SYS_ID)
/
