DROP INDEX CSSTG_OWNER.BB_CLASSIFICATIONS_S2_PK
/

--
-- BB_CLASSIFICATIONS_S2_PK  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.BB_CLASSIFICATIONS_S2_PK ON CSSTG_OWNER.BB_CLASSIFICATIONS_S2
(BB_SOURCE, PK1)
/
