DROP INDEX CSSTG_OWNER.PK_PS_UM_ITEM_TYPE_FA
/

--
-- PK_PS_UM_ITEM_TYPE_FA  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_UM_ITEM_TYPE_FA ON CSSTG_OWNER.PS_UM_ITEM_TYPE_FA
(SETID, ITEM_TYPE, AID_YEAR, SRC_SYS_ID)
/
