DROP INDEX CSSTG_OWNER.PK_PS_FEE_CLASS_TBL
/

--
-- PK_PS_FEE_CLASS_TBL  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_FEE_CLASS_TBL ON CSSTG_OWNER.PS_FEE_CLASS_TBL
(SETID, FEE_CLASS, SRC_SYS_ID)
/
