DROP INDEX CSSTG_OWNER.PK_UM_FA_IR_CDS_STG
/

--
-- PK_UM_FA_IR_CDS_STG  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_UM_FA_IR_CDS_STG ON CSSTG_OWNER.UM_FA_IR_CDS_STG
(INSTITUTION, TERM, EMPLID, CAREER)
/
