DROP INDEX CSSTG_OWNER.PK_PS_RQ_LN_DETL_TBL
/

--
-- PK_PS_RQ_LN_DETL_TBL  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_RQ_LN_DETL_TBL ON CSSTG_OWNER.PS_RQ_LN_DETL_TBL
(REQUIREMENT, EFFDT, RQ_LINE_KEY_NBR, RQ_LINE_DET_SEQ, SRC_SYS_ID)
/
