DROP INDEX CSSTG_OWNER.PK_PS_BUDGET_ITEM_TBL
/

--
-- PK_PS_BUDGET_ITEM_TBL  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_BUDGET_ITEM_TBL ON CSSTG_OWNER.PS_BUDGET_ITEM_TBL
(INSTITUTION, AID_YEAR, BGT_ITEM_CATEGORY, BUDGET_ITEM_CD, SRC_SYS_ID)
/
