DROP INDEX CSSTG_OWNER.PK_PS_PSTREELEAF
/

--
-- PK_PS_PSTREELEAF  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_PSTREELEAF ON CSSTG_OWNER.PSTREELEAF
(SETID, SETCNTRLVALUE, TREE_NAME, EFFDT, TREE_NODE_NUM, 
RANGE_FROM, RANGE_TO, TREE_BRANCH, SRC_SYS_ID)
/
