DROP INDEX CSSTG_OWNER.PK_PS_GRADE_ROSTER
/

--
-- PK_PS_GRADE_ROSTER  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_GRADE_ROSTER ON CSSTG_OWNER.PS_GRADE_ROSTER
(STRM, CLASS_NBR, GRD_RSTR_TYPE_SEQ, EMPLID, ACAD_CAREER, 
SRC_SYS_ID)
/
