DROP INDEX CSSTG_OWNER.UMOL_ACTIVITY_ACCUMULATOR_UMDAR_I1
/

--
-- UMOL_ACTIVITY_ACCUMULATOR_UMDAR_I1  (Index) 
--
CREATE INDEX CSSTG_OWNER.UMOL_ACTIVITY_ACCUMULATOR_UMDAR_I1 ON CSSTG_OWNER.UMOL_ACTIVITY_ACCUMULATOR_UMDAR
(TIMESTAMP)
/
