DROP INDEX CSSTG_OWNER.PK_PS_STDNT_TERM_BDGT
/

--
-- PK_PS_STDNT_TERM_BDGT  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_STDNT_TERM_BDGT ON CSSTG_OWNER.PS_STDNT_TERM_BDGT
(EMPLID, INSTITUTION, AID_YEAR, ACAD_CAREER, STRM, 
EFFDT, EFFSEQ, SRC_SYS_ID)
/
