DROP INDEX CSSTG_OWNER.PK_PS_RESIDENCY_APEAL
/

--
-- PK_PS_RESIDENCY_APEAL  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_RESIDENCY_APEAL ON CSSTG_OWNER.PS_RESIDENCY_APEAL
(EMPLID, ACAD_CAREER, INSTITUTION, EFFECTIVE_TERM, EFFDT, 
SRC_SYS_ID)
/
