DROP INDEX CSSTG_OWNER.PK_PS_UM_REFL_DTL_TBL
/

--
-- PK_PS_UM_REFL_DTL_TBL  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_UM_REFL_DTL_TBL ON CSSTG_OWNER.PS_UM_REFL_DTL_TBL
(INSTITUTION, UM_REFRL_GRP, UM_REFRL_DTL, SRC_SYS_ID)
/
