DROP INDEX CSSTG_OWNER.PK_PS_BI_BILLING_LINE
/

--
-- PK_PS_BI_BILLING_LINE  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_BI_BILLING_LINE ON CSSTG_OWNER.PS_BI_BILLING_LINE
(BUSINESS_UNIT, INVOICE_ID, COMMON_ID, SA_ID_TYPE, ITEM_NBR, 
ITEM_LINE, SRC_SYS_ID)
/
