DROP INDEX CSSTG_OWNER.PK_PS_DISB_PLAN_TBL
/

--
-- PK_PS_DISB_PLAN_TBL  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_DISB_PLAN_TBL ON CSSTG_OWNER.PS_DISB_PLAN_TBL
(INSTITUTION, AID_YEAR, ACAD_CAREER, DISBURSEMENT_PLAN, SRC_SYS_ID)
/
