DROP INDEX CSSTG_OWNER.PK_PS_SSR_STDGRD_ENRL
/

--
-- PK_PS_SSR_STDGRD_ENRL  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_SSR_STDGRD_ENRL ON CSSTG_OWNER.PS_SSR_STDGRD_ENRL
(EMPLID, INSTITUTION, ACAD_CAREER, STDNT_CAR_NBR, ACAD_PROG, 
EXP_GRAD_TERM, DEGREE, STRM, CLASS_NBR, SRC_SYS_ID)
/
