DROP INDEX CSSTG_OWNER.PK_PS_ISIR_00_3_EC
/

--
-- PK_PS_ISIR_00_3_EC  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_ISIR_00_3_EC ON CSSTG_OWNER.PS_ISIR_00_3_EC
(ECTRANSID, ECQUEUEINSTANCE, ECTRANSINOUTSW, ISIR_SEQ_NO, SRC_SYS_ID)
/
