DROP INDEX CSSTG_OWNER.PK_PS_STDNT_AWRD_DISB
/

--
-- PK_PS_STDNT_AWRD_DISB  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_STDNT_AWRD_DISB ON CSSTG_OWNER.PS_STDNT_AWRD_DISB
(EMPLID, INSTITUTION, AID_YEAR, ITEM_TYPE, ACAD_CAREER, 
DISBURSEMENT_ID, SRC_SYS_ID)
/
