DROP INDEX CSSTG_OWNER.PK_PS_COMMUNICATION
/

--
-- PK_PS_COMMUNICATION  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_COMMUNICATION ON CSSTG_OWNER.PS_COMMUNICATION
(COMMON_ID, SEQ_3C, SRC_SYS_ID)
/
