DROP INDEX CSSTG_OWNER.PK_PS_CHKLST_ITEM_TBL
/

--
-- PK_PS_CHKLST_ITEM_TBL  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_CHKLST_ITEM_TBL ON CSSTG_OWNER.PS_CHKLST_ITEM_TBL
(CHKLST_ITEM_CD, EFFDT, SRC_SYS_ID)
/
