DROP INDEX CSSTG_OWNER.PK_PS_BUDGET_GRP_TBL
/

--
-- PK_PS_BUDGET_GRP_TBL  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_BUDGET_GRP_TBL ON CSSTG_OWNER.PS_BUDGET_GRP_TBL
(INSTITUTION, BUDGET_GROUP_CODE, AID_YEAR, ACAD_CAREER, STRM, 
SRC_SYS_ID)
/
