DROP INDEX CSSTG_OWNER.UMOL_COURSE_CONTENTS_S1_PK
/

--
-- UMOL_COURSE_CONTENTS_S1_PK  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.UMOL_COURSE_CONTENTS_S1_PK ON CSSTG_OWNER.UMOL_COURSE_CONTENTS_S1
(BB_SOURCE, PK1)
/
