DROP INDEX CSSTG_OWNER.BB_ACTIVITY_ACCUMULATOR_UMLOW_DAY_PK
/

--
-- BB_ACTIVITY_ACCUMULATOR_UMLOW_DAY_PK  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.BB_ACTIVITY_ACCUMULATOR_UMLOW_DAY_PK ON CSSTG_OWNER.BB_ACTIVITY_ACCUMULATOR_UMLOW_DAY
(PK1)
/
