DROP INDEX CSSTG_OWNER.PK_PS_STDNT_ENRL_NOTE
/

--
-- PK_PS_STDNT_ENRL_NOTE  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_STDNT_ENRL_NOTE ON CSSTG_OWNER.PS_STDNT_ENRL_NOTE
(EMPLID, ACAD_CAREER, INSTITUTION, STRM, CLASS_NBR, 
TSCRPT_NOTE_SEQ, SRC_SYS_ID)
/
