DROP INDEX CSSTG_OWNER.PK_PS_PERSON_COMMENT
/

--
-- PK_PS_PERSON_COMMENT  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_PERSON_COMMENT ON CSSTG_OWNER.PS_PERSON_COMMENT
(COMMON_ID, SEQ_3C, SRC_SYS_ID)
/
