DROP INDEX CSSTG_OWNER.PK_PS_ISIR_COMMENTS
/

--
-- PK_PS_ISIR_COMMENTS  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_ISIR_COMMENTS ON CSSTG_OWNER.PS_ISIR_COMMENTS
(EMPLID, INSTITUTION, AID_YEAR, EFFDT, EFFSEQ, 
COMMENT_CODE, SRC_SYS_ID)
/
