DROP INDEX CSSTG_OWNER.PK_PS_VAR_DATA_LOAN
/

--
-- PK_PS_VAR_DATA_LOAN  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_VAR_DATA_LOAN ON CSSTG_OWNER.PS_VAR_DATA_LOAN
(COMMON_ID, VAR_DATA_SEQ, SRC_SYS_ID)
/
