DROP INDEX CSSTG_OWNER.PK_PS_EXT_ACAD_DATA
/

--
-- PK_PS_EXT_ACAD_DATA  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_EXT_ACAD_DATA ON CSSTG_OWNER.PS_EXT_ACAD_DATA
(EMPLID, EXT_ORG_ID, EXT_CAREER, EXT_DATA_NBR, SRC_SYS_ID)
/
