DROP INDEX CSSTG_OWNER.PK_PS_ACAD_PROG_TBL
/

--
-- PK_PS_ACAD_PROG_TBL  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_ACAD_PROG_TBL ON CSSTG_OWNER.PS_ACAD_PROG_TBL
(INSTITUTION, ACAD_PROG, EFFDT, SRC_SYS_ID)
/
