DROP INDEX CSSTG_OWNER.PK_PS_UM_SAP_STATUS
/

--
-- PK_PS_UM_SAP_STATUS  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_UM_SAP_STATUS ON CSSTG_OWNER.PS_UM_SAP_STATUS
(EMPLID, INSTITUTION, AID_YEAR, EFFDT, UM_SAP_STATUS, 
SRC_SYS_ID)
/
