DROP INDEX CSSTG_OWNER.PK_PS_CLASS_TBL
/

--
-- PK_PS_CLASS_TBL  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_CLASS_TBL ON CSSTG_OWNER.PS_CLASS_TBL
(CRSE_ID, CRSE_OFFER_NBR, STRM, SESSION_CODE, CLASS_SECTION, 
SRC_SYS_ID)
/
