DROP INDEX CSSTG_OWNER.PK_PS_ETHNIC_GRP_TBL
/

--
-- PK_PS_ETHNIC_GRP_TBL  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_ETHNIC_GRP_TBL ON CSSTG_OWNER.PS_ETHNIC_GRP_TBL
(SETID, ETHNIC_GRP_CD, EFFDT, SRC_SYS_ID)
/
