DROP INDEX CSSTG_OWNER.PK_PS_CAMPUS_EVNT_ATT
/

--
-- PK_PS_CAMPUS_EVNT_ATT  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_CAMPUS_EVNT_ATT ON CSSTG_OWNER.PS_CAMPUS_EVNT_ATT
(CAMPUS_EVENT_NBR, CAMPUS_EVENT_ATND, SRC_SYS_ID)
/
