DROP INDEX CSSTG_OWNER.PK_PS_SCC_CKLSITM_TBL
/

--
-- PK_PS_SCC_CKLSITM_TBL  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_SCC_CKLSITM_TBL ON CSSTG_OWNER.PS_SCC_CKLSITM_TBL
(CHKLST_ITEM_CD, EFFDT, SRC_SYS_ID)
/
