DROP INDEX CSSTG_OWNER.PK_PS_ADM_APP_CAR_SEQ
/

--
-- PK_PS_ADM_APP_CAR_SEQ  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_ADM_APP_CAR_SEQ ON CSSTG_OWNER.PS_ADM_APP_CAR_SEQ
(EMPLID, ACAD_CAREER, STDNT_CAR_NBR, ADM_APPL_NBR, APPL_PROG_NBR, 
SRC_SYS_ID)
/
