DROP INDEX CSSTG_OWNER.PK_PS_ADM_PRSPCT_SBPL
/

--
-- PK_PS_ADM_PRSPCT_SBPL  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_ADM_PRSPCT_SBPL ON CSSTG_OWNER.PS_ADM_PRSPCT_SBPL
(EMPLID, ACAD_CAREER, INSTITUTION, ACAD_PROG, ACAD_PLAN, 
ACAD_SUB_PLAN, SRC_SYS_ID)
/
