DROP INDEX CSSTG_OWNER.PK_PS_COMM_CTXT_TBL
/

--
-- PK_PS_COMM_CTXT_TBL  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_COMM_CTXT_TBL ON CSSTG_OWNER.PS_COMM_CTXT_TBL
(INSTITUTION, COMM_CONTEXT, EFFDT, SRC_SYS_ID)
/
