DROP INDEX CSSTG_OWNER.PK_PS_ADM_RECRCTR_TBL
/

--
-- PK_PS_ADM_RECRCTR_TBL  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_ADM_RECRCTR_TBL ON CSSTG_OWNER.PS_ADM_RECRCTR_TBL
(INSTITUTION, ADM_RECR_CTR, EFFDT, SRC_SYS_ID)
/
