DROP INDEX CSSTG_OWNER.PK_PS_SFA_ASG_CIP_CD
/

--
-- PK_PS_SFA_ASG_CIP_CD  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_SFA_ASG_CIP_CD ON CSSTG_OWNER.PS_SFA_ASG_CIP_CD
(AID_YEAR, SFA_COD_PROGCIP_CD, SRC_SYS_ID)
/
