DROP INDEX CSSTG_OWNER.PK_PS_E_S_COMPANY_TBL
/

--
-- PK_PS_E_S_COMPANY_TBL  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_E_S_COMPANY_TBL ON CSSTG_OWNER.PS_E_S_COMPANY_TBL
(ERROR_SID, SRC_SYS_ID)
/
