DROP INDEX CSSTG_OWNER.PK_PS_RECRUITER_CAT
/

--
-- PK_PS_RECRUITER_CAT  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_RECRUITER_CAT ON CSSTG_OWNER.PS_RECRUITER_CAT
(INSTITUTION, ACAD_CAREER, RECRUITER_ID, EFFDT, ASSIGNMENT_STAGE, 
RECRUITMENT_CAT, SRC_SYS_ID)
/
