DROP INDEX CSSTG_OWNER.PK_PS_ACCOM_OPTION
/

--
-- PK_PS_ACCOM_OPTION  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_ACCOM_OPTION ON CSSTG_OWNER.PS_ACCOM_OPTION
(EMPLID, EMPL_RCD, ACCOMMODATION_ID, ACCOMMODATION_OPT, SRC_SYS_ID)
/
