DROP INDEX CSSTG_OWNER.PK_PS_VISA_PERMIT_TBL
/

--
-- PK_PS_VISA_PERMIT_TBL  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_VISA_PERMIT_TBL ON CSSTG_OWNER.PS_VISA_PERMIT_TBL
(COUNTRY, VISA_PERMIT_TYPE, EFFDT, SRC_SYS_ID)
/
