DROP INDEX CSSTG_OWNER.PK_UM_JOB_STATS
/

--
-- PK_UM_JOB_STATS  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_UM_JOB_STATS ON CSSTG_OWNER.UM_JOB_STATS
(PROJECT, JOB_NBR, JOB_NAME, JOB_STATUS, START_TIME)
/
