DROP INDEX CSSTG_OWNER.PK_PS_AUDIT_CLSMTG_UM
/

--
-- PK_PS_AUDIT_CLSMTG_UM  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_AUDIT_CLSMTG_UM ON CSSTG_OWNER.PS_AUDIT_CLSMTG_UM
(CRSE_ID, CRSE_OFFER_NBR, STRM, SESSION_CODE, CLASS_SECTION, 
CLASS_MTG_NBR, SRC_SYS_ID)
/
