DROP INDEX CSSTG_OWNER.PK_PS_IMMUN_CRITERIA
/

--
-- PK_PS_IMMUN_CRITERIA  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_IMMUN_CRITERIA ON CSSTG_OWNER.PS_IMMUN_CRITERIA
(EMPLID, IMMUNIZATION, IMMUN_SEQ, CRITERIA_SEQ, SRC_SYS_ID)
/
