DROP INDEX CSSTG_OWNER.BB_ACTIVITY_ACCUMULATOR_UMOL_PK
/

--
-- BB_ACTIVITY_ACCUMULATOR_UMOL_PK  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.BB_ACTIVITY_ACCUMULATOR_UMOL_PK ON CSSTG_OWNER.BB_ACTIVITY_ACCUMULATOR_UMOL
(PK1)
/
