DROP INDEX CSSTG_OWNER.PK_PS_ISIR_SAR_XREF
/

--
-- PK_PS_ISIR_SAR_XREF  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_ISIR_SAR_XREF ON CSSTG_OWNER.PS_ISIR_SAR_XREF
(AID_YEAR, RECNAME, FIELDNAME, SRC_SYS_ID)
/
