DROP INDEX CSSTG_OWNER.PK_PS_CLASS_MTG_PAT
/

--
-- PK_PS_CLASS_MTG_PAT  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_CLASS_MTG_PAT ON CSSTG_OWNER.PS_CLASS_MTG_PAT
(CRSE_ID, CRSE_OFFER_NBR, STRM, SESSION_CODE, CLASS_SECTION, 
CLASS_MTG_NBR, SRC_SYS_ID)
/
