DROP INDEX CSSTG_OWNER.PK_PS_SSR_STDGRD_HONR
/

--
-- PK_PS_SSR_STDGRD_HONR  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_SSR_STDGRD_HONR ON CSSTG_OWNER.PS_SSR_STDGRD_HONR
(EMPLID, INSTITUTION, ACAD_CAREER, STDNT_CAR_NBR, ACAD_PROG, 
EXP_GRAD_TERM, DEGREE, SEQNUM, SRC_SYS_ID)
/
