DROP INDEX CSSTG_OWNER.PK_UM_PELL_PAY
/

--
-- PK_UM_PELL_PAY  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_UM_PELL_PAY ON CSSTG_OWNER.UM_PELL_PAY
(AID_YEAR, FA_LOAD, COA_MIN, COA_MAX, EFC_MIN, 
EFC_MAX)
/
