DROP INDEX CSSTG_OWNER.PK_PS_SAA_ADB_CRSEUSE
/

--
-- PK_PS_SAA_ADB_CRSEUSE  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_SAA_ADB_CRSEUSE ON CSSTG_OWNER.PS_SAA_ADB_CRSEUSE
(EMPLID, ANALYSIS_DB_SEQ, SAA_CAREER_RPT, SAA_ENTRY_SEQ, SAA_COURSE_SEQ, 
CRSE_TAG, SRC_SYS_ID)
/
