DROP INDEX CSSTG_OWNER.PK_PS_PERSON_CHK_ITEM
/

--
-- PK_PS_PERSON_CHK_ITEM  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_PERSON_CHK_ITEM ON CSSTG_OWNER.PS_PERSON_CHK_ITEM
(COMMON_ID, SEQ_3C, CHECKLIST_SEQ, SRC_SYS_ID)
/
