DROP INDEX CSSTG_OWNER.PK_PS_STDNT_GROUP_TBL
/

--
-- PK_PS_STDNT_GROUP_TBL  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_STDNT_GROUP_TBL ON CSSTG_OWNER.PS_STDNT_GROUP_TBL
(INSTITUTION, STDNT_GROUP, EFFDT, SRC_SYS_ID)
/
