DROP INDEX CSSTG_OWNER.PK_PS_AUDIT_ISIR_CHNG
/

--
-- PK_PS_AUDIT_ISIR_CHNG  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_AUDIT_ISIR_CHNG ON CSSTG_OWNER.PS_AUDIT_ISIR_CHNG
(EMPLID, INSTITUTION, AID_YEAR, DTTM_STAMP, ISIR_FIELD_NUM, 
SRC_SYS_ID)
/
