DROP INDEX CSSTG_OWNER.PK_PS_CLASS_SBFEE_TBL
/

--
-- PK_PS_CLASS_SBFEE_TBL  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_CLASS_SBFEE_TBL ON CSSTG_OWNER.PS_CLASS_SBFEE_TBL
(SETID, CRSE_ID, CRSE_OFFER_NBR, STRM, SESSION_CODE, 
CLASS_SECTION, SSR_COMPONENT, ACCOUNT_TYPE_SF, ITEM_TYPE, SRC_SYS_ID)
/
