DROP INDEX CSSTG_OWNER.PK_PS_EMAIL_ADDRESSES
/

--
-- PK_PS_EMAIL_ADDRESSES  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_EMAIL_ADDRESSES ON CSSTG_OWNER.PS_EMAIL_ADDRESSES
(EMPLID, E_ADDR_TYPE, SRC_SYS_ID)
/
