DROP INDEX CSSTG_OWNER.PK_PS_STDNT_GRPS_HIST
/

--
-- PK_PS_STDNT_GRPS_HIST  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_STDNT_GRPS_HIST ON CSSTG_OWNER.PS_STDNT_GRPS_HIST
(EMPLID, INSTITUTION, STDNT_GROUP, EFFDT, SRC_SYS_ID)
/
