DROP INDEX CSSTG_OWNER.PK_PS_AID_YEAR_TBL
/

--
-- PK_PS_AID_YEAR_TBL  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_AID_YEAR_TBL ON CSSTG_OWNER.PS_AID_YEAR_TBL
(INSTITUTION, AID_YEAR, SRC_SYS_ID)
/
