DROP INDEX CSSTG_OWNER.PK_PS_WAIVER_TBL
/

--
-- PK_PS_WAIVER_TBL  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_WAIVER_TBL ON CSSTG_OWNER.PS_WAIVER_TBL
(SETID, WAIVER_CODE, EFFDT, EFF_STATUS, SRC_SYS_ID)
/
