DROP INDEX CSSTG_OWNER.PK_PS_CMNT_CATG_TBL
/

--
-- PK_PS_CMNT_CATG_TBL  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_CMNT_CATG_TBL ON CSSTG_OWNER.PS_CMNT_CATG_TBL
(INSTITUTION, CMNT_CATEGORY, EFFDT, SRC_SYS_ID)
/
