DROP INDEX CSSTG_OWNER.PK_PS_CRSE_TOPICS
/

--
-- PK_PS_CRSE_TOPICS  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_CRSE_TOPICS ON CSSTG_OWNER.PS_CRSE_TOPICS
(CRSE_ID, EFFDT, CRS_TOPIC_ID, SRC_SYS_ID)
/
