DROP INDEX CSSTG_OWNER.PK_UM_AF_AMH_STUDENT_ADM_S2
/

--
-- PK_UM_AF_AMH_STUDENT_ADM_S2  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_UM_AF_AMH_STUDENT_ADM_S2 ON CSSTG_OWNER.UM_AF_AMH_STUDENT_ADM_S2
(INSTITUTION_CD, ADMIT_TERM_CD, PERSON_ID, ADM_APPL_NBR, SLATE_ID, 
EXT_ADM_APPL_NBR, ACAD_CAR_CD, ACAD_PROG_CD, ACAD_PLAN_CD)
/
