DROP INDEX CSSTG_OWNER.PK_PS_STDNT_RESPONSE
/

--
-- PK_PS_STDNT_RESPONSE  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_STDNT_RESPONSE ON CSSTG_OWNER.PS_STDNT_RESPONSE
(EMPLID, ACAD_CAREER, STDNT_CAR_NBR, ADM_APPL_NBR, SEQNUM, 
SRC_SYS_ID)
/
