DROP INDEX CSSTG_OWNER.PK_PS_DISB_ID_TBL
/

--
-- PK_PS_DISB_ID_TBL  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_DISB_ID_TBL ON CSSTG_OWNER.PS_DISB_ID_TBL
(INSTITUTION, AID_YEAR, ACAD_CAREER, DISBURSEMENT_PLAN, DISBURSEMENT_ID, 
SRC_SYS_ID)
/
