DROP INDEX CSSTG_OWNER.PK_PS_RQMNT_DESIG_TBL
/

--
-- PK_PS_RQMNT_DESIG_TBL  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_RQMNT_DESIG_TBL ON CSSTG_OWNER.PS_RQMNT_DESIG_TBL
(RQMNT_DESIGNTN, EFFDT, SRC_SYS_ID)
/
