DROP INDEX CSSTG_OWNER.PK_PS_CLASS_NOTES_TBL
/

--
-- PK_PS_CLASS_NOTES_TBL  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_CLASS_NOTES_TBL ON CSSTG_OWNER.PS_CLASS_NOTES_TBL
(INSTITUTION, CLASS_NOTE_NBR, EFFDT, SRC_SYS_ID)
/
