DROP INDEX CSSTG_OWNER.PK_PS_ADM_PRSPCT_CAR
/

--
-- PK_PS_ADM_PRSPCT_CAR  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_ADM_PRSPCT_CAR ON CSSTG_OWNER.PS_ADM_PRSPCT_CAR
(EMPLID, ACAD_CAREER, INSTITUTION, SRC_SYS_ID)
/
