DROP INDEX CSSTG_OWNER.UMOL_ACTIVITY_ACCUMULATOR_UMAMH_PK
/

--
-- UMOL_ACTIVITY_ACCUMULATOR_UMAMH_PK  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.UMOL_ACTIVITY_ACCUMULATOR_UMAMH_PK ON CSSTG_OWNER.UMOL_ACTIVITY_ACCUMULATOR_UMAMH
(PK1)
/
