DROP INDEX CSSTG_OWNER.PK_PS_ATHL_PART_TBL
/

--
-- PK_PS_ATHL_PART_TBL  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_ATHL_PART_TBL ON CSSTG_OWNER.PS_ATHL_PART_TBL
(ATHL_PARTIC_CD, EFFDT, SRC_SYS_ID)
/
