DROP INDEX CSSTG_OWNER.PK_PS_ENRL_REQ_HEADER
/

--
-- PK_PS_ENRL_REQ_HEADER  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_ENRL_REQ_HEADER ON CSSTG_OWNER.PS_ENRL_REQ_HEADER
(ENRL_REQUEST_ID, SRC_SYS_ID)
/
