DROP INDEX CSSTG_OWNER.PK_PS_UM_DEGR_LIM_TBL
/

--
-- PK_PS_UM_DEGR_LIM_TBL  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_UM_DEGR_LIM_TBL ON CSSTG_OWNER.PS_UM_DEGR_LIM_TBL
(INSTITUTION, ACAD_CAREER, ACAD_PROG, ACAD_PLAN, ACAD_SUB_PLAN, 
EFFDT, SRC_SYS_ID)
/
