DROP INDEX CSSTG_OWNER.BB_COURSE_MAIN_S2_TEMP_AK1
/

--
-- BB_COURSE_MAIN_S2_TEMP_AK1  (Index) 
--
CREATE INDEX CSSTG_OWNER.BB_COURSE_MAIN_S2_TEMP_AK1 ON CSSTG_OWNER.BB_COURSE_MAIN_S2_SP
(BB_SOURCE, DTMODIFIED)
/
