DROP INDEX CSSTG_OWNER.PK_PS_UM_STRZ_HSGDTL
/

--
-- PK_PS_UM_STRZ_HSGDTL  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_UM_STRZ_HSGDTL ON CSSTG_OWNER.PS_UM_STRZ_HSGDTL
(INSTITUTION, EMPLID, COMMENT1, SRC_SYS_ID)
/
