DROP INDEX CSSTG_OWNER.PK_PS_UM_STDNT_WS_AWD
/

--
-- PK_PS_UM_STDNT_WS_AWD  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_UM_STDNT_WS_AWD ON CSSTG_OWNER.PS_UM_STDNT_WS_AWD
(EMPLID, INSTITUTION, AID_YEAR, ITEM_TYPE, ACAD_CAREER, 
EFFDT, SEQNO, SRC_SYS_ID)
/
