DROP INDEX CSSTG_OWNER.PK_PS_EVENT_TYPE_TBL
/

--
-- PK_PS_EVENT_TYPE_TBL  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_EVENT_TYPE_TBL ON CSSTG_OWNER.PS_EVENT_TYPE_TBL
(CAMPUS_EVENT_TYPE, EFFDT, SRC_SYS_ID)
/
