DROP INDEX CSSTG_OWNER.PK_PARTITION_SWAP_CONTROL
/

--
-- PK_PARTITION_SWAP_CONTROL  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PARTITION_SWAP_CONTROL ON CSSTG_OWNER.PARTITION_SWAP_CONTROL
(TABLE_OWNER, TABLE_NAME)
/
