DROP INDEX CSSTG_OWNER.PK_PS_BUDGET_CATG_TBL
/

--
-- PK_PS_BUDGET_CATG_TBL  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_BUDGET_CATG_TBL ON CSSTG_OWNER.PS_BUDGET_CATG_TBL
(INSTITUTION, AID_YEAR, BGT_ITEM_CATEGORY, SRC_SYS_ID)
/
