DROP INDEX CSSTG_OWNER.PK_S_RESP_RSN_TBL
/

--
-- PK_S_RESP_RSN_TBL  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_S_RESP_RSN_TBL ON CSSTG_OWNER.PS_RESP_RSN_TBL
(INSTITUTION, ACAD_CAREER, RESPONSE_REASON, EFFDT, SRC_SYS_ID)
/
