DROP INDEX CSSTG_OWNER.UMOL_ACTIVITY_ACCUMULATOR_UMWOR_PK
/

--
-- UMOL_ACTIVITY_ACCUMULATOR_UMWOR_PK  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.UMOL_ACTIVITY_ACCUMULATOR_UMWOR_PK ON CSSTG_OWNER.UMOL_ACTIVITY_ACCUMULATOR_UMWOR
(PK1)
/
