DROP INDEX CSSTG_OWNER.PK_PS_CRSE_SUBFEE_TBL
/

--
-- PK_PS_CRSE_SUBFEE_TBL  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_CRSE_SUBFEE_TBL ON CSSTG_OWNER.PS_CRSE_SUBFEE_TBL
(SETID, CRSE_ID, SSR_COMPONENT, INSTITUTION, CAMPUS, 
LOCATION, STRM, SESSION_CODE, ACCOUNT_TYPE_SF, ITEM_TYPE, 
SRC_SYS_ID)
/
