DROP INDEX CSSTG_OWNER.PK_PS_ACAD_PLAN_OWNER
/

--
-- PK_PS_ACAD_PLAN_OWNER  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_ACAD_PLAN_OWNER ON CSSTG_OWNER.PS_ACAD_PLAN_OWNER
(INSTITUTION, ACAD_PLAN, EFFDT, ACAD_ORG, SRC_SYS_ID)
/
