DROP INDEX CSSTG_OWNER.PK_PS_CLASS_INSTR
/

--
-- PK_PS_CLASS_INSTR  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_CLASS_INSTR ON CSSTG_OWNER.PS_CLASS_INSTR
(CRSE_ID, CRSE_OFFER_NBR, STRM, SESSION_CODE, CLASS_SECTION, 
CLASS_MTG_NBR, INSTR_ASSIGN_SEQ, SRC_SYS_ID)
/
