DROP INDEX CSSTG_OWNER.PK_PS_VAR_DATA_FINA
/

--
-- PK_PS_VAR_DATA_FINA  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_VAR_DATA_FINA ON CSSTG_OWNER.PS_VAR_DATA_FINA
(COMMON_ID, VAR_DATA_SEQ, SRC_SYS_ID)
/
