DROP INDEX CSSTG_OWNER.PK_PS_LOCATION_TBL
/

--
-- PK_PS_LOCATION_TBL  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_LOCATION_TBL ON CSSTG_OWNER.PS_LOCATION_TBL
(SETID, LOCATION, EFFDT, SRC_SYS_ID)
/
