DROP INDEX CSSTG_OWNER.PK_PS_SSR_GRADNOTETBL
/

--
-- PK_PS_SSR_GRADNOTETBL  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_SSR_GRADNOTETBL ON CSSTG_OWNER.PS_SSR_GRADNOTETBL
(INSTITUTION, SSR_GRAD_NOTE, EFFDT, SRC_SYS_ID)
/
