DROP INDEX CSSTG_OWNER.ROLEDEFN_ROLENAME
/

--
-- ROLEDEFN_ROLENAME  (Index) 
--
CREATE BITMAP INDEX CSSTG_OWNER.ROLEDEFN_ROLENAME ON CSSTG_OWNER.PSROLEDEFN
(ROLENAME)
  LOCAL (  
  PARTITION PARTITION_0,  
  PARTITION PARTITION_1
)
/
