DROP INDEX CSSTG_OWNER.PK_PS_COMM_CATG_TBL
/

--
-- PK_PS_COMM_CATG_TBL  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_COMM_CATG_TBL ON CSSTG_OWNER.PS_COMM_CATG_TBL
(INSTITUTION, COMM_CATEGORY, EFFDT, SRC_SYS_ID)
/
