DROP INDEX CSSTG_OWNER.PK_PS_STDNT_AGGR_SCHL
/

--
-- PK_PS_STDNT_AGGR_SCHL  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_STDNT_AGGR_SCHL ON CSSTG_OWNER.PS_STDNT_AGGR_SCHL
(EMPLID, AGGREGATE_AREA, AID_YEAR, AGGREGATE_LEVEL, CPS_SCHOOL_CODE, 
AGGREGATE_STATUS, SRC_SYS_ID)
/
