DROP INDEX CSSTG_OWNER.PK_PS_CLASS_NOTES
/

--
-- PK_PS_CLASS_NOTES  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_CLASS_NOTES ON CSSTG_OWNER.PS_CLASS_NOTES
(CRSE_ID, CRSE_OFFER_NBR, STRM, SESSION_CODE, CLASS_SECTION, 
CLASS_NOTES_SEQ, SRC_SYS_ID)
/
