DROP INDEX CSSTG_OWNER.PK_PS_TERM_SUBFEE_TBL
/

--
-- PK_PS_TERM_SUBFEE_TBL  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_TERM_SUBFEE_TBL ON CSSTG_OWNER.PS_TERM_SUBFEE_TBL
(SETID, FEE_CODE, STRM, SESSION_CODE, SUB_FEE_CODE, 
INSTITUTION, ACAD_CAREER, ACAD_GROUP, SUBJECT, CAMPUS, 
LOCATION, INSTRUCTION_MODE, ACAD_PROG, SSR_COHORT_YR, UNIT_FROM, 
UNIT_TO, SRC_SYS_ID)
/
