DROP INDEX CSSTG_OWNER.PK_PS_DISB_ID_SPLIT
/

--
-- PK_PS_DISB_ID_SPLIT  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_DISB_ID_SPLIT ON CSSTG_OWNER.PS_DISB_ID_SPLIT
(INSTITUTION, AID_YEAR, ACAD_CAREER, DISBURSEMENT_PLAN, SPLIT_CODE, 
DISBURSEMENT_ID, SRC_SYS_ID)
/
