DROP INDEX CSSTG_OWNER.PK_PS_FACILITY_TBL
/

--
-- PK_PS_FACILITY_TBL  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_FACILITY_TBL ON CSSTG_OWNER.PS_FACILITY_TBL
(SETID, FACILITY_ID, EFFDT, SRC_SYS_ID)
/
