DROP INDEX CSSTG_OWNER.PK_PS_UM_ADM_BHE
/

--
-- PK_PS_UM_ADM_BHE  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_UM_ADM_BHE ON CSSTG_OWNER.PS_UM_ADM_BHE
(EMPLID, ACAD_CAREER, STDNT_CAR_NBR, ADM_APPL_NBR, APPL_PROG_NBR, 
SRC_SYS_ID)
/
