DROP INDEX CSSTG_OWNER.PK_PS_ADM_APPLCTR_TBL
/

--
-- PK_PS_ADM_APPLCTR_TBL  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_ADM_APPLCTR_TBL ON CSSTG_OWNER.PS_ADM_APPLCTR_TBL
(INSTITUTION, ADM_APPL_CTR, EFFDT, SRC_SYS_ID)
/
