DROP INDEX CSSTG_OWNER.PK_PS_ACAD_HISTORY
/

--
-- PK_PS_ACAD_HISTORY  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_ACAD_HISTORY ON CSSTG_OWNER.PS_ACAD_HISTORY
(EMPLID, EXT_ORG_ID, SRC_SYS_ID)
/
