DROP INDEX CSSTG_OWNER.PK_PS_UM_STDNT_DEGLIM
/

--
-- PK_PS_UM_STDNT_DEGLIM  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_UM_STDNT_DEGLIM ON CSSTG_OWNER.PS_UM_STDNT_DEGLIM
(EMPLID, INSTITUTION, ACAD_CAREER, STDNT_CAR_NBR, ACAD_PROG, 
ACAD_PLAN, ACAD_SUB_PLAN, EFFDT, SRC_SYS_ID)
/
