DROP INDEX CSSTG_OWNER.PK_PS_ACAD_SUBPLAN
/

--
-- PK_PS_ACAD_SUBPLAN  (Index) 
--
CREATE UNIQUE INDEX CSSTG_OWNER.PK_PS_ACAD_SUBPLAN ON CSSTG_OWNER.PS_ACAD_SUBPLAN
(EMPLID, ACAD_CAREER, STDNT_CAR_NBR, EFFDT, EFFSEQ, 
ACAD_PLAN, ACAD_SUB_PLAN, SRC_SYS_ID)
/
